### ISSUE TITLE
Point.fromLngLat is dangerous

### ISSUE THREAD

**Issue by eygraber** [mapbox/mapbox-maps-android#1005]
I'm updating from v9 to v10, and (aside from the other massive amount of changes), the change from LatLng to Point is made very dangerous by the fact that Point.fromLngLat expects the longitude first, while LatLng had the latitude first.

At the very least there should be a Point.fromLatLng

**Comment by ZiZasaurus** [comment]
@eygraber thank you for your feedback. The use of the lnglat convention derives from the [GeoJSON specification](https://geojson.org/). We will consider your request for adding this convenience in a future version of v10.
