### ISSUE TITLE
addOnMapClickListener V10 Android Java

### ISSUE THREAD

**Issue by sagar24v** [mapbox/mapbox-maps-android#1006]
The document only shows Map click Listener only using Kotlin. Why you guys don't have Java documentation?

How can i get Map Click point in android java using v10

**Comment by kiryldz** [comment]
Hey @sagar24v, we will be adding more docs for Java usage in the nearest future.

General logic is pretty straight-forward for extension Kotlin functions, in your case it's related to map gestures plugin, so it would be:
```
GesturesUtils.addOnMapClickListener(mapView.getMapboxMap(), clickedPoint -> true);
```

or you could first get instance of the gesture plugin from `MapView` and access it from there:
```
GesturesUtils.getGestures(mapView).addOnMapClickListener(clickedPoint -> true);
```
