### ISSUE TITLE
Migrating from v9 to v10

### ISSUE THREAD

**Issue by ajaasazeez** [mapbox/mapbox-maps-android#1009]
From where can I find deprecated methods and their alternatives while migrating from v9 to v10.
The migration guide only contains major changes.

**Comment by ZiZasaurus** [comment]
@ajaasazeez, currently the migration guide is the only documentation that compares deprecated methods and their alternatives. Please refer to the Maps SDK for Android guides [here](https://docs.mapbox.com/android/maps/guides/) for assistance with implementing various features in v10.
