### ISSUE TITLE
Memory Leak in ViewAnnotationManager

### ISSUE THREAD

**Issue by florianPOLARSTEPS** [mapbox/mapbox-maps-android#1020]
## Environment

- Android OS version: Any
- Devices affected: Irrelevant
- Maps SDK Version: 10.2.0

## Observed behavior and steps to reproduce

There seems to be a memory leak related to the new ViewAnnotationManager. Specifically, the way it registers and unregisters the `OnGlobalLayoutListener` in relation to the View.

```
┬───
│ GC Root: System class
│
├─ android.view.inputmethod.InputMethodManager class
│    Leaking: NO (InputMethodManager↓ is not leaking and a class is never leaking)
│    ↓ static InputMethodManager.sInstance
├─ android.view.inputmethod.InputMethodManager instance
│    Leaking: NO (ViewRootImpl↓ is not leaking and InputMethodManager is a singleton)
│    ↓ InputMethodManager.mCurRootView
├─ android.view.ViewRootImpl instance
│    Leaking: NO (ViewRootImpl#mView is not null)
│    ↓ ViewRootImpl.mAttachInfo
│                   ~~~~~~~~~~~
├─ android.view.View$AttachInfo instance
│    Leaking: UNKNOWN
│    ↓ View$AttachInfo.mTreeObserver
│                      ~~~~~~~~~~~~~
├─ android.view.ViewTreeObserver instance
│    Leaking: UNKNOWN
│    ↓ ViewTreeObserver.mOnGlobalLayoutListeners
│                       ~~~~~~~~~~~~~~~~~~~~~~~~
├─ android.view.ViewTreeObserver$CopyOnWriteArray instance
│    Leaking: UNKNOWN
│    ↓ ViewTreeObserver$CopyOnWriteArray.mData
│                                        ~~~~~
├─ java.util.ArrayList instance
│    Leaking: UNKNOWN
│    ↓ ArrayList.elementData
│                ~~~~~~~~~~~
├─ java.lang.Object[] array
│    Leaking: UNKNOWN
│    ↓ Object[].[1]
│               ~~~
├─ com.mapbox.maps.ViewAnnotationManagerImpl$prepareViewAnnotation$globalLayoutListener$1 instance
│    Leaking: UNKNOWN
│    Anonymous class implementing android.view.ViewTreeObserver$OnGlobalLayoutListener
│    ↓ ViewAnnotationManagerImpl$prepareViewAnnotation$globalLayoutListener$1.this$0
│                                                                             ~~~~~~
├─ com.mapbox.maps.ViewAnnotationManagerImpl instance
│    Leaking: UNKNOWN
│    ↓ ViewAnnotationManagerImpl.mapView
│                                ~~~~~~~
╰→ com.mapbox.maps.MapView instance
​     Leaking: YES (ObjectWatcher was watching this because com.x.x.MapFragment received Fragment#onDestroyView() callback (references to its views should be cleared to prevent leaks))
​     key = 6d0c3e8d-4810-4719-8be9-01e140d1381a
​     watchDurationMillis = 89878
​     retainedDurationMillis = 84875
​     mContext instance of com.x.x.MainActivity with mDestroyed = false
​     View#mParent is null
​     View#mAttachInfo is null (view detached)
​     View.mID = R.id.null
​     View.mWindowAttachCount = 1
METADATA
Build.VERSION.SDK_INT: 30
Build.MANUFACTURER: OnePlus
LeakCanary version: 2.4
```

## Expected behavior

No memory leak

## Notes / preliminary analysis

It seems that when the cleanup is happening (`ViewAnnotationManagerImpl.destroy()`) the call to `ViewTreeObserver.removeOnGlobalLayoutListener()` does not actually remove the listener from the same `ViewTreeObserver` as it was added to, hence leaking a reference. (see https://stackoverflow.com/a/63713958).

## Additional links and references

https://stackoverflow.com/a/63713958

**Comment by yunikkk** [comment]
@florianPOLARSTEPS hi, `com.x.x.MapFragment` is your custom fragment class, right? And to confirm - have you called `mapView.onDestroy`?

**Comment by florianPOLARSTEPS** [comment]
> @florianPOLARSTEPS hi, `com.x.x.MapFragment` is your custom fragment class, right? And to confirm - have you called `mapView.onDestroy`?

Yep... You are correct. That is my custom MapFragment. 
As far as I see `mapView.onDestroy` is called properly. I am not calling it myself but it is called by the `Mapbox Lifecycle Plugin` callback.

**Comment by kiryldz** [comment]
@florianPOLARSTEPS I tried to reproduce that issue by running pretty straight-forward [activity](https://github.com/mapbox/mapbox-maps-android/blob/main/app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/ViewAnnotationBasicAddActivity.kt). I was adding several view annotations and then returning back to parent activity however leak canary did not catch anything.

Could you please provide a bit more information when you observe the leak e.g. device, Android version, perhaps describe your situation in more detail. 
Also would be grateful if you could run [this code](https://github.com/mapbox/mapbox-maps-android/blob/main/app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/ViewAnnotationBasicAddActivity.kt) as well and see if you observe leak there.

**Comment by florianPOLARSTEPS** [comment]
@kiryldz I am trying to run the sample project but having some setup issues. Meanwhile I created a test project demonstrating the issue for you:

https://github.com/florianPOLARSTEPS/MapboxAnnotationLeak

**Comment by kiryldz** [comment]
@florianPOLARSTEPS sorry for the delay, I do see a leak in your test app, will try to fix this week.
