### ISSUE TITLE
Hi I can not import com.mapbox.maps.testapp and it is not clear why.

### ISSUE THREAD

**Issue by Freeze35** [mapbox/mapbox-maps-android#1022]
Environment
---
- OC: Windows
- IDE: Android Studio
- Maps SDK Version: 10.2.0

Hi  When trying to import only com.mapbox.maps.testapp there is nothing in gradle dependencies. But all other dependencies work fine.

> I am new to using mapbox.maps. Please help.

I tried to run this example: https://docs.mapbox.com/android/maps/examples/location-component/
But without importing i won't have permission from phone.

Or use PermissionsManager for launch?: https://docs.mapbox.com/android/core/guides/#permissionsmanager

**Dependencies build.grudle**
[build.gradle.module.txt](https://github.com/mapbox/mapbox-maps-android/files/7826086/build.gradle.module.txt)
**List dependcies**
[List dependcies.txt](https://github.com/mapbox/mapbox-maps-android/files/7826090/List.dependcies.txt)

**Comment by ZiZasaurus** [comment]
@Freeze35 are you trying to run a single example or the whole example project?

**Comment by Freeze35** [comment]
I tried to run different options, but considering that I have only one import of the permission request in the form of LocationPermissionHelper missing. I just won't get access to launch location fixing. Therefore, I did not start other examples.

**Comment by ZiZasaurus** [comment]
@Freeze35 the package that you are referencing, `com.mapbox.maps.testapp`, is relative to the examples app. If you would like to create your own project using this example, you would want to reference the package specific to your project.

If you would like to build the android test app, please clone the repository and follow the steps in our DEVELOPING.MD's configuring the project section [here](https://github.com/mapbox/mapbox-maps-android/blob/main/DEVELOPING.md#configuring-the-project).

**Comment by Freeze35** [comment]
Thanks for the link, I'll try to figure it out

**Comment by Adityasai1431** [comment]
Hello how can I import this??
com.mapbox.maps.testapp.utils.LocationPermissionHelper
