### ISSUE TITLE
setCameraMode not working directly after enabling location component

### ISSUE THREAD

**Issue by jonschmidt** [mapbox/mapbox-maps-android#1023]
## Environment

- Android OS version: 12
- Devices affected: Pixel 5
- Maps SDK Version: com.mapbox.mapboxsdk:mapbox-android-sdk:9.7.0 (I think its present in 10.x as well)

## Observed behavior and steps to reproduce

If I set the camera mode immediately after enabling the location components, it does not go to the requested tracking mode.
E.g.
```
val locationEngineRequest = LocationEngineRequest.Builder(750)
    .setFastestInterval(750)
    .setPriority(LocationEngineRequest.PRIORITY_BALANCED_POWER_ACCURACY)
    .build()

map.locationComponent.activateLocationComponent(
    LocationComponentActivationOptions
        .builder(context, map.style!!)
        .useDefaultLocationEngine(true)
        .locationEngineRequest(
            locationEngineRequest
        )
        .build()
)
map.locationComponent.renderMode = RenderMode.COMPASS
map.locationComponent.cameraMode = CameraMode.TRACKING_COMPASS
map.locationComponent.isLocationComponentEnabled = true
```
Will not go to `CameraMode.TRACKING_COMPASS`, it will enter `CameraMode.NONE`.

If I add a one second delay before calling

`map.locationComponent.cameraMode = CameraMode.TRACKING_COMPASS`

it works fine.

## Expected behavior

Calling 

`map.locationComponent.cameraMode = CameraMode.TRACKING_COMPASS`

sets the camera to TRACKING_COMPASS mode

## Notes / preliminary analysis

I think it has something to do with the fact that the camera goes to CameraMode.NONE by default when you initialize the location component. The subsequent call seems to fail silently.

Thats another detail, is that often I find that calls I make fail with little to no logging. It would be great if there was more logging in location component.

**Comment by ank27** [comment]
@jonschmidt in v10, we dont have `CameraMode.*`. LocationComponent doesn't handle camera. Please refer to [this](https://github.com/mapbox/mapbox-maps-android/blob/main/app/src/main/java/com/mapbox/maps/testapp/examples/LocationComponentActivity.kt) example on how to use Location plugin in v10.

**Comment by kiryldz** [comment]
@jonschmidt in general camera modes and connected things are tracked by viewport plugin that provides more flexibility to control the camera.
It has just been introduced in [v10.3.0-beta.1](https://github.com/mapbox/mapbox-maps-android/releases/tag/android-v10.3.0-beta.1), you could find example activity [here](https://github.com/mapbox/mapbox-maps-android/blob/main/app/src/main/java/com/mapbox/maps/testapp/examples/viewport/ViewportShowcaseActivity.kt).

If you have any issues for maps 9.7.0 - please open an issue in v9 [repo](https://github.com/mapbox/mapbox-gl-native-android).
