### ISSUE TITLE
Add GeometryTileProvider like v9

### ISSUE THREAD

**Issue by MatteoAlberghini** [mapbox/mapbox-maps-android#1024]
## New Feature
Wondering if support for `GeometryTileProvider` as constructor parameter for `CustomGeometrySource` is a planned feature in v10.

## Why
I need to be able to have a function similar to `getFeaturesForBounds(LatLngBounds bounds, int zoomLevel)` to query my existing POIs databases.

**Comment by ank27** [comment]
In order to get the features from Source, you can use `querySourceFeatures` or `queryRenderedFeatures`. Let me know if you need more help.
