### ISSUE TITLE
Mapbox Navigation BlackScreen 

### ISSUE THREAD

**Issue by szyrelle290612** [mapbox/mapbox-maps-android#1026]
E/MbxViewportDataSource: Provided following padding does fit the map size:
    mapSize: [width: 64.0, height: 64.0]
    padding: [top: 360.0, left: 80.0, bottom: 300.0, right: 80.0]
E/MbxViewportDataSource: Provided following padding does fit the map size:
    mapSize: [width: 64.0, height: 64.0]
    padding: [top: 360.0, left: 80.0, bottom: 300.0, right: 80.0]
    
    when i run my app on another phone i encounter this error and the map is blackscreen anyone can solve this issue
    thanks in advance

**Comment by ZiZasaurus** [comment]
@szyrelle290612 closing this ticket for now, but please feel free to reopen if you can provide details regarding your implementation.
