### ISSUE TITLE
Provide Bitmap for ImageSource rather then just url in v10

### ISSUE THREAD

**Issue by kajaba** [mapbox/mapbox-maps-android#1027]
## New Feature

As in previous SDK version I would like to add my custom Bitmap to ImageSource. Now only url is supported

## Why
In case I need to create special image (Bitmap), that I need to show on map, I cant because there is not such possibility as it was in previous version of SDK

**Comment by ank27** [comment]
@kajaba, You can follow the example [here](https://github.com/mapbox/mapbox-maps-android/blob/main/app/src/main/java/com/mapbox/maps/testapp/examples/ImageSourceActivity.kt#L41-L46), Let me know if this helps.

**Comment by kajaba** [comment]
Oh I get the idea. Thanks for pointing that out :)
