### ISSUE TITLE
Use default feature property value defined in MapboxStudio

### ISSUE THREAD

**Issue by kajaba** [mapbox/mapbox-maps-android#1028]
## New Feature

- In Mapxbox studio, there is possible to style the layers (color/fillColor) with conditions. 
- In code I can change color/opacity with expression.

It would be nice to have such feature that allows me to change color/opacity ONLY for some layer features.
Something like:

LineLayer line= ((LineLayer)LayerUtils.getLayer(mapboxMap.getStyle(),"rivers-union"));
line.lineColor(
			Expression.match(
				Expression.get("orgId"),Expression.literal(60),
				COLOR_DEFINED_IN_MAPBOX_STUDIO,
				Expression.color(ContextCompat.getColor(getContext(),R.color.white))
			)
);

## Why
In our usecase, we style the features for all users in certain way. But sometimes our customers need to see customized features, where some of them are "greyed" and some of them are normal as styled in mapbox studio.

**Comment by ZiZasaurus** [comment]
@kajaba this functionality currently exists. Please take a look at our StyleCirclesCategoricallyActivity example [here](https://github.com/mapbox/mapbox-maps-android/blob/main/app/src/main/java/com/mapbox/maps/testapp/examples/StyleCirclesCategoricallyActivity.kt).

**Comment by kajaba** [comment]
> here

Thank you for responding. I looked at your example and if you were referring to circleColor match get... it does not work as I wanted. Your example sets circle colors when: 
ethnicity - white rgb(251.0, 176.0, 59.0)
ethnicity - black rgb(34.0, 59.0, 83.0)
etc...
OTHERWISE - rgb(0.0, 0.0, 0.0)
This sets color BLACK for nonmatching ehnicities. But I dont want to define this otherwise color at all and expect that the color defined in MapStudio will be used.

Is there any way to retrieve from layer only some features (that match some property) and only those colorize?
Thank you

**Comment by kajaba** [comment]
> this
Thanks, but I am aware how to filter. But my goal is to colorize only SOME features. Cant do it with filter, or?

**Comment by kiryldz** [comment]
Sorry, I can't get what exactly you're asking for...

 >  my goal is to colorize only SOME features

sounds to me exactly like 
 - filter those features first (filter)
 - colorize them depending on some condition (match)

If you're able to to do that in Mapbox studio - why can't you prepare your style there and simply load it by URL in Android?

**Comment by kajaba** [comment]
Our use case is this: In mapbox studio we have our data (rivers and lakes) colorized based on some conditions:
In app some users dont want to see rivers and lakes in some special areas colorized, but want to see them in grey color. Others they want to see colorized as we prepared them in studio.

With filter I can make some features visible/invisible. Cant use filter to colorize only some features (rivers/lakes) am I right?

**Comment by ZiZasaurus** [comment]
@kajaba the match expression you're using doesn’t seem to evaluate to 60. The underlying data may not be in the string format. Can you try setting 60 to a string using [toString](https://docs.mapbox.com/android/maps/api/10.2.0/mapbox-maps-android/com.mapbox.maps.extension.style.expressions.dsl.generated/to-string.html) or setting orgID [toNumber](https://docs.mapbox.com/android/maps/api/10.2.0/mapbox-maps-android/com.mapbox.maps.extension.style.expressions.dsl.generated/to-number.html)?

**Comment by kajaba** [comment]
> @kajaba the match expression you're using doesn’t seem to evaluate to 60. The underlying data may not be in the string format. Can you try setting 60 to a string using [toString](https://docs.mapbox.com/android/maps/api/10.2.0/mapbox-maps-android/com.mapbox.maps.extension.style.expressions.dsl.generated/to-string.html) or setting orgID [toNumber](https://docs.mapbox.com/android/maps/api/10.2.0/mapbox-maps-android/com.mapbox.maps.extension.style.expressions.dsl.generated/to-number.html)?

The orgID is number and it matches. It seems you do not understand the issue.
If I do this
Expression.match(
Expression.get("orgId"),Expression.literal(60),
Expression.color(ContextCompat.getColor(getContext(),R.color.white))
)
);
I get an error because  it seems that sintax is:
LineColor(Match (dataAttribute, dataValue), colorOfMatched, colorOfOthers)
The colorOfOthers must be explicitly defined, but I would like to not define it, so default values can be used from Mapbox Studio.

**Comment by ZiZasaurus** [comment]
@kajaba this feature is currently not supported as expression usage will overwrite the match expression in Studio. One workaround would be to filter out the features that you want to modify in the original layer, create a duplicate layer, and then set the duplicated layer to filter out the selected feature and color the remaining features gray.

**Comment by ZiZasaurus** [comment]
@kajaba this feature is currently not supported as expression usage will overwrite the match expression in Studio, however, we will consider your request for adding this feature in a future version of v10. 

One workaround would be to filter out the features that you want to modify in the original layer, create a duplicate layer, and then set the duplicated layer to filter out the selected feature and color the remaining features gray.
