### ISSUE TITLE
Hide location puck bearing if device doesn't have compass

### ISSUE THREAD

**Issue by ittna** [mapbox/mapbox-maps-android#1055]
## Environment

- Android OS version: 12
- Devices affected: devices without compass
- Maps SDK Version: 10.3.0-beta.1

## Observed behavior and steps to reproduce

Device without compass shows heading pointing to north always. Should it hide bearing if it can't get device heading?

```
mapView.location.updateSettings {
    enabled = true
    puckBearingSource = PuckBearingSource.HEADING
}
```

## Expected behavior

Location puck hides bearing image when it can't get device heading.

**Comment by kiryldz** [comment]
Stale, outdated. Also let's assume it works like that by design in SDK (show north if no compass).
