### ISSUE TITLE
URL Request Transform

### ISSUE THREAD

**Issue by ac87** [mapbox/mapbox-maps-android#106]
## New Feature

Looking at the v10 API I cannot find a replacement for the FileSource Resource Transform Callback:
https://docs.mapbox.com/android/maps/api/9.5.0/com/mapbox/mapboxsdk/storage/FileSource.ResourceTransformCallback.html
The Observable plugin might provide this feature but I cannot see a way or example to modify the request.

## Why

Other Tile providers such as HERE require custom headers on requests https://developer.here.com/documentation/vector-tiles-api/dev_guide/topics/examples/mapbox.html

It was added to GL JS on numerous requests.
https://github.com/mapbox/mapbox-gl-js/pull/5021

**Comment by jpietri** [comment]
Anything new on this request? I'm having the same issue.
See my [post on StackOverflow](https://stackoverflow.com/questions/67616505/how-to-provide-an-authentication-token-to-a-tile-provider-with-mapbox-android-sd).
Thanks :-)

**Comment by kiryldz** [comment]
Closing as I'd say solution from https://stackoverflow.com/a/76964550 should be fine. Re-open if this is still relevant.
