### ISSUE TITLE
Offline 3d terrain

### ISSUE THREAD

**Issue by cobra811** [mapbox/mapbox-maps-android#1063]
## Offline 3d Terrain
I was not able to find any documentation on offline 3d terrain, so I'm assuming it is not possible yet? I could be wrong. It would be a great feature.

**Comment by dudeuter** [comment]
@cobra811 As this is more of an Integration Issue than a Platform/Android specific issue, do you mind creating a support ticket at https://support.mapbox.com/hc/en-us/?

You can mention my Github handle to get it assigned to me.

**Comment by maclne** [comment]
@dudeuter is the 3d Terrain available offline yet? I can't find any information on it.
