### ISSUE TITLE
Allow setting metadata with the legacy OfflineRegionManager. 

### ISSUE THREAD

**Issue by DejanRistic** [mapbox/mapbox-maps-android#1072]
## New Feature
Allow setting metadata while creating a new offline region using the legacy OfflineRegionManager.

## Why
In the old SDK we were able to set metadata for an OfflineRegion while creating it. With the legacy OfflineRegionManager we can access the metadata, but we can't set it.

**Comment by pengdev** [comment]
The `OfflineRegion.setMetadata` method is introduced in the [v10.3.0-rc.1](https://github.com/mapbox/mapbox-maps-android/releases/tag/android-v10.3.0-rc.1) release.
