### ISSUE TITLE
v10.2.0 OnMapIdle listener doesn't provide event when map movement is completely stop

### ISSUE THREAD

**Issue by Aram-dev** [mapbox/mapbox-maps-android#1078]
## New Feature

Define the event when the MapView is completely stopped after moving(after fling)

## Why

In case of continueos work with MapView (add, remove, update PointAnnotation by using PointAnnotationManager) and when the user simultenusely moves the map phisically(or by animation) the event of OnMapIdleListener does not achive correctly when map completely stops after moving(after fling). 
The porpose is to get new center-point of MapView after movement is completely stoped

**Comment by kiryldz** [comment]
@Aram-dev do you mean IDLE event is not triggered at all or that it gets triggered after small delay?

**Comment by Aram-dev** [comment]
> @Aram-dev do you mean IDLE event is not triggered at all or that it gets triggered after small delay?

@kiryldz IDLE event is not triggered at all. I just need the event which should trigger in the end of movement (after the fling motion is ended)

https://user-images.githubusercontent.com/56653267/151174344-201ef1b2-eb8a-406c-8dcf-981ec4b4f062.mp4

**Comment by ZiZasaurus** [comment]
@Aram-dev, I'm unable to reproduce the behavior you're experiencing, please see my screen recording below. Are you able to create a minimal test case that reproduces this behavior? 

https://images.zenhubusercontent.com/330365289/14d39c48-4f2b-4170-aba5-228e8f6cc2b5/screen_recording_2022_01_26_at_10_00_49_am.mov

**Comment by Aram-dev** [comment]
@ZiZasaurus  I tried reproduce these events for Activity and Fragment in test project.  For Activity it works fine and doesn't work for Fragment. 
For fragment I used the same implementation as for Activity. In My real case the MapView is inside of Fragment(in fragment.xml). I'll provide videos or the github link of test project as soon as posible.

**Comment by Aram-dev** [comment]
[https://github.com/Aram-dev/MapBoxTest](url) 
This is the link to test project. the MapView used inside of both, Activity and Fragment. You can see the video attached.

https://user-images.githubusercontent.com/56653267/151359003-06e922ba-a9f4-4ef2-9b8a-b25c23f57789.mp4

**Comment by Chaoba** [comment]
@Aram-dev A 
Firstly, you have imported  v10.2.0 by ` implementation("com.mapbox.maps:android:10.2.0")`, this would include all the plugins, so please don't import other plugins separately, this will cause conflict.

Secondly, you enabled `pulsingEnabled` this will trigger an animator continuously update the map

Thirdly, for fragment, you created a `mapview` with binding and then created another one by `inflater.inflate(R.layout.main_fragment, container, false)`, however the first one is not added to the UI so no event will be triggered. Please fix it like below.
```
    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View {
        binding = MainFragmentBinding.inflate(layoutInflater)
        return binding.main
//        return inflater.inflate(R.layout.main_fragment, container, false)
    }
```
Let me know if you have other questions.

**Comment by Aram-dev** [comment]
@Chaoba thanks for your detailed explanation. I'd like to give some feedback
About dependencies - I'll change the implementations part. Anyway I had haven't any conflict connected to it.
The Fragment case, I agree there was a mistake in the code and thanks for mentioning it.

But I didn't get the solution of the main case for what I opened this issue.
I'll try to explane my porpose again 

1. I need to work (render or animete some objects) with map continuously - (there is no some problems)
2. In the same time I need the ability to move the map(manually or with animation) - (there is no some problems)
3. And in the end I need some event that the map completely stopped moving (Like OnIdle state) - (here is the problem becouse there is continious rendering on Map)

My example is quite similar to "AnimatePointAnnotationActivity" example.
As I understand there is NO way to get the OnIdle event when there is continuous rendering (animation like in "AnimatePointAnnotationActivity") on map.

In this case can you provide some solution to get some "Map completely Stopped" event after manual moving

As an example we can consider the ability of triggering OnIdle(or some) event in the "AnimatePointAnnotationActivity" in case if the user swipes map manually.

**Comment by Chaoba** [comment]
You can try `OnMoveListener`
```
    gesturesPlugin.addOnMoveListener(object : OnMoveListener {
      override fun onMoveBegin(@NonNull detector: MoveGestureDetector) {
      }

      override fun onMove(@NonNull detector: MoveGestureDetector): Boolean {
        return false
      }

      override fun onMoveEnd(@NonNull detector: MoveGestureDetector) {
      }
    })
```
