### ISSUE TITLE
Why is my LineLayer not showing?

### ISSUE THREAD

**Issue by meanrod** [mapbox/mapbox-maps-android#1092]
My goal is to add line layer that will connect the two view annotations that i added.
I followed the docs about adding line layer with geojsonsource . 

I tried to test a static value of geojsonsource using this,but still not showing.
`featureCollection(
                                FeatureCollection.fromFeatures(
                                        arrayOf(
                                                Feature.fromGeometry(
                                                        Point.fromLngLat(
                                                                12.554729,
                                                                55.70651
                                                        )
                                                ),
                                                Feature.fromGeometry(
                                                        Point.fromLngLat(
                                                                12.65147,
                                                                55.608166
                                                        `)`
                                                )
                                        )
                                )
                        )`

 Is there anything i forgot?

     fun initMap(){
            binding.mapView.getMapboxMap().loadStyle(
                    styleExtension = style(Style.MAPBOX_STREETS) {
                        binding.mapView.scalebar.enabled = false;
                        val point = Point.fromLngLat(lng!!.toDouble(), lat!!.toDouble())
                        val point_prop = Point.fromLngLat(property_data.property_lng.toDouble(), property_data.property_lat.toDouble())
    
                        val cameraOptions = CameraOptions.Builder()
                                .center(point)
                                .zoom(15.5)
                                .build()
    
                        binding.mapView.getMapboxMap().setCamera(cameraOptions)
                        val pin: LayoutPinMapBinding = LayoutPinMapBinding.inflate(activity.layoutInflater, binding.mapView, true)
                        val property: LayoutNearbyPropertyAnnotationBinding = LayoutNearbyPropertyAnnotationBinding.inflate(activity.layoutInflater, binding.mapView, true)
    
                        property.parent.setBackgroundTintList(ColorStateList.valueOf(ContextCompat.getColor(activity, R.color.selected_bubble_color_nearby_properties)))
                        property.annotation.setTextColor(ContextCompat.getColor(activity, R.color.white))
                        property.annotation.setText(property_data.property_name)
    
                        val options_property = ViewAnnotationOptions.Builder()
                                .geometry(point_prop)
                                .allowOverlap(true)
                                .anchor(ViewAnnotationAnchor.CENTER)
                                .build()
                        val options_amenity = ViewAnnotationOptions.Builder()
                                .geometry(point)
                                .allowOverlap(true)
                                .anchor(ViewAnnotationAnchor.CENTER)
                                .build()
    
                        val viewAnnotationManager = binding.mapView.viewAnnotationManager
                        viewAnnotationManager.addViewAnnotation(pin.getRoot(), options_amenity)
                        viewAnnotationManager.addViewAnnotation(property.getRoot(), options_property)
    
                        +geoJsonSource("line-source") {
                            featureCollection(
                                    FeatureCollection.fromFeatures(
                                            arrayOf(
                                                    Feature.fromGeometry(
                                                            Point.fromLngLat(
                                                                    12.554729,
                                                                    55.70651
                                                            )
                                                    ),
                                                    Feature.fromGeometry(
                                                            Point.fromLngLat(
                                                                    12.65147,
                                                                    55.608166
                                                            )
                                                    )
                                            )
                                    )
                            )
                        }
    
                        +lineLayer("linelayer", "line-source") {
                            lineWidth(8.0)
                            lineColor("#FF0000")
                        }
                    }
            )
        }

Btw i am using mapbox for android v10.2.0

**Comment by ZiZasaurus** [comment]
@meanrod, featureCollection(point, point) is not a line string. If you just want to use points, you can make a point array and reference it like so:
```
     val coordinates = listOf<Point>(
      Point.fromLngLat(
        12.554729,
        55.70651
      ),
      Point.fromLngLat(
        12.65147,
        55.608166
      )
    )

      +geoJsonSource(SOURCE_ID) {
           geometry(LineString.fromLngLats(coordinates))
      }
```
or you can reference a FeatureCollection like so: https://github.com/mapbox/mapbox-maps-android/blob/7e6c94892f063c1bee878bfac84043f[…]java/com/mapbox/maps/testapp/examples/RuntimeStylingActivity.kt 

Please feel free to reach out to our support team by creating a ticket at https://support.mapbox.com/hc/en-us/ if you have any additional implementation questions.
