### ISSUE TITLE
How to detect on cluster click?

### ISSUE THREAD

**Issue by misha-n-ka** [mapbox/mapbox-maps-android#1095]
I need to detect when user clicked on cluster marker. I used PointAnnotationClusterActivity.kt from examples. 

1) From Example
`pointAnnotationManager?.addClickListener(
            OnPointAnnotationClickListener {
              Toast.makeText(
                this@PointAnnotationClusterActivity,
                "Click: ${it.id}",
                Toast.LENGTH_SHORT
              )
                .show()
              true
            }`
The listener above triggers only when user clicks on annotation,  but not on cluster.

2) Using queringMapForFeatures by pointAnnotationManager with clicked point
` mapView.getMapboxMap().addOnMapClickListener { clickedPoint ->
      val annotation = pointAnnotationManager?.queryMapForFeatures(clickedPoint)
} `
In this case when user clicks on annotation,  I receive PointAnnotation, but when clicking on cluster the "annotation" is null

3) queryRenderedFeatures by mapbox
In this way expectedFeature returns null when user clicks on cluster, but when user clicks on just annotation expectedFeature is exist.
`mapView.getMapboxMap().addOnMapClickListener { clickedPoint ->
mapView.getMapboxMap().queryRenderedFeatures(
        geometry = RenderedQueryGeometry(
          mapView.getMapboxMap().pixelForCoordinate(clickedPoint)
        ),
        options = RenderedQueryOptions(
          listOf(layerId),
          null
        )
      ) { expectedFeature ->
        expectedFeature.value?.forEach { queriedFeature ->
          val feature = queriedFeature.feature
        }
      }
}`

Please answer how should I retreive or detect cluster which user clicked on for zooming to the cluster or something else?

P.s. mapbox version: 10.2.0

**Comment by Chaoba** [comment]
@misha-n-ka The pointAnnotationManager doesn't support detecting click on a cluster, because the click listener needs to return the clicked annotation but the cluster circle is not the annotation managed by pointAnnotationManager.
A workaround is that you query from the cluster layer with this [layerId](https://github.com/mapbox/mapbox-maps-android/blob/main/plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationManagerImpl.kt#L834) directly. 

Let me know if this does not work for you.

**Comment by misha-n-ka** [comment]
Thank you for answer! I found that I queried features from layer for annotation, but not for clusters. I found out that mapbox creates cluster layer with default layerId and quering the correct cluster layerId allowed me to retrieve cluster feature
