### ISSUE TITLE
Mapbox Official Flutter version

### ISSUE THREAD

**Issue by BorisGautier** [mapbox/mapbox-maps-android#1102]
## New Feature

MapBox for Flutter Developper

## Why

MapBox is the best alternative today to google Maps in term of map sdk, it would be very interesting that your teams create a real stable and official version of mapbox for flutter in view of the many developers who go more and more to this solution

**Comment by tobrun** [comment]
Hey @BorisGautier, cool seeing you on this repository :) We are currently evaluating this type of SDK but for time being the [community driven solution](https://github.com/tobrun/flutter-mapbox-gl) is your best bet. While that version is still using v9 of the Maps SDK product, it should still suffice for most use-cases. If we don't bring out a v10 compatible Flutter SDK, I will bring that to the community plugin instead! Going to close as this doesn't have much to do with android SDK though. Thank you for reaching out!

**Comment by BorisGautier** [comment]
Good Thanks you
