### ISSUE TITLE
Could not get createPointAnnotationManager ,annotationApi's in Android Java for SDK Version 10.0

### ISSUE THREAD

**Issue by Suyash171** [mapbox/mapbox-maps-android#1106]
## Environment

- Android OS version: 31 
- Devices affected: 
- Maps SDK Version: v10.0

Does version 10.0 SDK support Android java?
We are trying to get kotlin functions in Java based code.

**Comment by Chaoba** [comment]
@Suyash171  thank you for reaching out. Have you seen our java api checker [here](https://github.com/mapbox/mapbox-maps-android/blob/45ecd7cad2eb61bf81d05904cf6097e72a368573/app/src/main/java/com/mapbox/maps/testapp/examples/JavaInterfaceChecker.java#L204)??

**Comment by Chaoba** [comment]
Close this as no feedback received, feel free to reopen if still have questions about this.
