### ISSUE TITLE
Legacy OfflineRegionManager can not load tiles into map after download

### ISSUE THREAD

**Issue by IolandaRosa** [mapbox/mapbox-maps-android#1107]
## Environment

- Android OS version: 30
- Devices affected:
- Maps SDK Version: 10.3.0-rc1

## Observed behaviour and steps to reproduce

I am downloading the tiles using the legacy OfflineRegionManager following the steps:
- instanciate the OfflineRegionManager with the default resource options
- then create an offline region with OfflineRegionTilePyramidDefinition and a callback (the styleURI is SATELITTE_STREETS)
- in the callback if no error occur I set the metadata and after the metadata is set I set the download state to active and add an observer to the download state
- when the download finishes without an error and the state is INACTIVE then I have my tiles downloaded with success

- to know the maps that I have I use the getOfflineRegions and get the metadata that I save, but if I am offline when I go to the map I do not have the tiles there.... instead I receive an error during the load of style URL (SATELLITE_STREETS) with the message:

Failed to load tile 14/4128/6193=>14 for source mapbox://mapbox.satellite: Unable to resolve host "api.mapbox.com": No address associated with hostname

- It looks like mapbox does not uses the offline downloaded tiles for the location....
- In the version 9 of mapbox I am using this approach and it seems to work fine.
- I also tried your new api but it does not retrieve high resolution tiles and we have a response from you that for this purpose we should use the legacy API
- The problem is the legacy API does not have proper examples of usage and also few documentation I only found this: https://docs.mapbox.com/android/maps/api/10.2.0/mapbox-maps-android/com.mapbox.maps/[android-jvm]-offline-region-manager/ and its not even updated for version 10.3.0-rc-1

## Expected behavior
-When I am offline I should be able to see the downloaded tiles in the map for the regions that I download

## Notes / preliminary analysis

- I am making the download in a fragment and try to see the tiles in other fragment. Both android fragments have maps instantiated individually but using in the mapbox v9 the behaviour of offline map is fine and also in 10.2.0 using the new api its fine I only get the error using the legacy api in version 10.3.0-rc-1

**Comment by ZiZasaurus** [comment]
@IolandaRosa, thank you for reaching out. I'm not encountering any issues with the legacy OfflineRegionManager in 10.3.0-rc.1. Have you seen our example for implementing legacy OfflineRegionManager [here](https://github.com/mapbox/mapbox-maps-android/blob/45ecd7cad2eb61bf81d05904cf6097e72a368573/app/src/main/java/com/mapbox/maps/testapp/examples/LegacyOfflineActivity.kt)?

Additionally, are you using the v9 offline implementation from scratch? Are you trying to migrate an existing app from v9 to v10 and expecting to get the existing regions on a device to work?

**Comment by IolandaRosa** [comment]
@ZiZasaurus thanks. I already migrate the mapbox version and I know that the old maps will not be accessible in this new version. I will look into your example now and try to see if I have anything wrong in my approach.
