### ISSUE TITLE
Legacy OfflineRegion missing a status check. 

### ISSUE THREAD

**Issue by DejanRistic** [mapbox/mapbox-maps-android#1108]
## New Feature

Add a getStatus() to the legacy OfflineMapRegion. Currently only an observer is available that will only report back if a change is detected. We can't just ask for a status directly. 

## Why

In the old SDK we were able to call getStatus on an OfflineRegion, which allowed us to get the state to see if the download was paused, finished, etc.. after the app had been closed and restarted. 

the old method was:

```java
region.getStatus(new OfflineRegion.OfflineRegionStatusCallback() {
   @Override
   public void onStatus(OfflineRegionStatus status) { }
   @Override
   public void onError(String error) {  }
});
```

The legacy OfflineMapRegion allows us to get the status by adding an observer, but this is only hit when status is changed and there is no way to get the current status unless a change is detected.

**Comment by pengdev** [comment]
Hi @DejanRistic, thanks for reaching out! For now I think you can work around this issue by observing the `OfflineRegionStatusCallback` and keep a local variable to keep track of the latest status. In the mean time, we will evaluate internally and possibly re-introduce this feature in the next releases.

**Comment by DejanRistic** [comment]
@pengdev While I can start saving local variables for every new region, we can't really do this for packs already downloaded on the users device, from older versions. 🤔
