### ISSUE TITLE
Java compatibility for adding layers at runtime

### ISSUE THREAD

**Issue by dmeignan** [mapbox/mapbox-maps-android#1111]
## New Feature

We are trying to migrate to MapBox Maps Android v10.2.0 and it seems that the methods for adding layers at runtime are not accessible from Java.

In MapBox v8, we used the following code to add a layer (in the `OnMapReadyCallback`):
```Java
GeoJsonSource traceSource = new GeoJsonSource("trace-source");
LineLayer traceLayer = new LineLayer(
        "trace-layer", "trace-source")
        .withProperties(
                PropertyFactory.lineWidth(4.f),
                PropertyFactory.lineColor(Color.parseColor("#31661d")),
                PropertyFactory.lineOpacity(0.5f)
        );
style.addSource(traceSource);
style.addLayerBelow(traceLayer, "route-layer");
```

Using v10, the methods `addSource` and `addLayer` are implemented in the Extension Builder `StyleExtensionImpl `. But we didn't find a way to access these methods via Java. There should be static methods accessible in Java when a extension in Kotlin is made, but it doesn't seem to be accessible. For instance, the Kotlin extension `@JvmName("addSource") operator fun Source.unaryPlus()` should be accessible via a Java static method in `StyleExtensionImplKt` or `SourceKt`.

The Java code for MapBox v10 should look like this, but does not work:
```Java
GeoJsonSource traceSource = new GeoJsonSource.Builder("trace-source").build();
LineLayer traceLayer = new LineLayer("trace-layer", "trace-source")
        .lineWidth(4.f)
        .lineColor(Color.parseColor("#31661d"))
        .lineOpacity(0.5f);
SourceKt.addSource(style, traceSource);
SourceKt.addLayerBelow(style, traceLayer, "route-layer");
```

We also tested with the method names `unaryPlus`, and also looked at available methods in `Style`. `StyleContract.StyleExtension`, `StyleExtensionImplKt`...

Finally, we were not able to use the methods `Source#addStyleSource` and `Source#addStyleLayer`, because they require a `Value` parameter that does not seem to be compatible with the source and layer object created.

## Why

The method `addSource`, `addLayer` and `addLayerBelow` should be available in Java for compatibility: [Maps SDK for Android - Java compatibility](https://docs.mapbox.com/android/maps/guides/#java-compatibility).

Currently, publishing an app in the Play store requires Android 30, and mapBox Android SDK v8 and v9 are not entirely compatible with the last AndroidX SDK. Thus, mapBox Android SDK v10 seems the only alternative to integrate mapbox in an app.

**Comment by ZiZasaurus** [comment]
@dmeignan thank you for reaching out. Have you seen our java examples demonstrating adding sources and layers [here](https://github.com/mapbox/mapbox-maps-android/tree/45ecd7cad2eb61bf81d05904cf6097e72a368573/app/src/main/java/com/mapbox/maps/testapp/examples/java)?

**Comment by dmeignan** [comment]
Thank you for the fast answer. We are testing this and I come back here today, to let a note and close the issue, if everything works.

**Comment by ZiZasaurus** [comment]
@dmeignan was your testing successful?

**Comment by dmeignan** [comment]
Yes, it works!
We finished the upgrade to MapBox v10 (in java) and everything works. I wanted to test every styling features before posting my answer. We tested successfully with MapBox 10.2.0 and Mapbox 10.3.0-rc.1.

The code to add source and layer:
```java
GeoJsonSource traceSource = new GeoJsonSource.Builder("trace-source").build();
LineLayer traceLayer = new LineLayer("trace-layer", "trace-source")
        .lineWidth(4.f)
        .lineColor(Color.parseColor("#31661d"))
        .lineOpacity(0.5f);
SourceUtils.addSource(style, traceSource);
LayerUtils.addLayerBelow(style, traceLayer, "route-layer");
```

We tested/implemented the following features:

* Adding `SymbolLayer` at runtime with custom properties (`iconImage`, `iconAllowOverlap`, `iconRotate`), :heavy_check_mark:
* Adding `LineLayer` at runtime with custom properties (`lineDasharray`, `lineWidth`, `lineOpacity`...), :heavy_check_mark:
* Changing layer visibility using `Layer#visibility()`, :heavy_check_mark:
* Updating source features at runtime using `GeoJsonSource#feature()` and `GeoJsonSource#featureCollection()`, :heavy_check_mark:
* Updating layer properties at runtime. :heavy_check_mark:

![Screenshot_20220208-120515_FeelSpace-03](https://user-images.githubusercontent.com/8985498/152981684-748cfbe5-4535-4305-bf37-1b277f1acd41.jpg)

The only strange thing (not really related to this initial Issue ticket) is that a type error (from Lint) is showing when we use `addSource` and `addLayer`. But, this is a Lint error and the code compile correctly. These errors does not show with the code from the `mapbox-maps-android` repository (using the same Android Studio). This is probably not related to MapBox and only an AndroidStudio/Kotlin/Java/Lint/... problem.

![addSource-LINT-error](https://user-images.githubusercontent.com/8985498/152973098-e9ee616d-77f6-4dbd-b1ba-aa64e1db23eb.png)

Thanks @ZiZasaurus you solved our problem.

**Comment by ZiZasaurus** [comment]
@dmeignan fantastic news! I will close this ticket but please feel free to reopen if you have additional questions.

**Comment by sfaci** [comment]
Hi @dmeignan and @ZiZasaurus, I take your word and I take the oportunity to comment on this ticket to add a new question related to the code that @dmeignan posted a few comments above.

First of all I have to say that your piece of code was really useful for me. I was trying to do exactly the same as you and, after spend some hours, I finally find your code and it's working for me. But, I had to call another method (_addLayer_ instead of _addLayerBelow_) and remove the name of the "route-layer". Like you, I'm using mapbox v10 with Java and Android. I think I'm working in a sample like yours. In my case I have a previous calculated route that I want to draw into the map.

Is it your sample code wrong or am I doing something wrong?
Thank you very much!!

Instead of using this:

```
GeoJsonSource traceSource = new GeoJsonSource.Builder("trace-source").build();
LineLayer traceLayer = new LineLayer("trace-layer", "trace-source")
        .lineWidth(4.f)
        .lineColor(Color.parseColor("#31661d"))
        .lineOpacity(0.5f);
SourceUtils.addSource(style, traceSource);
LayerUtils.addLayerBelow(style, traceLayer, "route-layer");
```

I had to use this:

```
GeoJsonSource traceSource = new GeoJsonSource.Builder("trace-source")
          .geometry(routeLine)       // routeLine is my already calculated route
          .build();
LineLayer traceLayer = new LineLayer("trace-layer", "trace-source")
          .lineWidth(4.f)
          .lineColor(Color.parseColor("#31661d"))
          .lineOpacity(0.5f);
SourceUtils.addSource(style, traceSource);
LayerUtils.addLayer(style, traceLayer);
```
