### ISSUE TITLE
Scrolling with two fingers only

### ISSUE THREAD

**Issue by markosopcic** [mapbox/mapbox-maps-android#1125]
Hi!

Is there a way to make the MapView scroll through the map only when two fingers are used?

**Comment by markosopcic** [comment]
To clarify, I have a use case where I want the map as a part of a scrollable view, so this view would be scrollable with one finger and the MapView would be scrolled with two fingers to make it more user friendly since the scrolling behavior is a bit weird when both are scrollable with one finger.

**Comment by kiryldz** [comment]
Stale, outdated. Also not precisely clear what exactly is not working, if this is still relevant for latest versions - please provide visuals.
