### ISSUE TITLE
Plugin [id: 'com.android.lint'] was not found in any of the following sources

### ISSUE THREAD

**Issue by bharathkandula99** [mapbox/mapbox-maps-android#1136]
* Exception is:
org.gradle.api.plugins.UnknownPluginException: Plugin [id: 'com.android.lint'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (plugin dependency must include a version number for this source)

getting this error , while performing gradle

**Comment by kiryldz** [comment]
Closing as not enough details are provided (what is building, what env is used etc).
