### ISSUE TITLE
OnMapLoadErrorListener does not support SAM conversions

### ISSUE THREAD

**Issue by tynn** [mapbox/mapbox-maps-android#1149]
The `OnMapLoadErrorListener` is not defined as a `fun interface` and thus doesn't support conversions

    interface OnMapLoadErrorListener { ... }

**Comment by kiryldz** [comment]
It's done on purpose because of `MapboxMap` method:
```
fun loadStyleUri(
    styleUri: String,
    onStyleLoaded: Style.OnStyleLoaded? = null,
    onMapLoadErrorListener: OnMapLoadErrorListener? = null
  )
```
where `Style.OnStyleLoaded` is a functional interface already. Using 2 functional interfaces in such function signature is not supported.

**Comment by tynn** [comment]
@kiryldz thanks for your replay, but I'm not sure I understand your point
> Using 2 functional interfaces in such function signature is not supported.
Do you have a source for this? Eventually it's just a type and it should not matter how you could create an instance of it.

In general it works. You'd be able to do:

    loadStyleUri(styleUri, { style -> ... }, { eventData -> ... })

while now it's necessary to do

    loadStyleUri(styleUri, { style -> ... }, object : OnMapLoadErrorListener {
        override fun onMapLoadError(eventData: MapLoadingErrorEventData) {
            ...
        }
    })

Am I missing anything?

**Comment by kiryldz** [comment]
As we're using default parameters and in plenty of use-cases `onMapLoadErrorListener` parameter is omitted - this will lead to ambiguity e.g. 

<img width="788" alt="image" src="https://user-images.githubusercontent.com/15800566/153583013-da89a727-8d7b-47c0-aadd-b21f12ce77c0.png">

Could you please describe your use-case a bit more why declaring `OnMapLoadErrorListener` as a regular interface is an issue?

**Comment by tynn** [comment]
I really don't want to write

    loadStyleUri(styleUri, { style -> ... }, object : OnMapLoadErrorListener {
        override fun onMapLoadError(eventData: MapLoadingErrorEventData) {
            ...
        }
    })

This is not really idiomatic _Kotlin_ code.

I haven't noticed the default arguments before. I think the problem is, that you mixed overloads and default arguments.

So instead of

    fun loadStyleUri(
        styleUri: String,
    ) = loadStyleUri(styleUri, null, null)

    fun loadStyleUri(
        styleUri: String,
        onStyleLoaded: Style.OnStyleLoaded,
    ) = loadStyleUri(styleUri, onStyleLoaded, null)

    fun loadStyleUri(
        styleUri: String,
        onStyleLoaded: Style.OnStyleLoaded? = null,
        onMapLoadErrorListener: OnMapLoadErrorListener? = null,
    ) { ... }

you would just define a single function annotated with `JvmOverloads`

    @JvmOverloads
    fun loadStyleUri(
        styleUri: String,
        onStyleLoaded: Style.OnStyleLoaded? = null,
        onMapLoadErrorListener: OnMapLoadErrorListener? = null,
    ) { ... }

The only disadvantage might be that the lambda defined outside of the parenthesis always binds to the last parameter `onMapLoadErrorListener`. That's why I usually put the most important functional interface or function as the last parameter.

Alternatively everything would be working well if you removed the default null arguments...

Is there any chance you'd change any of this?

**Comment by kiryldz** [comment]
@tynn thanks for detailed answer! I tend to agree however sadly we can't drop existing public methods as this will be a breaking change. However we'll see what we could do - perhaps we could introduce method with `@JvmOverloads` as you mentioned and mark other as deprecated (as well as make interface functional).

**Comment by kiryldz** [comment]
This was implemented in Maps v11. Please re-open if needed.
