### ISSUE TITLE
IconAnchor issue for bitmap

### ISSUE THREAD

**Issue by VitaminPSG** [mapbox/mapbox-maps-android#1153]
Anchor point has invalid offset on the bottom

issue is reproduced on [sm/marker-anchor-point](https://github.com/mapbox/mapbox-maps-android/tree/sm/marker-anchor-point)

![Screenshot_20220211_191929](https://user-images.githubusercontent.com/5839897/153629435-341815ad-22ef-4c20-9d65-30f96587c565.png)

**Comment by Chaoba** [comment]
@VitaminPSG You are mixing `IconAnchor` and `TextAnchor`. If you change the `CENTER` point as an image, it will be rendered as expected. Please see the picture below, the center of the airport images are located exactly on the position of the views.
I have upload the test codes to your branch.
![image](https://user-images.githubusercontent.com/8577318/153789704-da8a8aca-8882-4ba6-bfb5-9abb92267dbb.png)

**Comment by VitaminPSG** [comment]
Sorry for misleading, I thought that text is a part of annotation and centered as icon

**Comment by kiryldz** [comment]
Closing then, please re-open if any other issues will pop-up.
