### ISSUE TITLE
Two finger pan

### ISSUE THREAD

**Issue by esisa** [mapbox/mapbox-maps-android#1157]
After upgrading to v10 I can no longer get two-finger pan to work.  In version 9 I can pan the map with two fingers and thus also zoom in while panning at the same time. 

https://user-images.githubusercontent.com/660586/153891193-ea21a335-1cb6-4218-bee8-f3a9261661cf.mp4
This is how it works in the current demo app using version 9. I can pan the map using two fingers back and forth and then I zoom and pan at the same time. 

https://user-images.githubusercontent.com/660586/153891881-5da0174c-f326-4499-ac44-59d7775f313a.mp4
This is an app using version 10. I am just loading the style and nothing else. Doing the same gestures as above no longer works. 

I have seen issues here where users want their app to work like it does default in version 10, but I have not found any discussion on how to make the gestures work as they did in version 9. 

What do I need to do to bring back the version 9 functionality?

**Comment by ZiZasaurus** [comment]
@esisa at the moment two finger pan is not supported on Android v10 due to how gestures are implemented. We'll consider implementing this gesture in a future version of the SDK.

**Comment by esisa** [comment]
Oh, that is a serious regression then... Thanks for the quick response though :-)

**Comment by kiryldz** [comment]
@esisa did not go into details but this works for me in Maps v11. I also suspect that it might got fixed in latest Maps v10. Closing this, please re-open if needed.
