### ISSUE TITLE
How to remove annotation marker from the map

### ISSUE THREAD

**Issue by Dharmesh-Dabhi** [mapbox/mapbox-maps-android#1163]
## Environment

- Android OS version: 11
- Devices affected: 1
- Maps SDK Version: 10.2.0

## Observed behavior and steps to reproduce
`annotationManager.deleteAll()`
- Marker annotation not removed from the Map screen

## Expected behavior

How to clear map, remove all marker and route

**Comment by Chaoba** [comment]
@Dharmesh-Dabhi Thank you for reporting. Can you provide more details on how to reproduce or a minimum project that could reproduce this?

**Comment by ZiZasaurus** [comment]
@Dharmesh-Dabhi I will close this ticket for now. Please feel free to reopen this ticket with the additional information requested by @Chaoba.
