### ISSUE TITLE
Can the map rotate automatically？？

### ISSUE THREAD

**Issue by zhufeixiang** [mapbox/mapbox-maps-android#1169]

**Comment by Chaoba** [comment]
@zhufeixiang Can you describe your question specifically?

**Comment by zhufeixiang** [comment]
Without any operation, the earth rotates automatically, just like an accessor

https://user-images.githubusercontent.com/26599058/155051981-80dda3dc-b7b2-4d8e-abd4-bb2246bca1be.mp4

**Comment by Chaoba** [comment]
Can you try to apply `easeTo` with a long during?
  ```
  mapboxMap.easeTo(
      cameraOptions {
          center(Point.fromLngLat(-0.07520, 51.50550))
          zoom(17.0)
          bearing(180.0)
          pitch(30.0)
       },
      mapAnimationOptions {
        duration(5000L)
      }
)
```

**Comment by zhufeixiang** [comment]
> 

This can't achieve my effect.I just need to rotate from left to right, and the others remain the same，like that video.Anyway thanks

**Comment by ZiZasaurus** [comment]
The code provided by @Chaoba is what you would use to set the rotate. You can omit any zoom, bearing or pitch setting if you do not need them. I've attached my recreation and code snippet below. I set my camera to my desired point first and then set the camera I want to use for `easeTo`.

```
      setCamera(
        cameraOptions {
          center(Point.fromLngLat(60.9086103, 38.7080325))
          zoom(1.0)
          bearing(0.0)
          pitch(0.0)
        }
      )
      easeTo(
        cameraOptions {
          center(Point.fromLngLat(-130.5857361,39.6214024))
        },
        mapAnimationOptions {
          duration(20_000L)
        }
      )
```

https://user-images.githubusercontent.com/44972592/155180528-aada0c14-0b24-4afa-8683-8dbcd24d2a48.mov

**Comment by zhufeixiang** [comment]
> The code provided by @Chaoba is what you would use to set the rotate. You can omit any zoom, bearing or pitch setting if you do not need them. I've attached my recreation and code snippet below. I set my camera to my desired point first and then set the camera I want to use for `easeTo`.
> 
> ```
>       setCamera(
>         cameraOptions {
>           center(Point.fromLngLat(60.9086103, 38.7080325))
>           zoom(1.0)
>           bearing(0.0)
>           pitch(0.0)
>         }
>       )
>       easeTo(
>         cameraOptions {
>           center(Point.fromLngLat(-130.5857361,39.6214024))
>         },
>         mapAnimationOptions {
>           duration(20_000L)
>         }
>       )
> ```
> 
>  rotatingGlobeDemo.mov

thank you @ZiZasaurus ,it almost solve my problem
