### ISSUE TITLE
Optimize GeoJsonSource API for geometry/feature/featurecollection

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-maps-android#117]
The v9.0.0 version of the GeoJsonSource was compatible with Mapbox java geojson classes. It was easy to create a GeoJsonSource using geometry, features or feature collection. 

![image](https://user-images.githubusercontent.com/2151639/108523572-5f24aa80-72ce-11eb-88cc-75c98409b992.png)

Would be a nice to have to bring similar functionality back

**Comment by pengdev** [comment]
These are available in the current SDK, we have [convenient methods](https://github.com/mapbox/mapbox-maps-android/blob/main/extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSource.kt#L468-L493) within GeoJsonSource builder to take in Feature, FeatureCollection and Geometry.

**Comment by tobrun** [comment]
facepalm
