### ISSUE TITLE
Clustering on Polygon points

### ISSUE THREAD

**Issue by PavlosTze** [mapbox/mapbox-maps-android#1171]
Hello, 

We are developing an application on **Android**, we use MapBox and we would like to implement clustering on Polygon Annotations after a specific zoom level, like it has been implemented here:
https://explorer.helium.com/

Is that possible? I could't find something on the documentation for the Android SDK.

**Comment by ZiZasaurus** [comment]
@PavlosTze, the hexagon layer you're referring to is not a Mapbox feature, but a third party library that they are using on their servers. If you have a geoJSON of points, you could use Turf.js and a heatmap layer on the points to create something similar. Alternatively, you could cluster your data using a heatmap layer like in this example https://github.com/mapbox/mapbox-maps-android/blob/main/app/src/main/java/com/mapbox/maps/testapp/examples/HeatmapLayerActivity.kt.
