### ISSUE TITLE
videoview in viewpager out of the boundary

### ISSUE THREAD

**Issue by wingkingbobo** [mapbox/mapbox-maps-android#1188]
When sliding the viewpager, the videoview is out of the range of the viewpager. If there is no MapView below, the display is correct.

The black area in the recording screen is viewpager.
https://user-images.githubusercontent.com/16450470/155669372-dd968a1d-7a1f-4841-8c63-cff24ba3be84.mp4

```xml
<FrameLayout>
    <MapView/>
    <ViewPager/>
</FrameLayout>
```
```java
viewPager.setAdapter(new MyAdapter())
```
```java
package com.wingkingbobo.androidvideo.util;

import android.graphics.Color;
import android.media.MediaPlayer;
import android.view.Gravity;
import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import android.widget.VideoView;

import com.wingkingbobo.androidvideo.R;
import com.wingkingbobo.avlib.util.UriUtil;

import java.util.HashMap;
import java.util.Map;

import androidx.annotation.NonNull;
import androidx.viewpager.widget.PagerAdapter;

public class MyAdapter extends PagerAdapter {

    private Map<Integer, ViewGroup> map = new HashMap<>();

    @Override
    public int getCount() {
        return 5;
    }

    @Override
    public boolean isViewFromObject(@NonNull View view, @NonNull Object object) {
        return view == object;
    }

    @NonNull
    @Override
    public Object instantiateItem(@NonNull ViewGroup container, int position) {
        FrameLayout frameLayout = new FrameLayout(container.getContext());
        frameLayout.setLayoutParams(new ViewGroup.LayoutParams(
                ViewGroup.LayoutParams.MATCH_PARENT,
                ViewGroup.LayoutParams.MATCH_PARENT
        ));
        frameLayout.setBackgroundColor(Color.BLACK);
        container.addView(frameLayout);


        VideoView videoView = new VideoView(container.getContext());
        FrameLayout.LayoutParams lp = new FrameLayout.LayoutParams(
                ViewGroup.LayoutParams.MATCH_PARENT,
                ViewGroup.LayoutParams.MATCH_PARENT
        );
        lp.gravity = Gravity.CENTER;
        videoView.setLayoutParams(lp);
        frameLayout.addView(videoView);
        map.put(position, frameLayout);

        videoView.setOnErrorListener(new MediaPlayer.OnErrorListener() {
            @Override
            public boolean onError(MediaPlayer mp, int what, int extra) {
                return false;
            }
        });
        videoView.setVideoURI(UriUtil.getResourceUri(container.getContext(), R.raw.video1));
        videoView.start();
        return frameLayout;
    }

    @Override
    public void destroyItem(@NonNull ViewGroup container, int position, @NonNull Object object) {
        ViewGroup group = map.remove(position);
        VideoView view = (VideoView) group.getChildAt(0);
        view.stopPlayback();
        container.removeView(group);
    }

}

```

**Comment by kiryldz** [comment]
@wingkingbobo can you try create `MapView` with `mapbox:mapbox_mapSurface="texture_view"` mode?

**Comment by wingkingbobo** [comment]
@kiryldz After setting MapView to use TextureView, videoview can be displayed in the correct position. But I'm worried that the performance of TextureView will be significantly lower than that when using surfaceview. Do you have relevant test data.

**Comment by wingkingbobo** [comment]
@kiryldz 
https://user-images.githubusercontent.com/16450470/155689342-3ed2b204-cfa0-474d-abe2-41c12499df99.mp4

Setting it to TextureView causes another strange problem. Zoom in or out of the map. The place where the tiles have not been loaded becomes transparent. You can see the activity at the lower level. Here is the Android desktop.

**Comment by yunikkk** [comment]
> @kiryldz After setting MapView to use TextureView, videoview can be displayed in the correct position. But I'm worried that the performance of TextureView will be significantly lower than that when using surfaceview. Do you have relevant test data.

We don't have such data, will try to compare and get back with the results. 

Meanwhile you can try to apply the workaround with surfaceview as well, using approach similar to [MultiSurfaceActivity](https://github.com/google/grafika/blob/master/app/src/main/java/com/android/grafika/MultiSurfaceActivity.java#L63), adding `Surface.setZOrderMediaOverlay` or `Surface.setZOrderOnTop` for the videoView playing video.

**Comment by wingkingbobo** [comment]
@yunikkk The problem is solved, but not with ImageView. My final plan is to use TextureView and MediaPlayer instead of Android videoview. During the test, it is found that the videoview will become transparent during the loading process. MapView can be seen in that area. It will return to normal only after the loading is completed.

**Comment by yunikkk** [comment]
@wingkingbobo got it. Please report if TextureView will have issues with the performance (though we don't expect it should happen).
