### ISSUE TITLE
[android automotive] the "user" icon does not move on the Map

### ISSUE THREAD

**Issue by ghadeeraqraa1992** [mapbox/mapbox-maps-android#1217]
## Environment

- Android OS version: android automotive 11
- Maps SDK Version:10

the "user" icon does not move on the Map. i.e the icon does not move on the map altho we are in a driving car 

while dibbeging this issue we noticed that below two listeners were not invoked on automotive tablets and they are invoked with the normal android tablets :

```
private val onIndicatorBearingChangedListener = OnIndicatorBearingChangedListener {
    mapView.getMapboxMap().setCamera(CameraOptions.Builder().bearing(it).build())
}

private val onIndicatorPositionChangedListener = OnIndicatorPositionChangedListener {
    mapView.getMapboxMap().setCamera(CameraOptions.Builder().center(it).build())
    mapView.gestures.focalPoint = mapView.getMapboxMap().pixelForCoordinate(it)
}

```

**Comment by kmadsen** [comment]
You may need to [set your own location provider](https://github.com/mapbox/mapbox-maps-android/blob/abc7e7ec8dc2b94aa833c8ae1f27801160bb4109/plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPluginImpl.kt#L158).

The navigation simulator [works by overriding this](https://github.com/mapbox/mapbox-maps-android/blob/abc7e7ec8dc2b94aa833c8ae1f27801160bb4109/app/src/main/java/com/mapbox/maps/testapp/utils/NavigationSimulator.kt#L217) and then sending fake location.
``` kotlin
mapView.location.setLocationProvider(..)
```

Considering your automobile may be receiving its locations from a different location providers, can you test this location consumer to see if anything is being emitted?
``` kotlin
mapView.location.getLocationProvider()
  ?.registerLocationConsumer(youDebuggingConsumer)
```

**Comment by ghadeeraqraa1992** [comment]
Hi @kmadsen 
thanks for quick response 
I created my custom provider following[ this example ](https://github.com/mapbox/mapbox-maps-android/blob/4c663db9d0a1ab9f9c592e9fb640f098dec2f211/app/src/main/java/com/mapbox/maps/testapp/examples/LocationComponentAnimationActivity.kt) and the user icon was moving as expected 
After that I couldn't advance with building custom [locationEngin](https://docs.mapbox.com/android/core/guides/#locationengine) 
can you help ?

**Comment by yunikkk** [comment]
> Hi @kmadsen thanks for quick response I created my custom provider following[ this example ](https://github.com/mapbox/mapbox-maps-android/blob/4c663db9d0a1ab9f9c592e9fb640f098dec2f211/app/src/main/java/com/mapbox/maps/testapp/examples/LocationComponentAnimationActivity.kt) and the user icon was moving as expected After that I couldn't advance with building custom [locationEngin](https://docs.mapbox.com/android/core/guides/#locationengine) can you help ?

@ghadeeraqraa1992 could you pls describe what are you trying to achieve?

**Comment by ghadeeraqraa1992** [comment]
> > Hi @kmadsen thanks for quick response I created my custom provider following[ this example ](https://github.com/mapbox/mapbox-maps-android/blob/4c663db9d0a1ab9f9c592e9fb640f098dec2f211/app/src/main/java/com/mapbox/maps/testapp/examples/LocationComponentAnimationActivity.kt) and the user icon was moving as expected After that I couldn't advance with building custom [locationEngin](https://docs.mapbox.com/android/core/guides/#locationengine) can you help ?
> 
> @ghadeeraqraa1992 could you pls describe what are you trying to achieve?

actually I'm not sure what I have do , so just I added my custom location provider "FakeLocationProvider" the icon was moving and it works 
after that I'm stuck and I'm not able to advance with making it works using real gps and real location

**Comment by ghadeeraqraa1992** [comment]
Hi @yunikkk 
the issue is still reproducible in Harman emulator ,The user  location icon position doesn't get updated while the App is in the foreground, when returning from another app it gets updated. 
onIndicatorPositionChangedListener is not triggered after the map has been in the foreground.if I open any screen inside the app and go back to the map screen the icon position updated after the above listener called. 

`   mapView?.location?.addOnIndicatorPositionChangedListener(
            onIndicatorPositionChangedListener
        )` 

`  private val onIndicatorPositionChangedListener = OnIndicatorPositionChangedListener {
            updateBoundsAndZoomLevel()
            val playerComponentMaxX = content_box_frame_container.measuredWidth + 24 // maxX
            val topPadding = Resources.getSystem().displayMetrics.heightPixels.toDouble() - (where_to_sound_home.measuredHeight + 30 + 200)
            val padding = EdgeInsets(
                topPadding,
                playerComponentMaxX.toDouble(),
                1.0,
                1.0
            )
            mapView?.getMapboxMap()?.setCamera(CameraOptions.Builder().center(it).padding(padding).build())
            
    }`
