### ISSUE TITLE
Draggable polygon annotations do not maintain their shape in 3D

### ISSUE THREAD

**Issue by cramptonism** [mapbox/mapbox-maps-android#1218]
## Environment

- Android OS version: 11
- Devices affected: All
- Maps SDK Version: 10.3.0

## Observed behavior and steps to reproduce

Draggable polygon annotations do not maintain their shape in 3D, particularly in areas of mountainous terrain

https://user-images.githubusercontent.com/13057523/157730300-8b4c255f-8d48-43c3-933e-81e4644823d0.mp4

## Expected behavior

As is the case in 2D, polygons should maintain their shape while being dragged.

## Notes / preliminary analysis

I believe this happens because the translation of the lat/lon corners differs based on the terrain at that corner

**Comment by cramptonism** [comment]
I believe the core of the issue lies within this bit of code in PolygonAnnotation.kt, and would presumably affect Polylines as well:

```
    val points = geometry.coordinates()
      .map {
        it.map {
          mapCameraManagerDelegate.pixelForCoordinate(it)
        }.map {
          mapCameraManagerDelegate.coordinateForPixel(
            ScreenCoordinate(
              it.x - moveDistancesObject.distanceXSinceLast,
              it.y - moveDistancesObject.distanceYSinceLast
            )
          )
        }
      }
```

I believe this code is making an incorrect assumption that each vertex moves the same distance in the world when moving X/Y pixels on the screen. This is fine in 2D but because 3D adjusts the distance based on terrain it ends up with this shifting shape.

**Comment by Chaoba** [comment]
@cramptonism Thanks for your reporting, will address it later.

**Comment by cramptonism** [comment]
Thanks for the quick fix!
