### ISSUE TITLE
Unable to resolve dependency

### ISSUE THREAD

**Issue by Codemenschen248** [mapbox/mapbox-maps-android#1219]
## Environment

- Maps SDK Version: 10.3.0

I am trying to add latest version of Map box, but its failing.
I have followed [MapBox Documentation][1]

secret token in **gradle.properties** file:

    MAPBOX_DOWNLOADS_TOKEN=MY_SECRET_MAPBOX_ACCESS_TOKEN_IN_PAIN_TEXT_WITHOUT_QUOTES

My **settings.gradle** File.

    dependencyResolutionManagement {
        repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
        repositories {
            google()
            mavenCentral()
            jcenter() // Warning: this repository is going to shut down soon
            maven {
                url 'https://api.mapbox.com/downloads/v2/releases/maven'
                authentication {
                    basic(BasicAuthentication)
                }
                credentials {
                    // Do not change the username below.
                    // This should always be `mapbox` (not your username).
                    username = "mapbox"
                    // Use the secret token you stored in gradle.properties as the password
                    password = MAPBOX_DOWNLOADS_TOKEN
                }
            }
            maven { url "https://maven.google.com" }
            maven { url 'https://jitpack.io' }
       }
    }

app level **gradle** file

    dependencies {
      //OTHER DEPENDENCIES....
      implementation 'com.mapbox.maps:android:10.3.0'
    }

After Syncing Gradle Files.

    Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve com.mapbox.mapboxsdk:mapbox-android-sdk:10.3.0.
    Show Details
    Affected Modules: app
    
    Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.mapbox.mapboxsdk:mapbox-android-sdk:10.3.0.
    Show Details
    Affected Modules: app
    
    Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve com.mapbox.mapboxsdk:mapbox-android-sdk:10.3.0.
    Show Details
    Affected Modules: app

I have checked below answers, but not working.
1. https://stackoverflow.com/questions/64738753/how-to-solve-failed-to-resolve-com-mapbox-mapboxsdkmapbox-android-sdk9-5-0
2. https://stackoverflow.com/questions/63904628/why-is-mapbox-android-sdk-not-resolving-from-build-gradle

I don't know what's wrong.

  [1]: https://docs.mapbox.com/android/maps/guides/install/

**Comment by ZiZasaurus** [comment]
@Codemenschen248, as this is more of a product support Issue, can you please create a support ticket at https://support.mapbox.com/hc/en-us/ and our support team will be happy to get you the answers you need.

**Comment by Siddiq200** [comment]
I was facing the same issue, and I resolved it by updating my private token permission, it must have permission `DOWNLOAD:READ`
