### ISSUE TITLE
How to remove a single marker or clear all the markers on the map (Android SDK v10)

### ISSUE THREAD

**Issue by Usama99786** [mapbox/mapbox-maps-android#1228]
I am using implementation 'com.mapbox.maps:android:10.3.0' in my android app. 
I have added multiple markers using following code

 val annotationApi = binding.mapView?.annotations
        val pointAnnotationManager = annotationApi?.createPointAnnotationManager(binding.mapView)
// Set options for the resulting symbol layer.
        val pointAnnotationOptions: PointAnnotationOptions = PointAnnotationOptions()
            .withPoint(
                com.mapbox.geojson.Point.fromLngLat(
                   lng,
                   lat
                )
            )
            .withIconImage(bitmapFromDrawableRes(requireContext(), R.drawable.ic_map_active)!!)
// Add the resulting pointAnnotation to the map.
          pointAnnotationManager?.create(pointAnnotationOptions)
    
I found multiple solutions. i.e mapview.removeAllAnnotations(), .clear(), but none of them are available in this version. I also want to remove one marker at a time but I also have not been able to do it.

**Comment by voilet0604** [comment]
pointAnnotationManager.deleteAll() or pointAnnotationManager.delete(annotation)

**Comment by ZiZasaurus** [comment]
Thanks, @voilet0604! 
@Usama99786, answered [here](https://github.com/mapbox/mapbox-maps-android/issues/1227) as well.
