### ISSUE TITLE
[Java] Could not apply correct line gradient colors to LineLayer

### ISSUE THREAD

**Issue by ohcheung** [mapbox/mapbox-maps-android#1231]
## Environment

- Android OS version: Android 11
- Devices affected: Samsung
- Maps SDK Version: 10.3

## Observed behavior and steps to reproduce

Hi, I'm trying to apply line gradient to line layer using Java. Most of the documentation I found are written in Kotlin, so I'm not sure if I set something wrong in my code. The line became black color instead of gradient.

Here's my code:
```
        Expression.InterpolatorBuilder interpolateBuilder = new Expression.InterpolatorBuilder("interpolate");
        interpolateBuilder.linear();
        interpolateBuilder.lineProgress();
        interpolateBuilder.stop(builder -> {
            builder.literal(0f);
            builder.color(Color.RED);
            return null;
        });
        interpolateBuilder.stop(builder -> {
            builder.literal(0.3f);
            builder.color(Color.BLUE);
            return null;
        });
        interpolateBuilder.stop(builder -> {
            builder.literal(0.5f);
            builder.color(Color.GREEN);
            return null;
        });
        interpolateBuilder.stop(builder -> {
            builder.literal(1f);
            builder.color(Color.YELLOW);
            return null;
        });

        LineLayer lineLayer = new LineLayer(layerId, sourceId)
                .lineWidth(5.f)
                .lineJoin(LineJoin.ROUND)
                .lineCap(LineCap.ROUND)
                .lineGradient(interpolateBuilder.build());

        LayerUtils.addLayerBelow(style, lineLayer, LocationComponentConstants.LOCATION_INDICATOR_LAYER);
```

Is this the correct way to set linegradient to LineLayer in Java? Thank you!

## Expected behavior
Expected to display a colorful line as shown in this example:
https://docs.mapbox.com/android/legacy/maps/examples/line-gradient/

**Comment by kiryldz** [comment]
@ohcheung this looks correct at the first glance. 
Did you set `lineMetrics(true)` for the source that is connected with your line layer? In Kotlin DSL it looks like [this](https://github.com/mapbox/mapbox-maps-android/blob/e8becd34eede7049feeaa4a8d3cca1b72be9f1bb/app/src/main/java/com/mapbox/maps/testapp/examples/linesandpolygons/LineGradientActivity.kt#L32).

**Comment by ohcheung** [comment]
thank you so much @kiryldz , that was what I missed. It is working now
