### ISSUE TITLE
Get visible camera bounds 

### ISSUE THREAD

**Issue by mani-w3w** [mapbox/mapbox-maps-android#1240]
Hi there, I have trying to find a way to get visible bounds SW, NE on v10, I tried getBounds() but it's never updated, seems to always give me:  bounds: center:  0.0,  0.0; sw: -90.0,  -180.0; ne: 90.0,  180.0.

Is there a way to get visible camera bounds that I'm not seeing? 

Thanks!

**Comment by ZiZasaurus** [comment]
@mani-w3w you can use `mapView.getMapboxMap().coordinateBoundsForCamera()` to get the coordinate bounds that correspond to the current camera.

**Comment by VahanLab** [comment]
Yeah same issue here with 10.8.1
Combined with the suggestion above, I managed to find the current bounding box using 

```
mapView.apply {
      val options = CameraOptions.Builder()
                        .zoom(getMapboxMap().cameraState.zoom)
                        .center(getMapboxMap().cameraState.center)
                        .build()
      val currentBbox = mapView.getMapboxMap().coordinateBoundsForCamera(options)

     }
```

That looks a bit overkilled but it is what it is
