### ISSUE TITLE
Java code

### ISSUE THREAD

**Issue by rez20004** [mapbox/mapbox-maps-android#1258]
How do we get the Java code? I see kotlin everywhere.

**Comment by ZiZasaurus** [comment]
@rez20004 the current [API documentation](https://docs.mapbox.com/android/maps/api/10.4.0/mapbox-maps-android/) works for both Kotlin and Java. We have some Java examples [here](https://github.com/mapbox/mapbox-maps-android/tree/main/app/src/main/java/com/mapbox/maps/testapp/examples/java) and also try to make our code base java friendly, however Kotlin as a language is compatible with Java. 

Please note that while we will continue to ensure that the SDK can be used by Java, there are no plans to create Java versions of our existing Kotlin code snippets or examples.
