### ISSUE TITLE
MapboxOptions singleton across multiple map instances

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-maps-android#126]
## Environment

- Maps SDK Version: v10.0.0-beta.13

## Observed behavior and steps to reproduce

Inflate a `MapView` that defines some attributes via XML.

Inflate another `MapView` instance in the same app process with different XML attributes.

The second map instance will use the options of the first map instance.

## Expected behavior

Both map instances have different options as defined in the XMLs.

## Notes / preliminary analysis

I haven't thoroughly tested this but looking at the code:
https://github.com/mapbox/mapbox-maps-android/blob/68d12be295cf47f3a5fdff652eed866c42c23237/sdk/src/main/java/com/mapbox/maps/MapboxMapOptions.kt#L64-L68

`MapboxOptions.isInitialized()` will return `true` for the second map instance, so it will inherit the options from the first instance. 

/cc @mapbox/maps-android

**Comment by tobrun** [comment]
The mentioned class has been fully revisited and removed. MapInitOptions should not have any shared state anymore
