### ISSUE TITLE
Showing accuracy ring with coarse location permission

### ISSUE THREAD

**Issue by ittna** [mapbox/mapbox-maps-android#1273]
## Environment

- Android OS version: 12
- Maps SDK Version: 10.4.1

## Observed behavior and steps to reproduce

Accuracy ring doesn't show around location puck. I tried with both fine and coarse location permission. Also is there someway to set that accuracy ring would show only with coarse location permission and location puck would show only with fine location permission or do I have to change location puck configuration based on permissions?

```
mapView.location2.updateSettings2 {
    showAccuracyRing = true
}
```

## Expected behavior

Accuracy ring would show with coarse location permission.

**Comment by ZiZasaurus** [comment]
@ittna please take a look at our [BasicPulsingCircleActivity](https://github.com/mapbox/mapbox-maps-android/blob/sd-accessibility-activity/app/src/main/java/com/mapbox/maps/testapp/examples/BasicLocationPulsingCircleActivity.kt) to see the implementation for the pulsing accuracy ring. 

When it comes to how/ when you would like the accuracy ring to show, this implementation would be handled by you.

**Comment by ittna** [comment]
I don't want pulsing circle. I only want to show accuracy ring for the coarse location permission same way as Google Maps does it.

**Comment by ZiZasaurus** [comment]
@ittna our [LocationComponentActivity](https://github.com/mapbox/mapbox-maps-android/blob/main/app/src/main/java/com/mapbox/maps/testapp/examples/LocationComponentActivity.kt) demonstrates enabling and disabling the accuracy ring: 

```
binding.mapView.location2.showAccuracyRing = true
```

**Comment by ArthurCowboy** [comment]
@ittna were you able to make it work? 
@ZiZasaurus tried to fork the repo, gave coarse permission and the accuracyRing is not working. It is working only for the precise location. Is there something I'm missing?

**Comment by ittna** [comment]
No, bug still exists. For our app coarse location is not that important though so it is not a blocker. I would still appreciate if mapbox would fix it.
