### ISSUE TITLE
Vector API unwanted requests 

### ISSUE THREAD

**Issue by Christophe668** [mapbox/mapbox-maps-android#1284]
**Mapbox Navigation SDK version:** 2.3

Hi, 

We are trying to investigate why we have such a huge pike on the Vector API.
We released an app update on the 28th of March with the migration from 1.* to 2.3.
In one day, we had 180.000 requests and then nothing after.
Do you have maybe an idea where this could come from?

<img width="1276" alt="Screenshot 2022-04-06 at 10 15 03" src="https://user-images.githubusercontent.com/1552554/161928475-d1e642f8-ee17-4b76-90b1-b67a3b7fdd9c.png">

Your help would be very much appreciated.

Thanks

**Comment by ZiZasaurus** [comment]
@Christophe668, as this is more of a product support Issue, please create a support ticket at https://support.mapbox.com/hc/en-us/ and our support team will be happy to get you the answers you need.
