### ISSUE TITLE
LocationProvider is null in the LocationComponentPlugin

### ISSUE THREAD

**Issue by mhille3** [mapbox/mapbox-maps-android#1298]
## Environment

- Android OS version: 11
- Devices affected: Desktop Head Unit, LG G8s
- Maps SDK Version: 10.4.0

## Observed behavior and steps to reproduce

So basically I tried to display the mapbox map on Android Auto. The sample app does that, with location updates.
To make it more comfortable to me, I took the parts I needed and translated them to java. 
After many hard errors, I figured it out and it now displays a map. 

In the CarCameraController you want to take the LocationComponentPlugin and its fellow listeners.
I get it via getPlugin(Plugin.MAPBOX_LOCATION_COMPONENT_PLUGIN_ID).

But for me it comes without a LocationProvider, not even the default one. I tried to create one, but that does not trigger any location updates.

If someone could help me somehow, i would appreciate it very much.

Kind regards
Marco

**Comment by yunikkk** [comment]
@mhille3 hi, could you please share the code you're running?

**Comment by mhille3** [comment]
Had to share in txt or zip, so i hope the one script is enough

[CarCameraController.txt](https://github.com/mapbox/mapbox-maps-android/files/8540875/CarCameraController.txt)

**Comment by mhille3** [comment]
Bump, because i really need help on that

**Comment by mhille3** [comment]
+help

**Comment by ZiZasaurus** [comment]
@mhille3 sorry your response was not seen sooner. I'd be happy to assist. Were you able to get this behavior resolved?

**Comment by ZiZasaurus** [comment]
Closing this ticket, but please feel free to reopen if you continue to experience this behavior.
