### ISSUE TITLE
MapView keeps getting destroyed on Fragment Navigation, leading to ugly grey background being displayed

### ISSUE THREAD

**Issue by stolzda** [mapbox/mapbox-maps-android#1299]
We have a MapView, which is displayed in a Fragment. The problem we face, is that when the user navigates to a different Fragment and back, the MapView is always recreated, which leads to an ugly grey flickering.

We would like to somehow persist either the MapView, or the state of the Map, to allow for a faster recreation. 

I couldn't find anything on how to persist the MapView state across fragment navigation.

**Comment by ZiZasaurus** [comment]
@stolzda the mapview is bound to the lifecycle of the fragment that contains it. When navigating between fragments, these fragments are destroyed and recreated, so is the mapview. This guarantees that the mapview doesn’t leak memory during the fragment re-creation process, or if the fragment is destroyed and never comes back.

There might be ways to increase the creation speed, for example minimize the runtime styling, use a lighter style, use cache(enabled by default if you don’t disable it specifically) etc.
