### ISSUE TITLE
Could not find method lintOptions() for arguments

### ISSUE THREAD

**Issue by JWKriti** [mapbox/mapbox-maps-android#1300]
I just cloned the mapbox repository from git and its throwing an error when trying to open it in studio:

A problem occurred evaluating project ':mapbox-lint'.
> Could not find method lintOptions() for arguments [build_7tuqtmtm9nc9vuh5i2bo73wts$_run_closure1@6573e068] on project ':mapbox-lint' of type org.gradle.api.Project.

**Comment by ZiZasaurus** [comment]
@JWKriti are you trying to build our example app? For that, all you should need is to enter your access token in the developer-config.xml file.

**Comment by JWKriti** [comment]
Hii, @ZiZasaurus,
i cloned the repo by  following these steps
$ git clone git@github.com:mapbox/mapbox-maps-android.git && cd mapbox-maps-android 
and opened mapbox-maps-android folder in studio, and it throws the error mentioned above.
Also am not able to find developer-config.xml file.

**Comment by ZiZasaurus** [comment]
@JWKriti we are not experiencing any issues cloning the repo on our end. As this appears to be more of a product support Issue, can you please create a support ticket at https://support.mapbox.com/hc/en-us/ and our support team will be happy to get you the answers you need.
