### ISSUE TITLE
Removed tile regions show as fully downloaded

### ISSUE THREAD

**Issue by ittna** [mapbox/mapbox-maps-android#1301]
## Environment

- Android OS version: 12
- Maps SDK Version: 10.4.2

## Observed behavior and steps to reproduce

```
tileStore.removeTileRegion("region")
```

After removing has finished region still shows as `region.completedResourceCount == region.requiredResourceCount`

After restart it shows correctly.

## Expected behavior

Tile region shows correctly as removed after removing has finished.

**Comment by ZiZasaurus** [comment]
@ittna `TileRegion` is a record/data class and is not mutable after construction. The best way to verify that your tile regions are removed would be to check that your array of style packs and/ or tile packs are empty like we do in our [Offline Activity](https://github.com/mapbox/mapbox-maps-android/blob/sd-accessibility-activity/app/src/main/java/com/mapbox/maps/testapp/examples/OfflineActivity.kt) example:

```kotlin
tileStore.getAllTileRegions { expected ->
      if (expected.isValue) {
        expected.value?.let { tileRegionList ->
          logInfoMessage("Existing tile regions: $tileRegionList")
        }
      }
      expected.error?.let { tileRegionError ->
        logErrorMessage("TileRegionError: $tileRegionError")
      }
    }
    // Get a list of style packs that are currently available.
    offlineManager.getAllStylePacks { expected ->
      if (expected.isValue) {
        expected.value?.let { stylePackList ->
          logInfoMessage("Existing style packs: $stylePackList")
        }
      }
```

**Comment by ittna** [comment]
@ZiZasaurus I did fetch them again with getAllTileRegions and it didn't give empty region array.

**Comment by ZiZasaurus** [comment]
@ittna after executing `removeStylePack()` and `removeTileRegion()`, the style packs and tile regions are still in the local storage, and they will be overwritten by new data when the maximum cache size is reached. However, if you use the `clearData` method, like in our [Offline Activity example](https://github.com/mapbox/mapbox-maps-android/blob/428a50f20df2a65736af10dae68ca66b0309946a/app/src/main/java/com/mapbox/maps/testapp/examples/OfflineActivity.kt#L301) it will clean up the database immediately.

**Comment by ittna** [comment]
Thanks, actually my code didn't call getAllTileRegions as I expected. I got it working now and calling clearData doesn't seem to be necessary for this use case either.
