### ISSUE TITLE
Add convenient geographical methods for BoundingBox and CoordinateBounds.

### ISSUE THREAD

**Issue by pengdev** [mapbox/mapbox-maps-android#131]
## New Feature

This ticket tracks adding the geographic convenient methods like `center`, `contains`, `union` to the `BoundingBox` and `CoordinateBounds`.

## Why

These functions are available in v9, it would be good to provide these utility functions to v10.

**Comment by tobrun** [comment]
Todo ticket upstream

**Comment by yuryybk** [comment]
could you pls add `intersect` too?

**Comment by kiryldz** [comment]
> could you pls add `intersect` too?

yes
closing in favor of more modern ticket: https://github.com/mapbox/mapbox-maps-android/issues/182
