### ISSUE TITLE
GesturesPlugin with rotate and zoom does not present to ViewportPlugin as user gesture

### ISSUE THREAD

**Issue by purdyk** [mapbox/mapbox-maps-android#1312]
### Background
We're using the viewport plugin with our project, and have the expectation that user interaction with the map will cause our viewport to transition to the Idle state.

This is working well except for rotation gestures, which cause the map to rotate out from under the user's fingers every time a location update comes through.

### Analysis 
This is a result of the code block found here:
https://github.com/mapbox/mapbox-maps-android/blob/main/plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPluginImpl.kt#L906

Which plays the bearing and anchor animations together, both with tag `GESTURES`.
The camera animations framework converts these to the tag `INTERNAL`
https://github.com/mapbox/mapbox-maps-android/blob/main/plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImpl.kt#L785

Which the viewport plugin disregards.

**Comment by pengdev** [comment]
@purdyk Thanks for the detailed report and analysis, there's indeed issue with the animator owner originated from the rotation gestures, I've prepared a fix at https://github.com/mapbox/mapbox-maps-android/pull/1345. Thanks for the contribution!
