### ISSUE TITLE
locationConsumer->onLocationUpdates does not include altitude

### ISSUE THREAD

**Issue by jimduchek** [mapbox/mapbox-maps-android#1320]
## New Feature
Honestly, I kind of feel like this is almost a bug report, though perhaps more an 'oversight report'.  in the DefaultLocationProvider, the consumer is sent the new location with:

`consumer.onLocationUpdated(Point.fromLngLat(location.longitude, location.latitude))`

when it should be: 

```
if (location.hasAltitude()) { 
    consumer.onLocationUpdated(Point.fromLngLat(location.longitude, location.latitude, location.altitude))
} else {
    consumer.onLocationUpdated(Point.fromLngLat(location.longitude, location.latitude))
}
```

This passes on the hasAltitude() status properly, but 99% of the time if we're on GPS, altitude will be provided, and that ought to be passed on.

## Why
There is basically no reason not to pass this data on, as Point already supports it, and Location has the info.  Altitude is an important part of the location information for some (my :D) apps.

**Comment by pengdev** [comment]
Thanks for the feedback, it will be fixed by https://github.com/mapbox/mapbox-maps-android/pull/1478
