### ISSUE TITLE
Documentation on viewport orientation tracking

### ISSUE THREAD

**Issue by tir38** [mapbox/mapbox-maps-android#1322]
## New Feature

_Not sure if this is a feature with missing documentation, or not (yet) a feature in v10._

I'm migrating from v9 to v10. Previously I could switch between tracking the compass or not, when also tracking users location

```
val trackOrientation :Boolean = ... 

mapView?.getMapboxMap()!!.locationComponent.apply {
    activateLocationComponent(locationComponentActivationOptions)
    isLocationComponentEnabled = true
    cameraMode = if (trackOrientation) TRACKING_COMPASS else TRACKING
}
```

I now see that this is handled by the `viewport` plugin, not by location component. I'm following along [the sample](https://github.com/mapbox/mapbox-maps-android/blob/main/app/src/main/java/com/mapbox/maps/testapp/examples/viewport/ViewportShowcaseActivity.kt#L124) but I don't see how this is configurable. Currently this _always_ tracks orientation and location

```
mapView?.viewport?.apply {
    transitionTo(
        makeFollowPuckViewportState(
            FollowPuckViewportStateOptions.Builder()
                .pitch(0.0) // keep birds-eye view
                .build()
        )
    )
}
```

How can I do the same thing in v10?

**Comment by yunikkk** [comment]
@tir38 please use [FollowPuckViewportStateOptions.bearing](https://docs.mapbox.com/android/maps/api/10.5.0/mapbox-maps-android/com.mapbox.maps.plugin.viewport.data/-follow-puck-viewport-state-options/#%5Bcom.mapbox.maps.plugin.viewport.data%2FFollowPuckViewportStateOptions%2Fbearing%2F%23%2FPointingToDeclaration%2F%5D%2FProperties%2F1136490705) if you want to disable bearing and just track location of the puck. There's also an example for this api https://github.com/mapbox/mapbox-maps-android/blob/main/app/src/main/java/com/mapbox/maps/testapp/examples/viewport/AdvancedViewportGesturesExample.kt#L57

**Comment by kiryldz** [comment]
Stale, outdated.
