### ISSUE TITLE
Crash with "shader failed to compile" on Android 6

### ISSUE THREAD

**Issue by akirmse** [mapbox/mapbox-maps-android#1367]
## Environment

- Android OS version: 6.0
- Devices affected: Alcatel Pixi4 9003X
- Maps SDK Version: 10.4.0

I'm seeing crashes in the wild with this stack trace.  Sorry there's not more info.  It's only from this one device.

Fatal Exception: java.lang.Error: shader failed to compile
       at com.mapbox.maps.Map.render(Map.java)
       at com.mapbox.maps.NativeMapImpl.render(NativeMapImpl.kt:32)
       at com.mapbox.maps.renderer.MapboxRenderer.render(MapboxRenderer.kt:125)
       at com.mapbox.maps.renderer.MapboxRenderThread.draw(MapboxRenderThread.kt:253)
       at com.mapbox.maps.renderer.MapboxRenderThread.doFrame(MapboxRenderThread.kt:420)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:892)
       at android.view.Choreographer.doCallbacks(Choreographer.java:696)
       at android.view.Choreographer.doFrame(Choreographer.java:628)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:880)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:207)
       at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by kiryldz** [comment]
@akirmse is terrain used in style?

**Comment by akirmse** [comment]
Yes:

```
        mMap.loadStyle(
            styleExtension = style(Style.SATELLITE_STREETS) {
                +rasterDemSource("TERRAIN_SOURCE") {
                    url("mapbox://mapbox.mapbox-terrain-dem-v1")
                    // 514 specifies padded DEM tile and provides better performance than 512 tiles.
                    tileSize(514)
                }
                +terrain("TERRAIN_SOURCE") {
                    exaggeration(MapConstants.TERRAIN_VERTICAL_EXAGGERATION)
                }
                +skyLayer("sky") {
                    skyType(SkyType.ATMOSPHERE)
                    skyAtmosphereColor(SKY_ATMOSPHERE_COLOR)
                    skyAtmosphereHaloColor(SKY_ATMOSPHERE_HALO_COLOR)
                    skyAtmosphereSun(listOf(skyAtmosphereCenterA, skyAtmosphereCenterP))
                    skyAtmosphereSunIntensity(skyAtmosphereSunIntensity)
                }
            },
```

**Comment by kiryldz** [comment]
That should be fixed in v10.5.0, see:
- Disable terrain rendering if GPU does not support Vertex Texture Fetch. https://github.com/mapbox/mapbox-maps-android/pull/1315

**Comment by akirmse** [comment]
OK, thanks.

Is there a way to detect whether terrain rendering is enabled?  I have a button labeled "3D", and if it doesn't actually draw 3D, that's not great.

**Comment by kiryldz** [comment]
There's no dedicated API for it but I did come up with following code:
```kotlin
    mapView.queueEvent({
      val resultBuffer = IntBuffer.allocate(1)
      GLES20.glGetIntegerv(GLES20.GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS, resultBuffer)
      resultBuffer.rewind()
      val result = resultBuffer.get()
      if (result > 0) {
        logI("TAG", "3D terrain supported")
      } else {
        logI("TAG", "3D terrain not supported")
      }
    }, needRender = false)
```
That could be called right after `MapView` is created and in general in any moment of time I assume.

**Comment by akirmse** [comment]
I would need a way to detect this in advance.  i.e. if terrain rendering isn't supported, I wouldn't show a 3D button or in fact use Mapbox at all (I use Google for all other modes).  Some kind of static method encapsulating the GL call would be best.  I suppose I could make the GL call myself but that's a Mapbox detail that's best kept hidden.

**Comment by kiryldz** [comment]
> I would need a way to detect this in advance. i.e. if terrain rendering isn't supported, I wouldn't show a 3D button or in fact use Mapbox at all (I use Google for all other modes). Some kind of static method encapsulating the GL call would be best. I suppose I could make the GL call myself but that's a Mapbox detail that's best kept hidden.

The code I've provided in https://github.com/mapbox/mapbox-maps-android/issues/1367#issuecomment-1130119099 is exactly what you need, it will execute on render thread in correct moment of time. So from what I understand on app startup you do not yet show button 3D, perform this check and based on result show / not show 3D button.

**Comment by akirmse** [comment]
Sorry, I should have been clearer.  I need a way to detect whether Mapbox supports terrain rendering *without* creating a Mapbox MapView.  If terrain rendering is not supported, then I will never create a Mapbox MapView; I will use only a Google MapView.

**Comment by kiryldz** [comment]
I've prepared PR with the static method on `MapView`, see https://github.com/mapbox/mapbox-maps-android/pull/1368

**Comment by kiryldz** [comment]
Static method `MapView.isTerrainRenderingSupported()` will be introduced in `v10.6.0-beta.1` happening tomorrow. I'll close this issue but feel free to re-open if something unexpected will pop-up.
