### ISSUE TITLE
Setting puckBearingEnabled to false does not reset bearing

### ISSUE THREAD

**Issue by jonschmidt** [mapbox/mapbox-maps-android#1376]
## Environment

- Android OS version: 12
- Devices affected: all
- Maps SDK Version: 10.5

## Observed behavior and steps to reproduce

We have a few different map modes that we transition between. One shows the bearing on the user location puck. One does not (should always be orientated north). When we transition from the one that shows bearing to the one that doesn't, the bearing is still applied, so the location  "topImage" is rotated to whatever it was when we were showing bearing.

## Expected behavior

Disabling bearing should also reset bearing.

**Comment by OmarShehe** [comment]
Hi, @jonschmidt. 
Did you manage to find a workaround for this issue?

**Comment by OmarShehe** [comment]
It will be a good idea for the location puck to get reset after disabling it. Or to have an option to update the bearing manually.

**Comment by jonschmidt** [comment]
Hi @OmarShehe , sorry for the late reply. No, we actually disabled the bearing because of this and are on hold until we figure something out

**Comment by ZiZasaurus** [comment]
This behavior has been resolved in 10.9.
