### ISSUE TITLE
Default Marker elevation arrangement

### ISSUE THREAD

**Issue by Lokarzz** [mapbox/mapbox-maps-android#1392]
Current problem is marker are overlapping each other. How do we prioritize a marker to be on top for all of them. I'm using PointAnnotation. 

Tried the geometry but no luck on this code
prioritizePointAnnotation.point = Point.fromLngLat(long, lat, 10)
defaultPointAnnotation.point = Point.fromLngLat(long, lat, -10)

![image](https://user-images.githubusercontent.com/15919408/170198557-134c2132-384a-4804-9c70-6bb6a77de673.png)

**Comment by ZiZasaurus** [comment]
@Lokarzz, you can use the [symbolSortKey](https://docs.mapbox.com/android/maps/api/10.5.0/mapbox-maps-android/com.mapbox.maps.plugin.annotation.generated/-point-annotation/#%5Bcom.mapbox.maps.plugin.annotation.generated%2FPointAnnotation%2FsymbolSortKey%2F%23%2FPointingToDeclaration%2F%5D%2FProperties%2F1136490705) property, which will allow you to sort your features in ascending order.
