### ISSUE TITLE
libEGL error

### ISSUE THREAD

**Issue by SamuelBrucksch** [mapbox/mapbox-maps-android#1397]
Hi,

we have an android app that uses mapbox for android auto. Sometimes we see an error like this:
```
2022-04-24 08:16:54.219 21096-21261/com.iternio.abrpapp E/libEGL: eglCreateWindowSurfaceTmpl:676 error 3003 (EGL_BAD_ALLOC)
2022-04-24 08:16:54.219 21096-21261/com.iternio.abrpapp E/Mbgl-EglCore: eglCreateWindowSurface: EGL error: 0x3003
2022-04-24 08:16:54.220 21096-21261/com.iternio.abrpapp E/libEGL: eglCreateWindowSurface: native_window_api_connect (win=0x7938f806d0) failed (0xffffffea) (already connected to another API?)
```
This error repeats every few miliseconds and spams the log a lot so we can not really see the error that ocurred.

I'm not really sure if it is related to mapbox, but i haven't seen it before, when we still used osmdroid. However it could as well be related to Android Auto, but the behaviour we see is that android auto behaves normally, even updates all the UIs like distance and instructions on the car display, but the map is frozen.

For some people it happens when switching to other apps and back, so maybe related to the lifecycle. I also saw it a few times during development and thought it migth have been an issue with the emulator, when installing a new testversion and the old version was still running.

We currently use
```
    implementation ("com.mapbox.maps:android:10.3.0-rc.1") 
    implementation ('com.mapbox.plugin:maps-locationcomponent:10.3.0-rc.1')
```

And our code for SurfaceCallback is this:
```
    private final SurfaceCallback mSurfaceCallback = new SurfaceCallback() {

        @Override
        public void onSurfaceAvailable(@NonNull SurfaceContainer surfaceContainer) {
            synchronized (MapRenderer.this) {
                if (surfaceContainer.getSurface() == null)
                    return;

                String savedStyle = getMapStyleFromPreferences(getMapTypeFromPreferences());
                // setup map first to not load mapbox specific styles accidentally
                MapInitOptions options = new MapInitOptions(mCarContext,
                        resourceOptions,
                        new MapOptions.Builder().build(),
                        Arrays.asList(new Plugin.Mapbox(Plugin.MAPBOX_CAMERA_PLUGIN_ID), new Plugin.Mapbox(Plugin.MAPBOX_LOCATION_COMPONENT_PLUGIN_ID)),
                        currentCamera.build(),
                        false,
                        savedStyle,
                        null);

                Surface s = surfaceContainer.getSurface();
                mapSurface = new MapSurface(mCarContext, s, options);
                mapSurface.setMaximumFps(60);
                mapSurface.onStart();
                mapSurface.surfaceCreated();
                mapSurface.surfaceChanged(width, height);

                mapboxMap = mapSurface.getMapboxMap();


            }
        }

        @Override
        public void onSurfaceDestroyed(@NonNull SurfaceContainer surfaceContainer) {
            synchronized (MapRenderer.this) {
                   if (mapSurface == null) {
                    Log.d(TAG, "MapSurface is null");
                    return;
                }

                ...
                mapSurface.onStop();
                mapSurface.surfaceDestroyed();
                mapSurface.onDestroy();

               ...
            }
        }
```

And in the lifecycle code we do this:
```
    @Override
    public void onDestroy(@NonNull LifecycleOwner owner) {
        if (mapSurface != null) {
            mapSurface.onStop();
            mapSurface.surfaceDestroyed();
            mapSurface.onDestroy();
        }
    }

    @Override
    public void onLowMemory() {
        Log.d(TAG, "onLowMemory");
        if (mapSurface != null) {
            mapSurface.onLowMemory();
        }
    }
```

Do you have any idea, what could cause the above error? It almost seams as if that error comes for each time the map tries to render, it is logged every few ms.

As for some people it happens when switching between apps in android auto, i could imagine that somethin in the lifecycle causes the surface not being cleaned up correctly or so. Any hints on that?

**Comment by kmadsen** [comment]
@SamuelBrucksch Are you using https://github.com/mapbox/mapbox-maps-android/releases/tag/extension-androidauto-v0.1.0? The framework is responsible for ensuring these issues do not happen.

If you are attempting to build your own wrapper around the maps sdk, it will need to be maintained separately - so please try to use the `extension-androidauto`

To help with the issue though, this is the code inside the SDK that is responsible for ensuring the map surface is destroyed https://github.com/mapbox/mapbox-maps-android/blob/6b0b4a0925f4655bab7c4bdc443a33343d65c881/extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/CarMapSurfaceOwner.kt#L68-L70

**Comment by SamuelBrucksch** [comment]
I can reproduce this behaviour, when our app is running on AA and currently active on the screen. If I then install a new version of our app, while the current app is still running, I see this libEGL error.

I also tried it with the sample app, and i can reproduce the same behaviour. Just install it, start it and while it is active on the screen install it again and you should see lot's of these libEGL errors.

Not sure if this is a valid test and is the same situation as the user has, but it is the only way to reproduce this for me now...

**Comment by kmadsen** [comment]
> I also tried it with the sample app, and i can reproduce the same behaviour. Just install it, start it and while it is active on the Android Auto screen install it again and you should see lot's of these libEGL errors.

Ok I can reproduce with this as well. 

```
2022-06-06 14:04:52.885 15926-15926/com.mapbox.maps.testapp.auto I/Mapbox: [maps-android\CarMapSurfaceCallback]: onSurfaceAvailable [Surface(name=null)/@0x751b2d2, 800x400, dpi: 160]
2022-06-06 14:04:53.019 15926-15926/com.mapbox.maps.testapp.auto I/Mapbox: [maps-android\CarMapSurfaceCallback]: onVisibleAreaChanged visibleArea:Rect(0, 112 - 716, 400)
2022-06-06 14:04:59.038 16390-16390/com.mapbox.maps.testapp.auto I/Mapbox: [maps-android\CarMapSurfaceCallback]: onSurfaceAvailable [Surface(name=null)/@0xd737d66, 800x400, dpi: 160]
2022-06-06 14:04:59.208 16390-16420/com.mapbox.maps.testapp.auto E/libEGL: eglCreateWindowSurface: native_window_api_connect (win=0xb40000753a1a12b0) failed (0xffffffea) (already connected to another API?)
2022-06-06 14:04:59.208 16390-16420/com.mapbox.maps.testapp.auto E/libEGL: eglCreateWindowSurfaceTmpl:676 error 3003 (EGL_BAD_ALLOC)
2022-06-06 14:04:59.208 16390-16420/com.mapbox.maps.testapp.auto E/Mapbox: [maps-android\Mbgl-EglCore]: eglCreateWindowSurface: EGL error: 0x3003
2022-06-06 14:04:59.256 16390-16390/com.mapbox.maps.testapp.auto I/Mapbox: [maps-android\CarMapSurfaceCallback]: onVisibleAreaChanged visibleArea:Rect(0, 112 - 716, 400)
2022-06-06 14:04:59.259 16390-16420/com.mapbox.maps.testapp.auto E/libEGL: eglCreateWindowSurface: native_window_api_connect (win=0xb40000753a1a12b0) failed (0xffffffea) (already connected to another API?)
2022-06-06 14:04:59.259 16390-16420/com.mapbox.maps.testapp.auto E/libEGL: eglCreateWindowSurfaceTmpl:676 error 3003 (EGL_BAD_ALLOC)
2022-06-06 14:04:59.259 16390-16420/com.mapbox.maps.testapp.auto E/Mapbox: [maps-android\Mbgl-EglCore]: eglCreateWindowSurface: EGL error: 0x3003
2022-06-06 14:04:59.311 16390-16420/com.mapbox.maps.testapp.auto E/libEGL: eglCreateWindowSurface: native_window_api_connect (win=0xb40000753a1a12b0) failed (0xffffffea) (already connected to another API?)
2022-06-06 14:04:59.311 16390-16420/com.mapbox.maps.testapp.auto E/libEGL: eglCreateWindowSurfaceTmpl:676 error 3003 (EGL_BAD_ALLOC)
2022-06-06 14:04:59.311 16390-16420/com.mapbox.maps.testapp.auto E/Mapbox: [maps-android\Mbgl-EglCore]: eglCreateWindowSurface: EGL error: 0x3003
2022-06-06 14:04:59.362 16390-16420/com.mapbox.maps.testapp.auto E/libEGL: eglCreateWindowSurface: native_window_api_connect (win=0xb40000753a1a12b0) failed
```

`onSurfaceDestroyed` is never called when there is a reload with the `desktop_head_unit`. That is not actually a production use case, unless the android auto system creates this same behavior when attach/detaching the head unit. In that case, it's an issue to send to https://issuetracker.google.com/u/0/issues?q=componentid:460472

**Comment by kmadsen** [comment]
> And in the lifecycle code we do this:
```
    @Override
    public void onDestroy(@NonNull LifecycleOwner owner) {
        if (mapSurface != null) {
            mapSurface.onStop();
            mapSurface.surfaceDestroyed();
            mapSurface.onDestroy();
        }
    }
```

I don't think this is needed. The surface destroy call is called before a car session is destroyed. It's not fixing the libEGL error, but it is not making it worse either.

**Comment by SamuelBrucksch** [comment]
Ok so I will add some logging for that user if onSurfaceDestroyed and onSurfaceCreated is called correctly, and if not, I will open an issue at Google and if both are correctly called I will report back here.

**Comment by kmadsen** [comment]
https://issuetracker.google.com/u/0/issues/235121269

@SamuelBrucksch I just made an issue for this :)

**Comment by SamuelBrucksch** [comment]
Great, thanks. Will add my findings to that issue then if there are any...

**Comment by SamuelBrucksch** [comment]
Is this possible from our app too? Then I could add that as well and check if it works for that user. This shouldn't work for the re-installation though, as it is a seperate instance.... Do you have a code snipped i could try?

**Comment by kmadsen** [comment]
I just tried it and it doesn't help. the android auto car library would need to tell us to destroy the surface. The surface continues to exist in the desktop head unit, and any downstream application will have no way to clean up an old surface

https://github.com/mapbox/mapbox-maps-android/issues/1397#issuecomment-1147944018

if that happens on production, that would definitely be a memory leak that the google car team would want to fix.

**Comment by SamuelBrucksch** [comment]
Ok then I'll verify that with more logging.

**Comment by SamuelBrucksch** [comment]
Got the logs and it actually looks like "onSurfaceAvailable" is called two times right after another:
```
06-07 11:32:19.838 10438  7917  7917 D MapRenderer: onPause
06-07 11:32:19.867 10438  7917  7917 D MapRenderer: onStop
06-07 11:32:19.868 10438  7917  7917 D MapRenderer: onSurfaceDestroyed
06-07 11:32:19.868 10438  7917  7917 D MapRenderer: clearing mapbox map listeners
06-07 11:32:19.873 10438  7917  7917 D MapRenderer: mapSurface.onStop()
06-07 11:32:19.880 10438  7917  7917 D MapRenderer: mapSurface.surfaceDestroyed()
06-07 11:32:19.909 10438  7917  7917 D MapRenderer: mapSurface.onDestroy()
06-07 11:32:37.381 10438  7917  7917 D MapRenderer: onStart
06-07 11:32:37.430 10438  7917  7917 D MapRenderer: onResume
06-07 11:32:37.461 10438  7917  7917 D MapRenderer: onSurfaceAvailable: surface is not null
06-07 11:32:37.576 10438  7917  7917 D MapRenderer: Cache size: 128
06-07 11:32:37.637 10438  7917  7917 D MapRenderer: onSurfaceAvailable: surface is not null
06-07 11:32:37.701 10438  7917 24593 D libEGL  : ANGLE Info:Debug.cpp:490 (insertMessage): EGL ERROR: eglCreateWindowSurface: Internal Vulkan error (-1000000001): The requested window is already connected to a VkSurfaceKHR, or to some other non-Vulkan API, in ../../src/libANGLE/renderer/vulkan/android/WindowSurfaceVkAndroid.cpp, createSurfaceVk:32.
06-07 11:32:37.701 10438  7917  7917 D MapRenderer: Cache size: 128
06-07 11:32:37.704 10438  7917 24593 D libEGL  : ANGLE Info:Debug.cpp:490 (insertMessage): EGL ERROR: eglCreateWindowSurface: Internal Vulkan error (-1000000001): The requested window is already connected to a VkSurfaceKHR, or to some other non-Vulkan API, in ../../src/libANGLE/renderer/vulkan/android/WindowSurfaceVkAndroid.cpp, createSurfaceVk:32.
06-07 11:32:37.704 10438  7917 24593 D libEGL  : ANGLE Info:Debug.cpp:490 (insertMessage): EGL ERROR: eglCreateWindowSurface: Internal Vulkan error (-1000000001): The requested window is already connected to a VkSurfaceKHR, or to some other non-Vulkan API, in ../../src/libANGLE/renderer/vulkan/android/WindowSurfaceVkAndroid.cpp, createSurfaceVk:32.
```

Then a possible solution might be to check if a mapsurface already exists and if so destroy it and create a new one... However that is actually just a workaround rather than a solution. Will let google know about this log.

I'll check if the workaround works with the user and let you know.

**Comment by SamuelBrucksch** [comment]
So on a first quick test the user said it worked, did not get another report yet for a longer test where he did more switching between the app.

My workaround looks like this:
```
        public void onSurfaceAvailable(@NonNull SurfaceContainer surfaceContainer) {
            synchronized (MapRenderer.this) {
                ...

                if (mapSurface != null) {
                    // if this is called twice shut down previous mapbox instance
                    shutdownMapbox();
                }

               ... // mapbox initialization
            }
        }

        private void shutdownMapbox() {
            if (mapboxMap != null) {
                mapboxMap.removeOnCameraChangeListener(MapRenderer.this::onCameraChanged);
                mapboxMap.removeOnStyleImageMissingListener(MapRenderer.this::onStyleImageMissing);
                mapboxMap.removeOnStyleLoadedListener(MapRenderer.this::onStyleLoaded);
                mapboxMap.removeOnRenderFrameFinishedListener(MapRenderer.this::onRegionChange);
            }

            if (mapSurface != null) {
                mapSurface.onStop();
                mapSurface.surfaceDestroyed();
                mapSurface.onDestroy();
            }

            mapboxMap = null;
            mapSurface = null;
        }
```

My proposal here would also be to offer a function, to update the surface of the mapbox, if that is possible. Because then we could initialize the MapSurface only once, and just update the Surface every time onSurfaceAvailable is called. Not sure if that makes sense fom mapbox perspective, but would avoid to reinitilize mapbox all the time. @kmadsen what do you think?

**Comment by kmadsen** [comment]
> My proposal here would also be to offer a function, to update the surface of the MapSurface, if that is possible. Like mapSurface.surfaceChanged(surface) Because then we could initialize the MapSurface only once, and just update the Surface every time onSurfaceAvailable is called. Not sure if that makes sense fom mapbox perspective, but would avoid to reinitilize mapbox all the time. @kmadsen what do you think?

Considering this surfaceChanged function, the purpose of it would be to simplify the interactions with the mapSurface? There is a solution available for simplifying map interactions with android auto in the extension https://github.com/mapbox/mapbox-maps-android/issues/1397#issuecomment-1147778664. It is designed to work well with surface recreation because android auto will recreate the surface when you open the search screen and back to the map. 

Can you use the [MapboxCarMap](https://github.com/mapbox/mapbox-maps-android/blob/5dfc8a87b0cebf3b96310c4ea0ce7b41f5c25df1/extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/MapboxCarMap.kt#L34-L36) to help with the surface interactions?

The MapSurface definition is under an api contract, so the changes to that API requires a lot of justification. Notice how the [surface is passed to the constructor](https://github.com/mapbox/mapbox-maps-android/blob/5dfc8a87b0cebf3b96310c4ea0ce7b41f5c25df1/sdk/src/main/java/com/mapbox/maps/MapSurface.kt#L30-L34). Changing it would require a migration from downstream developers. Maybe still worth exploring, but I'm more interested in the reason why you don't want to use `MapboxCarMap`

cc: @SamuelBrucksch also sorry for the delay, am catching up on messages after a summer vacation

**Comment by kiryldz** [comment]
Stale, outdated.

**Comment by wcandillon** [comment]
@SamuelBrucksch your comment and bug report at https://issuetracker.google.com/u/0/issues/235172947 perfectly captures the issue we are seeing as well. I was wondering if you have more thoughts on this? I would like to understand this issue a bit deeper and see what workaround can be provided for this.

**Comment by SamuelBrucksch** [comment]
The only workaround is to check if the renderer is already initialized with the surface and if so recreate it.
