### ISSUE TITLE
When creating an Expression Stop small numbers are converted to scientific notation.

### ISSUE THREAD

**Issue by cafesilencio** [mapbox/mapbox-maps-android#143]
## Environment

- Android OS version:
- Devices affected:
- Maps SDK Version: 10.0.0-beta.13

## Observed behavior and steps to reproduce

With in the Nav. SDK we have a feature that calculates the percentage of a route that has been traveled and create a gradient line to indicate the route traveled has one color and the route yet to travel has a different color. 

The value for the percentage traveled can be a very small number. A customer reported a crash that occurred when two of the values used for the Expression.Stop were converted to scientific notation.  It appears values smaller than 0.001 will get converted to scientific notation rather than the literal decimal number.  

## Expected behavior

I put in a fix on the Nav. SDK side to filter out values below 0.001 but perhaps there's something that can be done on the Maps SDK side to address this as well.

## Notes / preliminary analysis

From the customer's stack trace:
03-01 17:17:32.563  9369  9369 E AndroidRuntime: java.lang.RuntimeException: Set layer property "line-gradient" failed:
03-01 17:17:32.563  9369  9369 E AndroidRuntime: [743]: Input/output pairs for "step" expressions must be arranged with input values in strictly ascending order.
03-01 17:17:32.563  9369  9369 E AndroidRuntime: [step, [line-progress], [rgba, 0.0, 0.0, 0.0, 0.0], 0.0, [rgba, 86.0, 168.0, 251.0, 1.0], 7.875125394489743E-4, [rgba, 255.0, 149.0, 0.0, 1.0], 9.88627405946961E-4, [rgba, 86.0, 168.0, 251.0, 1.0], 0.0011926985676139702, [rgba, 255.0, 149.0, 0.0, 1.0], 0.0013977277614471628,  ...

Here's some code to produce this similar to what's being done in the Nav. SDK:

```
        val expressionBuilder = Expression.ExpressionBuilder("step")
        expressionBuilder.lineProgress()
        expressionBuilder.stop {
            rgba {
                literal(0.0)
                literal(0.0)
                literal(0.0)
                literal(0.0)
            }
        }

        expressionBuilder.stop {
            literal(0.0007875125394489743)
            color(0)
        }
        expressionBuilder.stop {
            literal(0.000988627405946961)
            color(0)
        }
        expressionBuilder.stop {
            literal(0.001)
            color(0)
        }
        expressionBuilder.stop {
            literal(0.0011926985676139702)
            color(0)
        }
        expressionBuilder.stop {
            literal(0.0013977277614471628)
            color(0)
        }

        
    expressionBuilder.build().toString()
    //[step, [line-progress], [rgba, 0.0, 0.0, 0.0, 0.0], 7.875125394489743E-4, [rgba, 0.0, 0.0, 0.0, 0.0], 9.88627405946961E-4, 
    //[rgba, 0.0, 0.0, 0.0, 0.0], 0.001, [rgba, 0.0, 0.0, 0.0, 0.0], 0.0011926985676139702, [rgba, 0.0, 0.0, 0.0, 0.0], 
    //0.0013977277614471628, [rgba, 0.0, 0.0, 0.0, 0.0]]
```

**Comment by pengdev** [comment]
Hi @cafesilencio I think the crash shouldn't be caused by `the small numbers are converted to scientific notation` , we constructed Expression to a `Value` class which contains `List<Value>`, and numbers are saved as `Double` rather than string when passed to gl-native. In the above example, when printed in log, the `toString` method automatically convert the double to scientific notation.

You can try to use expression.toJson() instead of toString() to see the printed result as a Json string. The above mentioned example will be printed as:

```
expressionBuilder.build().toJson()

printed result:
["step",["line-progress"],["rgba",0.0,0.0,0.0,0.0],0.0007875125394489743,["rgba",0.0,0.0,0.0,0.0],0.000988627405946961,["rgba",0.0,0.0,0.0,0.0],0.001,["rgba",0.0,0.0,0.0,0.0],0.0011926985676139703,["rgba",0.0,0.0,0.0,0.0],0.0013977277614471628,["rgba",0.0,0.0,0.0,0.0]]
```

I think you could double check if the thrown error log is the cause: `Input/output pairs for "step" expressions must be arranged with input values in strictly ascending order.`

**Comment by cafesilencio** [comment]
After examining the expression more closely I can see there were two steps with the same value. This would account for the values not being in ascending order as there would be two duplicates.  Closing this issue.
