### ISSUE TITLE
Legacy Offline Manager set maxZoom per source

### ISSUE THREAD

**Issue by IolandaRosa** [mapbox/mapbox-maps-android#1445]
## New Feature

Allow download of high resolution tiles using legacy offline manager setting different zoom levels per source.

## Why
For offline map downloads, I use a style with multiple sources. 

The mapbox.satellite is one of the sources: 

- For this source, I only want to download tiles until maxzoom 18 (because this zoom level already allows for high-resolution tiles, and as the zoom level increases, the number of resources to download increases dramatically, which I don't want). 

However, for the other sources in the style, I want to be able to go until zoom level 21 because the tiles for zoom level 18 are insufficient for the app's purposes. 

I've already attempted to set the maxzoom level at the source level in the style, as shown below:

`"satellite-raster": {
      "url": "mapbox://mapbox.satellite",
      "type": "raster",
      "maxzoom": 18.0
    },`

When I download with the max zoom level set to 21, this property "maxzoom: 18" is ignored, and the satellite tiles appear until zoom level 21 is reached with a lot of resources being downloaded.

Is there a way to have the expected behaviour with the current Legacy Offline Manager? If not, I believe this would be a useful feature to add.

**Comment by ZiZasaurus** [comment]
@IolandaRosa can you please provide a sample app that reproduces this behavior so that we can see your implementation?

**Comment by ZiZasaurus** [comment]
@IolandaRosa our newer version v10.7 provides more control and should allow you to accomplish your use case. Are you able to test this out and let us know how it works for you?

**Comment by ZiZasaurus** [comment]
@IolandaRosa, closing this ticket but please feel free to reopen if you have additional questions.
