### ISSUE TITLE
load 3dtiles data

### ISSUE THREAD

**Issue by westlifeChen** [mapbox/mapbox-maps-android#1457]
## New Feature

Whether 3dtiles format data loading is supported?

## Why
<- 1-2 sentence description of why you're requesting this feature. What problem does it solve? Why is it valuable? ->

**Comment by ZiZasaurus** [comment]
@westlifeChen as this is more of a product support Issue, can you please create a support ticket at https://support.mapbox.com/hc/en-us/ and our support team will be happy to get you the answers you need.
