### ISSUE TITLE
[help wanted] iconOffset Expression

### ISSUE THREAD

**Issue by fantasyado** [mapbox/mapbox-maps-android#148]
Hi,
I want to set iconOffset using the expression way, It requires a float array but I don't know how to do it.  Searched in demo project but no luck, Could someone help me on this?

Thanks a lot.

**Comment by tobrun** [comment]
iconOffset expects a expression array:

``` 
     iconOffset(
        array {
          literal(2.0)
          literal(3.0)
        }
      )
```
