### ISSUE TITLE
GeoJSON symbol icon dissapears on some zoom levels

### ISSUE THREAD

**Issue by Dkhusainov** [mapbox/mapbox-maps-android#1496]
## Environment

- Android OS version: 28
- Devices affected:
- Maps SDK Version: 10.6.1

## Observed behavior and steps to reproduce

Add a source which is GeoJSON FeatureCollection of points

Add a layer:
```
  {
    id: "point"
    type: "symbol"
    source: "points"

    layout: {
      icon-image: "place"
    }
```

Add image to style:
```
style.addStyleImage(
        imageId = "place",
        image = image,
        sdf = false,
        scale = style.pixelRatio,
        stretchX = emptyList(),
        stretchY = emptyList(),
        content = null,
      )
```
## Expected behavior

Symbol icon always shows 

## Additional links and references

https://user-images.githubusercontent.com/7382654/178740600-1d51ddfe-ce11-41a3-b779-ac2bea585271.mp4

Reproducer:
[MyApplication2.zip](https://github.com/mapbox/mapbox-maps-android/files/9126479/MyApplication2.zip)
Notice how icon dissapears on zoom 15, This icon is from Mapbox [page about SDF images](https://docs.mapbox.com/help/troubleshooting/using-recolorable-images-in-mapbox-maps/)

**Comment by ZiZasaurus** [comment]
@Dkhusainov,  can you test the attached apk and show us that the symbol layer is still disappearing?
[symbol not vanishing.zip](https://github.com/mapbox/mapbox-maps-android/files/9132905/symbol.not.vanishing.zip)

**Comment by ZiZasaurus** [comment]
@Dkhusainov I am not experiencing the symbol layer disappearing. Are you able to restart your AS/ emulator or test in another emulator?

**Comment by Dkhusainov** [comment]
Restart doesn't help. I'm on Windows, maybe that's the cause

**Comment by ZiZasaurus** [comment]
@Dkhusainov i am not experiencing any issues on windows. Do you perhaps have another device that you can use to test?

**Comment by Dkhusainov** [comment]
Don't know what else to say. Happens on emulators with different architectures and different Android SKD versions. I guess the issue can be closed if it isn't reproducible anywhere else

**Comment by ZiZasaurus** [comment]
Closing for now, but please feel free to reopen if you continue to experience this issue.
