### ISSUE TITLE
FillExtrusionLayer cannot be transparent

### ISSUE THREAD

**Issue by kmadsen** [mapbox/mapbox-maps-android#150]
## Environment

- Maps SDK Version: 10.0.0-beta.13

## Observed behavior and steps to reproduce

<img width="368" alt="Screen Shot 2021-03-02 at 4 21 25 PM" src="https://user-images.githubusercontent.com/3021882/109733153-69b72d80-7b73-11eb-856b-024b74900031.png">

## Expected behavior

`var fillExtrusionColor = Color.argb(0xB2, 0xAA, 0xAA, 0xAA)`

Fill extrusion color has some transparency, so we expect to be able to see other buildings. Here is the draft where it is being reproduced https://github.com/mapbox/mapbox-navigation-android/pull/4078

**Comment by tobrun** [comment]
It can be if you use the right API :) 


From [fill-extrusion-color](https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#paint-fill-extrusion-) API:

> The base color of the extruded fill. The extrusion's surfaces will be shaded differently based on this color in combination with the root light settings. If this color is specified as rgba with an alpha component, the alpha component will be ignored; use fill-extrusion-opacity to set layer opacity.
