### ISSUE TITLE
App crashes with java.lang.IllegalStateException when loading style

### ISSUE THREAD

**Issue by zhurbaTT** [mapbox/mapbox-maps-android#1511]
## Environment

- Android OS version: 12, 11, 10, 8
- Devices affected: Samsung, Xiaomi, Honor, Huawei
- Maps SDK Version: 10.3.0

## Observed behavior and steps to reproduce

In Firebase I see some crash events. It happens not very often.
The trace is:

_Fatal Exception: java.lang.IllegalStateException
com.mapbox.maps.UtilsKt.call (Utils.kt:9)
com.mapbox.maps.MapboxMap.loadStyleUri (MapboxMap.kt:107)
com.mapbox.maps.MapboxMap.loadStyle (MapboxMap.kt:168)
com.mapbox.maps.MapboxMap.loadStyle (MapboxMap.kt:181)
ru.trendagent.map.domain.mapService.modehelpers.SingleBlockModeHelper.initMap (SingleBlockModeHelper.kt:59)
ru.trendagent.map.domain.mapService.MapBoxService.start (MapBoxService.kt:99)
ru.trendagent.map.domain.usecase.LoadMapUseCase$loadSingleBlockMap$1.invoke (LoadMapUseCase.kt:53)
ru.trendagent.map.domain.usecase.LoadMapUseCase$loadSingleBlockMap$1.invoke (LoadMapUseCase.kt:50)
trendmultiplatform.api.terminal.Terminal$getMapDetail$2.invoke (Terminal.kt:1338)
trendmultiplatform.api.terminal.Terminal$getMapDetail$2.invoke (Terminal.kt:1289)
multiplatform_rx.SingleReq$multiRequests$1$2.invokeSuspend (SingleReq.kt:108)
kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (ContinuationImpl.kt:33)
kotlinx.coroutines.DispatchedTask.run (DispatchedTask.kt:106)
android.os.Handler.handleCallback (Handler.java:938)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1135)_

## Notes / preliminary analysis

Looks like nativeMap weak reference is not existing anymore. How can this happen?
The problem affects only a part of our users.

**Comment by kiryldz** [comment]
@zhurbaTT 10.3.0 is pretty outdated version, weak references for map / style were revisited in v10.5.0. 

In general when reloading the style - you should update all local references to `Style` in your codebase (same applies if you're storing `MapboxMap` object). In v10.5.0 and after crashes you described should not happen but you will see warning log messages that you're potentially leaking map / style.

**Comment by zhurbaTT** [comment]
Thank you, @kiryldz ! 
We will set the mapBox dependency version to the latest one and check how it will affect our users.
I'll come back with new info in 1 week.

**Comment by zhurbaTT** [comment]
I don't see any new cases after upgrading to 10.6.2.
