### ISSUE TITLE
mapview all black

### ISSUE THREAD

**Issue by 1242128273wangpeng** [mapbox/mapbox-maps-android#1521]
![image](https://user-images.githubusercontent.com/10842360/180212242-d461e3aa-b304-4709-a2ec-46371e7635b8.png)
![image](https://user-images.githubusercontent.com/10842360/180212272-99e080ac-1fcf-4a1c-8769-1b3a5c5c747d.png)
![image](https://user-images.githubusercontent.com/10842360/180212309-e216df1d-0d4b-44e4-9f57-5128f84f75d4.png)

**Comment by ZiZasaurus** [comment]
@1242128273wangpeng are you following our installation instructions [here](https://docs.mapbox.com/android/maps/guides/install/)? A black screen is often an indication of a missing access token.
