### ISSUE TITLE
Annotation drag is too sensitive; triggers on marker clicks

### ISSUE THREAD

**Issue by akirmse** [mapbox/mapbox-maps-android#1528]
## Environment

- Android OS version: 10
- Devices affected: Samsung Galaxy S9
- Maps SDK Version: 10.6.1

I have both a ```OnPointAnnotationClickListener``` and a ```OnPointAnnotationDragListener```.  I observe that nearly every time I touch a marker (a point annotation), I get 3 events in this order:

- Annotation start drag
- Annotation end drag
- Annotation click

I think it's undesirable to have a drag triggered before nearly every click.  It certainly messes up my app's logic.  Perhaps the drag threshold is too low?  I don't see this behavior on the Mapbox iOS SDK.

**Comment by akirmse** [comment]
More seriously, I get drag events even if the annotation has its draggable property set to false: 

https://github.com/mapbox/mapbox-maps-android/blob/a35ee8cc52b7980f2b0d8a4808f71b96a6e4304f/plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationOptions.kt#L637

**Comment by ZiZasaurus** [comment]
@akirmse thank you for reporting. The team will look into what could be causing this behavior.

**Comment by Chaoba** [comment]
@akirmse We listen to the events from `AndroidGesturesManager` and it does fire `onMoveBegin` and then `onSingleTapConfirmed` events when clicking.



> More seriously, I get drag events even if the annotation has its draggable property set to false:

This is a bug and will be fixed.

**Comment by Chaoba** [comment]
Fixed in https://github.com/mapbox/mapbox-maps-android/pull/1552. Feel free to reopen this issue if you have other questions about this.
