### ISSUE TITLE
Location puck bearing never shown in Maps SDK v10

### ISSUE THREAD

**Issue by samcrawford** [mapbox/mapbox-maps-android#1537]
## Environment

- Android OS version: 12
- Devices affected: Samsung S21 and Samsung S8, at least
- Maps SDK Version: Navigation SDK 2.4.1 / Maps SDK v10.4.3

## Observed behavior and steps to reproduce

The bearing arrow is never displayed on the location puck. The location puck is being displayed correctly and is being updated just fine. It's just the bearing arrow that is missing. It used to be displayed just fine on Maps SDK v9.

## Expected behavior

The location puck is displayed, with the little arrow around it indicating bearing.

## Additional links and references

Here is the code I'm using to initialise the location component plugin (note I'm using Java):
```
            LocationComponentPlugin2 locationComponentPlugin2 = LocationComponentUtils.getLocationComponent2(mapView);
            locationComponentPlugin2.setPulsingEnabled(true);
            locationComponentPlugin2.setPuckBearingEnabled(true);
            locationComponentPlugin2.setPuckBearingSource(PuckBearingSource.HEADING);
```

There's a very good chance that I'm doing something wrong!

**Comment by samcrawford** [comment]
Looks like I was missing the following magic line:
```
locationComponentPlugin2.setLocationPuck(LocationComponentUtils.createDefault2DPuck(locationComponentPlugin2, this.getContext(), true));
```

The final `true` enables the bearing. Painful and not obvious!

**Comment by ctissier** [comment]
Hey @samcrawford, did you manage to make the bearing point towards the right direction?

I can display the bearing (with the exact same code as you (also in Java)), but it always points north...

If so, what did you do to make it work?
