### ISSUE TITLE
MapView snapshot does not contain view annotations

### ISSUE THREAD

**Issue by haydnwiese** [mapbox/mapbox-maps-android#1550]
### Environment
  Android OS version: 10
  Maps SDK version: 10.6.2
  
  ### Description
When taking a snapshot of a MapView with view annotations added using ViewAnnotationManager, the image only contains the underlying map, with no view annotations visible. This differs from v9, where MapboxMap#snapshot returns an image containing views added using the MarkerView plugin. 

Below is example code:
  
  ```
  mapboxMap.loadStyleUri(Style.MAPBOX_STREETS) {
     // Get the center point of the map
     val center = mapboxMap.cameraState.center

     val pieChartView = PieChartView()

     // Add the view annotation at the center point
     viewAnnotationManager.addViewAnnotation(pieChartView, options = viewAnnotationOptions {
          geometry(point)
     })
  }

  // called after some event
  mapView.snapshot {
       ...
  }
  ```

Below are screenshots of the actual vs expected MapView snapshot. Is there some other provided way to obtain a snapshot with view annotations included?
  
  | Actual | Expected |
  | ------------- | ------------- |
  | <img width=400 src="https://user-images.githubusercontent.com/45501692/181601466-3f8de105-ec1b-479c-8e4e-b0a7ca1bf404.png" /> | <img width=400 src="https://user-images.githubusercontent.com/45501692/181631275-5c27ead2-fcfb-4862-a03e-91303d5d2efc.png" /> |

**Comment by kiryldz** [comment]
@haydnwiese thanks for reporting. `MapView.snapshot` does not support adding anything on top of the map as it simply reads current map state from GPU memory (while view annotations are drawn on top as separate views).
However we do have [Snapshotter](https://docs.mapbox.com/android/maps/api/10.7.0/mapbox-maps-android/com.mapbox.maps/-snapshotter/?query=open%20class%20Snapshotter) class with more parameters but indeed view annotations are not supported there as well. That could be treated as SDK feature (however not sure we will implement it in nearest future) or, taking into account that view annotation is actually your view you're adding, you could add it on top of the result bitmap in your code (any Android view could be converted to a bitmap, see e.g. this [link](https://stackoverflow.com/a/3036736)).

**Comment by haydnwiese** [comment]
@kiryldz Thank you for the info

**Comment by bytebitx** [comment]
Snapshotter requires a network connection. If there is no network connection, how can I get a screenshot containing viewannotation?

**Comment by bytebitx** [comment]
> @haydnwiese thanks for reporting. `MapView.snapshot` does not support adding anything on top of the map as it simply reads current map state from GPU memory (while view annotations are drawn on top as separate views). However we do have [Snapshotter](https://docs.mapbox.com/android/maps/api/10.7.0/mapbox-maps-android/com.mapbox.maps/-snapshotter/?query=open%20class%20Snapshotter) class with more parameters but indeed view annotations are not supported there as well. That could be treated as SDK feature (however not sure we will implement it in nearest future) or, taking into account that view annotation is actually your view you're adding, you could add it on top of the result bitmap in your code (any Android view could be converted to a bitmap, see e.g. this [link](https://stackoverflow.com/a/3036736)).


Snapshotter requires a network connection. If there is no network connection, how can I get a screenshot containing viewannotation?
