### ISSUE TITLE
Crash on zoom in

### ISSUE THREAD

**Issue by bartek977** [mapbox/mapbox-maps-android#1559]
## Environment

- Android OS version: Android 11, Android 8
- Devices affected: Samsung Galaxy Tab A8, Huawei MediaPad T5
- Maps SDK Version: 10.7.0

## Observed behavior and steps to reproduce

There is a crash when I zoom in to a specified value in style.json. Maybe there is a problem with huge amounts of features/ points (sometimes there are 260k features/ 540k points).

During loading sources (on map zoom in) there is fast memory use growth (from 0,5GB to 2,2GB and then there is the crash)

## Expected behavior

No crash when moving/ zooming the map

## Notes / preliminary analysis

I use geojsons as sources, and have to have the possibility to work offline

## Additional links and references

demo app: https://github.com/bartek977/MapboxDemoApp

**Comment by bartek977** [comment]
Hi, any ideas how to solve this problem?

**Comment by kiryldz** [comment]
Hey @bartek977! I did check out your project and was able to see indeed runtime crashes. This is related to huge feature collections we need to parse in runtime on worker threads. Runtime styling is not prepared to accept such huge collections however there's another way to do this in a better way (and it is actually designed to apply huge amount of data).

You should prepare your data as vector tiles using https://www.mapbox.com/mts and then you could easily apply it in runtime like it's done in [this](https://github.com/mapbox/mapbox-maps-android/blob/2220e35d817837a16c36a976530b57d6d7fd923f/app/src/main/java/com/mapbox/maps/testapp/examples/StyleCirclesCategoricallyActivity.kt#L34-L36) example. Our example looks like this:


https://user-images.githubusercontent.com/15800566/185388061-35b5dd78-c630-403d-886b-6a29ab9f5fb2.mp4

**Comment by bartek977** [comment]
Hi @kiryldz, thanks for the answer, but is it possible to use vector tiles offline? Could you share an example how to do it?

**Comment by kiryldz** [comment]
> Hi @kiryldz, thanks for the answer, but is it possible to use vector tiles offline? Could you share an example how to do it?

Yes, vector sources should be working in offline as well. An example how to work with offline could be found in [this](https://github.com/mapbox/mapbox-maps-android/blob/main/app/src/main/java/com/mapbox/maps/testapp/examples/OfflineActivity.kt) activity. The only thing is that you'll need then to add those vector sources in style directly (not as runtime styling in your code), that could be done in Mapbox [Studio](https://studio.mapbox.com/).

**Comment by bartek977** [comment]
Hey @kiryldz, I've prepared vector tiles using mapbox studio and even tilesets cli, but something is not working. I get `Mapbox: [maps-core]: {TileStoreFileSo}[General]: Failed to get datasets from URL template http://a.tiles.mapbox.com/v4/appsgoconnectit.maatvoering-lijn/{z}/{x}/{y}.vector.pbf?access_token=REDACTED`

**Comment by kiryldz** [comment]
@bartek977 just a wild guess - do you have `android:usesCleartextTraffic="true"` declared in your AndroidManifest.xml?

**Comment by bartek977** [comment]
yep, without it I had Network security policy exception

**Comment by kiryldz** [comment]
@bartek977 did you follow https://docs.mapbox.com/help/tutorials/get-started-mts-and-tilesets-cli/#? Or how did you get your vector source from above?

**Comment by bartek977** [comment]
Yeah, I followed steps from video, and the vector tile is working in Mapbox studio.
My recipe:
```{
  "version": 1,
  "layers": {
    "maatvoering-lijn": {
      "source": "mapbox://tileset-source/appsgoconnectit/maatvoering-lijn",
      "minzoom": 16,
      "maxzoom": 16
    }
  }
}```

**Comment by kiryldz** [comment]
@bartek977 could you please try loading vector source as:
```kotlin
        mapView?.getMapboxMap()?.loadStyleJson(styleJson) {
            it.addSource(
                vectorSource("maatvoering-lijn") {
                    url("mapbox://appsgoconnectit.<TILESET_ID>")
                }
            )
//            sources.forEach { (id, featureCollection) ->
//                it.addSource(geoJsonSource(id) {
//                    featureCollection(featureCollection)
//                })
//            }
            it.addImage("carrow-10-#000000.png", image!!)
        }
```
Then add source-layer property to your `style.json`:
```
      "source-layer": "maatvoering-lijn",
```
And also not forget to set camera programatically to the correct position:
```kotlin
        mapView?.getMapboxMap()?.setCamera(
            cameraOptions = cameraOptions {
                zoom(16.0)
                center(Point.fromLngLat(4.459, 51.521))
            }
        )
```

**Comment by bartek977** [comment]
Okay, it works, thank you very much :) is there a way to load vector tiles created using [tippecanoe](https://github.com/mapbox/tippecanoe)?

**Comment by kiryldz** [comment]
Glad to hear it did work!
I don't know tbh what tippecanoe is, I'm aware only about tilesets prepared with MTS.

**Comment by bartek977** [comment]
tippecanoe is an util from Mapbox to convert geojson to vector tiles. I already have converted geojsons to mbtiles but have a problem with loading them into mapbox. The solution with Mapbox vector tiles works very good, but I need to load sources without internet connectivity, so offline manager from [this example](https://github.com/mapbox/mapbox-maps-android/blob/main/app/src/main/java/com/mapbox/maps/testapp/examples/OfflineActivity.kt) also doesn't fit my needs (offline manager first download style pack and then user can use offline)
