### ISSUE TITLE
[rendering] Expose function to schedule runnable on GL thread

### ISSUE THREAD

**Issue by kiryldz** [mapbox/mapbox-maps-android#156]
## New Feature

Expose two methods for render thread: `queueGlEvent` and `queueEvent` instead of one now.

## Why
It may be useful in some cases to split putting some `Runnable` in GL thread event queue and simply running it and putting that `Runnable` (most likely with GL commands) to a queue, executing them and performing buffer swap to see result on screen. Current implementation of `queueEvent` always performs drawing after executing `Runnable`.

**Comment by kiryldz** [comment]
As discussed offline with @alexshalamov we could generally have 2 initial approaches:
 1. When we get some new `Runnable` that has come from `queueEvent` or core `scheduleTask`(and thus does not require actually posting a `doFrame` via Choreographer with drawing and swapping buffers) - we could add them to our own queue created in renderer and run all those runnable __after__ next VSYNC update (requested by `queueGlEvent` or `scheduleRepaint`).
 2. Simply post a `Runnable` on a render thread and execute is ASAP (without swapping buffers).

I am more to the first approach, @mapbox/maps-android WDYT? Although I'll check out both of them with some concrete numbers.

**Comment by tobrun** [comment]
> I am more to the first approach

same

> I'll check out both of them with some concrete numbers.

that would be amazing
