### ISSUE TITLE
Make possible to zoom to a FeatureCollection or a list of Points

### ISSUE THREAD

**Issue by gdgcentrica** [mapbox/mapbox-maps-android#1562]
## New Feature
Add on CameraBoundsOptions.Builder the possibility to zoom to bounds made by a FeatureCollection and/or by multiple Points. 
(If this feature already exists please make it clear on documentation)

## Why
On v9 sdk it was possible to zoom to a LatLngBound builded by a list of LatLng, now in v10 sdk is impossible to do the same with Point and CoordinateBounds.
Now if i want to display a route on map and zoom to it i don't know how to do it, so I think this is a feature that almost everyone needs.

**Comment by ZiZasaurus** [comment]
@gdgcentrica you can use the following methods to set the camera to a specific geometry or coordinates:
- [cameraForGeometry ](https://docs.mapbox.com/android/maps/api/10.7.0/mapbox-maps-android/com.mapbox.maps/-camera-manager/#1074437554%2FFunctions%2F540127926) if you'd like to center the camera on a particular shape
- [cameraForCoordinateBounds](https://docs.mapbox.com/android/maps/api/10.7.0/mapbox-maps-android/com.mapbox.maps/-camera-manager/#1520214208%2FFunctions%2F540127926) if you'd like to specify coordinate bounds you with the camera to stay inside
- [cameraForCoordinates](https://docs.mapbox.com/android/maps/api/10.7.0/mapbox-maps-android/com.mapbox.maps/-camera-manager/#457043219%2FFunctions%2F540127926) will allow you to center the camera over a series of coordinates.

**Comment by VincentJoshuaET** [comment]
> @gdgcentrica you can use the following methods to set the camera to a specific geometry or coordinates:
> 
> * [cameraForGeometry ](https://docs.mapbox.com/android/maps/api/10.7.0/mapbox-maps-android/com.mapbox.maps/-camera-manager/#1074437554%2FFunctions%2F540127926) if you'd like to center the camera on a particular shape
> * [cameraForCoordinateBounds](https://docs.mapbox.com/android/maps/api/10.7.0/mapbox-maps-android/com.mapbox.maps/-camera-manager/#1520214208%2FFunctions%2F540127926) if you'd like to specify coordinate bounds you with the camera to stay inside
> * [cameraForCoordinates](https://docs.mapbox.com/android/maps/api/10.7.0/mapbox-maps-android/com.mapbox.maps/-camera-manager/#457043219%2FFunctions%2F540127926) will allow you to center the camera over a series of coordinates.

`cameraForCoordinates ` only takes a list of `Points` though. Would be great to have List<Geometry>

**Comment by ZiZasaurus** [comment]
@VincentJoshuaET if you use [cameraForGeometry](https://docs.mapbox.com/android/maps/api/10.7.0/mapbox-maps-android/com.mapbox.maps/-camera-manager/#1074437554%2FFunctions%2F540127926) you can pass a line string or any geometry instead of a list of points.

**Comment by gdgcentrica** [comment]
@ZiZasaurus  thank you very much, it was exactly what i was searching for. 

I think that this feature is important and needs to be highlighted here: [Guides](https://docs.mapbox.com/android/maps/guides/) and/or here: [Examples](https://docs.mapbox.com/android/maps/examples/)

**Comment by cattcal** [comment]
How to get CoordinateBounds, I want to get its east, west, north and south？

**Comment by manuelsilverio** [comment]
After I use this I still need to zoom the correct amount. How I can zoom in the right amount to include two points (origin and destination) on android SDK V10? 

At the moment I'm doing this:

```
val origin = Point.fromLngLat(lonOrigin, latOrigin)
val destination = Point.fromLngLat(lonDestination, latDestination)
val cameraOptions = binding.map.getMapboxMap().cameraForCoordinates(coordinates = listOf<Point>(origin, destination))
map.getMapboxMap().easeTo(cameraOptions)
```

It centers correctly but does not zoom in.
