### ISSUE TITLE
Fatal Exception: java.lang.Error unordered_map::at: key not found

### ISSUE THREAD

**Issue by BenCooke** [mapbox/mapbox-maps-android#1566]
Fatal Exception: java.lang.Error
unordered_map::at: key not found
com.mapbox.maps.Map.render (Map.java)
com.mapbox.maps.NativeMapImpl.render (NativeMapImpl.java:2)
com.mapbox.maps.renderer.MapboxRenderer.render (MapboxRenderer.java:5)
com.mapbox.maps.renderer.MapboxRenderThread.draw (MapboxRenderThread.java:77)
com.mapbox.maps.renderer.MapboxRenderThread.doFrame (MapboxRenderThread.java:10)

**Mapbox Navigation SDK version:**com.mapbox.navigation:android:2.6.0-rc.2

I am having this Crash showing up in my Crashlytics

**Comment by ZiZasaurus** [comment]
@BenCooke can you please provide the following information so we can investigate this behavior:
-  When are you receiving this crash? 
-  Is this a consistent crash or does it happen intermittently?
-  What version and which SDK are you running?

**Comment by BenCooke** [comment]
Hello,

This is an intermittent crash while the Map is on screen
Using Mapbox Navigation SDK version: 2.6.0

**Comment by ZiZasaurus** [comment]
@BenCooke to help the team investigate this issue further, can you please provide a minimal test case that reproduces this behavior.

**Comment by ZiZasaurus** [comment]
Closing this ticket, but please feel free to reopen if the issue persists.
