### ISSUE TITLE
Using Mapbox and Pytorch in the same project

### ISSUE THREAD

**Issue by Oriient-Michael** [mapbox/mapbox-maps-android#1579]
Hello,

I'm trying to use Mapbox and Pytorch together in the same Android project but I receive this compilation error:
2 files found with path 'lib/arm64-v8a/libc++_shared.so' from inputs:
 - /Users/eyalamir/.gradle/caches/transforms-3/39574a221961eb18fa9deadbee69fea4/transformed/common-22.1.0/jni/arm64-v8a/libc++_shared.so
 - /Users/eyalamir/.gradle/caches/transforms-3/c73fb4c1d8f48b7cbb206e310613488d/transformed/pytorch_android_lite-1.10.0/jni/arm64-v8a/libc++_shared.so
If you are using jniLibs and CMake IMPORTED targets, see
https://developer.android.com/r/tools/jniLibs-vs-imported-targets

If I only use one of the libraries, the project compiles correctly.
I also reproduced this issue with a new Android Project.

i'm using these versions:
Mapbox - com.mapbox.maps:android:10.7.0
Pytorch - org.pytorch:pytorch_android_lite:1.10.0

The issue is also reproduced with the full pytorch library instead of the lite version.

Can you please instruct me on how to solve this issue?

**Comment by kiryldz** [comment]
Hello @Oriient-Michael! 
From what I see in https://pytorch.org/mobile/android/ - `It’s recommended to use NDK 21.x.`.
We're building our native part with https://github.com/android/ndk/wiki/Changelog-r21#r21e as well.

All that in total allows me make an assumption that `libc++_shared.so` used both for Mapbox and Pytorch should be compatible and the solution in your case will be adding to your app level `build.gradle.kts` file:
```kotlin
android {
    // other staff
    packagingOptions {
        jniLibs.pickFirsts += "**/libc++_shared.so"
    }
}
```

**Comment by Oriient-Michael** [comment]
Thank you @kiryldz, we will give it a try!

**Comment by JasonCromer** [comment]
@kiryldz @Oriient-Michael we are using both the Mapbox and Oriient SDK in our project, and have tried the solution above.
This yields an error that two of our modules `contain entry 'lib/arm64-v8a/libc++_shared.so' with different content.` One of these modules contains the mapbox SDK, and the other contains the Oriient SDK.

The issue here is that the `so` files are mismatching, which leads me to believe something else is mismatching in the native libs used.

**Comment by Oriient-Michael** [comment]
@kiryldz Can it be that PyTorch and MapBox are built with different patches of NDK 21? If that is true, what is the risk of choosing one over another?

**Comment by Oriient-Michael** [comment]
@kiryldz Can it be that PyTorch and MapBox are built with different patches of NDK 21? If that is true, what is the risk of choosing one over another?

**Comment by kiryldz** [comment]
@Oriient-Michael that could be possible. NDKs within one patch should potentially be compatible however at least from my experience NDK developers may not be that graceful and some breaking changes could appear even between patches - I do remember once that some public method was dropped between patches in the same NDK 😄 

I could just advise you check hashes for `libc++_shared.so` for both Pytorch you're using and compare it to the Mapbox one. If they match - then it means that one NDK is used and it should be 100% safe to use both libraries in your app. If not - it still should be OK but worth doing deep testing to make sure there are no runtime crashes and all native symbols could be resolved.

**Comment by Oriient-Michael** [comment]
@kiryldz Thank you for the support. Eventually, we managed to rebuild PyTorch from the source and adjust the build process to use static runtime for C++ STL. This way we will avoid conflicts with MapBox and any other vendors that use shared runtime. It is interesting that using the shared runtimes is discouraged in the [documentation](https://developer.android.com/ndk/guides/cpp-support#shared_runtimes) but seems to be quite popular  😄
