### ISSUE TITLE
Use pixelRatio from MapboxMapOptions when addImage to the style.

### ISSUE THREAD

**Issue by pengdev** [mapbox/mapbox-maps-android#159]
## Environment

- Android OS version:
- Devices affected:
- Maps SDK Version: v10.0.0-beta.15

## Observed behavior and steps to reproduce

Currently the following extension functions: 
`StyleManagerInterface.addImage(image: StyleContract.StyleImageExtension)` and `StyleManagerInterface.addStyleImage(imageId: String, bitmap: Bitmap)`
are using the density of the primary display as the scale by default, which will result in the unexpected image scaling issues on the secondary display(if the density is different from the primary display).

Further, since the LocationComponentPlugin is using the `StyleManagerInterface.addStyleImage(imageId: String, bitmap: Bitmap)` API as well, the location puck's size is also affected.

## Expected behavior

Instead of using the density of the primary display as the pixel ratio when adding image to the map, we should respect the specified pixel ratio when the MapView is initialised, since we do provide the interface to overwrite the default pixel ratio during the MapView's initialisation.

## Notes / preliminary analysis

The APIs exposed directly under Style class like `Style#addImage(imageId: String, bitmap: Bitmap) ` are already using the given pixel ratio, which is the desired behaviour, the issue only exists on the above two mentioned extension functions. We  need to fix these APIs to be consistent with each other.

**Comment by pengdev** [comment]
cc @mapbox/maps-ios

**Comment by macdrevx** [comment]
On iOS, `UIImage` instances have a scale property, and we use that when adding the image: https://github.com/mapbox/mapbox-maps-ios/blob/main/Sources/MapboxMaps/Style/Style.swift#L185

@pengdev let's chat next week to make sure these behaviors are sufficiently aligned.
