### ISSUE TITLE
CameraAnimationsPluginImpl deadlock

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-maps-android#164]
Maps SDK: `10.0.0-beta.13`.

I can't reproduce the issue but I run into a situation where an animator was added to `runningAnimatorsQueue` and was never cleared. This led to the camera's complete deadlock because the plugin animates on the first animator's ticks:
https://github.com/mapbox/mapbox-maps-android/blob/ab7290356e290dd3de717ded1cfba7873fc1879a/plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImpl.kt#L317-L348

and since the first animator wasn't running (I was able to plug in a debugger and check, `firstAnimator.isRunning` and `firstAnimator.isStarted` were returning `false` as well), we had no camera updates being dispatched.

From the user's perspective, there was no other way to recover from this deadlock besides restarting the activity (recreating the map).

/cc @mapbox/maps-android

**Comment by knov** [comment]
@kiryldz can you follow up with @LukasPaczos  to determine if this is still an issue and what the  priority is?

**Comment by kiryldz** [comment]
Sadly could not reproduce. Was trying to simulate bunch of `flyTo` methods running one after another, constantly cancelling each other etc.
Would be glad if some determined scenario could be advised to reproduce this issue, looking at code it seems that everything should be fine.

**Comment by LukasPaczos** [comment]
@kiryldz I'd recommend trying this out with gestures. For example, schedule transitions (post them with a handler) to trigger while you're executing a drag gesture. Looks like a mix of transitions coming from gestures and programmatically scheduled were contributing to the issue, I was able to occasionally reproduce like that. This might not be related in the end, but might be easier to repro.

**Comment by kiryldz** [comment]
@LukasPaczos I was trying such code (changing numbers, with gesture / without) but could not still reproduce 😢 
```
for (i in 0..100) {
      mapView.postDelayed(
        {
          mapView.camera.flyTo(
            CameraOptions.Builder()
              .center(Point.fromLngLat(LONGITUDE + (i + 1) * 0.1, LATITUDE + (i + 1) * 0.1))
              .bearing(10.0 * i)
              .zoom(10.0 + (i / 2.0))
              .build()
          )
        },
        50L * i
      )
    }
```

**Comment by LukasPaczos** [comment]
I just pushed an example that reproduces the issue into [lp-164-repro](https://github.com/mapbox/mapbox-maps-android/tree/lp-164-repro) which copies some code from the Nav SDK to setup the transitions:

https://user-images.githubusercontent.com/16925074/122391006-dadbee80-cf72-11eb-9608-17377134a3f7.mp4

The key here is the:
```kotlin
mapView.camera.addCameraAnimationsLifecycleListener(NavigationBasicGesturesHandler {
  animatorSet.cancel()
  animatorSet.childAnimations.forEach {
    mapView.camera.unregisterAnimators(it as ValueAnimator)
  }
})
```
without which the issue is not reproducible. It gets called whenever the `NAVIGATION_CAMERA_OWNER` transition is interrupted by another transition and in this specific scenario, it locks up:
```kotlin
override fun onAnimatorStarting(
    type: CameraAnimatorType,
    animator: ValueAnimator,
    owner: String?
) {
    if (owner != NAVIGATION_CAMERA_OWNER) {
      listener()
    }
}
```

**Comment by Guardiola31337** [comment]
For reference I was also able to reproduce when running Navigation SDK [`examples` test app](https://github.com/mapbox/mapbox-navigation-android/tree/main/examples) 👀 

https://user-images.githubusercontent.com/1668582/122435439-00aec680-cf66-11eb-8ddd-6efb45f2ec65.mov

This is "consistently" reproducible when setting a really long route.
