### ISSUE TITLE
Listen to all gestures in single listener

### ISSUE THREAD

**Issue by tir38** [mapbox/mapbox-maps-android#1640]
## New Feature

I need a way to detect *that* the user interacted with the map. I don't care if they pinched/ panned/ zoomed/ flinged etc. Currently I have to wire up a bunch of listeners to `GesturePlugin`, one for each gesture type. I then have to keep track of these listeners and remove each one in `onStop`. I would love a method that took in a single function to call on _any_ change. I don't even need to know the change.

## Why

I need this so that I can track whether to zoom back to user's location. We have custom logic (beyond just a location update) that triggers a zoom back to users location. If user had changed the map in any way, we don't want to override their behavior by zooming back to their location.

**Comment by ZiZasaurus** [comment]
@tir38 thank you for reaching out. You can use [mapView.setOnTouchListener ](https://docs.mapbox.com/android/maps/api/10.9.0/mapbox-maps-android/com.mapbox.maps/-map-view/#-1966760991%2FFunctions%2F540127926) to detect all events.

**Comment by tir38** [comment]
Finally got around to testi9ng this. Works perfectly. I should have known to just listen to base `View` interactions.
