### ISSUE TITLE
Crash: Out of memory when adding layer source.

### ISSUE THREAD

**Issue by cafesilencio** [mapbox/mapbox-maps-android#1644]
This is a clone of an issue reported to the navigation SDK team.  Unfortunately this is all the information we have at this time.  

> **Issue report:**
> 
> Note that the customer has an unusual app set up, the Nav SDK is integrated inside a "dynamic feature module" to reduce impact to application size.
> 
> Q	A
> Timestamp and location of the event:	
> Captured with 1TAP (y/n):	N
> Platform:	Android
> Navigation SDK Version:	v2.6.0
> Other SDKs Used + Versions:	
> Customer reported urgency	
> Is this issue blocking the customer's release or launch?	
> Estimated % of customer's users affected:	0.01%
> Style used:	
> Mapbox username:	
> ### Steps to reproduce
> Not provided.
> 
> ### Expected behavior
> Crash-free integration of Nav SDK with customer app.
> 
> ### Actual behavior
> Crash detected by their monitoring system.
> 
> ```
> java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
> 	at java.lang.Thread.nativeCreate(Native Method)
> 	at java.lang.Thread.start(Thread.java:883)
> 	at com.mapbox.maps.extension.style.sources.generated.GeoJsonSource.<clinit>(GeoJsonSource.kt:630)
> 	at com.mapbox.maps.extension.style.sources.generated.GeoJsonSource$Builder.build(GeoJsonSource.kt:620)
> 	at com.mapbox.maps.extension.style.sources.generated.GeoJsonSourceKt.geoJsonSource(GeoJsonSource.kt:787)
> 	at com.mapbox.navigation.ui.maps.internal.route.line.MapboxRouteLineUtils.addSource(MapboxRouteLineUtils.kt:960)
> 	at com.mapbox.navigation.ui.maps.internal.route.line.MapboxRouteLineUtils.initializeLayers(MapboxRouteLineUtils.kt:979)
> 	at com.mapbox.navigation.ui.maps.route.line.api.MapboxRouteLineView.renderRouteDrawData(MapboxRouteLineView.kt:150)
> ```
>

**Comment by kiryldz** [comment]
Precisely this OOM could not be fixed from our side however in latest versions of Maps SDK working with geojsons was very much optimized (e.g. marshalling data on worker thread; catching exceptions). Closing this as non-actionable from our end as even if in theory this could be fixed - any other memory allocation would have fail as the system is completely out of memory.
