### ISSUE TITLE
Show built-in UI to calibrate compass

### ISSUE THREAD

**Issue by VincentJoshuaET** [mapbox/mapbox-maps-android#1649]
## New Feature

Something like the one from Google Maps:
![image](https://user-images.githubusercontent.com/19756326/188760137-9efab661-bb16-4ac6-b440-ebe46e7ba7ef.png)

**Comment by tobrun** [comment]
We recently added callback to invoked when this dialog should be shown. 
You can implement your own UI on top of this. 
see https://github.com/mapbox/mapbox-maps-android/pull/1513

**Comment by EricGeiler** [comment]
cc: @sridhar261990

**Comment by EricGeiler** [comment]
Except from Mapbox Support: 

Hi there,
 
Thanks for reaching out to Mapbox support, happy to help!
 
Our recent pre-release version of Maps SDK Android (10.8.0-beta.1) introduced a callback ([addOnCompassCalibrationListener](https://docs.mapbox.com/android/maps/api/10.8.0-beta.1/mapbox-maps-android/com.mapbox.maps.plugin.locationcomponent/-default-location-provider/add-on-compass-calibration-listener.html)) to be invoked when the device compass sensors need to be re-calibrated.
Here is how you can implement in your apps:

```
val locationProvider = location.getLocationProvider() as DefaultLocationProvider
locationProvider.addOnCompassCalibrationListener {
    Toast.makeText(context, "Compass needs to be calibrated", Toast.LENGTH_LONG).show()
}

```
For more information please check out our [release notes](https://github.com/mapbox/mapbox-maps-android/releases/tag/v10.8.0-beta.1) for version 10.8.0-beta.1.

I am afraid that we don't have any interface available when compass sensors need to be re-calibrated in pre v10 SDKs.
But however you can implement your own interface using Android's [SensorManager](https://developer.android.com/reference/android/hardware/SensorManager) and [SensorEventListener](https://developer.android.com/reference/android/hardware/SensorEventListener) APIs.
Below is an example SensorActivity of how you can implement these apis:

```
class SensorActivity : Activity(), SensorEventListener {

    private val mSensorManager: SensorManager = getSystemService(SENSOR_SERVICE) as SensorManager
    private val mSensor: Sensor = mSensorManager.getDefaultSensor(Sensor.TYPE_ROTATION_VECTOR)

    override fun onResume() {
        super.onResume()
        mSensorManager.registerListener(this, mSensor, SensorManager.SENSOR_DELAY_NORMAL)
    }

    override fun onPause() {
        super.onPause()
        mSensorManager.unregisterListener(this)
    }

    override fun onAccuracyChanged(sensor: Sensor, accuracy: Int) {
        if (accuracy == SensorManager.SENSOR_STATUS_UNRELIABLE) {
            Toast.makeText(this, "Compass needs to be calibrated", Toast.LENGTH_LONG).show()
        }
    }

    override fun onSensorChanged(event: SensorEvent) {
        
    }
}
``` 

Also please be note that android system will not disable sensors automatically when the screen turns off.
Always make sure to disable sensors you don't need, especially when your activity is paused. Failing to do so can drain the battery in just a few hours.
 
And please be reminded that a [newer version of the Maps SDK](https://www.mapbox.com/mobile-maps-sdk) is available now and recommended for all users. Customers who’ve already upgraded are benefiting from an SDK that’s more performant, easier to work with, and which brings new capabilities like 3D terrain, globe view, and faster offline downloads.
Mapbox is in the process of deprecating v9 of the Android Maps SDK and will stop publishing bug and compatibility fixes for pre-v10 versions of our SDK after April 4, 2023. As we will no longer be able to guarantee support or compatibility on older versions, we strongly recommend [migrating to v10](https://docs.mapbox.com/android/maps/guides/migrate-to-v10/) so we can continue supporting your project needs in the future.


I hope this can help anyone looking for compass calibration ideas / concepts / methods.
