### ISSUE TITLE
ClusterOptions ClickListener

### ISSUE THREAD

**Issue by kayc90** [mapbox/mapbox-maps-android#1663]
## New Feature

I can't set a ClickListener on a Cluster when I set `cluster = true` in the `AnnotationSourceOptions` while initializing MapBox in a Fragment:

`AnnotationSourceOptions(
                  clusterOptions = ClusterOptions(
                      cluster = true
                  )
              )
`

## Why

From UX perspective it would be easier if Clusters of PointAnnotations are clickable. Otherwise currently the Users have to zoom-in manually until the Cluster becomes invisible and PointAnnotations get visible. Or is there a way to set a `ClickListener` to each Cluster?

**Comment by ZiZasaurus** [comment]
@kayc90 while we do not have any options in AnnotationOption to click clusters, you can use [queryRenderedFeatures](https://docs.mapbox.com/android/maps/api/10.8.0/mapbox-maps-android/com.mapbox.maps/-mapbox-map/query-rendered-features.html) to accomplish this.

**Comment by kayc90** [comment]
@ZiZasaurus thank you for the information. It worked pretty well with `queryRenderedFeatures`. This is how I solved it:

`

                        mapView.getMapboxMap().queryRenderedFeatures(
                            geometry = RenderedQueryGeometry.valueOf(
                                mapView.getMapboxMap().pixelForCoordinate(pressedPoint) // pressedPoint: Point
                            ), options = RenderedQueryOptions(
                                listOf(
                                    "mapbox-android-cluster-circle-layer-0"
                                ),
                                null
                            ), callback = {
                                val onClusterPressed = it.value?.isNotEmpty() == true

                                when {
                                    onClusterPressed -> {
                                        ....
                                    }
                                }
                            })
`

**Comment by tristan-garaud** [comment]
How to know the mapbox-android-cluster-circle-layer-0 for sure ?
