### ISSUE TITLE
jetpack compose - map

### ISSUE THREAD

**Issue by ismai117** [mapbox/mapbox-maps-android#1668]
Hi, how do we add markers on the map when using jetpack compose?

I'm trying implement a start and destination markers but I can't figure it out.

**Comment by ZiZasaurus** [comment]
@ismai117 please take a look at our compose app [here](https://github.com/mapbox/mapbox-maps-android/tree/main/compose-app).

**Comment by ismai117** [comment]
HI @ZiZasaurus, I've already checked the compose app, it does not show how to add markers or location puck specifically for compose. When the maps show up, I can't see the location pointer
