### ISSUE TITLE
Use the location component without asking for permissions

### ISSUE THREAD

**Issue by FinitelyFailed** [mapbox/mapbox-maps-android#167]
I would like to use the location component without asking for permission. As it is possible that one wants to use the component to display a location which has nothing to do with the devices location and where the location is given through a custom location engine or similar where the devices GPS etc. is never used.

I'm quite new to Mapbox, so I'm sorry if one already can do that or my request is not valid because of my ignorance.

**Comment by pengdev** [comment]
Hi @FinitelyFailed , thanks for trying out the Mapbox SDK, you can set your own location provider before enabling the location component plugin. Detailed instructions can be found [here](https://github.com/mapbox/mapbox-maps-android/tree/main/plugin-locationcomponent#provide-your-own-locationprovider-with-custom-puck-animators).

**Comment by pengdev** [comment]
Closing this ticket,  @FinitelyFailed please reopen if needed.
