### ISSUE TITLE
I want to be able to anchor the location puck to the bottom

### ISSUE THREAD

**Issue by jonschmidt** [mapbox/mapbox-maps-android#1678]
## New Feature

We want to be able to make a 2d location puck that has a bottom anchor (basically looks like a more traditional map marker with a tail). Currently it seems you can only provide a puck with a middle anchor. We tried changing the image so that there was empty space at the bottom so that it would work as a center anchor, but the image was unexpectedly scaled by mapbox.

## Why
This is what our design requires.

**Comment by ZiZasaurus** [comment]
@jonschmidt, thanks for reaching out. To better assist you, can you please provide us with some additional information about what you're trying to accomplish, as well as a screenshot of the implementation you're looking for? This will help us better understand your request.

**Comment by unatarajan** [comment]
Hi @ZiZasaurus Please see [this ZD ticket](https://mapbox.zendesk.com/agent/tickets/129670) for additional details around the ask.

**Comment by kiryldz** [comment]
Stale, outdated.
