### ISSUE TITLE
Issue with 3D Terrain Offline Caching for Mobile 

### ISSUE THREAD

**Issue by Njuselis** [mapbox/mapbox-maps-android#1680]
We released Mapbox support in our Android and iOS clients last week as a beta feature. Adoption is going well with over 2500 users in the first week.

That said, we have a few critical issues that are holding up broader adoption related to offline caching. 
We can't get 3d terrain to work offline in either Android or iOS. Is this a supported feature?
Satellite tile data isn't caching on Android, as identified in this ticket: https://github.com/mapbox/mapbox-maps-android/issues/1460
Can you let us know if 3d terrain is cacheable for offline usage? Any way to raise the priority or timeline on resolving the satellite caching bug described above?

**Comment by kiryldz** [comment]
Closing as the issue linked is closed.
