### ISSUE TITLE
Map is partially black when minimizing the App while soft-keyboard is shown

### ISSUE THREAD

**Issue by kayc90** [mapbox/mapbox-maps-android#1687]
## Environment

- Android OS version: 12 & 13
- Devices affected: Google Pixel 4 (real device), Google Pixel 5 (emulator) - most likely also other devices
- Maps SDK Version: 10.8.0

## Observed behavior and steps to reproduce

I have a `EditText`/ `TextInput`-View in my Fragment (on top of the `MapView`). When the focus is on the `TextInput`-layout and the soft-keyboard is shown, the Map is partially black after I minimize and re-open the app. This issue occurs on specific devices I've so far tested on Pixel 4 SDK Version 33 (real device) and Pixel 5 SDK Version 31 (emulator).

Steps to reproduce:
1. Create TextEdit which is on top of the MapView
2. Click on TextEdit and enter sth. (so that soft-keyboard is shown)
3. click on home-button (while the keyboard is shown)
4. Re-open the app
5. Most likely is Map will be partially cut

## Expected behavior

Map shouldn't be partially cut

## Notes / preliminary analysis

The weird thing is, that the black-part of the map still is kind of interactive. I can still move around in the map when sliding on the black part.

## Additional links and references

<img width="391" alt="map_partially_cut" src="https://user-images.githubusercontent.com/7412530/191728165-4eb29c8a-861f-4e7c-95e1-7c5a4eff2e53.png">

[map_cut.webm](https://user-images.githubusercontent.com/7412530/191728572-be3aa441-0163-45e6-b5b7-0589108756dc.webm)

**Comment by kayc90** [comment]
I found a workaround by adding `mapbox:mapbox_mapSurface="texture_view"` to my XML-definition:

 <com.mapbox.maps.MapView xmlns:mapbox="http://schemas.android.com/apk/res-auto"
                   android:id="@+id/map_view"
                    android:layout_width="match_parent"
                   android:layout_height="match_parent"
                   mapbox:mapbox_mapSurface="texture_view" />
  
Would this be a valid workaround?

**Comment by kayc90** [comment]
I'm already using version 10.8.0

**Comment by tobrun** [comment]
cc @kiryldz

**Comment by kiryldz** [comment]
@kayc90 - can you try with `surface_view` mode and with latest [v10.9.0-beta.1](https://github.com/mapbox/mapbox-maps-android/releases/tag/v10.9.0-beta.1) version? The fix @tobrun was referencing to is not present in 10.8.0.

If that does not help - then indeed `texture_view` is preferable if you have complex layout with other views overlaying the map, that are changing visibility, transformed etc. Also you could try to force-hide keyboard when your app is going background.

**Comment by kayc90** [comment]
@kiryldz @tobrun With `surface_view` and the latest beta version `v10.9.0-beta.1` it seems to work fine now. Thank you.
