### ISSUE TITLE
Multiple 3d Annotations

### ISSUE THREAD

**Issue by rkariath** [mapbox/mapbox-maps-android#1705]
Is it possible to create multiple 3d model annotations in mapbox?

I can create a LocationPuck3d but this works only for current location. 
I can also create Point annotations but this accepts only bitmaps or strings (not glb). Am i overlooking something here? Can i loop and create multiple LocationPuck3D in multiple points of the map?

**Comment by ZiZasaurus** [comment]
@rkariath, while this is not a supported feature at the moment, the team is working to make this feature available in a future update.

**Comment by kiryldz** [comment]
This is possible now, see https://github.com/mapbox/mapbox-maps-android/blob/main/app/src/main/java/com/mapbox/maps/testapp/examples/terrain3D/ModelLayerActivity.kt as a reference.
