### ISSUE TITLE
Mapbox SDK memory leak detected! MapboxMap object (accessing getStyle) should not be stored and used after MapView is destroyed. 

### ISSUE THREAD

**Issue by swathysreenivas** [mapbox/mapbox-maps-android#1715]
## Environment

- Android OS version: 12
- Devices affected: Pixel 4 a
- Maps SDK Version: 10.7.0

## Observed behavior and steps to reproduce

Integrated map SDK and react native bridging done. Unfortunately, the app got stuck and got an error as Mapbox SDK memory leak detected!

## Expected behavior

Map view with navigation should be displayed

## Notes / preliminary analysis

It was working fine when placed as an initial screen. Error got when used as an inner component of another view.

**Comment by IsaacTrevino** [comment]
Getting a similar issue,
```
E/Mapbox: [maps-android\Mbgl-Style]: Mapbox SDK memory leak detected! Style object (accessing setStyleLayerProperty) should not be stored and used after MapView is destroyed or new style has been loaded.
```

```
E/Mapbox: [maps-android\Mbgl-Style]: Mapbox SDK memory leak detected! Style object (accessing styleLayerExists) should not be stored and used after MapView is destroyed or new style has been loaded.
```

My guess is, styleLayer is not being destroyed along with the map

**Comment by ZiZasaurus** [comment]
@IsaacTrevino, @swathysreenivas are you able to reproduce this issue on our most recent SDK, v10.9.0?

**Comment by IsaacTrevino** [comment]
@ZiZasaurus
Yes, I have just finished testing it with `10.9.0` and the bug persists.
![Screenshot_20221024_113908_2](https://user-images.githubusercontent.com/13424971/197580310-169e963f-d559-43d3-9a53-ac047e63d9a1.png)

**Comment by kiryldz** [comment]
Stale, outdated. Reproducible example will be appreciated if this is still the case with latest version of the SDK.
