### ISSUE TITLE
App suddenly requires ACCESS_BACKGROUND_LOCATION

### ISSUE THREAD

**Issue by SamuelBrucksch** [mapbox/mapbox-maps-android#1741]
Hi,

we have an app which currently uses
```
    implementation("com.mapbox.maps:android:10.9.0-beta.1") 
    implementation('com.mapbox.plugin:maps-locationcomponent:10.9.0-beta.1')
```
When I change both versions to `10.9.0-rc.1` then i can't submit the app to play store anymore for testing, unless I provide information why I want to use background location.

We did not require that permission ourself, and when I go back to `10.9.0-beta.1` it immediately works again. So for me this looks like one of the packages from version `10.9.0-rc.1` seems to require it.

Is that something you are aware of?

**Comment by jush** [comment]
Thanks for reporting, we are aware and working on a solution for next release.

Meanwhile, you can add the following snippet to your `AndroidManifest.xml`:
```XML
    <uses-permission
        android:name="android.permission.ACCESS_BACKGROUND_LOCATION"
        tools:node="remove" />
```
