### ISSUE TITLE
Why cameraState.center not in screen

### ISSUE THREAD

**Issue by zzkggmy** [mapbox/mapbox-maps-android#1743]
## Environment

- Android OS version:12
- Devices affected:Oneplus 8
- Maps SDK Version:10.8.0

## Observed behavior and steps to reproduce

![image](https://user-images.githubusercontent.com/18183531/194864545-c945f7ee-39ba-4013-9a27-195be73779a8.png)
 When I'm sliding to stop to get the center Point, but the point is not on the screen
 
![image](https://user-images.githubusercontent.com/18183531/194864755-596eb71f-6dd2-47ab-8785-db22f0355b59.png)
So I need to get the current Point in the CameraAnimatorChangeListener, I hope can get the correct in OnMoveEnd center Point, rather than the center Point after delay for a period of time to get right

**Comment by ZiZasaurus** [comment]
@zzkggmy as this is more of a product support Issue, can you please create a support ticket at https://support.mapbox.com/hc/en-us/ and our support team will be happy to get you the answers you need.
