### ISSUE TITLE
Migrate CameraMode and RenderMode from v9 SDK to viewport v10 SDK

### ISSUE THREAD

**Issue by Guimareshh** [mapbox/mapbox-maps-android#1748]
Hello,

I'm doing a migration from Android SDK v9 to v10, and I'm trying to understand how to center on user's location at runtime. Here's a piece of code I'm trying to migrate:

```kotlin
when (locationMode) {
    LocationMode.Approximate, LocationMode.FocusedOnUser  -> {
        locationComponent.cameraMode = CameraMode.TRACKING_GPS_NORTH
        locationComponent.renderMode = RenderMode.NORMAL
    }
    LocationMode.Tracking -> {
        locationComponent.cameraMode = CameraMode.TRACKING_COMPASS
        locationComponent.renderMode = RenderMode.COMPASS
    }
}
```

I have been able to migrate the camera mode for tracking user's location with the viewport plugin, but I'm not sure what is the best option to center on user location:

```kotlin
 when (locationMode) {
    LocationMode.Approximate, LocationMode.FocusedOnUser -> {
        //TODO mapboxMap.centerTo(user.location)
    }
    LocationMode.Tracking -> {
        mapView.viewport.apply {
            transitionTo(
                makeFollowPuckViewportState(
                    FollowPuckViewportStateOptions
                        .Builder()
                        .pitch(0.0)
                        .zoom(MapBoxUtils.DEFAULT_ZOOM)
                        .build()
                )
            )
        }
    }
}
```

**Comment by pengdev** [comment]
@Guimareshh please refer to our [migration guide](https://docs.mapbox.com/android/maps/guides/migrate-to-v10/#location-component-plugin-with-puck-and-camera-decoupled) and [user location guide ](https://docs.mapbox.com/android/maps/guides/user-location/#location-tracking)

With v10, the puck and camera updates have been decoupled, the location component plugin will only handle the location puck updates(and puck appearance customisation). And the [Mapbox Viewport Plugin](https://github.com/mapbox/mapbox-maps-android/tree/main/plugin-viewport) is introduced as the successor of the location tracking modes of v9.

For centering on user location, I'd suggest you to try using `FollowPuckViewportState`, and transitionTo idle once the transition has been finished.
```
mapView.viewport.apply {
      transitionTo(
        makeFollowPuckViewportState(
          FollowPuckViewportStateOptions
            .Builder()
            // in case if you want to keep the north up
            .bearing(FollowPuckViewportStateBearing.Constant(0.0))
            .pitch(0.0)
            .zoom(MapBoxUtils.DEFAULT_ZOOM)
            .build()
        )
      ) {
        idle()
      }
```

**Comment by Guimareshh** [comment]
Thanks for your quick reply, that's exactly what I was looking for!

About the FollowPuckViewportState, when I'm on "tracking mode" I find the viewport plugin laggy and less performant than the v9 SDK. I setup the tracking mode as following:

```kotlin
mapView.viewport.apply {
    transitionTo(
        makeFollowPuckViewportState(
            FollowPuckViewportStateOptions
                .Builder()
                .bearing(FollowPuckViewportStateBearing.SyncWithLocationPuck)
                .pitch(0.0)
                .zoom(DEFAULT_ZOOM)
                .build()
        )
    )
}
```


Here is quick example of the implemented code on a device:

https://user-images.githubusercontent.com/9654353/195834797-2760a929-90a7-479e-ba52-b93f61355c0a.mov


As you can see, on the v10 version (first app with the scale bar) the camera isn't properly sync. It's supper laggy. 

Am I doing something wrong? I just want the same behavior as I had with `CameraMode.TRACKING_COMPASS` and `RenderMode.COMPASS` with the legacy SDK.

**Comment by pengdev** [comment]
> Am I doing something wrong? I just want the same behavior as I had with CameraMode.TRACKING_COMPASS and RenderMode.COMPASS with the legacy SDK.

I think in this case you want the location puck to follow the compass bearing instead of GPS bearing, by default, the puck's bearing follows the GPS(where the location puck moves towards), you can make the location puck follow the Compass heading using the following code snippet:
```
mapView.location2.puckBearingSource = PuckBearingSource.HEADING
```
Documentation can be found [here](https://docs.mapbox.com/android/maps/api/10.8.1/mapbox-maps-android/com.mapbox.maps.plugin/-puck-bearing-source/).

**Comment by Guimareshh** [comment]
It's perfect! I'm closing the issue as it fixes my issue ✅ 

Thanks for your help!
