### ISSUE TITLE
Location plugin: java.lang.StackOverflowError: stack size 8MB

### ISSUE THREAD

**Issue by kiryldz** [mapbox/mapbox-maps-android#175]
## Environment

- Android OS version: 28
- Devices affected: Pixel
- Maps SDK Version: stable beta.15, commit 7510bd518904f1a31932c9255ccc29fca7cf7b2d

## Observed behavior and steps to reproduce

https://console.firebase.google.com/u/0/project/mapbox-maps-android/testlab/histories/bh.2bfab35e2b9f8cf5/matrices/4915282270164649532/executions/bs.1d73fb337b5647e7/issues

## Expected behavior

No crashing.

## Notes / preliminary analysis

Seems to be not determined, seen only on CI, locally all LocationActivities work fine.

**Comment by tobrun** [comment]
Code was removed and issue is stale
