### ISSUE TITLE
change map style based on dark/light mode 

### ISSUE THREAD

**Issue by ghadeeraqraa1992** [mapbox/mapbox-maps-android#1761]
## Environment

- Android OS version: Android 11 + Automotive 
- Devices affected: real device + emulators 
- Maps SDK Version: 10.8.1

## Observed behavior and steps to reproduce

We have 2 custom styles created Using Mapbox visual studio for dark/light modes, I added the styles URLs in the string files (one for dark/night mode and the other for light/day mode) 
After running the app then going to settings and switching the current mode the map activity went to onDestroy method and then to onCreate method.
I notice the below logs 
Mapbox: [maps-android\Mbgl-RenderThread]: RenderThread : surface destroyed
## Expected behavior

keep the activity in the latest state 

#NOTE::
I tested the above case by creating simple map screen example, and I got the same issue , the map activity went to onDestroy then to onCreate with the below logs : 
/Mapbox: [maps-android\Mbgl-Renderer]: onDestroy
I/Mapbox: [maps-android\Mbgl-Renderer]: Destroy renderer 
Here is my code : 
Activity: 
`

import android.annotation.SuppressLint
import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import com.example.automotive.R
import com.mapbox.maps.MapView
import com.mapbox.maps.Style

class TestMapBoxActivity : AppCompatActivity() {
    var mapView: MapView? = null

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_test_map_box)
        mapView = findViewById(R.id.mapView)
        mapView?.getMapboxMap()?.loadStyleUri(Style.MAPBOX_STREETS)
    }

    @SuppressLint("Lifecycle")
    override fun onStart() {
        super.onStart()
        mapView?.onStart()
    }

    @SuppressLint("Lifecycle")
    override fun onStop() {
        super.onStop()
        mapView?.onStop()
    }

    @SuppressLint("Lifecycle")
    override fun onLowMemory() {
        super.onLowMemory()
        mapView?.onLowMemory()
    }

    @SuppressLint("Lifecycle")
    override fun onDestroy() {
        super.onDestroy()
        mapView?.onDestroy()
    }
}`

XML : 
`<?xml version="1.0" encoding="utf-8"?>
<com.mapbox.maps.MapView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    xmlns:mapbox="http://schemas.android.com/apk/res-auto"
    android:id="@+id/mapView"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    mapbox:mapbox_cameraTargetLat="59.31"
    mapbox:mapbox_cameraTargetLng="18.06"
    mapbox:mapbox_cameraZoom="9.0"
    />
`

**Comment by jush** [comment]
Changing the system theme settings is a configuration change. See documentation for [uiMode](https://developer.android.com/reference/android/content/res/Configuration#uiMode):
> The [UI_MODE_NIGHT_MASK](https://developer.android.com/reference/android/content/res/Configuration#UI_MODE_NIGHT_MASK) defines whether the screen is in a special mode. They may be one of [UI_MODE_NIGHT_UNDEFINED](https://developer.android.com/reference/android/content/res/Configuration#UI_MODE_NIGHT_UNDEFINED), [UI_MODE_NIGHT_NO](https://developer.android.com/reference/android/content/res/Configuration#UI_MODE_NIGHT_NO) or [UI_MODE_NIGHT_YES](https://developer.android.com/reference/android/content/res/Configuration#UI_MODE_NIGHT_YES).

Therefore, Android system recreates the activity unless you handle it manually with the right flags in your manifest (see [Handle configuration changes](https://developer.android.com/guide/topics/resources/runtime-changes))
