### ISSUE TITLE
Duplicate Dependency Issue when using Map and Search SDK

### ISSUE THREAD

**Issue by mahadevan-k** [mapbox/mapbox-maps-android#1763]
## Environment

- Android OS version: 10
- Devices affected: Moto e(7)
- Maps SDK Version: 10.8.1

## Observed behavior and steps to reproduce

When I try to use the Maps SDK and the Search SDK like so:

    implementation "com.mapbox.maps:android:10.8.1"
    implementation "com.mapbox.search:mapbox-search-android-ui:1.0.0-beta.38"

I get the following error while building wtih gradle

    Duplicate class com.mapbox.common.MapboxCommonLogger found in modules jetified-base-10.8.1-runtime (com.mapbox.maps:base:10.8.1) and jetified-common-23.1.0-rc.1-runtime (com.mapbox.common:common:23.1.0-rc.1)

## Expected behavior

Build should succeed

## Notes / preliminary analysis

I guess that the MapboxCommonLogger is present in both libraries and creating an issue

## Additional links and references

None

**Comment by HieuLK** [comment]
Got the same issue:

Duplicate class com.mapbox.common.MapboxCommonLogger found in modules base-10.8.1-runtime (com.mapbox.maps:base:10.8.1) and common-23.1.0-rc.1-runtime (com.mapbox.common:common:23.1.0-rc.1)

**Comment by ZiZasaurus** [comment]
It appears as though there is a mismatch between the Search SDK and Maps SDK versions. For v10.8.1 of the Maps SDK, you would want to use v1.0.0-beta.35 of the Search SDK.

**Comment by ZiZasaurus** [comment]
Closing this ticket, but please feel free to reopen if you continue to experience this issue.
