### ISSUE TITLE
setBounds(cameraBoundsOptions) causes map hide

### ISSUE THREAD

**Issue by bartek977** [mapbox/mapbox-maps-android#1764]
## Environment

- Android OS version: Android 11
- Devices affected: Samsung Galaxy Tab A8
- Maps SDK Version: 10.6.1

## Observed behavior and steps to reproduce

When I set bounds with a small area, the map hides.

Example:
```
mapView?.getMapboxMap()?.addOnMapClickListener {
            mapView?.getMapboxMap()?.setBounds(
                CameraBoundsOptions.Builder()
                    .bounds(CoordinateBounds(
                        Point.fromLngLat(4.000001,52.0000022),
                        Point.fromLngLat(4.000002,52.0000025)
                    ))
                    .build()
            )
            true
        }
```

## Expected behavior

the map shouldn't hide, but maybe increase the bounding box area if it's too small

**Comment by ZiZasaurus** [comment]
@bartek977 thank you for reaching out. To better assist you, can you please explain what you mean when you say the map hides? When i use your code to create the bounding box on click, the bounding box is created as expected. Can you please try this on the newest version of our SDK and let us know if you're still experiencing this issue?

![video1](https://user-images.githubusercontent.com/44972592/197537523-d2fa38db-c321-42c7-9a6f-e58f33a46eb7.gif)

After moving the coordinates to encompass a bigger area to ensure that the feature behaves as expected, I am still able to see the map with no issues:
```
    mapView?.getMapboxMap()?.addOnMapClickListener {
      mapView?.getMapboxMap()?.setBounds(
        CameraBoundsOptions.Builder()
          .bounds(
            CoordinateBounds(
            Point.fromLngLat(-93.32176563420416, 39.50288747926271),
            Point.fromLngLat(-86.60753866070553, 34.7648822646416)
          )
          )
          .build()
      )
      true
    }
```
![video2](https://user-images.githubusercontent.com/44972592/197537507-dff3e19b-0351-4c0e-8b20-ba49ced56255.gif)
