### ISSUE TITLE
Preloading map tiles fails for locally provided style.json

### ISSUE THREAD

**Issue by florianPOLARSTEPS** [mapbox/mapbox-maps-android#1768]
## Environment

- Android OS version: Any
- Devices affected: Any
- Maps SDK Version: 10.8.1

## Observed behavior and steps to reproduce

For my usecase, I am shipping a style bundled with the app which I am using to render the map. This all works fine, but I would like to prefetch tiles related to this style. I have been pretty much following the instructions provided [here](https://docs.mapbox.com/android/maps/guides/offline/#defining-a-tileset-descriptor-and-tile-region) to do so.

Instead of setting a `mapbox://...` style url in order do prefetch data, I am using a local url `asset://styles.json`. The map renders just fine with this `URI`, but for prefetching, I only get an error in the console. `[type: TilesetDescriptor, message: Failed to resolve tileset descriptors: Failed to load style.]`

```kotlin
val tilesetDescriptor = offlineManager.createTilesetDescriptor(
    TilesetDescriptorOptions.Builder()
        .styleURI("asset://style.json")
        .stylePackOptions(stylePackLoadOptions)
        .minZoom(0)
        .maxZoom(4)
        .build()
)
```

## Expected behavior

Tile/ stylepack prefetching works the same for remotely available styles or locally provided styles.

## Additional links and references

I have created [a sample project](https://github.com/florianPOLARSTEPS/MapboxOfflineDownload) demonstrating the issue. 
The locally provided style (`style.json`) is 100% the same style as the default `Satellite` style. I downloaded it via mapbox studio.

**Comment by ZiZasaurus** [comment]
@florianPOLARSTEPS, do your local styles still rely on Mapbox tilesets?

**Comment by florianPOLARSTEPS** [comment]
> @florianPOLARSTEPS, do your local styles still rely on Mapbox tilesets?
Yes, they do. 👍

**Comment by ZiZasaurus** [comment]
Thank you for this info.  As long as the tilesets you are referencing are mapbox tilesets, you can use the [alternate API for tileset descriptor construction](https://docs.mapbox.com/android/maps/api/10.9.0/mapbox-maps-android/com.mapbox.maps/-offline-manager/create-tileset-descriptor.html), which doesn't require the style url.

```
`open fun createTilesetDescriptor(@NonNull tilesetDescriptorOptionsForTilesets: TilesetDescriptorOptionsForTilesets): TilesetDescriptor` 
```

**Comment by florianPOLARSTEPS** [comment]
Thanks! @ZiZasaurus . I will give it a try and see if this works out good enough for our usecase. 

Conceptually speaking it's not a `nice` thing for us since it will move responsibility of knowing what to download into our app, rather than just relying on this being defined by the `style.json`.

**Comment by kiryldz** [comment]
Stale, outdated.
