### ISSUE TITLE
Expression migration v9 to v10: Branch labels must be numbers or strings

### ISSUE THREAD

**Issue by Guimareshh** [mapbox/mapbox-maps-android#1769]
I'm trying to migrate the following expression from Mapbox SDK v9 to v10: 

```kotlin
PropertyFactory.iconSize(match(Expression.toString(get(WAYPOINT_SELECTED)), literal(0.6f), stop("true", 1.2f))),
//This line of code check if a SymbolLayer is selected: if yes we want the icon size to be x0.6 else x1.2
```

Trying to following the migration guide and new documentation on expressions I updated the previous line of code with the folloing:

```kotlin
iconSize(
    match {
        get { literal(WAYPOINT_SELECTED) }
        stop {
            literal(true)
            literal(1.2)
        }
        literal(0.6)
    }
)
```

But I get the following error: `com.mapbox.maps.MapboxStyleException: Add layer failed: Failed to set `icon-size` property for `WaypointLayer` layer. Error: [2]: Branch labels must be numbers or strings.`

Thanks for your help!

**Comment by kiryldz** [comment]
@Guimareshh as the error indicates `Branch labels must be numbers or strings` while you are wrapping `bool`. Even in v9 snippet you're using `true` but as the string. Changing `literal(true)` to `literal("true")` assuming `WAYPOINT_SELECTED` will be either `"true"` or `"false"` should fix the issue.

**Comment by Guimareshh** [comment]
🤦 I wasn't paying attention enough that I was using String in v9, thank you!
