### ISSUE TITLE
Maps get overlapped from different fragments into one

### ISSUE THREAD

**Issue by meciusMP** [mapbox/mapbox-maps-android#1776]
## Environment

- Android OS version: 12
- Devices affected: Pixel 3a and multiple emulators
- Maps SDK Version: 10.8.1

## Observed behavior and steps to reproduce

Hey, 

we ran into a problem where one map overlaps the other or there's a visible overlap on one screen. 

Both screens with maps are initiated in viewpager. and both look the same in xml's. 

We couldn't reproduce the error on lower android version so it seems to be android 12 bug. 
<img width="319" alt="Screenshot 2022-10-21 at 16 53 08" src="https://user-images.githubusercontent.com/90251898/197214535-513ff9e8-2995-4a74-ab6e-3c01bc6ab979.png">
<img width="317" alt="Screenshot 2022-10-21 at 16 53 43" src="https://user-images.githubusercontent.com/90251898/197214548-914cd07c-b8c7-4ab6-b6c2-67cc03a0eb77.png">

For example we have 2 fragments: 
Fragment A & Fragment B

When opening the app B overlaps A. B is frozen but you can see how A moves. 

When going from A to B everything is perfect.

On return to A from B small part of the map is left on the right side of the screen. 

I've also tried to update to v10.9.1 beta version but the bug persisted.

 ```
<com.mapbox.maps.MapView
        android:id="@+id/find_map_events"
        mapbox:mapbox_mapSurface="texture_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_below="@+id/find_tabs" />
```

## Expected behavior

maps should not overlap and stay in their fragments.

**Comment by ZiZasaurus** [comment]
@meciusMP thank you for reaching out. To better assist you, can you please provide a minimal sample application that reproduces this behavior?

**Comment by ZiZasaurus** [comment]
Closing this ticket but please feel free to reopen and respond with the requested information above if you continue to experience this issue.
