### ISSUE TITLE
Pinch-to-zoom seems broken when simultaneousRotateAndPinchToZoomEnabled false

### ISSUE THREAD

**Issue by cramptonism** [mapbox/mapbox-maps-android#1780]
## Environment

- Android OS version: 13
- Devices affected: Pixel 6
- Maps SDK Version: 10.9

## Observed behavior and steps to reproduce

This was not an issue on the last version of Mapbox we were on, which was 10.3. We only observed it when upgrading. See video below for demo. Basically when `gesturesPlugin.simultaneousRotateAndPinchToZoomEnabled=false`, if you are pinch-zooming quickly the map sometimes jumps at the end of the gesture. To be specific, this happens when one finger lifts before the other, as it can be reproed if you start a pinch-zoom gesture and then release one finger before the other, the entire map jumps. In the past I believe that would be treated as the end of the gesture and momentum would take over.

https://user-images.githubusercontent.com/13057523/198074526-1e3dd68a-c7a3-4ae4-8a39-fab79f32f51b.mp4

## Expected behavior

Pinch-to-zoom momentum continues from point gesture ends. Instead the map snaps to what I assume is the position of the last finger to be lifted, and then momentum pans the map from there.

## Notes

I tested this in the sample app by adding a toggle to the menu in GesturesActivity

GesturesActivity.kt
```
      R.id.menu_gesture_simultaneous_pinch_zoom -> {
        gesturesPlugin.simultaneousRotateAndPinchToZoomEnabled = !gesturesPlugin.simultaneousRotateAndPinchToZoomEnabled
        item.isChecked = gesturesPlugin.simultaneousRotateAndPinchToZoomEnabled
      }
```

menu_gestures.xml
```
    <item
        android:id="@+id/menu_gesture_simultaneous_pinch_zoom"
        android:checkable="true"
        android:checked="true"
        android:title="@string/toggle_simultaneous_pinch_zoom_enabled" />
```

**Comment by ZiZasaurus** [comment]
Thank you for reporting. This has been brought to the team for investigation. As soon as we have any updates we will post them here.

**Comment by Sonosar** [comment]
Any news on this?

**Comment by nixolas1** [comment]
Not sure if it is the same issue, but we are experiencing something related to pinch to zoom. When zooming in with two fingers, then panning, the pan speed is based on the zoom level before zooming in. This results in the pan moving way too fast. 
Example: https://i.imgur.com/EUG1XUi.mp4

**Comment by e-hartig** [comment]
This is preventing us from updating to any of the latest versions because the zoom gesture is buggy with both settings of `simultaneousRotateAndPinchToZoomEnabled`. 

With `gesturesPlugin.simultaneousRotateAndPinchToZoomEnabled=false` the map jumps at the end of a zoom gesture unless both fingers are removed from the map at exactly the same time (as described in this issue).  With `gesturesPlugin.simultaneousRotateAndPinchToZoomEnabled=true` zooming has a very strange feel as the map pans much faster than the fingers move if zooming and then panning (as described by nixolas1 above).

**Comment by kiryldz** [comment]
This was fixed in latest version of Mapbox (but in v11 only if I recall correctly). Please re-open if the issue persists.
