### ISSUE TITLE
两个fragment加载不同的地图

### ISSUE THREAD

**Issue by LqTk** [mapbox/mapbox-maps-android#1781]
在6.0手机上会出现第二个地图被第一个地图遮盖看不见
在高版本手机上出现重新进入app出现情况是如果在第一个fragment页面从桌面后台进入app会显示第二个地图，第一个fragment的地图被遮挡

**Comment by ZiZasaurus** [comment]
> On the 6.0 mobile phone, the second map will appear hidden by the first map.
In the case of re-entering the app on high-version mobile phones, if you enter the app from the desktop background on the first fragment page, the second map will be displayed, and the map of the first fragment will be blocked.

Thank you for reaching out. To better assist you, can you please provide a minimal sample application that reproduces this behavior?

**Comment by ZiZasaurus** [comment]
Closing this ticket, but please feel to reach back out if you're still experiencing issues.
