### ISSUE TITLE
[10.9.x/10.10.x/10.11.x] Rendering glitches for symbols when animating the map

### ISSUE THREAD

**Issue by florianPOLARSTEPS** [mapbox/mapbox-maps-android#1785]
## Environment

- Android OS version: irrelevant
- Devices affected: irrelevant (observed on OnePlus Nord, Pixel 6, Pixel 6a, Emulator)
- Maps SDK Version: 10.9.0

## Observed behavior and steps to reproduce

It seems an issue was introduced with `Mapbox Android 10.9.0` regarding the rendering of symbols on the map (on top of already existing rendering glitches with fading symbols when panning).

You can observe the issues in the following video. It happens very visibly when the Symbol in `Antarctica` is "selected" on the map.

https://user-images.githubusercontent.com/21218132/199196602-22db4187-50c8-4706-894d-114f828dd77f.mp4

I do not know exactly what in my setup causes these glitches, but I have created a minimal sample project [here](https://github.com/florianPOLARSTEPS/Mapbox-10-9-0-Glitch) that demonstrates it.

## Expected behavior

Symbol rendering is stable when animating the camera, updating a geojson source, adding images.

## Notes / preliminary analysis

This is a major issue for our integration, since, in our production app, this glitch is even more visible and essentially flickers large portions of our screen when the user interacts with the map. We cannot update to `10.9.0` until this is resolved, and we would love to because we also want to benefit from #1019 (which is our biggest crash at the moment for our userbase)

### What I know so far
- From what I found out during my tests is that the issue is only visible when using styles that include vector information. In case I use `Style.SATELLITE`, I cannot observe it.
- The glitches do not happen in `10.8.x`
- The glitches only happen when symbol images are provided dynamically via. `addOnStyleImageMissingListener`

## Additional links and references
[Sample Project](https://github.com/florianPOLARSTEPS/Mapbox-10-9-0-Glitch)

**Comment by ZiZasaurus** [comment]
Thank you for reporting. This has been brought to the team for investigation. As soon as we have any updates we will post them here.

**Comment by florianPOLARSTEPS** [comment]
@ZiZasaurus Do you have any update on this issue? We are stuck on `Mapbox v10.8.x` and cannot upgrade to releases that include other very important (crash) fixes for us.

**Comment by ZiZasaurus** [comment]
@florianPOLARSTEPS, thank you for following up. Instead of updating the geojson source, you can use the feature state API and control selected/unselected state.

**Comment by florianPOLARSTEPS** [comment]
@ZiZasaurus Thanks for your input. We are using the feature-state APIs for certain things in our setup, but I do not believe (unless something changed) for this particular case we will be able to use them, since

1. Those APIs only work on `paint`properties. Therefore we will never be able to control `icon-image`properties with them.
2. Those APIs also do not work in `layer.filter` expressions.
3. Apart from that small sample project where the data is pretty static, in our production setup, we have highly `mutable` data and we will not be able to get around `updateSource` in a lot of cases.

**Comment by florianPOLARSTEPS** [comment]
@alexshalamov Thanks for the input. Like mentioned previously, we are well aware of the benefits of using feature-states and we are using them for a growing number of things inside our setup, but due to their limitations (only paint properties, no layer.filter support) we cannot use it for all of our use-cases. 

I have tried the other suggestion (disabling `transitionoptions` via `Style.Builder.transitionOptions` and placementTransitions via `TransitionOptions.Builder().enablePlacementTransitions(false).build()`) to no success unfortunately. The issue persists.

**Comment by florianPOLARSTEPS** [comment]
@alexshalamov @ZiZasaurus This issue is still present (and I feel it got even worse) with `10.11.0`. We can still not upgrade our mapbox integration.

**Comment by alexshalamov** [comment]
@florianPOLARSTEPS I tried the attached example application with v10.11, and I didn't observe the flickering that you reported initially.

https://user-images.githubusercontent.com/1001009/222466991-254d22ee-0011-46b6-bc08-fabe2b32bf7b.mp4

**Comment by florianPOLARSTEPS** [comment]
> @florianPOLARSTEPS I tried the attached example application with v10.11, and I didn't observe the flickering that you reported initially.

@alexshalamov Hmmm... i doublechecked on my end, but unfortunately I cannot confirm that it works for me. I tested on a `OnePlus Nord running Android 12`, and a `Pixel 2 Emulator running Android 12` and in both cases I still see the glitches with Mapbox Android `10.11.1` with the initial sample project. 

https://user-images.githubusercontent.com/21218132/222668253-3269d6b3-9e5b-4e27-b7ad-dd89bc455d7f.mov

**Comment by alexshalamov** [comment]
@florianPOLARSTEPS thanks. I can reproduce the issue with `10.11.1` (pixel2). We will look into the issue next week.

**Comment by florianPOLARSTEPS** [comment]
@alexshalamov It seems the `10.12.x` releases fixed this issue. 🎉
