### ISSUE TITLE
Maps Doesn't Show New Added Layer

### ISSUE THREAD

**Issue by FahrihFatahilah** [mapbox/mapbox-maps-android#1786]
## Environment

- Android OS version: 12
- Devices affected: 
- Maps SDK Version: 9.2.0

## Observed behavior and steps to reproduce
![WhatsApp Image 2022-11-01 at 16 15 15](https://user-images.githubusercontent.com/20915197/199201021-7ad01102-e0d3-4ca9-a596-d68e13194b2f.jpeg)

https://pastebin.com/pLibEpiF heres the code to create a property
https://pastebin.com/tguW1qfv heres the code for styling
the feature collection https://pastebin.com/GgkFPDTi

## Expected behavior
the maps expected showing the layer that i create

## Notes / preliminary analysis

i also already create init for featurecollection

private fun initCandateList(@NonNull loadedMapStyle: Style): GeoJsonSource {
        val candidateListFeatureCollection = FeatureCollection.fromFeatures(arrayOf())
        val candidateListGeoJsonSource = GeoJsonSource(
            CL_SOURCE_ID,
            candidateListFeatureCollection
        )
        loadedMapStyle.addSource(candidateListGeoJsonSource)

        return candidateListGeoJsonSource
    }

**Comment by FahrihFatahilah** [comment]
please help me

**Comment by ZiZasaurus** [comment]
As this is more of a product support Issue, can you please create a support ticket at https://support.mapbox.com/hc/en-us/ and our support team will be happy to get you the answers you need.

**Comment by FahrihFatahilah** [comment]
> As this is more of a product support Issue, can you please create a support ticket at https://support.mapbox.com/hc/en-us/ and our support team will be happy to get you the answers you need.

thank you i will try craete a support tiket

**Comment by FahrihFatahilah** [comment]
currently, I'm using a license from my working place, but in the email says: We are experiencing a high volume of tickets coming in. If you haven't purchased one of our [support plans](https://www.mapbox.com/support#support-plans), we may not be able to respond to your question.

is my question still will be answered?
