### ISSUE TITLE
Set network restriction for map 

### ISSUE THREAD

**Issue by RoProducts** [mapbox/mapbox-maps-android#1787]
## New Feature

I would like to restrict the map to load data only with WIFI connection. Is that possible like for OfflineManagers [TileRegionOptions ](https://docs.mapbox.com/ios/maps/api/10.0.1/Extensions/TileRegionLoadOptions.html#/s:So24MBXTileRegionLoadOptionsC10MapboxMapsE8geometry11descriptors8metadata13acceptExpired18networkRestriction21averageBytesPerSecondABSg4Turf8GeometryOSg_SaySo20MBXTilesetDescriptorCGypSgSbSo010MBXNetworkM0VSiSgtcfc)?

**Comment by ZiZasaurus** [comment]
You can accomplish this by using the [HTTPServiceInterceptorInterface](https://docs.mapbox.com/ios/maps/api/10.9.1/common/Protocols/MBXHttpServiceInterceptorInterface.html) and set the onRequest method to return an HTTP Request that disallows expensive network requests, like cellular.  I've included a code snippet below:

```
final class MyInterceptor: HttpServiceInterceptorInterface {
  func onRequest(for request: HttpRequest) -> HttpRequest {
          return HttpRequest(
              method: request.method,
              url: request.url,
              headers: request.headers,
              keepCompression: request.isKeepCompression,
              timeout: request.timeout,
              networkRestriction: .disallowExpensive,
              uaComponents: request.uaComponents,
              body: request.body
          )
      }
}
```

You would then reference this interceptor by using the following line: 
```
HttpServiceFactory.getInstance().setInterceptorForInterceptor(MyInterceptor())
```
