### ISSUE TITLE
Change log level to Verbose for CameraManager

### ISSUE THREAD

**Issue by Chaoba** [mapbox/mapbox-maps-android#180]
There are too many log outputs in CameraManager with log level `Info` and those logs will make it difficult to find the logs we are really interested in. 
The log level for those logs can be changed to `Verbose` so that we can easily filter them in Android Studio.

**Comment by tobrun** [comment]
I would even suggest, removing these logs all together or putting them behind a flag if we need to debug with them.

cc @mapbox/maps-android

**Comment by kiryldz** [comment]
> I would even suggest, removing these logs all together or putting them behind a flag if we need to debug with them.
> 
> cc @mapbox/maps-android

That was what I told @Chaoba as well, he just not added it to ticket.
Yes, I have plans in adding some API to enable / disable / control logs. Don't want to turn them off completely as they are often pretty helpful.

**Comment by tobrun** [comment]
Wonder if we need to make this a standard plugin configuration (log configuration for a plugin) ?

**Comment by pengdev** [comment]
Agree with @tobrun that we probably need a guideline of log levels for plugins.

**Comment by knov** [comment]
closing in favor of #876
