### ISSUE TITLE
Allow zooming beyond level 22

### ISSUE THREAD

**Issue by seadowg** [mapbox/mapbox-maps-android#1802]
## New Feature

Allow zooming beyond the current max level of 22 to at least the previous (v9) max of 25.

## Why

In https://github.com/getodk/collect, some users found it useful to be able to zoom beyond level 22 to be able to draw shapes (a feature the app supports) at a sub-metre level of accuracy (even though the map would often look fuzzy zoomed in this far). Mapbox v10's new max of 22 makes this much harder to do.

**Comment by kiryldz** [comment]
@seadowg I do not recall our SDK to have some hard limits on zoom actually. I guess it depends on the actual style definition. Although I see that our base `Layer` class has documentation that maxZoom maximum is 24 so perhaps your feature request has been partly implemented already 😄 

Please re-open with more details if needed.

**Comment by seadowg** [comment]
@kiryldz I'll check in with the folks that were having problems and see if it's better now.
