### ISSUE TITLE
Querying cluster for features (child, leaf)

### ISSUE THREAD

**Issue by Haoming-Wu92** [mapbox/mapbox-maps-android#1803]
## Environment

- Android OS version: 10, 12
- Devices affected: Xiaomi 9T, Google Pixel 3
- Maps SDK Version: 10.6.0, 10.9.0 (tried both)

## Problem
I'm trying to get all the children in a cluster, and I'm running into trouble. `queryRenderedFeatures, getGeoJsonClusterChildren, getGeoJsonClusterLeaves` all return the same thing. 

I can't seem to find any examples on V10 cluster from mapbox docs on how this is done. 
Is there a way to do this I'm not aware of?

## What I tried

```
val geoJsonSource = geoJsonSource(PARCEL_SOURCE_ID) {
    featureCollection(featureCollection) //All point features from server
    cluster(true)
    maxzoom(14)
    clusterRadius(20)
}

style.addSource(geoJsonSource)
```

1. queryRenderedFeatures:
```
mapboxMap.queryRenderedFeatures(
    RenderedQueryGeometry(
        ScreenBox(
            ScreenCoordinate(point.x - 10, point.y - 10),
            ScreenCoordinate(point.x + 10, point.y + 10)
        )
    ),
    RenderedQueryOptions(
        listOf(
            "cluster",
        ),
        null
    )
) { expected: Expected<String, MutableList<QueriedFeature>> ->
    Log.d("feature", "expected=" + expected.value.toString())
}
```

2. getGeoJsonClusterChildren:
```
mapboxMap.getGeoJsonClusterChildren(
    PARCEL_SOURCE_ID,
    feature //contains cluster
) {
    Log.d("cluster", "cluster=" + expected.value.toString())
}
```

3. getGeoJsonClusterLeaves: 
Pretty much the same as `getGeoJsonClusterChildren`, the only difference is with pagination parameters

## Result

When I click the cluster, all of the attempts return the same result from all 3 functions.
`
[[feature: Feature{type=Feature, bbox=null, id=10, geometry=Point{type=Point, bbox=null, coordinates=[-123.11751365661621, 49.267916563731774]}, properties={"cluster_id":10,"cluster":true,"point_count_abbreviated":"6","point_count":6}}, source: parcel-source, sourceLayer: , state: {}]]
`

## Expected Result

I was expecting `getGeoJsonClusterChildren` and `getGeoJsonClusterLeaves` to return me the children or leaves of the cluster

## Question

What I am doing wrong to get the child/leaf of the cluster?

**Comment by kiryldz** [comment]
@Haoming-Wu92 dedicated cluster click listeners were introduced in https://github.com/mapbox/mapbox-maps-android/commit/7a2610dff12fe1ea5ca489d2993f907e0e84c49b (v11.8.0-beta.1). Although it does not utilize `getGeoJsonClusterChildren` / `getGeoJsonClusterLeaves` - it makes it easier to work with cluster clicking. Let us know if this is sufficient. Closing the ticket, please re-open with concrete reproducible code example if needed.
