### ISSUE TITLE
Question: Android ImageSource (SDK v10)

### ISSUE THREAD

**Issue by dudiw** [mapbox/mapbox-maps-android#1804]
Hi @kiryldz and @tobrun, I really need your help

I'm trying to load an image from file and associate it with `ImageSource` (with coordinates) and `RasterLayer` with the same SOURCE_ID (using Mapbox Android SDK in Java).

Before v10, I would create an `ImageSource`, provide coordinates and Bitmap/Image and combine with a `RasterLayer` to show/hide the image. My code was working without issues:
The image would be displayed within the provided coordinates.
(Note: I verified that the coordinates are correct as a list of longitude and latitude pairs by testing it using GoogleMap's `GroundOverlay`).

Now in v10, I'm having trouble reconciling the Java-Kotlin API and I really need your help.

https://github.com/mapbox/mapbox-maps-android/blob/c932cc06971e319715cc9a39857c2bd2d327ba24/app/src/main/java/com/mapbox/maps/testapp/examples/ImageSourceActivity.kt#L41-L46

My current attempt does not print or throw an error, but the image isn't displayed.
(A similar implementation for GoogleMaps API does display the image for this file path and coordinates) 
```java
// inside MapboxMap.loadStyle() -> onStyleLoaded(Style style)
     
// load image from file
Bitmap bitmap = decodeFile(new File(base, path), 0);
ByteBuffer buffer = ByteBuffer.allocate(bitmap.getByteCount());
bitmap.copyPixelsToBuffer(buffer);
style.updateStyleImageSourceImage(SOURCE_ID, new Image(bitmap.getWidth(), bitmap.getHeight(), buffer.array()));                                 style.addImage(sourceId, bitmap);

// associate image with coordinates
ImageSource source = new ImageSource.Builder(SOURCE_ID)
     .coordinates(LNG_LAT_BOUNDS)  // List<List<Double>> of longitude and latitude pairs
     .build();
SourceUtils.addSource(style, source);

// associate image with layers
RasterLayer raster = new RasterLayer(getLayerId(level), SOURCE_ID);
LayerUtils.addLayer(style, raster);
```

Questions:
1.  Could you please share a Java example on achieving the above for SDK v10?
(maybe this official Mapbox Java example by @yunikkk can serve as a basis [DSLStylingJavaActivity.java](https://github.com/mapbox/mapbox-maps-android/blob/main/app/src/main/java/com/mapbox/maps/testapp/examples/java/DSLStylingJavaActivity.java))
2. Is there an option to add an `Image` or `ImageSource` with _url_ that points to a file from the device's storage instead of loading a Bitmap?

Thank you!

**Comment by kiryldz** [comment]
@dudiw can you please provide sample Github project of the code that's _not_ working for you?

**Comment by dudiw** [comment]
> @dudiw can you please provide sample Github project of the code that's _not_ working for you?

Thank you @kiryldz for following up on my issue.

My question is aimed at using [imageSource.updateImage()](https://github.com/mapbox/mapbox-maps-android/blob/c932cc06971e319715cc9a39857c2bd2d327ba24/app/src/main/java/com/mapbox/maps/testapp/examples/ImageSourceActivity.kt#L41-L46) in Java (Android). 

I saw examples for `PointAnnotationManager` and `LocationComponent` in Java and I could really use your insights for adding `ImageSource` to the map via Style or StyleExtension or in some other way

I appreciate your help!

**Comment by kiryldz** [comment]
You add an image source as shown here
https://github.com/mapbox/mapbox-maps-android/blob/c932cc06971e319715cc9a39857c2bd2d327ba24/app/src/main/java/com/mapbox/maps/testapp/examples/java/DSLStylingJavaActivity.java#L157-L164
and you could update an image with following code in Java:
```java
ImageSourceExtKt.updateImage(imageSource, new Image(bitmap.getWidth(), bitmap.getHeight(), byteBuffer.array()));
```

**Comment by dudiw** [comment]
> 

Thank you @kiryldz!
I got an error message when using `ImageSourceExtKt` saying that the plugin hasn't been initialized - is there another step for using the ImageSourceExt plugin?

**Comment by dudiw** [comment]
> It's hard to say what's happening w/o the code however I've updated our Java example in #1807 and fixed the bug that image source was not showing up. Now it does show up and image is taken from web by url, I guess that was the original question.

Thank you @kiryldz!
The updated example is helpful - any chance you could tell me how to reproduce the same effect but with an image store on the device? I have the image file path and I want to overlay it using `ImageSource` but I could not load the image (perhaps because the file path isn't a web url?)

**Comment by kiryldz** [comment]
@dudiw I'm sorry, I can not help without specifics here. Images could be stored on device in many different ways. If you want to keep things easy and allow Mapbox do the work - you could store your image in assets and access them as
```java
builder.addSource(
        new ImageSource.Builder(IMAGE_SOURCE_ID)
                .coordinates(POINT_LIST)
                .url("asset://<LOCAL_FILE_NAME>")
                .build()
);
```

**Comment by dudiw** [comment]
> @dudiw I'm sorry, I can not help without specifics here. Images could be stored on device in many different ways. If you want to keep things easy and allow Mapbox do the work - you could store your image in assets and access them as
> 
> ```java
> builder.addSource(
>         new ImageSource.Builder(IMAGE_SOURCE_ID)
>                 .coordinates(POINT_LIST)
>                 .url("asset://<LOCAL_FILE_NAME>")
>                 .build()
> );
> ```

Excellent @kiryldz I'll try it today and update this issue with my findings (and close it if resolved)

**Comment by dudiw** [comment]
> @dudiw I'm sorry, I can not help without specifics here. Images could be stored on device in many different ways. If you want to keep things easy and allow Mapbox do the work - you could store your image in assets and access them as
> 
> ```java
> builder.addSource(
>         new ImageSource.Builder(IMAGE_SOURCE_ID)
>                 .coordinates(POINT_LIST)
>                 .url("asset://<LOCAL_FILE_NAME>")
>                 .build()
> );
> ```

Hi @kiryldz - thank you for putting the effort to provide a code sample.
When I attempt to add an image through `ImageSource.Builder(SOURCE_ID).url(MY_URL).build()` I'm providing the image url as an absolute path:
```
/data/user/0/com.example.app/files/images/image_1.png
```
I've tested it and got the error:
```js
\Mbgl-StyleObserver]: OnMapLoadError: SOURCE, message: Failed to load source: Expected URL scheme 'http' or 'https' but no colon was found
```

The essence of what I'm trying to do:
I have an image file stored locally on the device. I want to overlay it on the map using a list of coordinates.
Before v10, I would simply instantiate an `ImageSource` with the file's absolute path and coordinates and attach to the style.
@kiryldz 
I'm trying to use the v10 Kotlin API from Java - and I'm looking for a way to load an image and attach it to an ImageSource (note: the image file is stored locally on the device - see path example above).

Would you be able to help me figure out how to load the image? I can use the file path or perhaps load the image as a `Bitmap` and then somehow attach it to the style? The documentation and examples don't show how to achieve this in Java

**Comment by dudiw** [comment]
Hi @kiryldz 

I was able to solve my problem - thank you so much for your help!
As it turns out, `ImageSource.Builder().url(#)` only accepts _https/http_ strings, and so instead I've added an `ImageSource` and a `RasterLayer` with the same `SOURCE_ID` using `StyleExtension.Builder` and then within the `OnStyleLoaded()` callback I invoked `style.updateStyleImageSourceImage(SOURCE_ID, Image())` with an `Image` I created explicitly (load Bitmap and construct a `com.mapbox.maps.Image`).

This is a bit more code compared with the SDK v9 but I'm glad to have arrived at the answer with your help

**Comment by pareshprajapati1990** [comment]
Hi @dudiw,

Could you please help me out? I'm facing the same issue for few images for few locations inside map not rendering when I'm trying to update after loading image using glide.

I have used following code snipped to update the image on button click.

Glide.with(<<context>>)
            .asBitmap()
            .load(<<remote image url>>)
            .into(object : CustomTarget<Bitmap>() {
                override fun onResourceReady(bitmap: Bitmap, transition: Transition<in Bitmap>?) {

                    // Updating retrieved image in map style
                    binding.mapFarmDetails.getMapboxMap().getStyle {
                        val imageSource: ImageSource = it.getSourceAs(IMAGE_POINT_ID)!!
                        val byteBuffer = ByteBuffer.allocate(bitmap.byteCount)
                        bitmap.copyPixelsToBuffer(byteBuffer)
                        imageSource.updateImage(
                            Image(
                                bitmap.width,
                                bitmap.height,
                                byteBuffer.array()
                            )
                        )
                    }
                }
                override fun onLoadCleared(placeholder: Drawable?) {}
            })
    }
    
    
I have also tried with updateStyleImageSourceImage(SOURCE_ID, Image()) but still few images are not displaying with both the approaches.

I would be thankful if anyone can help me here. I have search everywhere in google but didn't find any solution to my problem.

Let me know in anyway if I can help you to better understand the issue I'm facing if I'm missing out something here.

Thanks !!
