### ISSUE TITLE
How to do concat expression with prefix or suffix?

### ISSUE THREAD

**Issue by Haoming-Wu92** [mapbox/mapbox-maps-android#1805]
Mapbox version: 10.9.0

What I found on the GL web version example:
`['concat', 'square-rgb-', ['get', 'color']]`
suppose to output "square-rgb-{whatever color is}"

In kotlin
```
concat {
    get { literal("order_id") }
    literal(",")
}
```
I'm expecting: "14541,66541,69854," and so on.

Instead I'm getting:
`E/Mbgl-Source: {cluster=true, clusterProperties={order_ids=[concat, [get, order_id], ,]}, data=null, maxzoom=14, type=geojson, clusterRadius=20}`
`GeoJSON source clusterProperties member must be an array with length of 2`

To me `order_ids=[concat, [get, order_id], ,]`
looks pretty much just like the example's `['concat', 'square-rgb-', ['get', 'color']]`

how i am suppose to concat this string? I'm trying to add all the clustered ids into clusterProperties so I can get it when I click on it.
I have been searching high and low to find answers on expressions in Android, and it's really difficult.

**Comment by ZiZasaurus** [comment]
@Haoming-Wu92, as this is more of a product support Issue, can you please create a support ticket at https://support.mapbox.com/hc/en-us/ and our support team will be happy to get you the answers you need.

**Comment by longquangpham90** [comment]
v10.16.1 supported, but we can not concat numberFormat expression suffix
