### ISSUE TITLE
Expose utility functions for CoordinateBounds

### ISSUE THREAD

**Issue by kiryldz** [mapbox/mapbox-maps-android#182]
## New Feature

Expose functions: `getCenter`, `contains`, `union`, `intersect`, `containsLatitude`, `containsLongitude`, `include`, `getLatitudeSpan`, `getLongitudeSpan` as extension functions for `CoordinateBounds`.

Full definition of `LatLngBounds` (ancestor for `CoordinateBounds`) could be found [here](https://github.com/mapbox/mapbox-gl-native-android/blob/main/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry/LatLngBounds.java).

## Why

Provide easier migration from previous maps version, improve parity.

**Comment by pengdev** [comment]
seems duplicated with https://github.com/mapbox/mapbox-maps-android/issues/131

**Comment by kiryldz** [comment]
That's available for testing in [v10.2.0-beta.1](https://github.com/mapbox/mapbox-maps-android/releases/tag/android-v10.2.0-beta.1).
