### ISSUE TITLE
SoLoader problem on x64 - UnsatisfiedLinkError

### ISSUE THREAD

**Issue by ciprianiacobescu** [mapbox/mapbox-maps-android#1824]
## Environment

- Android OS version: 13
- Devices affected: Pixel 6
- Maps SDK Version: 10.9.1

## Observed behavior and steps to reproduce

Just load a map view.
Google Play store hints that the culprit might be SoLoader 0.8.4.

## Additional links and references

java.lang.UnsatisfiedLinkError: No implementation found for void com.mapbox.mapboxsdk.net.NativeConnectivityListener.initialize() (tried Java_com_mapbox_mapboxsdk_net_NativeConnectivityListener_initialize and Java_com_mapbox_mapboxsdk_net_NativeConnectivityListener_initialize__)

https://support.google.com/faqs/answer/12576726

**Comment by ciprianiacobescu** [comment]
Might be related to https://github.com/mapbox/mapbox-maps-android/issues/1697

**Comment by ciprianiacobescu** [comment]
Android 12, Samsung S21 affected also.

**Comment by ciprianiacobescu** [comment]
Found some old v9 embedded maps on old screens. Auch! 

As a quick workaround, to prevent the fatal crashes, i've added to build.gradel

implementation 'com.facebook.soloader:soloader:0.10.4'

until I have time to migrate to v10 (the important maps are v10).
 
Hope this helps somebody!

**Comment by yunikkk** [comment]
@ciprianiacobescu glad to see this resolved!
