### ISSUE TITLE
How to use the sketchEditor in mapbox android similar to arcgis android?

### ISSUE THREAD

**Issue by tanqidi** [mapbox/mapbox-maps-android#1832]
I used Kotlin to develop the mapbox android. I encountered a problem when drawing geometry. It is difficult for me to draw complex geometries, but I can use sketchEditor in arcgis android. Is there a tool class similar to sketchEditor in mapbox android? I see mapbox gl draw, but it is web based

**Comment by ZiZasaurus** [comment]
@tanqidi thank you for reaching out. We don't offer a built-in solution for drawing on mobile., however, you can use your own implementation to achieve your use case.
