### ISSUE TITLE
Rendering issues with long text fields on symbol layer

### ISSUE THREAD

**Issue by timMikkelsen** [mapbox/mapbox-maps-android#1838]
## Environment

- Android OS version: 13
- Devices affected: Pixel 7
- Maps SDK Version: 10.9.1

## Observed behavior and steps to reproduce

Rendering issues with long text on SymbolLayer when anchor is applied.

Steps to reproduce:

Create a geoJsonSource with a Point.
Create a symbolLayer with a long text and a long maxWidth to avoid line breaks:
```
val symbolLayer = SymbolLayer("testLayer", "test")
symbolLayer.textField("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum a lorem eu turpis varius dignissim vel sed ex. Proin imperdiet imperdiet lorem eu vehicula.")
symbolLayer.textMaxWidth(99999999.0)
symbolLayer.textAnchor(TextAnchor.LEFT)
```

Add this to a MapBoxMap and observe the label being rendered with artefacts;

![Screenshot_20221115-105302](https://user-images.githubusercontent.com/71499433/201888764-5d338279-89ce-488a-ab60-d0acfc9cd237.png)

## Expected behavior

That the label is rendered like any other label without the artefacts shown in the image

## Notes / preliminary analysis

The issue seems to appear at greater than 95 characters

**Comment by kiryldz** [comment]
Tried the code, fixed in latest versions (at least in v11.8.0-rc.1).
