### ISSUE TITLE
Add annotations (image markers) on offline map

### ISSUE THREAD

**Issue by dimitradg** [mapbox/mapbox-maps-android#1840]
I would like to ask, is possible to add image markers on a source when viewing offline maps?

**Comment by ZiZasaurus** [comment]
Yes, markers can be added when viewing offline maps. Please see our OfflineActivity example [here](https://github.com/mapbox/mapbox-maps-android/blob/main/app/src/main/java/com/mapbox/maps/testapp/examples/OfflineActivity.kt), which demonstrates adding a [circle annotation at runtime](https://github.com/mapbox/mapbox-maps-android/blob/f05f54d8708dedce2f41b6af8efe1ad827b11369/app/src/main/java/com/mapbox/maps/testapp/examples/OfflineActivity.kt#L88).
