### ISSUE TITLE
How to download offline tile region using featurecollection ?

### ISSUE THREAD

**Issue by JEFF0818REY** [mapbox/mapbox-maps-android#1863]
## New Feature

<- Description of the feature being requested and any outcomes desired, an example use case, and any suggestions for solution ->
I want to use offline map feature to download the tileregion of a city; Like Seattle, Chicago or LosAngles.
Where can I get the GeoJson of the city ?
How to put FeatureCollection in to tileRegionLoadOptions Builder?
Is there any example for this feature?

## Why
<- 1-2 sentence description of why you're requesting this feature. What problem does it solve? Why is it valuable? ->
I want to let use choose city and download the tileRegion of that city.

**Comment by ZiZasaurus** [comment]
@JEFF0818REY as this is more of a product support Issue, can you please create a support ticket at https://support.mapbox.com/hc/en-us/ and our support team will be happy to get you the answers you need.
