### ISSUE TITLE
Remove group of layers from styles programmatically 

### ISSUE THREAD

**Issue by dimitradg** [mapbox/mapbox-maps-android#1866]
Is there a way to remove group layers from a style programmatically?

I have created a custom style on MapBox studio and I have two group of layers, which I would like to use in custom occasions.

Is there a way to remove a group of layers from a style programmatically?

Right now I can remove a layer using

`style.removeStyleLayer()`

so I was wondering if there is something like `style.removeStyleGroupLayer`.

Thank you in advance

**Comment by ZiZasaurus** [comment]
@dimitradg there's no way to remove groups, however,  you can use [style.removeStyleLayer](https://docs.mapbox.com/android/maps/api/10.9.1/mapbox-maps-android/com.mapbox.maps/-style/#-1615402897%2FFunctions%2F540127926) and iterate over the layers you'd like to remove.
