### ISSUE TITLE
MapboxMap object (accessing getStyle) should not be stored and used after MapView is destroyed.

### ISSUE THREAD

**Issue by Dev-Bahaa-Alkhateeb** [mapbox/mapbox-maps-android#1869]
## Environment

- Android OS version: V12
- Devices affected: Google Pixel 6
- Maps SDK Version: 10.9.0

W/Mapbox: [maps-android\Mbgl-MapboxMap]: MapboxMap object (accessing getStyle) should not be stored and used after MapView is destroyed.
W/Mapbox: [maps-android\Mbgl-Style]: Style object (accessing getStyleImage) should not be stored and used after MapView is destroyed or new style has been loaded.

**Comment by kiryldz** [comment]
Warning message contains the needed information here: you are accessing either `MapboxMap` or `Style` object from your code when it is not advised to (`MapView` is already destroyed and / or style has been reloaded).

**Comment by Dev-Bahaa-Alkhateeb** [comment]
Thanks @kiryldz, there was a memory leak that caused this error.

Regards.
