### ISSUE TITLE
Migration issue (9.7.1 -> 10.9.1) unable to initialize MapBox with access token

### ISSUE THREAD

**Issue by sharmila-grandworks** [mapbox/mapbox-maps-android#1875]
## Environment

- Android OS version: Android 13(Tiramisu) Api 33
- Maps SDK Version: 10.9.1
- Android Studio: Dolphin(2021.3.1)

## Observed behavior and steps to reproduce

Up to Mapbox 9.7.1, We used to initialize Mapbox by calling 

`Mapbox.getInstance(getApplicationContext(),getResources().getString(R.string.map_box_key));`

However from V10 this is no longer possible. I could not find an alternate to this approach, and I am running into similar problem as [This one](https://stackoverflow.com/questions/74385604/why-am-i-getting-black-screenwith-mapbox-logo-on-my-android-app). 

![Screenshot_1669622000](https://user-images.githubusercontent.com/119421818/204542975-edf21421-168c-4b28-848d-e316327699ee.png)

I get this error in LogCat **`Failed to load style: HTTP status code 403`** which leads me to believe that it is a Token issue, However how exactly can we initialize with the Token.

## Expected behavior

Map to be loaded properly with the provided style.

**Comment by ZiZasaurus** [comment]
@sharmila-grandworks have you taken a look at our installation page for v10 [here](https://docs.mapbox.com/android/maps/guides/install/)? It outlines the steps to properly install the dependencies required to build with the Maps SDK for Android.

**Comment by sharmila-grandworks** [comment]
Hi, @ZiZasaurus , yes I have. All the tokens and libraries are configured as described. Thanks

**Comment by ZiZasaurus** [comment]
Can you please ensure that the username in your .netrc file is set to mapbox and check the DOWNLOADS:READ secret scope for your .netrc file secret token?

**Comment by sharmila-grandworks** [comment]
Thank you for the help @ZiZasaurus . We finally got it to fix by enabling the public scopes in our secret token. Before this, the secret token only had the DOWNLOAD:READ scope and nothing else. All the instantiation work of mapbox was done by the public token. That caused the issue. Now it's working fine.
