### ISSUE TITLE
[example] Add an example to showcase the usage of the new observable event API.

### ISSUE THREAD

**Issue by pengdev** [mapbox/mapbox-maps-android#189]
Refs https://github.com/mapbox/mapbox-maps-android/issues/49

With the land of https://github.com/mapbox/mapbox-maps-android/pull/166 and https://github.com/mapbox/mapbox-maps-android/pull/176 . We introduced the new observable event API. This ticket tracks the tail work to add an example activity to showcase the usage of the new observable event API.

cc @mapbox/maps-android

**Comment by tobrun** [comment]
Debug activity is using this API
