### ISSUE TITLE
Black screen after the installation of the app for several seconds

### ISSUE THREAD

**Issue by AndriiYanechko** [mapbox/mapbox-maps-android#1899]
## Environment

- Android OS version: Android 11,12,13
- Devices affected: Samsung S10, Emulator, Samsung Galaxy S22
- Maps SDK Version: 10.9.0, 10.9.1

## Observed behavior and steps to reproduce

Not related to my code, since I've commented out all code that interacts with the map, left just set default style in the `onCreate` and still see black screen for a second.

That's how view is defined in the XML:

```
        <com.mapbox.maps.MapView
            android:id="@+id/mapview"
            android:layout_width="match_parent"
            android:layout_height="match_parent"/>
```

## Expected behavior

I was migrating from the `9.X.X` version and I didn't see any black screen in the `9.X.X`, therefore I assume that black screen shouldn't be visible or at least better to put some "placeholder", but black screen is not acceptable and causes poor UX.

## Notes / preliminary analysis

Seems like performance issue of initialization, because it happens only the first time you've installed the app.

## Additional links and references

https://user-images.githubusercontent.com/112496967/206249032-66564fb2-8231-4083-bb2a-a70277e605ab.mp4

**Comment by AndriiYanechko** [comment]
Same behaviour for the `10.9.1`

**Comment by AndriiYanechko** [comment]
The issue is in loading custom style from URI, seems like it happening not fast enough. Maybe there are some best practices to avoid such behaviour for the first time ?

**Comment by AndriiYanechko** [comment]
@kiryldz Sorry for disinformation, seems like the issue is not in the loading of the style itself. I guess, I've found 100% reproduce case and I'm sharing code with you and Mapbox team. But still not sure is that an issue or something else.

**!!! NOTE !!!** You need to use url to the custom style

If I'm using the default Mapbox style's, like `mapbox://styles/mapbox/streets-v11` the issue doesn't appear, but whenever I put there url to my custom style the issue is happening almost each run whevener app requests a location permission while style is loading/mapbox initializing.

**How I fixed the issue** The fix is very simple - move request of the permission after Mapbox SDK style has been loaded, once I did it I don't saw that issue again. Maybe asking for the permission somehow affects the performance for app that asked the permission, like: OS think that app gone to the "background" and don't give all CPU time to the app, because system permission dialog is on the front. Also, maybe that's the issue in my style configuration, but beside that strange bug with permission app works fine.

The reproduce project I've used contains only this `MainActivity` class.

```
class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        val yourCustomUrl = "" // do not use default styles issue won't reproduce then
        findViewById<MapView>(R.id.mapView).apply {
            scalebar.enabled = false
        }.getMapboxMap().loadStyleUri(yourCustomUrl)
        if (!PermissionsManager.areLocationPermissionsGranted(this)) {
            ActivityCompat.requestPermissions(
                this,
                arrayOf(Manifest.permission.ACCESS_COARSE_LOCATION, Manifest.permission.ACCESS_FINE_LOCATION),
                101
            )
        }
    }
}
```

<details>
<summary>My XML code</summary>

```
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".MainActivity"
    >

    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Hello World!"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        />

    <com.mapbox.maps.MapView
        android:id="@+id/mapView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>

</androidx.constraintlayout.widget.ConstraintLayout>
```

</details>

<details>

<summary>My build.gradle file</summary>

```
plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'XXX.reproducemapbox'
    compileSdk 32

    defaultConfig {
        applicationId "XXX.reproducemapbox"
        minSdk 21
        targetSdk 32
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        buildConfigField "String", "MAPBOX_PRIVATE_API_KEY", "\"${secretProperty("MAPBOX_PRIVATE_API_KEY")}\""
        resValue "string", "mapbox_access_token", "\"${secretProperty("MAPBOX_PUBLIC_ACCESS_TOKEN")}\""
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {
    def mapboxSdkVersion = '10.9.0'
    implementation 'androidx.core:core-ktx:1.7.0'
    implementation 'androidx.appcompat:appcompat:1.5.1'
    implementation 'com.google.android.material:material:1.7.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation "com.mapbox.maps:android:$mapboxSdkVersion"
    implementation "com.mapbox.plugin:maps-locationcomponent:$mapboxSdkVersion"
    implementation "com.mapbox.plugin:maps-logo:$mapboxSdkVersion"
    implementation "com.mapbox.plugin:maps-gestures:$mapboxSdkVersion"
    implementation "com.mapbox.plugin:maps-animation:$mapboxSdkVersion"
    implementation "com.mapbox.plugin:maps-animation:$mapboxSdkVersion"
    implementation "com.mapbox.plugin:maps-compass:$mapboxSdkVersion"
    implementation "com.mapbox.plugin:maps-annotation:$mapboxSdkVersion"
    implementation "com.mapbox.plugin:maps-attribution:$mapboxSdkVersion"
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.0'
}
```

</details>

Here is another one reproducing video on `10.9.0` with code that I've mentioned above:

https://user-images.githubusercontent.com/112496967/206495274-a41b4927-3577-4b48-8cb0-e61b383943c8.mp4

**Comment by AndriiYanechko** [comment]
@kiryldz I'd expect to not seeing the black screen. That's for example how it was working for `9.4.0`. I also noticed that for some reason Android request permission dialog impacts the "performance" of loading the style (or it might be something else, but if I request the location permission same time the Mapbox SDK tries to get the my custom style I've got the black screen).

The other think on my mind why that could happen - the Mapbox somehow downloads/parses/applies the style slower that it was in `9.4.0`, therefore it do "that" operation doesn't fast enough (for the first launch) and it causes black screen.

That's how it was in `9.4.0` it has yellow-white screen, but not the black as in `10.9.0`:

https://user-images.githubusercontent.com/112496967/206537909-99bd07a4-0f16-4d7b-b6dc-eece618000e8.mp4

**Comment by kiryldz** [comment]
@AndriiYanechko thanks for the investigation! I'm not that familiar with v9 however in the recording you have from v9 loading time to me seems even longer and also glitchy - the only diff is that there's no black color.
We do not have dedicated API to control color before style is loaded and I can't say anything about actually permission dialog affecting overall performance.

Could you please try the following workaround and see if that suites you well:
```kotlin
// before loading style - use whatever color you find suitable for your UX
(mapView.getChildAt(0) as SurfaceView).setBackgroundColor(ContextCompat.getColor(this, android.R.color.holo_blue_dark))
// and clear color when style is loaded
mapView.getMapboxMap().loadStyleUri("customStyleUri") { loadedStyle ->
  (mapView.getChildAt(0) as SurfaceView).setBackgroundColor(ContextCompat.getColor(this@ActivityName, android.R.color.transparent))
  ...
}
```

**Comment by AndriiYanechko** [comment]
@kiryldz thanks! That's what I was looking for. This lines of code allows me to change the "black" screen to some other color that suits more for my UI, or even have a loading screen

**Comment by kiryldz** [comment]
Closing for now, please re-open if needed. I did create internal task to track better API to control `MapView` color before map is loaded but we do not have any strict timelines for this.
