### ISSUE TITLE
Block user's gestures to specific map area

### ISSUE THREAD

**Issue by dimitradg** [mapbox/mapbox-maps-android#1908]
I would like to restrict user's gestures to a specific map area, e.g. I want the user to be able to move around a map and zoom  in/out in a specific map area. Is this possible?

Thank you

**Comment by ZiZasaurus** [comment]
@dimitradg, please take a look at our restrict map panning example [here](https://docs.mapbox.com/android/maps/examples/restrict-bounds/). 

As this is more of a product support Issue, in the future please feel free to create a support ticket at https://support.mapbox.com/hc/en-us/ and our support team will be happy to get you the answers you need.
