### ISSUE TITLE
where is v10 version of plugin mapbox-android-plugin-places

### ISSUE THREAD

**Issue by byedo** [mapbox/mapbox-maps-android#1914]
if i upgrade to v10
how to upgrade this 
'com.mapbox.mapboxsdk:mapbox-android-plugin-places-v9:0.12.0'

i cannot not find 
com.mapbox.plugin:maps-places:10.10.0 or com.mapbox.extension:maps-places:10.10.0

**Comment by ZiZasaurus** [comment]
@byedo in v10 the dependencies are built into the SDK, so they do not need to be added separately. This plugin is not compatible with the Maps SDK v10 or higher. To add search functionality to an application using the Maps SDK v10 and higher, please take a look ar the [Search SDK for Android](https://docs.mapbox.com/android/search/guides/) documentation.
