### ISSUE TITLE
How to add a marker with text field in offline mode

### ISSUE THREAD

**Issue by dimitradg** [mapbox/mapbox-maps-android#1919]
I am using PointAnnotationManager to add annotations on my map when online.

I use the following code to load my annotations, which works properly:

`mapboxPointAnnotationManager = mapView.annotations.createPointAnnotationManager()`

```
mapboxPointAnnotationManager.create(
                        PointAnnotationOptions()
                            .withPoint(Point.fromLngLat(item.lon!!.toDouble(),  item.lat!!.toDouble()))
                            .withIconImage(ContextCompat.getDrawable(requireContext(),
                                R.drawable.ic_baseline_location_on_24)
                                ?.toBitmap(40, 40)!!)
                            .withIconAnchor(IconAnchor.BOTTOM)
                            .withTextField((index + 1).toString())
                            .withTextColor(annotationNumberColor)
                            .withTextJustify(TextJustify.CENTER)
                            .withTextAnchor(TextAnchor.TOP)
                            .withTextSize(16f.toDouble())
                            .withData(JsonParser.parseString(Gson().toJson(item)))
```
                    
Using the same piece of code offline, won't load any markers or TextFields, because API calls won't be able to executed, unless I load only an icon image like below:

```
mapboxPointAnnotationManager.create(
                        PointAnnotationOptions()
                            .withPoint(Point.fromLngLat(item.lon!!.toDouble(),  item.lat!!.toDouble()))
                            .withIconImage(ContextCompat.getDrawable(requireContext(),
                                R.drawable.ic_baseline_location_on_24)
                                ?.toBitmap(40, 40)!!)
                            .withData(JsonParser.parseString(Gson().toJson(item)))
                    )
```

Is there any way to load both ****icon images and text fields** annotation when offline?

Thank you in advance

**Comment by Rizigogogo** [comment]
got same  problem here, pleeeeeease tell me you finally solve it😍😍😍

**Comment by dimitradg** [comment]
I don't know if this is the proper solution, but I found the following work around that works for my case:

1 - I add a source of features to my style:

`style.addSource(
                geoJsonSource(SOURCE_ID) {
                    featureCollection(FeatureCollection.fromFeatures(loadMarkers()))
                }
            )`

where loadMarkers():

`private fun loadMarkers(): ArrayList<Feature> {
        val sourceMarkers = ArrayList<Feature>()

      items.forEachIndexed{ index, item ->
                val feature = Feature.fromGeometry(Point.fromLngLat(item.lon!!.toDouble(),  item.lat!!.toDouble()))
                feature.addStringProperty(MARKER_TITLE, (index+1).toString())
                sourceMarkers.add(feature)
        }
        return sourceMarkers
    }`
2 - add a symbol layer on the specific source and set text:

`style.addLayer(
                symbolLayer(LAYER_ID, SOURCE_ID){
                    textAllowOverlap(true)
                    textField(Expression.get(MARKER_TITLE))
                    textColor(Color.parseColor("#000000"))
                    textJustify(TextJustify.CENTER)
                    textSize(16f.toDouble())
                    textAnchor(TextAnchor.TOP)
                }
            )`

Hope that helps
