### ISSUE TITLE
Unable to navigate to browser when click on info options.

### ISSUE THREAD

**Issue by dilip786** [mapbox/mapbox-maps-android#1921]
## Environment

- Android OS version: Version 10+
- Devices affected: All devices.
- Maps SDK Version: 10.7.0'

## Observed behavior and steps to reproduce

* Enabled MaBoxLogo and Info icon from XML.
* I'm able to see logo and info icon.
* If i click on info, I'm able to see popup with options
* I'm not navigating to browser whe

https://user-images.githubusercontent.com/10658016/209120394-3dc0a049-e422-463b-8f18-1a5cb051de37.mp4

n i click on any option. 
Attached video for reference.

**Comment by jorgegomezdeveloper** [comment]
Good afternoon, in version 11.3 we still have the problem that several links in the information modal still do not work. Please see if your solution is possible. Thank you.

**Comment by kiryldz** [comment]
Might be connected with https://github.com/mapbox/mapbox-maps-android/issues/2304. Then this should be fixed in latest versions. Please check and re-open if the issue persists.
