### ISSUE TITLE
SymbolLayer().filter(Expression.literal(true))  bug

### ISSUE THREAD

**Issue by byedo** [mapbox/mapbox-maps-android#1923]
com.mapbox.maps.MapboxStyleException: Add layer failed: Failed to set `filter` property for `class-layer-line-id` layer. Error: filter value must be a non empty array

use sdk 10.10.0

why filter cannot use Expression.literal(true) or Expression.literal("true")

**Comment by mfazekas** [comment]
We're also seeing this, as a workaround we're using `Expression.all {}`

**Comment by kiryldz** [comment]
Closing as stale and having the workaround described in https://github.com/mapbox/mapbox-maps-android/issues/1923#issuecomment-1451707991
