### ISSUE TITLE
Setting LineLayer when taking Snapshots

### ISSUE THREAD

**Issue by vem-popprika** [mapbox/mapbox-maps-android#1926]
## New Feature
Draw LineLayer from style(has set) when taking snapshots

## Why
1. why you're requesting this feature
->  I can check LineLayer has drawn perfectly on my MapView but after I take a snapshot with set style data and check directory, **LineLayer is not showing on the result file...**  I would really appreciate any advice or adding this feature.
2. Why is it valuable?
-> User can check routes he/she passed by as a photo

**Comment by vem-popprika** [comment]
**MapSnapshotter.Options** is unresolved reference for SDK 10.9.0.
I've checked legacy reference from https://docs.mapbox.com/android/legacy/maps/examples/share-a-snapshot/
and I was going to try with **.withStyleBuilder** (to build option above) otherwise It's not possible due to unresolved reference.

it there any option for this function on current version(10.9.0) ???

**Comment by kiryldz** [comment]
Closing as stale. Please re-open with reproducible example if needed.
