### ISSUE TITLE
Setting a blank style at runtime will prevent symbols with text to be visible on map

### ISSUE THREAD

**Issue by SamYStudiO** [mapbox/mapbox-maps-android#1931]
## Environment

- Android OS version: 33
- Devices affected: Emulator
- Maps SDK Version: 10.10

## Observed behavior and steps to reproduce

When setting a blank style at runtime and adding a symbol using symbol layer then this symbol is not visible on map, though setting a blank style from mapbox studio works as expected.
```
getMapboxMap().loadStyle(style{}) // Wont work > symbol is not visible on map
getMapboxMap().loadStyle(style("mapbox://styles/samystudio/clckrokcf000i14miz31b8fqa") {}) // Will work > symbol is visible on map
...
style.addImage...
style.addSource...
style.addLayer(symbolLayer(...))
```

## Expected behavior
Symbol should be visible when using a blank style at runtime the same way using a blank style from an URI created from mapbox studio.

**Comment by ank27** [comment]
@SamYStudiO I have checked at my end it seems to be working.

below is the code snippet i have used.

```
   mapboxMap.loadStyle(style{ }) {
      it.addImage("marker_icon", BitmapFactory.decodeResource(resources, R.drawable.red_marker))
      it.addSource(geojsonSource)
      it.addLayer(
        symbolLayer(layerId = "layer-id", sourceId = "source-id") {
          iconImage("marker_icon")
          iconIgnorePlacement(true)
          iconAllowOverlap(true)
        }
      )
    }
```

And result ->
<img width="312" alt="Screenshot 2023-02-08 at 12 15 30 PM" src="https://user-images.githubusercontent.com/11589497/217501126-a7f937d8-60d5-4e08-a4ec-5b47b4b29812.png">

Let me know if you have configured the style and symbols correctly. Or you can also share the code snippet here.

**Comment by SocialPeppa** [comment]
> 



> After more research i found out this happens whit symbol containing text, it seems it can't build symbol without font? how can i specify font programmatically without a style?

I have the same problem. Have you solved it？

**Comment by SamYStudiO** [comment]
No i couldn't figure out for now, i thought this was a font related pb as when you specify a unknwon font with a symbol marker this will prevent it from showing on map but after more search from source code it seems a defaut font is included with an empty style

**Comment by kiryldz** [comment]
Closing as stale.
