### ISSUE TITLE
Mapbox v10: Expression.stop() missing?

### ISSUE THREAD

**Issue by cchierici** [mapbox/mapbox-maps-android#1933]
## Environment

- Android OS version: API 33
- Devices affected:
- Maps SDK Version: 10.10

## Observed behavior and steps to reproduce

I'm migrating from 9.5 to 10.10 and used SymbolLayers with adapted icon sizes (due to zoom level).
in 9.5 i used the function Expression.stop(input, output) of the interpolar builder. 
It's still documented in the API doc of 10.10:

https://docs.mapbox.com/android/maps/api/10.10.0/mapbox-maps-android/com.mapbox.maps.extension.style.expressions.generated/-expression/-interpolator-builder/

But it's NOT in the com.mapbox.extension:maps-style:10.10.0 aar

So what's wrong here? Is the doc or did i something wrong?

same for functions: lte(), gt(), gte() and some more.

TIA

**Comment by cchierici** [comment]
I found out that the missing functions have moved to your new DSL-way to set things up. Hopefully i use it the right way.
I close this case again

**Comment by AkshatDubey10** [comment]
Where did you get the method ?

**Comment by cchierici** [comment]
i use it i.e. like this: 
the interpolat function is this one:
https://docs.mapbox.com/android/maps/api/10.0.0-rc.3/-mapbox%20-maps%20-android/com.mapbox.maps.extension.style.expressions.dsl.generated/interpolate.html

```
interpolate {
    linear()
    zoom()
    stop {
        literal(1.0)
        literal(0.0)
    }
    stop {
        literal(10.0)
        literal(1.0)
    }
}
```

**Comment by AkshatDubey10** [comment]
but this does not seem to work with Java, I am using the following use case
`Layer routeLayer = new LineLayer(layerId, sourceId)
                .lineCap(LineCap.ROUND)
                .lineJoin(LineJoin.ROUND)
                .lineWidth(interpolate(
                        Expression.exponential(literal(1.5f)), zoom(),)
//                        stop(10f, 7f),
//                        stop(14f, 10.5f * scale),
//                        stop(16.5f, 15.5f * scale),
//                        stop(19f, 24f * scale),
//                        stop(22f, 29f * scale)
//                        )
                )
                .lineColor(
                        index == primaryRouteIndex ? routeShieldColor : alternativeRouteShieldColor);`

I have commented the code for stop, I also checked the Expression.kt file this does have the method but the ExpressionDsl.kt file doesn't seem to have this method

**Comment by cchierici** [comment]
hm the argument of _interpolate_ ( from ExpressionDSL.kt ) is the _Expression.InterpolatorBuilder_ (from Expression.kt), rsp. it's subsequent function call chain which is passed in a lamda (which means the code between "{ }" is treated as a function argument. so called high order functions.
As i remember java supports also lamda expressions, so may try it this way. 


```
interpolate {
    linear()
    stop()
}
```

**Comment by AkshatDubey10** [comment]
Thanks for the help, what I did was make a helper function in kotlin for creating the layer, there I was able to get the stop function and made my work lot more easy
