### ISSUE TITLE
Using scrollable views as annotations

### ISSUE THREAD

**Issue by serhuz** [mapbox/mapbox-maps-android#1939]
## Environment

- Android OS version: 12
- Devices affected: all
- Maps SDK Version: 10.10.0

## Observed behavior and steps to reproduce
* Add a `RecyclerView` as an annotation
* Try to scroll the recycler
* Map is being dragged instead

## Expected behavior
The recycler should be scrollable

## Notes / preliminary analysis
Seems like the `MapView` is consuming touch events and the recycler becomes unscrollable

**Comment by kiryldz** [comment]
hi, can you please check if recycler is scrollable when using `v10.9.0`?

**Comment by serhuz** [comment]
yes, scrolling works on `v10.9.0`

**Comment by kiryldz** [comment]
Thanks for confirming!
It seems that we need to introduce some new API to allow / restrict intercepted touch events. For now I believe using `v10.9.0` is the only option to make it work.

**Comment by yunikkk** [comment]
@serhuz could you try to call https://developer.android.com/reference/android/view/ViewGroup#requestDisallowInterceptTouchEvent(boolean) to stop map from intercepting recycler touch events?

**Comment by kiryldz** [comment]
Closing as stale.
