### ISSUE TITLE
How to launch the example app

### ISSUE THREAD

**Issue by abouroubi** [mapbox/mapbox-maps-android#1978]
The readme have a link to the Mapbox website (https://docs.mapbox.com/android/maps/examples/), and the in the Mapbox website we can read this

> Example application on GitHub
> 
> You can find additional examples for the Maps SDK on [GitHub](https://github.com/mapbox/mapbox-maps-android/tree/main/app). Clone the repository and run the example application following the instructions in the README.
> 

But there are no instructions on the readme file on how to run the example app.

**Comment by ank27** [comment]
hi @abouroubi . Can you please follow the instruction here https://github.com/mapbox/mapbox-maps-android/blob/main/DEVELOPING.md#building

Basically, you need to clone the project (and not just app). build it using gradle. and if you are using any ide (eg. Intellij), you can update the configuration option to `app` and just run using run icon on ide. 
Note: make sure you have configured credentials using https://docs.mapbox.com/android/maps/guides/install/#configure-credentials

Let me know if you still have some queries. thank you :)

**Comment by abouroubi** [comment]
It's working thank you
