### ISSUE TITLE
More flexibility on positioning anchor in annotation

### ISSUE THREAD

**Issue by tristan-garaud** [mapbox/mapbox-maps-android#1990]
## New Feature

I would like to have a feature where we could place more precisely the anchor on the annotation to make correspond to our image.
Our even decouple the anchor with the finger touch

## Why
When our image is having a little arrow to show where your point is, you don't want it to be covered by your finger. You need some visibilities for the user to put it not based on the finger but on the image.

**Comment by ank27** [comment]
Hi @tristan-garaud , could you share some code snippet for what you want to achieve. thank you :)

**Comment by kiryldz** [comment]
Closing as stale.
