### ISSUE TITLE
Mapbox: [LocationService]: Failed to get last location: no last known location available

### ISSUE THREAD

**Issue by yanshanshu** [mapbox/mapbox-maps-android#2001]
## Environment

- Android OS version:10
- Devices affected:
- Maps SDK Version:10.10.1

出现Mapbox: [LocationService]: Failed to get last location: no last known location available异常。
使用方法：
        callback = new LocationListeningCallback((BaseActivity) activity, productStatus);
        long DEFAULT_INTERVAL_IN_MILLISECONDS = 1000L;
        long DEFAULT_MAX_WAIT_TIME = DEFAULT_INTERVAL_IN_MILLISECONDS * 5;

        locationEngine = LocationEngineProvider.getBestLocationEngine((BaseActivity) activity);

        LocationEngineRequest request = new LocationEngineRequest.Builder(DEFAULT_INTERVAL_IN_MILLISECONDS)
                .setPriority(LocationEngineRequest.PRIORITY_NO_POWER)
                .setMaxWaitTime(DEFAULT_MAX_WAIT_TIME)
                .build();
        //判断是否有权限
        if (ActivityCompat.checkSelfPermission(activity, Manifest.permission.ACCESS_FINE_LOCATION)
                != PackageManager.PERMISSION_GRANTED && ActivityCompat.checkSelfPermission(activity,
                Manifest.permission.ACCESS_COARSE_LOCATION) != PackageManager.PERMISSION_GRANTED) {
            // TODO: Consider calling
            //    ActivityCompat#requestPermissions
            //在这里请求缺失的权限，然后重写公共无效onRequestPermissionsResult(int requestCode, String[] permissions，
            // int [] grantResults)
            //处理用户授予权限的情况。看文档
            //为ActivityCompat#requestPermissions获取更多详细信息。
            Log.d("MapboxLocationUtils","没有定位权限");
            return;
        }

        locationEngine.requestLocationUpdates(request, callback, activity.getMainLooper());
        locationEngine.getLastLocation(callback);

**Comment by jush** [comment]
Hi, this is normal behaviour if the device has not yet been able to acquire a location at the time when `locationEngine.getLastLocation(callback)` is called.
