### ISSUE TITLE
How to add 3D models to the map?

### ISSUE THREAD

**Issue by ghraibeh** [mapbox/mapbox-maps-android#2005]
I am trying to add  3D models to my Mapbox map on Android, but I am having trouble figuring out the correct approach. 

Could you please provide guidance on how to add 3D models ? It would be very helpful if you could provide an example or point me towards relevant documentation.

We have successfully implemented 3D on iOS, but we are facing difficulties in adding it to Android

**Comment by ank27** [comment]
Here is an example of how to add a location puck model https://github.com/mapbox/mapbox-maps-android/blob/main/app/src/main/java/com/mapbox/maps/testapp/examples/LocationComponentActivity.kt#L185-L190

Let me know if that's what you are looking for. Or any code-snippet would be helpful.

**Comment by kiryldz** [comment]
Closing as stale.
