### ISSUE TITLE
Unable to resolve mapbox android dependency

### ISSUE THREAD

**Issue by asifjavaid** [mapbox/mapbox-maps-android#2008]
## Environment

- Android OS version 12:
- Maps SDK Version:   'com.mapbox.maps:android:10.11.0'

## Observed behavior and steps to reproduce
We have just created a test application and add all the suggested instructions in settings.gradle for authentication with the public token however we are getting the error 

'Could not resolve com.mapbox.maps:android:10.11.0'. Could not get resource https:/.xxxxx 

![image](https://user-images.githubusercontent.com/5367376/219101862-112eb077-3403-4443-821f-4ac8b7dc781e.png)

![image](https://user-images.githubusercontent.com/5367376/219101915-79e1c37e-78d8-433b-b61d-5321e9731be2.png)

## Expected behavior

can you please let us know what steps we are missing to integrate the android SDK successfully.

**Comment by MohammadSayed-NM** [comment]
Same issue is happening with me

**Comment by MohammadSayed-NM** [comment]
When I tried to use the token directly it worked without using MAPBOX_DOWNLOADS_TOKEN it worked!!

**Comment by MohammadSayed-NM** [comment]
I found the reason:
When you declare the token in `gradle.properties` or in `local.properties` don't use double quotes. For example:
Use `MAPBOX_DOWNLOADS_TOKEN = ABCD1234....`
Not: `MAPBOX_DOWNLOADS_TOKEN = "ABCD1234...."`

**Comment by BigBen3** [comment]
I am experiencing the same issue but I have the MAPBOX_DOWNLOADS_TOKEN without ""
