### ISSUE TITLE
Set touch area of Circle Annotation 

### ISSUE THREAD

**Issue by sleushunou** [mapbox/mapbox-maps-android#2010]
## New Feature

Set touch area of Circle Annotation
## Why
By default, the circles are nice and small. But touching them is hard. Can we increase touch target without increasing the circle?
I found a similar problem on iOS, can we solve it on Android too? [https://github.com/mapbox/mapbox-maps-ios/issues/1088](https://github.com/mapbox/mapbox-maps-ios/issues/1088)

**Comment by kiryldz** [comment]
Should be possible in one of the upcoming versions (most likely v11.9.X series) where we will introduce some global config for all touch (click, long click) interactions. Closing for now, follow the release notes.
