### ISSUE TITLE
3D terrain with location indicator causes UI distortions

### ISSUE THREAD

**Issue by LethalMaus** [mapbox/mapbox-maps-android#2016]
## Environment

- Android OS version: 13
- Devices affected: Pixel 6
- Maps SDK Version: 10.11.0

## Observed behavior and steps to reproduce

Create a 3D outdoor terrain map style and implement device location tracking

```
 binding.mapView.getMapboxMap().setCamera(
            CameraOptions.Builder()
                .pitch(65.0)
                .zoom(15.0)
                .build()
        )
        binding.mapView.getMapboxMap().loadStyleUri(
            "mapbox://styles/lethalmaus/cle5n9ca1001401p6dqf00sgq"
        ) {
            initLocationComponent()
            setupGesturesListener()
        }

    private fun initLocationComponent() {
        val locationComponentPlugin = binding.mapView.location
        locationComponentPlugin.updateSettings {
            this.enabled = true
        }
        locationComponentPlugin.addOnIndicatorPositionChangedListener(onIndicatorPositionChangedListener)
    }
```

## Expected behavior

Please see attached pics/video, the location indicator is raised much higher than what it should be and the 3D buildings are also distorted. I have also tried the same style without 3D buildings and have attempted to follow as many guides possible to improve performance

## Notes / preliminary analysis

None

## Additional links and references

![Screenshot_20230217-233218.png](https://user-images.githubusercontent.com/29340043/219808391-df263aec-4656-4690-abbb-29e166ab29b7.png)

https://user-images.githubusercontent.com/29340043/219809552-9b634710-9290-406b-827d-baa9056fb37d.mp4

**Comment by kiryldz** [comment]
Should be fixed in later versions. Please re-open if the issue persists.
