### ISSUE TITLE
Show annotations above all layers

### ISSUE THREAD

**Issue by VincentJoshuaET** [mapbox/mapbox-maps-android#2029]
```
fun MapView.addAnnotations() {
    with(annotations) {
        val config = AnnotationConfig()
        createCircleAnnotationManager(config).create(CircleAnnotationOptions())
        createPointAnnotationManager(config).create(PointAnnotationOptions())
        createPolygonAnnotationManager(config).create(PolygonAnnotationOptions())
        createPolylineAnnotationManager(config).create(PolylineAnnotationOptions())
    }
}
```

Is there any way to add annotations so that they show above **ALL** layers, without specifying the topmost layer?

**Comment by kiryldz** [comment]
@VincentJoshuaET I don't quite get what is the code you pasted and how does it relate to the question. Moreover annotations are actually using runtime styling under the hood meaning that they should be actually added on top of the map style. 
If you could perhaps share more details and the screenshot what is not working - that would be helpful.

**Comment by marat-tlepberghenov** [comment]
@VincentJoshuaET Use `belowLayerId` parameter in `AnnotationConfig` 

Example
```
private val pointAnnotationManager by lazy {
      annotations.createPointAnnotationManager(AnnotationConfig(layerId = MARKERS_LAYER_ID))
   }
   private val polylineAnnotationManager by lazy {
      annotations.createPolylineAnnotationManager(AnnotationConfig(layerId = ROUTE_LAYER_ID, belowLayerId = MARKERS_LAYER_ID))
   }
```

**Comment by kiryldz** [comment]
Closing as stale.
