### ISSUE TITLE
Android 加载其他地图底图

### ISSUE THREAD

**Issue by yanshanshu** [mapbox/mapbox-maps-android#2030]
## New Feature

<- Description of the feature being requested and any outcomes desired, an example use case, and any suggestions for solution ->
如果我用mapbox地图，但是底图我想替换成高德、百度、或者谷歌，应该怎么做？
## Why
<- 1-2 sentence description of why you're requesting this feature. What problem does it solve? Why is it valuable? ->

**Comment by kiryldz** [comment]
因过期而关闭
