### ISSUE TITLE
Add circle layer with java

### ISSUE THREAD

**Issue by daxiangyj** [mapbox/mapbox-maps-android#2031]
请问一下如何用java的api添加circlelayer图层

**Comment by daxiangyj** [comment]
Android v10 sdk

**Comment by baleboy** [comment]
Hi, I'm afraid this issue doesn't contain enough information to be able to reply. Could describe more in detail what is the problem?

**Comment by daxiangyj** [comment]
我使用的是java进行开发的，目前调用android mapbox V10 SDK，但是无法通过java的方法添加CircleLayer，没有addLayer方法，但是koltlin版本是有这个方法的。或者能不能提供有关CircleLayer的java调用的DEMO，谢谢！

**Comment by yunikkk** [comment]
@daxiangyj you could use `LayerUtils.addLayer(style, layer);` to add layer in java

**Comment by daxiangyj** [comment]
Thanks，I will try it.

**Comment by daxiangyj** [comment]
Thanks，I will try it.
