### ISSUE TITLE
How to draw line between two locations (lats/longs) without json file

### ISSUE THREAD

**Issue by asifjavaid** [mapbox/mapbox-maps-android#2033]
Hi all,

I am using this sample to draw line between multiple locations.
https://github.com/mapbox/mapbox-maps-android/blob/v10.11.1/app/src/main/java/com/mapbox/maps/testapp/examples/linesandpolygons/DrawGeoJsonLineActivity.kt

However I want to draw lines by taping on the mapview and get the location for that point and then draw line to the point where i will again tap on the mapview? So i want to draw lines by locations list with out json file.

Can you please guide us?

Thank you.
Asif.

**Comment by yunikkk** [comment]
@asifjavaid you could use PolylineAnnotationManagers to create polylines without specifying json manually, refer to the [example](https://github.com/mapbox/mapbox-maps-android/blob/v10.11.1/app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/PolylineAnnotationActivity.kt) and listen for map taps with `mapboxMap.addOnMapClickListener`
