### ISSUE TITLE
In Mapbox v10 SDK how to set setOfflineMapboxTileCountLimit

### ISSUE THREAD

**Issue by asifjavaid** [mapbox/mapbox-maps-android#2036]
## Environment

- Android OS version: 13
- Devices affected: all
- Maps SDK Version:  'com.mapbox.maps:android:10.11.0'

Hi all,
We are migrating our app from old legacy v8 SDK to v10 SDK in kotlin. Can you please guide us how can we set the offline mapbox tile count to download the mapbox tiles for PAID SDK.?

Thank you.
Asif.

**Comment by kiryldz** [comment]
Please follow the official docs on the website.
