### ISSUE TITLE
onIndicatorPositionChangedListener not firing

### ISSUE THREAD

**Issue by tendaimaswaya** [mapbox/mapbox-maps-android#2049]
## Environment

- Android OS version: 12
- Devices affected: Samsung SM-G973F
- Maps SDK Version: 10.11.0 (`com.mapbox.maps:android:10.11.0`)

## Observed behavior and steps to reproduce:

I have an app in production, i randomly opened this app and noticed, the map no-longer navigates to the user's current location but instead the screen is blue and the map has no marker as expected. The blue screen i believe means the map has latitude and longitude is 0,0.

This lead me to believe the **IndicatorPositionChangedListener** was not hitting as expected. On debugging, the same app via Android Studio, i noticed that indeed `onIndicatorPositionChangedListener` method is no-longer triggering.

Usage:

```
val locationComponentPlugin = binding.mapView.location
locationComponentPlugin.addOnIndicatorPositionChangedListener(
            onIndicatorPositionChangedListener
        )

   private val onIndicatorPositionChangedListener = OnIndicatorPositionChangedListener {
        mapView.getMapboxMap().setCamera(CameraOptions.Builder().center(it).build())
        mapView.gestures.focalPoint = mapView.getMapboxMap().pixelForCoordinate(it)
    } 
```
I have not made any changes to this app and my account reflects that it is active and usage is still within the appropriate threshold.

I made an additional enquiry into the matter, not knowing what this means.
Using Postman, i have pinged `https://api.mapbox.com/downloads/v2/releases/maven` using _Basic Authentication_ - 

> username: mapbox
> password: MY_MAPBOX_TOKEN.

The response is` 404 - Not Found.` Is this the expected response? Or it's an indication that something is out of place?

## Expected behavior
When i navigate to the map, it should automatically navigate to my location and place a marker there.

**Comment by kiryldz** [comment]
@tendaimaswaya could it be that because you were not using app for a while location permission has been revoked? If that will not be the case, can you check if issue is persistent on previous versions (from your description I understood you treat this as regression)?

**Comment by tendaimaswaya** [comment]
@kiryldz, the location permissions are enabled. Yes, i was treating this as regression, as the current prod apk had stopped functioning as expected.
I updated from `10.11.0` to `10.11.2`, rotated my access token and reinstalled on a few devices and it seems to be working as expected. Maybe the issue was with the access token.
