### ISSUE TITLE
Duplicate class com.mapbox.mapboxsdk.text.LocalGlyphRasterizer found in modules jetified-android-core-10.0.0-beta.15-runtime (com.mapbox.maps:android-core:10.0.0-beta.15) and jetified-mapbox-android-sdk-9.1.0-runtime (com.mapbox.mapboxsdk:mapbox-android-sdk:9.1.0)

### ISSUE THREAD

**Issue by jovanDjordje** [mapbox/mapbox-maps-android#205]
Hi, when I run build.gradle i get this error message:

```Duplicate class com.mapbox.mapboxsdk.text.LocalGlyphRasterizer found in modules jetified-android-core-10.0.0-beta.15-runtime (com.mapbox.maps:android-core:10.0.0-beta.15) and jetified-mapbox-android-sdk-9.1.0-runtime (com.mapbox.mapboxsdk:mapbox-android-sdk:9.1.0) ```

It looks like the error is provoked when I try to run these two lines together in build.gradle Module file:

```
implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-places-v9:0.12.0'
implementation "com.mapbox.maps:android:10.0.0-beta.14"

```
Does anyone know how to fix this?
Thx.

**Comment by pengdev** [comment]
Hi @jovanDjordje , the dependency `com.mapbox.mapboxsdk:mapbox-android-plugin-places-v9:0.12.0` is only compatible with v9 version of Mapbox Maps SDK. You can not mix use the v9 map plugin with the v10 maps SDK.

**Comment by srajala** [comment]
@jovanDjordje You might be interested in replacing the places plugin with this: https://docs.mapbox.com/android/search/guides/
