### ISSUE TITLE
Crash MercatorCoordinate.<init>

### ISSUE THREAD

**Issue by samirasalah** [mapbox/mapbox-maps-android#2050]
## Environment

- Android OS version: 12
- Devices affected: Y16
- Maps SDK Version: 'com.mapbox.maps:android:10.11.0'

## Observed behavior and steps to reproduce

My goal is to convert a list of locations into a list of projections List<MercatorCoordinate> at each change of user's position, so that finally I could create some routes according to the obtained projections. For that I used the project function of the MapBox.
`fun MapboxMap.localProject(location: Location): MercatorCoordinate? {
   return try {
        this.project(
            location.locationToPoint(),
            2.0.pow(cameraState.zoom)
        )
    } catch (e: Throwable) {
        null
    }
}`

Although the function is in Try catch, the app crashes in some cases and I can't get more details about this problem especially because this crash happens rarely.

Here are the traces of crashlytics:
`main (runnable):tid=1 systid=21234 
       at com.mapbox.maps.MercatorCoordinate.<init>(MercatorCoordinate.java:16)
       at com.mapbox.maps.Projection.project(Native method)
       at com.mapbox.maps.MapboxMap.project(MapboxMap.kt:931)`

## Expected behavior

Convert any location without crash

**Comment by yunikkk** [comment]
@samirasalah MercatorCoordinate is calling a simple constructor, an exception couldn't be thrown there. Could you share more context about the issue - e.g. the full stacktrace, other devices affected, did it happen with the previous maps versions etc.

**Comment by samirasalah** [comment]
For information the crash is reproduced when there is a zoom effect in both crashes.

**Comment by samirasalah** [comment]
Thanks
