### ISSUE TITLE
Newly created view annotations don't attach to window until their anchor moves into the camera frustum

### ISSUE THREAD

**Issue by jchristof** [mapbox/mapbox-maps-android#2051]
## Environment

- Android OS version: 12
- Devices affected: Samsung Galaxy S21 & Emulator Pixel 4 API 30
- Maps SDK Version: 10.11.2

## Observed behavior and steps to reproduce

Android view annotations remain unattached to window until positioned inside the camera frustum.

## Expected behavior

View annotation should attach immediately even if they are not visible.
For normal views this is probably fine, but if the view contains a compose view that collects state, the composable is inactive and will not begin collecting state from the view model.

## Notes / preliminary analysis

Add code that listens for attach/detach on the annotation view.

```
annotationView?.addOnAttachStateChangeListener(object : View.OnAttachStateChangeListener{
    override fun onViewAttachedToWindow(p0: View) {
        Timber.i("RouteBuilder: annotationView attached")
    }

    override fun onViewDetachedFromWindow(p0: View) {
        Timber.i("RouteBuilder: annotationView detached")
    }
})
```

Create an annotation outside of a visible area.
Note that if the annotation contains a compose view, setContent{} will not run.
Position the camera such that the annotation should be visible.
Note that the annotation becomes attached to the window and active.

**Comment by kiryldz** [comment]
@jchristof what's the bug actually? why should we attach the view if it's not yet visible? this may lead to huge performance issues. 
If it's really needed, could you describe your use-case when you need to attach the view but not show it (as it's not in the current viewport)?

**Comment by jchristof** [comment]
I think the work arounds for this are fine for me (no changes required to the MB implementation.) I only needed to reuse a single annotation for a variety of ui. In order to activate and begin collecting state from a composable, either worked for me:

- Place the compose annotation in the camera frustum when creating the annotation, setting the view to gone until it needs to appear. This will attach the view immediately. Thereafter, the visibility can be managed by the collected state value.

- Perform setContent{} in the attach callback for the view.
