### ISSUE TITLE
📝 Missing drawable?

### ISSUE THREAD

**Issue by AdelsJarlen** [mapbox/mapbox-maps-android#2053]
https://github.com/mapbox/mapbox-maps-android/blob/b35837b8e7c85df8c5476056f065d38ea56d55a0/app/src/main/java/com/mapbox/maps/testapp/examples/LocationTrackingActivity.kt#L86

Hi, I am following the documentation tutorial for [Location puck](https://docs.mapbox.com/android/maps/guides/install/#location-puck), and I am unable to locate two files:
* R.drawable.mapbox_user_puck_icon 
* R.drawable.mapbox_user_icon_shadow

Are they not included in the repo?

**Comment by yunikkk** [comment]
They're https://github.com/mapbox/mapbox-maps-android/blob/main/plugin-locationcomponent/src/main/res/drawable/mapbox_user_puck_icon.xml / https://github.com/mapbox/mapbox-maps-android/blob/main/plugin-locationcomponent/src/main/res/drawable/mapbox_user_icon_shadow.xml
