### ISSUE TITLE
How to rotate the Earth in the direction of the South and North Poles.

### ISSUE THREAD

**Issue by wingkingbobo** [mapbox/mapbox-maps-android#2075]
## New Feature

Is there parameter like cesium `viewer.camera.constrainedAxis=undefined`, that can cause the Earth to rotate along the South and North Poles?

## Why
I hope to rotate freely like Google Earth.

**Comment by florianPOLARSTEPS** [comment]
+1

**Comment by kiryldz** [comment]
This is not on the closest roadmap from what I know. However keep an eye on release notes for upcoming releases. I'll close this issue for now, if it will get more upvoting, we can re-open it and I'll try to escalate this feature to rendering team.
