### ISSUE TITLE
Draggable point annotations are no longer considered part of a cluster when dragged

### ISSUE THREAD

**Issue by ivoGanev** [mapbox/mapbox-maps-android#2078]
## Environment

- Android OS version: 13
- Devices affected: Samsung SM-G781B
- Maps SDK Version: 10.12.1

## General Info

I have an app that allows the user to add point annotations to a map and also being able to drag them. One of my requirements is to display the point annotations in clusters depending on the zoom levels. I have this cluster configuration:

```kotlin
pointAnnotationManager = mapView.annotations.createPointAnnotationManager(loadClusterAnnotationConfig())
...
private fun loadClusterAnnotationConfig(): AnnotationConfig {
    return AnnotationConfig(
        annotationSourceOptions = AnnotationSourceOptions(
            clusterOptions = ClusterOptions(
                textColorExpression = Expression.color(Color.YELLOW),
                textSize = 20.0,
                circleRadiusExpression = literal(12),
                colorLevels = listOf(
                    Pair(100, Color.RED),
                    Pair(50, Color.BLUE),
                    Pair(0, Color.GREEN)
                )
            )
        )
    )
}
```

The code that enables the user to add points to the map and be able to drag them is this:
```kotlin
override fun onMapClick(point: Point): Boolean {
    val drawable = ...
    addMarkerAtPosition(point, drawable)
    return true
}

private fun addMarkerAtPosition(point: Point, @DrawableRes drawable: Int) {
      val bitmap = BitmapUtils.bitmapFromDrawableRes(applicationContext, drawable)
      val pointAnnotationOptions: PointAnnotationOptions = PointAnnotationOptions()
          .withPoint(point)
          .withIconImage(bitmap!!)
          .withDraggable(true)

      pointAnnotationManager.create(pointAnnotationOptions)
}
```

## Steps to reproduce
1. Add two (or more) annotation points close to each other to create a cluster
![image](https://user-images.githubusercontent.com/64789004/233834443-77a1c4af-3500-49b0-9ed2-cae2d6857d67.png)

2. Zoom on the cluster to reveal the individual points
![image](https://user-images.githubusercontent.com/64789004/233834506-b4fce940-8ea4-4e8f-89f9-e263583b2122.png)

3. **Drag any of the points slightly, bringing it closer to the other point**
![image](https://user-images.githubusercontent.com/64789004/233835013-ae8bcceb-2865-4220-a3e5-92e8a4b9cdbd.png)

4. Zoom out. At this point, the annotation points are no longer part of a cluster group
![image](https://user-images.githubusercontent.com/64789004/233835103-8394af02-cb40-4825-a577-b45d448c44aa.png)

NOTE: This bug can be easily reproduced on the MapBox demo app in `PointAnnotationsCustomActivity` when you set the Annotation options to have draggable set to `true`:

_PointAnnotationClusterActivity.kt_
```kotlin
...
      .withIconImage(ICON_FIRE_STATION)
      .withDraggable(true)
```

## Expected behavior

At step 4, I would expect the annotation points to remain in the same cluster group when zooming out, even if an annotation point was **dragged**. For example, this is the correct behaviour (note that on the image bellow, I didn't dragged any of the points)
![image](https://user-images.githubusercontent.com/64789004/233835190-d9c06d5a-72bd-4958-bbe8-6f623699879d.png)

**Comment by jush** [comment]
Thanks @ivoGanev for your detailed report.

We'll investigate it further and report back.

**Comment by kiryldz** [comment]
@ivoGanev after discussing this with core team - it seems we will not be able to fix this in nearest future. We updated our public docs (e.g. [here](https://docs.mapbox.com/android/maps/api/11.8.0-rc.1/mapbox-maps-android/com.mapbox.maps.plugin.annotation.generated/-circle-annotation-options/with-draggable.html)) stating this.
