### ISSUE TITLE
cameraForCoordinates() wrong zoom

### ISSUE THREAD

**Issue by zhurbaTT** [mapbox/mapbox-maps-android#2080]
## Environment

- Android OS version: 13
- Devices affected: OnePlus 9
- Maps SDK Version: 10.8.0

## Observed behavior and steps to reproduce

Sometimes (not always) when I call cameraForCoordinates() it returns CameraOptions object with wrong zoom level (camera too high).

```
val cameraOptions = mapEngine.cameraForCoordinates(
            coordinates = getPoints(),
            padding = EdgeInsets(20.0, 20.0, 20.0, 20.0)
        )

mapEngine.setCamera(cameraOptions)
```

## Expected behavior

cameraForCoordinates() with correct zoom level

## Notes / preliminary analysis

I assume, that the reason can be in onMeasure() function: when the error occurs measuring always happens before AND then after cameraForCoordinates(). 
When no error - measuring only before cameraForCoordinates().

Please provide some info: will it be fixed on dev side and what is the workaround?

**Comment by dudeuter** [comment]
@zhurbaTT Do you mind providing precondition, actual, and expected for the wrong zoom you're getting so we can reproduce the issue?

**Comment by kiryldz** [comment]
@zhurbaTT please refer to [this](https://github.com/mapbox/mapbox-maps-android/issues/2282#issuecomment-1976242458) comment. Closing this one, if you feel your use-case is different, feel free to re-open with more details.
