### ISSUE TITLE
Pressing on the top-right "reset to north" button raises a "mapLongClick" event

### ISSUE THREAD

**Issue by adibarda** [mapbox/mapbox-maps-android#2086]
## Environment

- Android OS version: 9
- Devices affected:
- Maps SDK Version: v10

## Observed behavior and steps to reproduce

1. in your Java code, register an event handler using: GesturesUtils.**addOnMapLongClickListener**
2. rotate the map so the "reset to north" button will appear in the top-right corner of the map
3. press on the "reset to north" button - the map is rotated back to point to north
4. drag the map a little bit
5. a mapLongClick event is raised

## Expected behavior
mapLongClick event should be raised only when performing a long-click on the map

Thanks!
Adi

**Comment by kiryldz** [comment]
I suspect this should be resolved already. Please check the latest version and re-open if needed. Thanks!
