### ISSUE TITLE
Mapbox SDK corrupting SQLite database

### ISSUE THREAD

**Issue by viktor76525** [mapbox/mapbox-maps-android#2087]
## Environment

- Android OS version: 10
- Devices affected: Samsung Active Pro, emulator (rarely)
- Maps SDK Version: 10.13.0 (since 10.0.0-beta.15)

## Observed behavior and steps to reproduce

Trying to get some help with #309 .
We have mostly gotten around mapbox writing TLS data into our db by opening it once at app startup instead of on every query. But there are other libraries that are having their DBs made corrupt. 
It appears this issue is specific to Android 10. It happens with the test app quite soon after starting on Samsung devices. I have attached a logcat log of it happening with the emulator (rare).
[Uploading logcat-android-10-emulator.txt…]()
The master branch is quite outdated, the updated branch reproduces the issue, even if further updated.
This issue has been pinpointed to 10.0.0-beta.15, before that works, equal or later does not. There must have been something specific in that release, updating some library or dependency which exposes a bug in Android 10?

## Expected behavior

DB not corrupting.

## Notes / preliminary analysis

May be good to test on Samsung devices with Android 10. Seems to be limited to Android 10.

## Additional links and references

[309](https://github.com/mapbox/mapbox-maps-android/issues/309)

**Comment by kiryldz** [comment]
Closing as stale. Also there were quite a lot of changes made to offline / tilestore in Maps v11. Please re-open if the issue persists with latest release.
