### ISSUE TITLE
Padding Functionality Not Working After Pinching on Map in some cases 

### ISSUE THREAD

**Issue by ghraibeh** [mapbox/mapbox-maps-android#2089]
## Environment

- Android OS version: Android 13
- Devices affected: samusung s21
- Maps SDK Version: 10.13.0

## Observed behavior and steps to reproduce

1. Open the Mapbox application on Android device
2. Attempt to adjust the padding using the designated controls.
3. Zoom in or out on the map by pinching the screen.
4. Observe that the padding functionality no longer works as expected.

## Expected behavior

After pinching on the map, the padding functionality should remain functional, allowing users to adjust the map padding as desired.

## Actual Behavior:
Upon pinching on the map, the padding functionality becomes unresponsive and fails to adjust the map padding.

## Notes / preliminary analysis

This issue significantly impacts the usability of the Mapbox application. As a user, I rely on the padding functionality to customize the map display according to my preferences. It would be greatly appreciated if your  could investigate and address this issue .

I have attached any relevant video  that may assist you in troubleshooting the problem.

## Additional links and references

https://github.com/mapbox/mapbox-maps-android/assets/95626723/6f6b76dd-36e4-4117-acfc-67c44d15f2c7

**Comment by kiryldz** [comment]
Closing as stale.
