### ISSUE TITLE
A way to Reset location provider to the `DefaultLocationProvider` after setting a custom one

### ISSUE THREAD

**Issue by iboalali** [mapbox/mapbox-maps-android#2092]
## New Feature
After setting a custom location provider, e.g. a `NavigationLocationProvider` as described in the [Navigation SDK for Android Guide](https://docs.mapbox.com/android/navigation/guides/device-location/#location-puck-on-the-map), I can't return to the `DefaultLocationProvider`. 

I would like to have access to the `DefaultLocationProvider` to create an instance of it, and set it. Or a public method that does it for us.

## Why
Because otherwise I have to reimplement the exact functionality of the `DefaultLocationProvider` again, just so I can switch between providers, which we do often in one session.

**Comment by jush** [comment]
You can build a new [`DefaultLocationProvider`](https://github.com/mapbox/mapbox-maps-android/blob/main/plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/DefaultLocationProvider.kt#L30) and set it.
