### ISSUE TITLE
java.lang.IllegalArgumentException: latitude must not be NaN

### ISSUE THREAD

**Issue by sooniln** [mapbox/mapbox-maps-android#2093]
Google is observing a variety of different Android app crashes, all with stack traces pointing to the MapBox SDK. One vector of many is Android U devices running the SpotAngels app, which crashes 100% of the time.

All of the crashing apps appear to have similar stack traces within the MapBox SDK.

One representative trace:

```
04-02 17:57:28.096 E AndroidRuntime: FATAL EXCEPTION: main
04-02 17:57:28.096 E AndroidRuntime: Process: com.spotangels.android, PID: 19611
04-02 17:57:28.096 E AndroidRuntime: java.lang.IllegalArgumentException: latitude must not be NaN
04-02 17:57:28.096 E AndroidRuntime: 	at com.mapbox.mapboxsdk.geometry.LatLng.h(LatLng.java:35)
04-02 17:57:28.096 E AndroidRuntime: 	at com.mapbox.mapboxsdk.location.e.a(LatLngEvaluator.java:20)
04-02 17:57:28.096 E AndroidRuntime: 	at com.mapbox.mapboxsdk.location.e.evaluate(LatLngEvaluator.java:5)
04-02 17:57:28.096 E AndroidRuntime: 	at android.animation.KeyframeSet.getValue(KeyframeSet.java:202)
04-02 17:57:28.096 E AndroidRuntime: 	at android.animation.PropertyValuesHolder.calculateValue(PropertyValuesHolder.java:1017)
04-02 17:57:28.096 E AndroidRuntime: 	at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1652)
04-02 17:57:28.096 E AndroidRuntime: 	at android.animation.ValueAnimator.animateValuesInRange(ValueAnimator.java:1466)
04-02 17:57:28.096 E AndroidRuntime: 	at android.animation.AnimatorSet.animateValuesInRange(AnimatorSet.java:1015)
04-02 17:57:28.096 E AndroidRuntime: 	at android.animation.AnimatorSet.animateBasedOnPlayTime(AnimatorSet.java:861)
04-02 17:57:28.096 E AndroidRuntime: 	at android.animation.AnimatorSet.initChildren(AnimatorSet.java:1154)
04-02 17:57:28.096 E AndroidRuntime: 	at android.animation.AnimatorSet.startAnimation(AnimatorSet.java:1374)
04-02 17:57:28.096 E AndroidRuntime: 	at android.animation.AnimatorSet.start(AnimatorSet.java:745)
04-02 17:57:28.096 E AndroidRuntime: 	at android.animation.AnimatorSet.start(AnimatorSet.java:696)
04-02 17:57:28.096 E AndroidRuntime: 	at com.mapbox.mapboxsdk.location.w.b(MapboxAnimatorSetProvider.java:15)
04-02 17:57:28.096 E AndroidRuntime: 	at com.mapbox.mapboxsdk.location.i.t(LocationAnimatorCoordinator.java:35)
04-02 17:57:28.096 E AndroidRuntime: 	at com.mapbox.mapboxsdk.location.i.m(LocationAnimatorCoordinator.java:179)
04-02 17:57:28.096 E AndroidRuntime: 	at com.mapbox.mapboxsdk.location.k.d0(LocationComponent.java:84)
04-02 17:57:28.096 E AndroidRuntime: 	at com.mapbox.mapboxsdk.location.k.c0(LocationComponent.java:16)
04-02 17:57:28.096 E AndroidRuntime: 	at com.mapbox.mapboxsdk.location.k.b(LocationComponent.java:1)
04-02 17:57:28.096 E AndroidRuntime: 	at com.mapbox.mapboxsdk.location.k$o.a(LocationComponent.java:16)
04-02 17:57:28.096 E AndroidRuntime: 	at com.mapbox.mapboxsdk.location.k$o.onSuccess(LocationComponent.java:3)
04-02 17:57:28.096 E AndroidRuntime: 	at fc.b$a.a(GoogleLocationEngineImpl.java:18)
04-02 17:57:28.096 E AndroidRuntime: 	at fc.b$a.onSuccess(GoogleLocationEngineImpl.java:3)
04-02 17:57:28.096 E AndroidRuntime: 	at com.google.android.gms.tasks.zzm.run(com.google.android.gms:play-services-tasks@@18.0.1:26)
04-02 17:57:28.096 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:958)
04-02 17:57:28.096 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-02 17:57:28.096 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:205)
04-02 17:57:28.096 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:294)
04-02 17:57:28.096 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8174)
04-02 17:57:28.096 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-02 17:57:28.096 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
04-02 17:57:28.096 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
```

After investigation it is our belief that the MapBix is not being passed Location objects with a NaN value from Google Play services, but that this problem originates within MapBox itself somehow.

Users have also anecdotally reported "the app does not crash if I also have Maps open and in navigation/driving mode".

A preliminary avenue of investigation is thus that this may have something to do with MapBox state initialization.

**Comment by yunikkk** [comment]
Hey @sooniln , @DzmitryFomchyn this is a known issue with Android 14. It generates NaN in ValueAnimator when animation of 0 duration are launched, there's a [bugreport](https://issuetracker.google.com/issues/280660517) for it. 
We plan to filter the NaN's internally however.

**Comment by seventhmoon** [comment]
> We plan to filter the NaN's internally however.

Is there an ETA for the release?

**Comment by baleboy** [comment]
The fix will be in 10.14 rc which will be out later this week.

**Comment by baleboy** [comment]
Closed with https://github.com/mapbox/mapbox-maps-android/releases/tag/v10.14.0-rc.1

**Comment by JDM8** [comment]
It would be awesome if we could get a hotfix for v9 @baleboy:
https://github.com/mapbox/mapbox-maps-android/issues/2059

I know it's not supported, but anything built on v9 is having the same issue.

**Comment by sqawwas** [comment]
Seconded that getting this fix in v9 is needed before Android 14 goes live. At least a code solution we can put in would be appreciated.

**Comment by JDM8** [comment]
@sqawwas The latest Android 14 beta fixed this for me (an update to v10 also fixed it for the previous beta):
Android 14 Beta 3.1 (June 2023)
This minor update to Android 14 Beta 3 includes the latest security patch level and the following fixes:
Fixed issues where Fingerprint Unlock was either unavailable or unusable on some devices. ([Issue #284360298](https://issuetracker.google.com/issues/284360298), [Issue #284529436](https://issuetracker.google.com/issues/284529436), [Issue #284436572](https://issuetracker.google.com/issues/284436572))
**Fixed platform compatibility issues that were affecting mapping SDKs, which caused dependent apps to crash in some cases.**

**Comment by sqawwas** [comment]
@JDM8  thanks for following up! I am seeing Android 13 users get this same crash as well, it started happening a couple months ago according to our logs. Seems like its not fully only on the Android 14 beta so a fix in v9 would still be appreciated if possible!

**Comment by dave-laye** [comment]
Hello we have the same issue right now with [flutter_mapbox_navigation: ^0.1.8](https://pub.dev/packages/flutter_mapbox_navigation)

**Comment by palicka** [comment]
same here..
mapbox version: 9.7.1
system version: Android 14
