### ISSUE TITLE
mapbox doesn’t show a map. 

### ISSUE THREAD

**Issue by pphilipp** [mapbox/mapbox-maps-android#2095]
## Environment

-  minSdk 25 / targetSdk 32
- Maps SDK Version: 10.13.0
- Compose 

## Observed behavior and steps to reproduce

The map doesn't show, instead a blue color. 
![Screenshot 2023-05-27 at 21 43 50](https://github.com/mapbox/mapbox-maps-android/assets/9698643/5215202e-0bdb-461a-a6e9-4cf7572c7df0)

**Steps to reproduce:**
- following by installation guide - [link ](https://docs.mapbox.com/android/maps/guides/install/)
- useed AndroidView() in compose 
- observed an issue 

## Notes / preliminary analysis
According to other [ticket](https://stackoverflow.com/questions/72546818/show-mapbox-using-jetpack-compose) and duplicate [issue ](https://github.com/mapbox/mapbox-maps-android/issues/1422) was recommended to remove a background color declaration in themes.xml. But in my case, it is not working.

![Screenshot 2023-05-27 at 21 53 24](https://github.com/mapbox/mapbox-maps-android/assets/9698643/2d561d83-5d95-4893-aa29-59b41119e674)

**Comment by baleboy** [comment]
Could you provide a minimal project that reproduces the issue?

**Comment by pengdev** [comment]
Hey @pphilipphave you tried our [compose extension](https://github.com/mapbox/mapbox-maps-android/tree/main/extension-compose) and see if you experience similar issue?

**Comment by pengdev** [comment]
Closing as no further information provided.
