### ISSUE TITLE
Cannot remove markers by any means

### ISSUE THREAD

**Issue by tidoo** [mapbox/mapbox-maps-android#2100]
## Environment

- Android OS version: 11
- Devices affected: oneplus
- Maps SDK Version: 10.12.0

## Observed behavior and steps to reproduce

add markers like this ->

```
private fun addMarker(point: Point, @DrawableRes resourceId: Int) {
            BitmapHelpers().bitmapFromDrawableRes(
                itemView.context,
                resourceId
            )?.let {
                val annotationApi = binding.mapView.annotations
                val pointAnnotationManager = annotationApi.createPointAnnotationManager()
                val pointAnnotationOptions: PointAnnotationOptions = PointAnnotationOptions()
                    .withPoint(point)
                    .withIconImage(it)
                val marker: PointAnnotation = pointAnnotationManager.create(pointAnnotationOptions)
                markersList.add(marker)
            }
        }
```

and then remove marker->

        private fun removeMarkers() {
            val annotationApi = binding.mapView.annotations
            val pointAnnotationManager = annotationApi.createPointAnnotationManager()
            pointAnnotationManager.delete(markersList)
            markersList.clear()
        }

## Expected behavior

markers should be removed

## Notes / preliminary analysis

markers not removed by pointAnnotationManager

**Comment by kiryldz** [comment]
@tidoo you should store `val pointAnnotationManager = annotationApi.createPointAnnotationManager()` and use this instance to remove the markers you have created beforehand. In your case in `removeMarkers()` you are creating the new instance of the manager that is not aware of markers.

Feel free to re-open if this does not help and perhaps providing full example code so that I could check it, thanks!

**Comment by tidoo** [comment]
@kiryldz thank your for taking the time to respond me, now it is working perfectly by storing pointAnnotationManager instance
