### ISSUE TITLE
[Crash][Privacy] Excessive amount of `locationManagerHandlerThread` created on Android <= 10

### ISSUE THREAD

**Issue by florianPOLARSTEPS** [mapbox/mapbox-maps-android#2101]
## Environment

- Android OS version: <= 10
- Devices affected: Galaxy A6, Galaxy J6, Moto E6 Play but probably more
- Maps SDK Version: 10.12.2

## Observed behavior and steps to reproduce

We are seeing a lot of crashes happening due to out of memory errors on devices running Android <= 10. These crashes started happening after we updated our mapbox version from `10.8.1` to `10.12.2`. After investigation of the stack traces we found that all of them are due to an increased amount of Threads being created on those devices with a majority of them being named `locationManagerHandlerThread`. 

[stacktrace_obfuscated.txt](https://github.com/mapbox/mapbox-maps-android/files/11660814/stacktrace_obfuscated.txt)

After investigation of the bytecode of the app, we found that the only place these threads are generated is in a class called `com.mapbox.common.location.AndroidLiveTrackingClient`. Since the class is part of your closed source codebase it is impossible for me to figure out why this might happen. I am also unable to reproduce the issue, since I am unsure when and how the code might actually be executed.

Furthermore: We are not using the the built-in `LocationComponent.locationProvider` (`DefaultLocationProvider`) when we do live tracking on our maps but rather a custom locationProvider which we set via `LocationComponentPlugin.setLocationProvider` each time the user opts in to live location tracking in our app. Seeing these types of threads created does not only lead to crashes, but for us also is highly alerting since I would not expect any default livetracking being done unless we explicitly enable it.

## Expected behavior

There are no threads being excessively created even when opting in to livetracking. Livetracking code is only executed when actually enabled.

**Comment by jush** [comment]
Thanks a lot for your detailed report. We will investigate and come back to you.

**Comment by anhnguyen1618** [comment]
Hi @florianPOLARSTEPS, Is it possible to get the logcat of the device when this issue happens?

**Comment by florianPOLARSTEPS** [comment]
> Hi @florianPOLARSTEPS, Is it possible to get the logcat of the device when this issue happens?

Hi! Unfortunately, I have nothing more than the stack traces above and I have to date not been able to reproduce the issue myself. I know it started happening after we upgraded from mapbox `10.8.0` to `10.12.2`(respectively 10.13.0, 10.14.0). 

I do not know in which situations this issue could occur unfortunately. It happens to our users in all sorts of situations when our app is in the foreground or in the background.

Is there any passive tracking going on if the app is not in the foreground from mapbox side? Is there a way to turn that off as a workaround?

**Comment by florianPOLARSTEPS** [comment]
This issue has been resolved with `Version 10.15.0`. Thank you! 🙌
