### ISSUE TITLE
No url method is added in ModelLayer

### ISSUE THREAD

**Issue by garethpp** [mapbox/mapbox-maps-android#2103]
## New Feature
Add methods for adding 3d model address in ModelLayer

## Why
In Android SDK, I want to add a 3d model (such as.obj format), I found the ModelLayer class, but did not find how to add a model link method

**Comment by kiryldz** [comment]
Please seethe following [example](https://github.com/mapbox/mapbox-maps-android/blob/main/app/src/main/java/com/mapbox/maps/testapp/examples/terrain3D/ModelLayerActivity.kt). I am not familiar with `obj` format but you can try to use it directly or convert to `glb` / `gltf`.
