### ISSUE TITLE
Delete Multiple Pointannotaions 

### ISSUE THREAD

**Issue by SebastianMaier03** [mapbox/mapbox-maps-android#2108]
## Environment

- Android OS version: 13.0
- Devices affected:  All Smartphones and Emulators
- Maps SDK Version: 10.12.1

## Observed behavior and steps to reproduce

IIf we delete a Pointannotation and we have more than 1, only the first one will be deleted, the other annotations will stay on the map. We use a button to delete the annotations

## Expected behavior

Every should be deleted 

## Additional links and references
 Thats the Code 

```Kotlin
 private fun configureViewAnnotationButtons(
        viewAnnotation: View,
        questID: Int,
        pointAnnotation: PointAnnotation
    ) {
        val binding = DialogAcceptQuestPopupBinding.bind(viewAnnotation)
        binding.dialogAcceptQuestDeclineButton.setOnClickListener {
            viewAnnotation.visibility = View.GONE
        }

        binding.dialogAcceptQuestAcceptButton.setOnClickListener {
            CoroutineScope(Dispatchers.IO).launch {
                QuestLogic(context).finishedQuestGoal(questID, START_GOAL)
            }
            viewAnnotationManager.removeViewAnnotation(viewAnnotation)
            pointAnnotationManager.delete(pointAnnotation)
        }
    }

```

Full code can be seen here: https://github.com/TheLaendOfAdventure/The-Laend-of-Adventure/blob/b5610c803d049344815001a49786c8189ac9c7dd/app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/helper/MapHelper.kt

**Comment by SebastianMaier03** [comment]
Sry cant make a video but here is a short description: Maybe it's just a bug on my side, but when you press the delete button, the corresponding point annotation is deleted. if i press it now on my second annotation, it doesn't do it anymore. always the first element i execute delete on is deleted, but not on others.

**Comment by kiryldz** [comment]
Closing as stale.
