### ISSUE TITLE
Localize labels to local names

### ISSUE THREAD

**Issue by ystsoi** [mapbox/mapbox-maps-android#2111]
## New Feature

While we can use `style.localizeLabels(Locale.ENGLISH)` to localize labels to use "name_en", it seems that there is no way to localize labels to use "name".

## Why

Useful for local people.

**Comment by kiryldz** [comment]
Not sure I understand that feature fully. More data would be appreciated. Also keep in mind that `localizeLabels` is [public](https://github.com/mapbox/mapbox-maps-android/tree/main/extension-localization) code so as a first step you could perhaps provide the PR of what you're trying to achieve.
