### ISSUE TITLE
PolylineAnnotationManager lineCap doesn't work 

### ISSUE THREAD

**Issue by OliverCulleyDeLange** [mapbox/mapbox-maps-android#2114]
## Environment
 
- Android OS version:  12
- Devices affected: OP Nord
- Maps SDK Version: 'com.mapbox.maps:android:10.14.0'

## Observed behavior and steps to reproduce

Setting `lineCap` property on `PolylineAnnotationManager` has no effect

```kotlin
mapView.getMapboxMap()
      .apply {
        val lines = mapView.annotations.createPolylineAnnotationManager().apply {
          lineCap = LineCap.ROUND
        }
        setCamera(
          CameraOptions.Builder()
            .center(Point.fromLngLat(0.0, 51.0))
            .zoom(9.0)
            .build()
        )
        addOnMapLongClickListener { point ->
          lines.create(PolylineAnnotationOptions()
            .withPoints(listOf(point, Point.fromLngLat(point.longitude() + 0.1, point.latitude() + 0.1)))
            .withLineColor("rgba(255, 0, 0, 255)")
            .withLineWidth(10.0)
            .withLineJoin(LineJoin.ROUND)
          )
          true
        }
      }

```
<img width="322" alt="image" src="https://github.com/mapbox/mapbox-maps-android/assets/5558242/a2d2157a-f8a9-4407-a4cf-de5b3d32a572">

## Expected behavior

Line cap should be round.

**Comment by kiryldz** [comment]
Works at least with v11.8.0-rc.1: 

![image](https://github.com/user-attachments/assets/5eac30eb-4079-4e34-b340-1f30d7b654b1)

Thanks for detailed issue description and sorry for the delay.
