### ISSUE TITLE
isDraggable does not honor belowLayerId

### ISSUE THREAD

**Issue by JonasVautherin** [mapbox/mapbox-maps-android#2115]
## Environment

- Android OS version: 13
- Devices affected: Pixel 6 API 33
- Maps SDK Version: 10.13.0 & 10.14.1

## Observed behavior and steps to reproduce

I create a Polygon and a Symbol, and I want the symbol to appear above. I do that by setting a `layerId`, and a `belowLayerId` for the Polygon layer (such that it is below the symbol).

This works for the rendering (I can invert them using `belowLayerId`), but not for the draggability: the Polygon (which is the one declared first) is always "on top" when it comes to draggability. I also tried to use the "sortKey" (which seems like it is a weird name for a z-index), but it seems like this is only internal to one layer.

Here is a video showing the issue:

https://github.com/mapbox/mapbox-maps-android/assets/2606672/c8f45457-5d1e-4f53-83a5-f1f7acdf0196

My code looks like this:

```kotlin
        // Create a Polygon
        val polygonAnnotationConfig = AnnotationConfig(layerId = "polygonLayer", belowLayerId = "symbolLayer")
        val polygonAnnotationManager = annotationApi.createPolygonAnnotationManager(polygonAnnotationConfig)
        val points = listOf(
            listOf(
                Point.fromLngLat(17.94, 39.25),
                Point.fromLngLat(28.18, 39.25),
                Point.fromLngLat(28.18, 59.37),
                Point.fromLngLat(17.94, 59.37)
            )
        )
        val polygonAnnotationOptions = PolygonAnnotationOptions()
            .withPoints(points)
            .withFillColor("#ee4e8b")
            .withFillOpacity(1.0)
            .withFillSortKey(0.0)
            .withDraggable(true)
        polygonAnnotationManager.create(polygonAnnotationOptions)

        // Create a symbol
        val markerIcon = bitmapFromDrawableRes(this, androidx.core.R.drawable.ic_call_answer)
        val symbolAnnotationConfig = AnnotationConfig(layerId = "symbolLayer")
        val pointAnnotationManager = annotationApi.createPointAnnotationManager(symbolAnnotationConfig)
        val pointAnnotationOptions = PointAnnotationOptions()
            .withPoint(Point.fromLngLat(18.06, 59.31))
            .withIconImage(markerIcon)
            .withIconSize(5.0)
            .withSymbolSortKey(1.0)
            .withDraggable(true)
        pointAnnotationManager.create(pointAnnotationOptions)
```

## Expected behavior

I would expect the dragging to correspond to the actual rendering order: if the symbol is drone above the polygon, then the symbol should be dragged. If the polygon is drawn above, then the polygon should be dragged.

**Comment by JonasVautherin** [comment]
It doesn't seem very active here, so let me just mention that if someone can confirm that it is indeed a bug and point me roughly to a place in the code where I could start investigating, then I could actually try to fix it myself.

That is, if third-party contributions are reviewed and merged.

**Comment by ank27** [comment]
hi @JonasVautherin , this looks like a bug on our side, seems like `queriedFeatures` are not returned in the correct order when draggable layers are clicked. I will look for the root cause and get back to you 🙂

**Comment by JonasVautherin** [comment]
I tried to look for `queriedFeatures` in the code base but I could not seem to find anything relevant :confused:. Happy to have more pointers if you have deeper insights to share.

**Comment by JonasVautherin** [comment]
Kindly pinging here :see_no_evil:. @ank27 if you could point me to some place where I could start looking, then maybe I could debug it. That is, if Mapbox takes community contributions at all?

**Comment by JonasVautherin** [comment]
Ok, I think I found it, it's [here](https://github.com/mapbox/mapbox-maps-android/blob/main/plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationManagerImpl.kt#L780). And it ends up calling `queryRenderedFeatures` that goes into the native renderer.

My understanding is that every `AnnotationManagerImpl` registers a `MapMove` to the `GesturesPlugin`, and I am guessing that the `GesturesPlugin` is the thing that receives my gesture and calls the `MapMove` callback for all the annotation managers. When `MapMove.onMoveBegin()` is called for a particular `AnnotationManager`, it queries the map for the features (I guess that correspond to itself?) and starts dragging if it receives a feature (actually it receives a list of features, and it drags the first one, which is fine).

Now I am not completely sure what makes sure that only one `AnnotationManager` starts dragging. Is `queryRenderedFeatures()` making sure that only one annotation manager is being dragged at a time? It is called like this:

```kotlin
mapFeatureQueryDelegate.queryRenderedFeatures(
        RenderedQueryGeometry(screenCoordinate),
        RenderedQueryOptions(
          layerList,
          literal(true)
        )
      )
```

Because then it feels like the bug comes from the lower level (native), which should take the layer vertical order into account. But wouldn't that mean that the bug is present in all the languages that use the native core? :thinking:.

**Comment by JonasVautherin** [comment]
I found a fix for a similar bug in MapLibre (suggesting that the bug actually came from the old open source Mapbox code): https://github.com/maplibre/maplibre-plugins-android/pull/47/files.

Just for the record (I have been largely ignored by Mapbox both on Discord and GitHub, I am not expecting this to change anymore).

**Comment by ank27** [comment]
hey @JonasVautherin , thank you for your patience. I have an internal ticket for this already as a bug and it will to be taken into consideration soon. 
In v10 we did quite a few changes around the AnnotationManager impl, so this might need some tweaking from both native and platform code. will definitely communicate once this is fixed. 

> Just for the record (I have been largely ignored by Mapbox both on Discord and GitHub, I am not expecting this to change anymore).

We can understand your concern. it has been quite a busy summer with the development of our new [v11 SDK](https://github.com/mapbox/mapbox-maps-android/releases/tag/v11.0.0-beta.1) and [compose-extension](https://github.com/mapbox/mapbox-maps-android/releases/tag/extension-compose-v0.1.0) releases. I hope the new feature set will be an improvement and we will try to be a bit more active on public forum. Thank you 🙂

**Comment by ank27** [comment]
> Now I am not completely sure what makes sure that only one AnnotationManager starts dragging. Is queryRenderedFeatures() making sure that only one annotation manager is being dragged at a time? It is called like this:

@JonasVautherin , your understanding is correct. when `moveBegin` calls, we get the features rendered on the map using `queryRenderedFeature` with `layerList` in `RenderedQueryOptions `. 
Here it should be all the layers that are included in the source and not just the clicked layer. so instead of `layerList`, providing `null` will fix the issue.
i.e.
```
mapFeatureQueryDelegate.queryRenderedFeatures(
        RenderedQueryGeometry(screenCoordinate),
        RenderedQueryOptions(
          null,
          literal(true)
        )
      )
```
and then native provide all the features associated at that point. This fixes the issue with draggable annotations.

[262074160-9da04603-0ca6-4c92-973b-a7e1b4959bd8.webm](https://github.com/mapbox/mapbox-maps-android/assets/11589497/6b881590-cf95-4d18-877b-2a63d3079f2e)

**Comment by kiryldz** [comment]
@JonasVautherin
