### ISSUE TITLE
FollowPuckViewportStateOptions using compass

### ISSUE THREAD

**Issue by SamYStudiO** [mapbox/mapbox-maps-android#2119]
## New Feature

I'm using `makeFollowPuckViewportState` along with `FollowPuckViewportStateOptions` and would like to set bearing with compass, is there any way to do so? 

Thx

**Comment by jush** [comment]
`FollowPuckViewportState` will use whatever bearing the current `LocationProvider` emits if `FollowPuckViewportStateBearing.SyncWithLocationPuck` is passed in the `FollowPuckViewportStateOptions` bearing options.

Therefore, you need to change the current `LocationProvider` to use `HEADING` instead. If you use the default location provider you can do the following:
```Kotlin
(mapView.location.getLocationProvider()!! as DefaultLocationProvider).updatePuckBearing(PuckBearing.HEADING)
```

**Comment by jush** [comment]
It seems to be the same: https://github.com/mapbox/mapbox-maps-android/blob/main/plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPluginImpl.kt#L391
