### ISSUE TITLE
CoordinateBounds implementation inconsistent

### ISSUE THREAD

**Issue by Mordag** [mapbox/mapbox-maps-android#212]
I had a first look at the v10 implementation (beta.15) and I noticed that one of the most significant blockers for me is the current usage of CoordinateBounds which replaces LatLngBounds. Unfortunately that new class implements pretty much none of the apis LatLngBounds was providing. One of these is `LatLngBounds.Builder().includes(...)` - without that my current map creation setup gets much more complex unless I want to recreate these missing apis myself.

Additionally I have noticed that the former CameraUpdate (now CameraOptions) does not really replace the usage of `CameraUpdateFactory.newLatLngBounds(bounds, padding)`. CameraOptions offers CoordinateBox, but it does not offer the same flexibility as the former apis. To keep consistency, I think it would also be helpful to inject a CoordinateBounds as a camera target instead of doing another object transformation.

I hope you reconsider the current implementation and usage of the CoordinateBounds. In its current state, it creates a less flexible api surface than v9 and makes any work with the map and camera more complex.

**Comment by kiryldz** [comment]
Thanks for bringing it up, will close as we already have similar ticket https://github.com/mapbox/mapbox-maps-android/issues/182.

**Comment by Mordag** [comment]
The PR is unclear if it will take care of all extension methods (including the builder ones). When do you believe that will be part of a release?

**Comment by kiryldz** [comment]
> The PR is unclear if it will take care of all extension methods (including the builder ones). When do you believe that will be part of a release?

We will try to target next release in approx. 2 weeks but can't say for sure.
