### ISSUE TITLE
X-Ray effect of MapView

### ISSUE THREAD

**Issue by KirylAkulich1** [mapbox/mapbox-maps-android#2120]
## Environment

- Android OS version: reproduce on android 12
- Devices affected: 
- Maps SDK Version: v10

##Observed behavior and steps to reproduce

Application has the next implementation:
New activity(dialog) is opened above another activity(root). In dialog activity application  inflate fragment with MapView. But when fragment with MapView is replaced with another fragment then MapView sometime "shows" previous activity(root) content for a moment. It works like X-Ray. It ignores background of fragment view background, dialog activity background. 

## Expected behavior

No "X-Ray" effect

**Comment by kiryldz** [comment]
Hey! Could you try creating the `MapView` in texture mode? From XML:
```xml
<com.mapbox.maps.MapView
    ...
    mapbox:mapbox_mapSurface="texture_view" />
```
or from code:
```kotlin
val mapView = MapView(context, MapInitOptions(context, textureView = useTexture))
```

Please re-open with visuals (video, screenshot) and reproducible code if the issue will persist, thanks!
