### ISSUE TITLE
Android,Please add CLICK POINT param in this method——override fun onAnnotationClick(annotation: PolygonAnnotation)

### ISSUE THREAD

**Issue by NightMoonCat** [mapbox/mapbox-maps-android#2126]
Sometimes,I need to show viewAnnotation on click-point position in this polygon.If you can,please add CLICK POINT param in this method.

**Comment by NightMoonCat** [comment]
AnnotationManagerImpl,kt

![image](https://github.com/mapbox/mapbox-maps-android/assets/26139865/4d0a2477-698c-4b9d-98f6-009125918eec)

**Comment by kiryldz** [comment]
Hey! This is sadly not possible as adding parameter to `OnAnnotationClickListener` is a breaking change. Also in the callback the annotation is returned so you should be able to obtain the geometry.
If you really need the exact point - guess the best option is to register `mapboxMap.addOnMapClickListener` and combine results with the callback coming from annotation.
