### ISSUE TITLE
Duplicate class on build

### ISSUE THREAD

**Issue by thiagomacauba88** [mapbox/mapbox-maps-android#2133]
## Environment

Android OS version: compileSdkVersion 32, minSdkVersion 21
Devices affected:  cannot deploy to the device.
Maps SDK Version: 10.14.1

## Observed behavior and steps to reproduce

I'm getting duplicate classes issue, this is my dependencies:

implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.42.6'
implementation 'com.mapbox.maps:android:10.14.1'
implementation ('com.mapbox.maps:android:10.14.1') {
   exclude group: 'group_name', module: 'module_name'
}

And I really need the implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.42.6' dependency :(

Duplicate class com.mapbox.android.core.location.LocationEngine found in modules jetified-common-23.6.0-runtime (com.mapbox.common:common:23.6.0) and jetified-mapbox-android-core-1.4.0-runtime (com.mapbox.mapboxsdk:mapbox-android-core:1.4.0)
Duplicate class com.mapbox.android.core.location.LocationEngineCallback found in modules jetified-common-23.6.0-runtime (com.mapbox.common:common:23.6.0) and jetified-mapbox-android-core-1.4.0-runtime (com.mapbox.mapboxsdk:mapbox-android-core:1.4.0)
Duplicate class com.mapbox.android.core.location.LocationEngineProvider found in modules jetified-common-23.6.0-runtime (com.mapbox.common:common:23.6.0) and jetified-mapbox-android-core-1.4.0-runtime (com.mapbox.mapboxsdk:mapbox-android-core:1.4.0)
Duplicate class com.mapbox.android.core.location.LocationEngineRequest found in modules jetified-common-23.6.0-runtime (com.mapbox.common:common:23.6.0) and jetified-mapbox-android-core-1.4.0-runtime (com.mapbox.mapboxsdk:mapbox-android-core:1.4.0)
Duplicate class com.mapbox.android.core.location.LocationEngineRequest$1 found in modules jetified-common-23.6.0-runtime (com.mapbox.common:common:23.6.0) and jetified-mapbox-android-core-1.4.0-runtime (com.mapbox.mapboxsdk:mapbox-android-core:1.4.0)
Duplicate class com.mapbox.android.core.location.LocationEngineRequest$Builder found in modules jetified-common-23.6.0-runtime (com.mapbox.common:common:23.6.0) and jetified-mapbox-android-core-1.4.0-runtime (com.mapbox.mapboxsdk:mapbox-android-core:1.4.0)
Duplicate class com.mapbox.android.core.location.LocationEngineResult found in modules jetified-common-23.6.0-runtime (com.mapbox.common:common:23.6.0) and jetified-mapbox-android-core-1.4.0-runtime (com.mapbox.mapboxsdk:mapbox-android-core:1.4.0)
Duplicate class com.mapbox.android.core.permissions.PermissionsListener found in modules jetified-common-23.6.0-runtime (com.mapbox.common:common:23.6.0) and jetified-mapbox-android-core-1.4.0-runtime (com.mapbox.mapboxsdk:mapbox-android-core:1.4.0)
Duplicate class com.mapbox.android.core.permissions.PermissionsManager found in modules jetified-common-23.6.0-runtime (com.mapbox.common:common:23.6.0) and jetified-mapbox-android-core-1.4.0-runtime (com.mapbox.mapboxsdk:mapbox-android-core:1.4.0)

Any ideas?

Thanks :)

**Comment by kiryldz** [comment]
`mapbox-android-navigation-ui:0.42.6` is not compatible with Maps v10. However take a look at [Nav v2](https://docs.mapbox.com/android/navigation/v2/guides/) which is compatible, perhaps it has the features you need.
