### ISSUE TITLE
Cannot access 'setGeoJson': it is private in 'GeoJsonSource'

### ISSUE THREAD

**Issue by orlypsumdolor** [mapbox/mapbox-maps-android#2134]
## New Feature

function setGeoJson

## Why
I'm getting these examples https://github.com/search?q=repo%3Amapbox%2Fmapbox-android-demo+setGeoJson&type=code but function is private how do I access it or do you have any solution updating GeoJson?

**Comment by kiryldz** [comment]
Please use `feature`, `featureCollection`, `geometry`, `data` or `url` functions instead (if we're talking about Maps v10 where you opened this issue). Link you've posted relates to Maps v9, see https://github.com/mapbox/mapbox-gl-native-android
