### ISSUE TITLE
Adaptive Pin Sizing

### ISSUE THREAD

**Issue by elmasrya** [mapbox/mapbox-maps-android#2140]
## Question
Can we create an adaptive resizing of the pin with numbers/text inside?

**Comment by kiryldz** [comment]
yes, please refer to [9patch](https://developer.android.com/studio/write/draw9patch) Mapbox [example](https://github.com/mapbox/mapbox-maps-android/blob/lts/v10/app/src/main/java/com/mapbox/maps/testapp/examples/NinePatchImageActivity.kt).
