### ISSUE TITLE
【addOnCameraChangeListener】How can I listen for the event callbacks when the camera starts and ends?

### ISSUE THREAD

**Issue by NightMoonCat** [mapbox/mapbox-maps-android#2141]
After SDK 10.0，【addOnCameraMoveStartedListener 】and 【addOnCameraIdleListener】have been deleted.

How can I listen for the event callbacks when the camera starts and ends?

**Comment by kiryldz** [comment]
@NightMoonCat as in v10 we introduced several levels of controlling the camera animations, you could read more about it [here](https://github.com/mapbox/mapbox-maps-android/tree/lts/v10/plugin-animation). So there's no more such monolith callbacks as were in v10 but you could still [register](https://docs.mapbox.com/android/maps/api/10.15.0/mapbox-maps-android/com.mapbox.maps.plugin.animation/-camera-animations-plugin/add-camera-animations-lifecycle-listener.html?query=abstract%20fun%20addCameraAnimationsLifecycleListener(listener:%20CameraAnimationsLifecycleListener)) the [CameraAnimationsLifecycleListener](https://docs.mapbox.com/android/maps/api/10.15.0/mapbox-maps-android/com.mapbox.maps.plugin.animation/-camera-animations-lifecycle-listener/) to control all the map camera animations. So to achieve what you want I guess you'll need to add some counter = 0 on your side and when it becomes > 0 - this means that any camera animation has started and when it hits 0 again - it means that all camera animations have ended.
