### ISSUE TITLE
Missing Marker Shadows on Display

### ISSUE THREAD

**Issue by aDamian88** [mapbox/mapbox-maps-android#2151]
## Environment

- Android OS version: 30 - 31
- Devices affected: Galaxy Nexus, Pixel 6 Pro
- Maps SDK Version: 10.0

## Observed behavior and steps to reproduce

The marker shadow is not displayed correctly.

## Expected behavior

Although I inserted markers on the map and the marker icons have small shadows, on the map itself, these markers appear without the expected shadows.

## Notes / preliminary analysis

The marker icon:
![Screenshot 2023-08-23 at 12 09 27 PM](https://github.com/mapbox/mapbox-maps-android/assets/25756325/89866a7d-0e0d-47a3-8a97-a415ee42c3ad)

The display on the map:
![Screenshot 2023-08-23 at 12 10 49 PM](https://github.com/mapbox/mapbox-maps-android/assets/25756325/c48cebd3-c21d-41cf-8bb7-d354c20a45f2)

**Comment by kiryldz** [comment]
@aDamian88 thanks for reporting! Several things you could try:
1. Could you try increasing the size of the marker? Maybe the shadow is there, just barely visible because of downscaling and filtering.
2. If this does not help - can you add the image you use here (original file, you could attach it as zip to be sure it's not anyhow changed in attachments)?

**Comment by aDamian88** [comment]
@kiryldz Sure, the resize approach didn't work. Here is the original icon:
[marker_grey_charging_station.xml.zip](https://github.com/mapbox/mapbox-maps-android/files/12418366/marker_grey_charging_station.xml.zip)

**Comment by aDamian88** [comment]
@kiryldz The icon above is provided as a vector image. I am also sending the PNG version. Thank you for your feedback, by the way.
[pin_grey.png.zip](https://github.com/mapbox/mapbox-maps-android/files/12418654/pin_grey.png.zip)

**Comment by aDamian88** [comment]
You are right @kiryldz seems that there is a compatibility issue between Android Studio with Figma.[ Related link](https://developer.android.com/jetpack/compose/tooling/relay/limitations-and-troubleshooting). I am closing the issue, thanks for your time!
