### ISSUE TITLE
TextAnchor Property Expressions Not Executing 

### ISSUE THREAD

**Issue by LivPNavusoft** [mapbox/mapbox-maps-android#2152]
## Environment

- Android OS version: API 33
- Devices affected: Emulated Pixel 4a, Nexus 9
- Maps SDK Version: 10.14.1

## Observed behavior and steps to reproduce

When setting a map style using a feature collection, attempting to base a TextAnchor value from a property using an expression doesn't appear to work. Using a match {} or switchCase{} expression to analyze a Boolean property will crash, and conditional logic based on other data types appears not to process at all. I was unable to find a similar issue, but apologies if this is due to a misunderstanding on my part!

Reproduction
- Create a featureCollection. 
- Add desired data to the features using  an implementation of 
      `public static Feature fromGeometry(@Nullable Geometry geometry, @Nullable com.google.gson.JsonObject properties,`
- Use addProperty to add a string key for an image, a string property for the text of a textField, and a boolean/string value that will determine what TextAnchor to display
- Create a style and symbol layer using StyleExtensionImpl.Builder.
- Define corresponding images for your icons in your symbol layer
- In your symbol layer, create an icon and set IconAnchor to IconAnchor.BOTTOM
- In your symbol layer, define an icon whose TextAnchor property is based on an expression.
- Use match{} or switchCase{}  logic to create an expression based on your earlier property, that sets a TextAnchor
-  Apply your style using `style.getSourceAs<GeoJsonSource>(SOURCE_ID)?.featureCollection(features)`
- Run the app and load the map
- Boolean conditional logic causes crashes, due to argument errors that can't seem to be satisfied
- String conditional logic will cause no errors/crashes, but the TextAnchor property will not be created, and does not even use the fallback value

## Expected behavior

TextAnchor values should be processed based on the conditional logic in the created style

## Notes / preliminary analysis

In trying to set properties for a TextAnchor on my symbol layer based on a boolean property, I ran into a couple issues. I was referencing https://docs.mapbox.com/android/maps/examples/style-circles-categorically/  as well as https://docs.mapbox.com/android/maps/guides/styles/use-expressions/for Syntax in creating it (and tried both syntaxes), along with the DSL docs for expressions. I did turn to third party resources as well, but there were not many Android specific or reproducible. Initially, I was trying 

`
+symbolLayer(LAYER_ID, SOURCE_ID) {
                    iconImage(get("icon"))
                    iconColor(Color.WHITE)
                    iconAnchor(IconAnchor.BOTTOM)
                    iconAllowOverlap(true)

                    textField(get("sequence"))
                    textColor(Color.WHITE)

                    textAnchor(
                        match {
                            get("hasIcon")

                            stop {
                                literal(true)
                                TextAnchor.TOP
                            }

                            TextAnchor.CENTER
                        }
                    )
                }
`

but received the error 

`Add layer failed: Failed to set `text-anchor` property for `services-text` layer. Error: Expected at least 4 arguments, but found only 2.`

Adding a condition for when the boolean is false increases it to 3/4. Assuming the conditions needed to be exhaustive, I noticed that the addProperty function for a JSON Object properties accepts a nullable

<img width="698" alt="Screenshot 2023-08-23 at 7 45 42 PM" src="https://github.com/mapbox/mapbox-maps-android/assets/118359244/e8df8e15-e892-4432-bc45-916d7398a6bf">

However, literal values aren't nullable.  I tried the following without the literal wrapper 

`
textAnchor(
                        match {
                            get("hasIcon")

                            stop {
                                literal(true)
                                TextAnchor.TOP
                            }

                            stop {
                                literal(false)
                                TextAnchor.CENTER
                            }

                            stop {
                                null
                                TextAnchor.CENTER
                            }

                            TextAnchor.CENTER
                        }
                    )
`

However, this didn't change the error any further after adding the false condition, and it remained stuck at 3/4 - seemingly counting true, false, and the fallback but not null. I'm unsure if the nullability is the cause, but was unable to determine what it wanted.

I tried using a string property with the string value of boolean conditions, just to test if the logic worked otherwise. At first I received a similar argument error, but I replaced my null value with an empty string, and the following was able to run without crashes. 

`
textAnchor(
                        match {
                            get("hasIcon")

                            stop {
                                literal("true")
                                TextAnchor.TOP
                            }

                            stop {
                                literal("false")
                                TextAnchor.CENTER
                            }

                            stop {
                                literal("")
                                TextAnchor.CENTER
                            }

                            TextAnchor.CENTER
                        }
                    )
`

Unfortunately, it was always centering the text, when that should be the minority in this case. To double check it wasn't the conditional logic, I set every TextAnchor value to TextAnchor.TOP including the fallback, but upon running it was still centered. Simply using TextAnchor(TextAnchor.TOP) works as expected. Apologies if this is due to a misunderstanding on my part!

**Comment by kiryldz** [comment]
@LivPNavusoft thanks for so much details, however tbh I got quite lost. In general, the main issue I see is not even in the code you shared but in the screenshot: you should do `addBooleanProperty` instead of `addProperty` which accepts `JsonElement` and you're passing `true` there which is incorrect.
Please refer to https://github.com/mapbox/mapbox-maps-android/blob/lts/v10/app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/AddMarkersSymbolActivity.kt which seems to be doing exactly what you want with only differences that string property is used and expressions are applied to other style properties.
