### ISSUE TITLE
 Received status code 401 from server: Unauthorized

### ISSUE THREAD

**Issue by ArturMazay** [mapbox/mapbox-maps-android#2159]
Received status code 401 from server: Unauthorized
Could not GET 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/maps/android/10.15.0/android-10.15.0.pom'. Received status code 401 from server: Unauthorized
After updating android Studio to giraffe, an error appeared... I can't decide...help.. pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
        maven(url = "https://jitpack.io")
        maven {
            url = uri("https://api.mapbox.com/downloads/v2/releases/maven")
            authentication
            credentials {
                username ="mapbox"
                password = System.getenv("MAPBOX_DOWNLOADS_TOKEN")
            }
        }
    }
}

buildscript{
    repositories {
        mavenCentral()
        maven ( url = "https://developer.huawei.com/repo/")
    }
    dependencies {
        classpath("com.huawei.agconnect:agcp:1.5.2.300")
    }
}

dependencyResolutionManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
        maven(url = "https://jitpack.io")
        maven {
            url = uri("https://api.mapbox.com/downloads/v2/releases/maven")
            credentials {
                username ="mapbox"
                password = System.getenv("MAPBOX_DOWNLOADS_TOKEN")
            }
        }
    }
}

**Comment by pengdev** [comment]
Hi @ArturMazay you will need to create a secret token following the instructions in https://docs.mapbox.com/android/maps/guides/install/#configure-credentials. As you shared in the code snippets, MAPBOX_DOWNLOADS_TOKEN should be defined to access our API end points
