### ISSUE TITLE
Issue Regarding the Display of China's National Border Lines

### ISSUE THREAD

**Issue by OneupLee** [mapbox/mapbox-maps-android#2163]
I have encountered an issue with national border lines while using Mapbox. We are developers from China, and we truly appreciate the level of detail Mapbox offers. As a result, we have integrated Mapbox maps into certain services within our app. However, we are facing an issue when configuring the "Worldview" within "Administrative boundaries" to "CN."

The problem arises specifically with the border markings of China's Heilongjiang Province in the area of "Fuyuan" on "黑瞎子岛" (English translation: Bolshoy Ussuriysky Island). The current representation of China's national border in this area does not align with the actual situation. The actual border should be as shown in the red-marked area in the image below:
![image](https://github.com/mapbox/mapbox-maps-android/assets/32166473/8b91c5d9-3da6-48ff-bff8-2600e74b97d6)
![image](https://github.com/mapbox/mapbox-maps-android/assets/32166473/ab0ba207-9954-4682-adf4-3b9cc1d3d87f)
![image](https://github.com/mapbox/mapbox-maps-android/assets/32166473/2f44657c-44c4-4fcc-86e4-2bfebfd4971c)
![image](https://github.com/mapbox/mapbox-maps-android/assets/32166473/0ac7023c-3a30-40f6-8207-a1853ea75c11)
If this issue is not resolved, we, as an app providing services to Chinese users, will be unable to display the national border lines accurately. We would only be able to continue hiding them. On September 2nd, China also released a confirmation of the new map, clearly marking and explaining the border lines in this area.

Therefore, I kindly request that you investigate whether this issue can be resolved. We look forward to your response. Thank you.

**Comment by sbma44** [comment]
closing as duplicate https://github.com/mapbox/mapbox-maps-flutter/issues/226
