### ISSUE TITLE
`SDK_REGISTRY_TOKEN` variable is undocumented

### ISSUE THREAD

**Issue by xobs** [mapbox/mapbox-maps-android#2168]
## Environment

- Android OS version: N/A
- Devices affected: N/A
- Maps SDK Version: N/A

## Observed behavior and steps to reproduce

When building the project, the build system generates the following error:

```
Could not get unknown property 'SDK_REGISTRY_TOKEN' for root project 'Mapbox Maps Android' of type org.gradle.api.Project.
```

Presumably there are steps one should take to set the `SDK_REGISTRY_TOKEN` variable, however this repository does not mention them, however the documentation never says to configure this.

## Expected behavior

The build should download as requested.

## Notes / preliminary analysis

I suspect the variable in this repository is incorrect. The environment variable here is called `SDK_REGISTRY_TOKEN`, however the documentation at https://docs.mapbox.com/android/search/guides/get-started/ says to name the variable `MAPBOX_DOWNLOADS_TOKEN`.

## Additional links and references

* Documentation describing environment variable: https://docs.mapbox.com/android/search/guides/get-started/

**Comment by dudeuter** [comment]
@xobs `SDK_REGISTRY_TOKEN` is the name we use internally for the `MAPBOX_DOWNLOADS_TOKEN`, use a token with the scopes `DOWNLOADS:READ`.

**Comment by dudeuter** [comment]
@xobs The documentation for `SDK_REGISTRY_TOKEN` within this repo can be found [here](https://github.com/mapbox/mapbox-maps-android/blob/main/DEVELOPING.md#sdk-registry-token). Anyone who's looking to run or contribute to this project should read the `DEVELOPING.md` to understand how to properly set up the environment to run the example applications and unit tests.

The only reference I found to `MAPBOX_DOWNLOADS_TOKEN` is the snapshot instructions.

```sh
mapbox-maps-android % grep -Ri "MAPBOX_DOWNLOADS_TOKEN" .  
./DEVELOPING.md:          password = project.properties['MAPBOX_DOWNLOADS_TOKEN'] ?: ""
```

Although these instructions are meant to be shared with users [consuming snapshots](https://github.com/mapbox/mapbox-maps-android/blob/main/DEVELOPING.md#use-snapshot-releases-in-your-app) outside of `mapbox-maps-android`, having the name consistent with the documentation here is expected.

I do share in your frustration that there are two names for a more or less _functionality-identical_ value, one of my first PRs at Mapbox was to make this value consistent for code examples meant to be used by [customers](https://github.com/mapbox/mapbox-android-demo/pull/1401/files). It would be a non-trivial task to make these all one consistent value, and while not common, there are occasions where we would want these values to be different for development purposes internally. In your case, you should just alias this value in your environment variables or gradle properties (however you decide to handle secrets).

**Comment by xobs** [comment]
Thank you for taking the time to respond. I really appreciate it! I also appreciate the link. You've been very helpful.

**Comment by dudeuter** [comment]
> Thank you for taking the time to respond. I really appreciate it! I also appreciate the link. You've been very helpful.

No problem! 🙂
