### ISSUE TITLE
Task 'wrapper' not found in project ':app'.

### ISSUE THREAD

**Issue by xobs** [mapbox/mapbox-maps-android#2169]
## Environment

- Android OS version: 34
- Devices affected: IDE
- Maps SDK Version: 2

## Observed behavior and steps to reproduce

1. Check out the repository
2. Replace `SDK_REGISTRY_TOKEN` with `MAPBOX_DOWNLOADS_TOKEN` (see https://github.com/mapbox/mapbox-maps-android/issues/2168)
3. Build `app` project

The project should build, however it fails with the following error:

```
Task 'wrapper' not found in project ':app'.

* Try:
> Run gradle tasks to get a list of available tasks.
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

```

Clicking the various links causes it to rebuild, but does not change the contents of the error, aside from removing the relevant argument from the error message.

## Expected behavior

The project should build.

## Notes / preliminary analysis

It's not clear what a "task" is, so it's difficult to troubleshoot this. Additionally, running the various options does not produce additional debug information, making it difficult to troubleshoot.

**Comment by kiryldz** [comment]
Closing as stale and outdated. Please try with latest `main`.
