### ISSUE TITLE
Memory leak (and crash afterwards) in compose Mapbox

### ISSUE THREAD

**Issue by dryaz** [mapbox/mapbox-maps-android#2174]
## Environment

- Android OS version: latest test on emulator sdk 32
- Devices affected: tested on emulator, no live device at the moment
- Maps SDK Version: 11.0.0-beta.3

## Observed behavior and steps to reproduce

Compose Mapbox crashes when try to hide/show and navigate with compose navigation approach (add composable based on some flag).

Steps to reproduce:
- Dowload repository
- Switch to 11.0.0-beta.3
- Build compose-app
- Open multi display sample
<img width="420" alt="CleanShot 2023-09-13 at 01 11 37@2x" src="https://github.com/mapbox/mapbox-maps-android/assets/1395176/571cd4c2-a22d-4f00-86a9-aca0ec80ea85">

- Hide/Show map on default display multiple times
- Check profiler, native memory increased (leak canary won't be triggered)
<img width="899" alt="CleanShot 2023-09-13 at 01 11 47@2x" src="https://github.com/mapbox/mapbox-maps-android/assets/1395176/931eab47-dd2f-4f80-ba14-294d2e02d5d7">

- Crash after hide/show process

## Expected behavior

No memory leak, no crash

## Notes / preliminary analysis

<img width="1485" alt="CleanShot 2023-09-13 at 01 25 06@2x" src="https://github.com/mapbox/mapbox-maps-android/assets/1395176/d29dd030-c36c-46a1-b8ac-7b3eb82a7927">

Bitmaps are leaking. There were some issues in past when location provider causes memory leaks but it's not the case 'cause leaks happening also with disabled location.

## Additional links and references

Dump from profiler: 
[memory-20230913T011301.heapprofd.zip](https://github.com/mapbox/mapbox-maps-android/files/12591560/memory-20230913T011301.heapprofd.zip)

**Comment by dryaz** [comment]
Possibly the same as https://github.com/mapbox/mapbox-maps-android/issues/2079

**Comment by yunikkk** [comment]
@dryaz thanks, we will check.

**Comment by pengdev** [comment]
Looks like an incorrect lifecycle handling issue for compose extension, I've created an internal ticket and update when the fix is landed.

**Comment by jush** [comment]
This has been fixed in https://github.com/mapbox/mapbox-maps-android/releases/tag/v11.0.0-rc.2.
