### ISSUE TITLE
Play Services Location version 21.x causes crash

### ISSUE THREAD

**Issue by adepto-io** [mapbox/mapbox-maps-android#2188]
## Environment

- Android 13
- Pixel 4a & 6 pro:
- v11.0.0-beta.4:

## Expected behavior

Using [**play-services-location**](https://play.google.com/sdks/details/com-google-android-gms-play-services-location) version 21.0.0 and 21.0.1 crashes the application.Temporary fix is to downgrade to version 20.0.0.

## Notes / preliminary analysis

This is the probable instigator:

[FusedLocationProviderClient](https://developers.google.com/android/reference/com/google/android/gms/location/FusedLocationProviderClient), [ActivityRecognitionClient](https://developers.google.com/android/reference/com/google/android/gms/location/ActivityRecognitionClient), [GeofencingClient](https://developers.google.com/android/reference/com/google/android/gms/location/GeofencingClient) and [SettingsClient](https://developers.google.com/android/reference/com/google/android/gms/location/SettingsClient) are now interfaces instead of classes, which helps enforce correct usage and improves testability.

Google's [changelog](https://developers.google.com/android/guides/releases#october_13_2022)

## Additional links and references

```kotlin
java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location
 .ActivityRecognitionClient, but class was expected (declaration of 'com.google.android.gms.location.ActivityRecognitionClient' appears 
  in /data/app/~~qu8GR1qUqTaseFMBQ5MKKA==/app.demo.com--0dVinSj8bnSP5h3_-0A_g==/base.apk!classes18.dex)
  at com.mapbox.common.movement.GoogleActivityRecognition.start(GoogleActivityRecognition.kt:115)
  at com.mapbox.common.movement.AndroidMovementMonitor.registerObserver(AndroidMovementMonitor.kt:60)
```

**Comment by kiryldz** [comment]
Thanks for reporting, this will be fixed in v11.0.0-beta.5 coming out today.
