### ISSUE TITLE
Android 14 (api level 34) SecurityException - RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED flag not set

### ISSUE THREAD

**Issue by lukaspetry** [mapbox/mapbox-maps-android#2191]
## Environment

- Android OS version: Android 14
- Devices affected: all beginning with Android 14
- Maps SDK Version: all versions below and including 11.0.0-beta.5

## Observed behavior and steps to reproduce

Set targetSdk of an app using the mapbox-maps sdk to api level 34 and the app will crash on the first startup with the following exception:

    java.lang.SecurityException: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
      at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
      at android.os.Parcel.createException(Parcel.java:3041)
      at android.os.Parcel.readException(Parcel.java:3024)
      at android.os.Parcel.readException(Parcel.java:2966)
      at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5684)
      at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1852)
      at android.app.ContextImpl.registerReceiver(ContextImpl.java:1792)
      at android.app.ContextImpl.registerReceiver(ContextImpl.java:1780)
      at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
      at com.mapbox.common.movement.GoogleActivityRecognition.start(GoogleActivityRecognition.kt:110)
      at com.mapbox.common.movement.AndroidMovementMonitor.registerObserver(AndroidMovementMonitor.kt:60)
     Caused by: android.os.RemoteException: Remote stack trace:
      at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:13908)
      at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2570)
      at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2720)
      at android.os.Binder.execTransactInternal(Binder.java:1339)
      at android.os.Binder.execTransact(Binder.java:1275)

## Expected behavior

The app using the mapbox-maps sdk doesn't crash when the target sdk level is set to 34.

## Notes / preliminary analysis

The mapbox-maps sdk sets the required flag RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED in the registerReceiver methods or in the file AndroidManifest.xml according to the required changes announced by Google (https://developer.android.com/about/versions/14/behavior-changes-14#runtime-receivers-exported). In the optimal case the mapbox-maps sdk also targets Android 14 (api level 34).

## Additional links and references

- [Google Docs RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED flag requirement](https://developer.android.com/about/versions/14/behavior-changes-14#runtime-receivers-exported)

**Comment by yunikkk** [comment]
Thanks @lukaspetry for the report, we will update the ticket when it's solved.

**Comment by lukaspetry** [comment]
@yunikkk Do you have any news regarding this issue? We investigated the issue further on our side and found additional information. The exception only occurs when the permission physical activity (ACTIVITY_RECOGNITION) is granted, i.e., the mapbox sdk uses this permission for maybe tracking some movement (see class AndroidMovementMonitor in the exception stacktrace). 

Anyways, we do not want this behavior. This is not necessarry for us because we only want to show static map data. Can we disable this behavior?

We do not find any documentation regarding this.

**Comment by sjd753** [comment]
Identical issue detected causing crash on android 14 

   ```
    implementation 'com.mapbox.maps:android:10.14.1'
    implementation "com.mapbox.navigation:android:2.14.1"
    implementation "com.mapbox.navigation:ui-dropin:2.14.1"
   ```

**Comment by sjd753** [comment]
It has been fixed [here](https://github.com/mapbox/mapbox-navigation-android/releases/tag/v2.16.0-rc.1) 
libtrip-notification/src/main/java/com/mapbox/navigation/trip/notification/internal/MapboxTripNotification.kt

```
    implementation 'com.mapbox.maps:android:10.16.1'
    implementation "com.mapbox.navigation:android:2.17.1"
    implementation "com.mapbox.navigation:ui-dropin:2.17.1"
```

**Comment by lukaspetry** [comment]
@sjd753 I can't confirm if the same bug is fixed for the Mapbox Navigation sdk, but we still need a fix for the Mapbox Maps sdk. @yunikkk Do you have any news regarding this?

**Comment by kiryldz** [comment]
This is fixed in https://github.com/mapbox/mapbox-maps-android/releases/tag/v11.0.0-rc.1.

**Comment by noorulakbar** [comment]
while using below mapbox dependency for android 14 device support
 implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:9.7.1'

this issue occurs
 Duplicate class com.mapbox.android.telemetry.AlarmReceiver found in modules jetified-mapbox-android-telemetry-8.1.5-runtime (com.mapbox.mapboxsdk:mapbox-android-telemetry:8.1.5) and jetified-mapbox-android-telemetry-okhttp3-8.1.0-runtime (com.mapbox.mapboxsdk:mapbox-android-telemetry-okhttp3:8.1.0)
 
how to fix this?
or

if we used 
    implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:9.6.0'

then 
Error occurred while initializing telemetry
 java.lang.SecurityException: com.global.tryggdevelopment.dev: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
 
please give me update on above issue @kiryldz

**Comment by inigoLlamosasConneqtech** [comment]
Hello, @yunikkk is there any news regarding this? @lukaspetry @noorulakbar how did you fix it? We cannot afford for now to migrate from v9 to v11 (it's mayhem btw), neither we are using Mapbox Navigation sdk. Please could we give it a revamp for us legacy customers? Thanks!

**Comment by lukaspetry** [comment]
Hi @inigoLlamosasConneqtech, we fixed it by updating to the new mapbox-maps sdk version 11. I don't think, that there is a way in fixing this without upgrading the sdk.

**Comment by yunikkk** [comment]
> Hello, @yunikkk is there any news regarding this?

Hey @inigoLlamosasConneqtech , as shared above - Maps v11 resolves the problem. It also has numerous other improvements and new features - strongly recommend updating, you can reach to us if anything in particular is not clear in the docs.

**Comment by abdelhameedo** [comment]
> It has been fixed [here](https://github.com/mapbox/mapbox-navigation-android/releases/tag/v2.16.0-rc.1) libtrip-notification/src/main/java/com/mapbox/navigation/trip/notification/internal/MapboxTripNotification.kt
> 
> ```
>     implementation 'com.mapbox.maps:android:10.16.1'
>     implementation "com.mapbox.navigation:android:2.17.1"
>     implementation "com.mapbox.navigation:ui-dropin:2.17.1"
> ```

Confirmed, if you are using mapbox 10.x updating to 10.16.1 fixed the issue , it seems they added ProxyGoogleActivityRecognitionClient to support both new and older versions of location library.
