### ISSUE TITLE
Supporting "name" localization

### ISSUE THREAD

**Issue by shani200apps** [mapbox/mapbox-maps-android#2192]
## New Feature

The android extension "localizeLabels" currently accept only Locale and not String, which make it impossible to use the functionality of setting the label localization to "name" (use local language for displayed country). 

## Why
This is a useful and existing functionality that can be added easily (just support directly String, or add a specific extension for that usage)

Thank you

**Comment by pengdev** [comment]
Hey @shani200apps thanks for your question, I think this is a valid limitation of current API, could you say a bit more about your use case?

**Comment by kiryldz** [comment]
Closing as stale.
