### ISSUE TITLE
Zooming is jumpy near peaks when 3D terrain is enabled

### ISSUE THREAD

**Issue by msuonp** [mapbox/mapbox-maps-android#2204]
## Environment

- Android OS version: 13
- Devices affected: Samsung Galaxy S20
- Maps SDK Version: 10.16.1

## Observed behavior and steps to reproduce

Zooming is jumpy near peaks when 3D terrain is enabled and the map is tilted. Trying to zoom smoothly using a pinch gesture causes the zoom level to change jerkily. Sometimes the map zooms in when user tries to zoom out and the other way round. See the video below.

https://github.com/mapbox/mapbox-maps-android/assets/9264000/e10206f8-f8bd-44bb-b04d-bfcf8a6cec22

A test application is available at https://github.com/msuonp/mapbox-test for reproducing the issue. See https://github.com/msuonp/mapbox-test/blob/master/app/src/main/java/com/example/mapboxtest/testcase/jumpyzooming/JumpyZoomingActivity.kt for how the map is created and positioned.

## Expected behavior

Zooming works smoothly like in earlier versions of the SDK. See the video below for correct behavior.

https://github.com/mapbox/mapbox-maps-android/assets/9264000/32955e3f-4d7a-4df7-8a8a-1e99b35ee28b

## Notes / preliminary analysis

The issue is not present in SDK version 10.14.1, but all 10.x.y versions released after it are affected.

**Comment by jush** [comment]
We just released v11 RC1. I was not able to reproduce in v11 but it would be really good if you could also try it on your end.

**Comment by msuonp** [comment]
Hi @jush! Version 11.0.0-rc.1 seems to work fine. Unfortunately, I cannot make the major version upgrade to it in my app just yet.

**Comment by msuonp** [comment]
Works fine with version 11.1.0.
