### ISSUE TITLE
Loading a 3d model works only randomly

### ISSUE THREAD

**Issue by tukez** [mapbox/mapbox-maps-android#2215]
## Environment

- Android OS version: 10
- Devices affected: DJI RC Pro
- Maps SDK Version: 11.0.0-rc.1

## Observed behavior and steps to reproduce

I am using the following code to add a 3d model.

```kotlin
style.addModel(model(modelId = DRONE_MODEL_ID) {
    uri("asset://dji_mavic_2_pro.glb")
})
style.addSource(geoJsonSource(id = DRONE_MODEL_SOURCE_ID) {
    feature(Feature.fromGeometry(Point.fromLngLat(0.0, 0.0), null, DRONE_MODEL_FEATURE_ID)
                .also { it.addStringProperty(MODEL_KEY, DRONE_MODEL_ID) })
})
style.addLayer(modelLayer(layerId = DRONE_MODEL_LAYER_ID, sourceId = DRONE_MODEL_SOURCE_ID) {
    modelId(get(MODEL_KEY))
    modelType(ModelType.LOCATION_INDICATOR)
    modelTranslation(listOf(0.0, 0.0, 0.0))
    modelRotation(listOf(0.0, 0.0, 0.0))
    modelScale(listOf(1.0, 1.0, 1.0))
    modelAmbientOcclusionIntensity(1.0)
})
```

Most of the time the model loading fails with following message:
```
14:29:07.214  9577-9780  Mapbox                     E  [maps-core]: {Utility Worker }[General]: No support for indices over 65535, (actual 1544180869)
14:29:07.217  9577-9780  Mapbox                     E  [maps-core]: {MapboxRenderThr}[General]: Could not load model asset://dji_mavic_2_pro.glb: No support for indices over: 65535
```

Weird part is that sometimes the model loads and shows correctly. Note that the actual index in the log message is random, it changes every time.

## Expected behavior

Model loading succeeds consistently.

## Additional links and references

Link to the model: https://sketchfab.com/3d-models/dji-mavic-2-pro-3e5b8566dbe24f4ba65473179650abd1

**Comment by kiryldz** [comment]
@tukez thanks for reporting! We indeed identified an issue in our code and this will be fixed in upcoming release happening next week. Closing this one but feel free to re-open if the issue will persist.
