### ISSUE TITLE
How to clear old marker?

### ISSUE THREAD

**Issue by JonathanNiez** [mapbox/mapbox-maps-android#2218]
I want to make this limit to 1

Here's my code:

    private fun addDestinationAnnotationToMap(
        destinationLongitude: Double,
        destinationLatitude: Double,
        bookingID: String
    ) {
        bitmapFromDrawableRes(
            this@MapPassengerActivity,
            R.drawable.location_pin_128
        ).let {

            val annotationApi = binding.mapView.annotations
            val pointAnnotationManager = annotationApi.createPointAnnotationManager()
            val pointAnnotationOptions: PointAnnotationOptions = PointAnnotationOptions()
                .withPoint(Point.fromLngLat(destinationLongitude, destinationLatitude))
                .withIconImage(it)

            pointAnnotationManager.create(pointAnnotationOptions)

            pointAnnotationManager.apply {
                addClickListener(
                    OnPointAnnotationClickListener {

                        showOwnBookingInfoDialog(bookingID)

                        true
                    }
                )
            }
        }
    }

**Comment by jush** [comment]
Hi, from the description it is not clear what is the bug or issue.

If you have any questions about how to use the SDK or if you need help with specific features, you can reach out to our support team [via our website](https://docs.mapbox.com/help/) or connect with our developer community by joining our [Discord channel](https://discord.gg/UshjQYyDFw).
