### ISSUE TITLE
Location component: puck displayed in screen center when enabling plugin

### ISSUE THREAD

**Issue by kiryldz** [mapbox/mapbox-maps-android#222]
## Environment

- Android OS version: any
- Devices affected: any
- Maps SDK Version: 10.0.0-beta.16

## Observed behavior and steps to reproduce

If enabling location component plugin - puck will appear immediately in current map camera center and start sliding (with animation) to correct location a bit later. 

This behaviour seems like a bug to me and also leads to other strange scenarios:

 - enable location component for first time
 - wait until puck will slide to correct position
 - wait for a little time not moving device so that gps updates do not arrive
 - disable location component
 - move camera to some other position
 - enable location component
 - puck appears in center of current camera position and does not move to correct location (because no gps updates arrive if phone is not moving)

## Expected behavior

Display puck only when actual gps position has arrived. Enabling and disabling plugin should also cache last valid location and use it as initial one if no gps updates are happening

## Additional links and references

https://user-images.githubusercontent.com/15800566/112631301-c0004f00-8e47-11eb-9f18-4e5e57101308.mp4

cc @LukasPaczos for visibility

**Comment by Chaoba** [comment]
Fixed in https://github.com/mapbox/mapbox-maps-android/pull/333
