### ISSUE TITLE
Displaying a view on top of MapSurface

### ISSUE THREAD

**Issue by Ali-Farhoud** [mapbox/mapbox-maps-android#2223]
## New Feature

I want to be able to add a view (animated speedometer in my case) on top of the map surface. it will look like what Waze uses on their app (highlighted in the picture below)

<img width="903" alt="Screenshot 2023-11-26 at 9 57 45 AM" src="https://github.com/mapbox/mapbox-maps-android/assets/73000313/7ea7ac9a-88f3-44d8-bcad-424b01d0db57">

## Why
I am adding android auto support for my navigation app that uses the Mapbox Maps sdk. The android auto extension has been useful and it is very restrictive when it comes to adding customs

**Comment by baleboy** [comment]
Are you able to add the custom view on a regular activity, i.e. is the problem only with Android Auto? Could you share a code sample of how you add the custom view?

**Comment by kiryldz** [comment]
Closing as stale.
