### ISSUE TITLE
In the example of SimulateNavigationRouteActivity under the main branch, the line and puck do not match perfectly, and over time, the alignment between the line and puck decreases.

### ISSUE THREAD

**Issue by androidwzl** [mapbox/mapbox-maps-android#2224]
## Environment

- Android OS version:11
- Devices affected
- Maps SDK Version:11.0.0-rc.1

## Observed behavior and steps to reproduce
To comment out lines 65 to 70 in the SimulateNavigationRouteActivity, edit and run the code.

//      handler.postDelayed(
//        {
//          finish()
//        },
//        SIMULATION_DURATION
//      )

## Expected behavior
line and puck match exactly

**Comment by baleboy** [comment]
Thanks for the report. This is expected, since this is sample code not meant for production use, the calculations used to track the route are kept simple which results in reduced accuracy.

**Comment by androidwzl** [comment]
> Thanks for the report. This is expected, since this is sample code not meant for production use, the calculations used to track the route are kept simple which results in reduced accuracy.

What if I want to simulate high-precision navigation using map box?

**Comment by jush** [comment]
For a more meaningful navigation solution we recommend https://www.mapbox.com/navigation-sdk
