### ISSUE TITLE
Mapbox-extensions-compose::ViewAnnotation

### ISSUE THREAD

**Issue by StringMeUp** [mapbox/mapbox-maps-android#2227]
## Environment

- Android OS version: Android 13
- Devices affected: Emulator/Device 
- Maps SDK Version: mapbox = "11.0.0" / maps-compose = "0.1.0"

## Observed behavior and steps to reproduce

I am simply trying to add a ViewAnnotation. Code is identical to the code from the example app. 
<img width="700" alt="Screenshot 2023-11-30 at 20 39 18" src="https://github.com/mapbox/mapbox-maps-android/assets/54727390/4fa7cd51-03cf-4b6b-a604-a9767969e43e">

## Expected behavior

It should show a "Viewannotation" i.e. button or whatever the "callout" component is. 
However, I receive the following crash. 
<img width="1339" alt="Screenshot 2023-11-30 at 20 43 27" src="https://github.com/mapbox/mapbox-maps-android/assets/54727390/dfcd5b8d-4ac0-40c5-8559-35ab34cd2112">

## Notes / preliminary analysis
While comparing the code from ViewAnnotation.kt (dependancy vs sample app) I spotted a difference. 
a)
<img width="1432" alt="Screenshot 2023-11-30 at 20 45 52" src="https://github.com/mapbox/mapbox-maps-android/assets/54727390/7c3fe928-90ec-410d-bda6-ec28f5976bdc">

b) 
<img width="1435" alt="Screenshot 2023-11-30 at 20 46 13" src="https://github.com/mapbox/mapbox-maps-android/assets/54727390/ddf0ea67-93f9-4e82-b36b-df6f1b694b13">

Not sure if it has to do anything with the comment:  // need set a tag to avoid crashing, more details in [ViewAnnotationManagerImpl.measureView]

## Additional links and references
Would appreciate some guidance.

**Comment by kiryldz** [comment]
@StringMeUp Compose is following the same versioning as the main SDK since [v11.0.0-rc.1](https://github.com/mapbox/mapbox-maps-android/blob/1d21e9740f14bf7738f589f89bf8d5218dac577d/CHANGELOG.md?plain=1#L103), please use Compose version 11.0.0 and this should be fixed there.
Please re-open if the issue will persist.

**Comment by StringMeUp** [comment]
Thank you.
