### ISSUE TITLE
Function Map::queryRenderedFeatures called from a thread that is not owning the object

### ISSUE THREAD

**Issue by msuonp** [mapbox/mapbox-maps-android#2232]
## Environment

- Android OS version: 13
- Devices affected: Samsung Galaxy S20
- Maps SDK Version: 11.0.0

## Observed behavior and steps to reproduce

The following error message always appears in the logs when the map is touched, provided an annotation manager instance has been created:
```[bindgen]: Function Map::queryRenderedFeatures called from a thread that is not owning the object```

The error message appears once for every annotation manager instance created. If no annotation managers are created, there won't be any error messages. It's not necessary to add annotations to see the errors. Simply creating a manager instance will suffice, as shown here:
```mapView.annotations.createPointAnnotationManager()```

## Expected behavior

No error messages in the logs

**Comment by kiryldz** [comment]
@msuonp thanks for flagging! Please disregard this warning, we will remove it in upcoming release.

**Comment by shahzaib-ch** [comment]
We are still getting this issue:
[bindgen]: Function StyleManager::getStyleImage called from a thread that is not owning the object
