### ISSUE TITLE
fill-outline-width

### ISSUE THREAD

**Issue by wingkingbobo** [mapbox/mapbox-maps-android#2237]
## New Feature
I would like to set the border width for Polygon. Currently, only `fill-outline-color` has been found, and `fill-outline-width` has not been found. The drawn edge width is only 1px. How can I modify the width.

**Comment by wingkingbobo** [comment]
I am currently using line layer to implement the edges of the face, but this will cause the edges to separate from the face when multiple faces intersect.

**Comment by kiryldz** [comment]
@wingkingbobo that property (or equivalent) is missing in the [style-spec](https://github.com/mapbox/mapbox-gl-js/blob/main/src/style-spec/reference/v8.json) which is considered to be the source-of-truth for all Mapbox SDKs. I'd suggest you check the GL-JS repo and raise this question there as the first step.
