### ISSUE TITLE
CoordinatesList 

### ISSUE THREAD

**Issue by Zee-93** [mapbox/mapbox-maps-android#2238]
## Java Android

- 12
- Google Pixel, Infinix
  implementation 'com.mapbox.maps:android:10.16.2'
    implementation 'com.mapbox.navigation:android:2.17.1'

## It should accept unlimited number of coordinates

But it give me error.

**Comment by jush** [comment]
Could you please provide more details?
What APIs are you using? what error is being reported?
It would tremendously speed up the resolution of your issue if you could also provide a minimal reproducible example.

**Comment by kiryldz** [comment]
Closing as non-actionable.
