### ISSUE TITLE
How to know the layerId when using cluster ?

### ISSUE THREAD

**Issue by tristan-garaud** [mapbox/mapbox-maps-android#2244]
## Environment

- Android OS version: 13
- Devices affected:
- Maps SDK Version: 10.10.0

## Observed behavior and steps to reproduce

I put this as a bug as I don't know if it's possible to get the layerid when creating a cluster. When clicking on a feature using queryRenderedFeatures. I'm supposed to pass a layerId in a list but how to get this layerId as at is autogenerated.
Thanks

**Comment by tristan-garaud** [comment]
I did this waiting for better solution:
`val clusterId = "mapbox-android-pointAnnotation-layer-${PointAnnotationManager.ID_GENERATOR}"`
But now Im strugling to passe data to the feature and retreive it in queryRenderedFeatures.

**Comment by tristan-garaud** [comment]
Ok, I managed to pass the data. Not cristal clear from the doc how to achived that.

**Comment by baleboy** [comment]
Thanks, which part of the documentation did you use and what did you feel was missing?
