### ISSUE TITLE
Set layer property "raster-opacity" failed:  Layer "custom_id" is not in style

### ISSUE THREAD

**Issue by Ashok-Media** [mapbox/mapbox-maps-android#2246]
## Environment

- Android OS version: All versions
- Devices affected: samsung s20
- Maps SDK Version: 10.5.0

## Observed behavior and steps to reproduce

sometimes I am getting crash at (below line)
`currentLayer.rasterOpacity(layerOpacity)`

the error message is: 
com.mapbox.maps.MapboxStyleException: Set layer property "raster-opacity" failed:
Layer "layer_id" is not in style

## Expected behavior

It should not crash

**Comment by baleboy** [comment]
Thanks for the report. Could you share a project that demonstrates the issue, or if it can't be reproduced consistently can you share the code you use to create/load and access the style?

**Comment by kiryldz** [comment]
Closing as stale.
