### ISSUE TITLE
How to turn on/off 3D building in Style.STANDARD on runtime?

### ISSUE THREAD

**Issue by mrpham** [mapbox/mapbox-maps-android#2247]
I want to know, how to turn on/off 3D building in Style.STANDARD on runtime? 
Please help me, many thanks

**Comment by melanieimfeld** [comment]
Hi @mrpham - to add to the above, we are investigating the ability to turn off buildings. I'm curious to know what your use case is for turning off buildings is: is it because you would refer the map to be in 2D? Or are you bringing in custom 3D data?

**Comment by lionpham-gis** [comment]
Hello @melanieimfeld, 
The 3D buildings obscure the satellite image background, I want the app user to be able to decide whether to enable or disable the buildings layer. 

Thanks,

**Comment by mrpham** [comment]
Hello @melanieimfeld ,

The 3D buildings obscure the satellite image background, I want the app user to be able to decide whether to enable or disable the buildings layer.

Thanks,

**Comment by jensstalder** [comment]
I also have maps with additional polygon layers. The buildings obscure these polygons now (even if in 2d mode). Maybe it would be more flexible if one could define the transparency for the 3d buildings? Or maybe there is a way to place the polygons above the building layer, so that when they are in 2d they are on top? (Same thing could be said for satellite imagery. In Satellite it might often be more helpful for the buildings to be outlines instead of being opaque, obscuring the imagery?

**Comment by guilhermeluciojardim** [comment]
Was there any workaround on this? it would be nice to have a way to disable the 3d buildings in runtime. I use threebox to put specific 3ds buildings on the map but the default buildings are on the way. just wish for a way to disable and enable the 3d buildings on the standard style at least.

**Comment by dje073** [comment]
Hi, 
I would like to have the same option here as I manage the buildings in 3d with my own datas.
Thanks

**Comment by Uelfol** [comment]
@guilhermeluciojardim The workaround that i found is to create another style, based on "streets" template and then change the option on Buildings -> Component properties -> Building Style -> 3d or 2d

**Comment by flasher297** [comment]
New v11.6.0-beta.1 release of SDK exposes a new experimental `ClipLayer` to remove 3D data (fill extrusions, landmarks, instanced trees) and symbols.
https://github.com/mapbox/mapbox-maps-android/releases/tag/v11.6.0-beta.1
You could check the example and try it:
https://github.com/mapbox/mapbox-maps-android/blob/main/app/src/main/java/com/mapbox/maps/testapp/examples/ClipLayerActivity.kt

**Comment by kiryldz** [comment]
The proper Standard style configuration `show3dObjects` config has been rollout. You could read more about it [here](https://docs.mapbox.com/android/maps/guides/styles/set-a-style/#mapbox-standard-1). Please note that typed API for Jetpack Compose for this property is available only from https://github.com/mapbox/mapbox-maps-android/releases/tag/v11.6.0-rc.1.

Closing this ticket, feel free to open a new one if functionality is not working as expected.
