### ISSUE TITLE
ResourceOptionsManager is not accessible in 11.0.0 maps andorid

### ISSUE THREAD

**Issue by Ashok-Media** [mapbox/mapbox-maps-android#2248]
## Environment

- Android OS version: 13
- Devices affected: Samsung S 20
- Maps SDK Version: 11.0.0

## Observed behavior and steps to reproduce

when I try to migrate from v10 to v11 
I used below code for update token at runtime

`ResourceOptionsManager.getDefault(context,maxBoxToken)`

but after 11 it seems like "ResourceOptionsManager" this class is not available
what is the replacement for above code in v11?

**Comment by jush** [comment]
Please find migration guidelines for those replacements in https://docs.mapbox.com/android/maps/guides/migrate-to-v11/#32-resourceoptions-and-resourceoptionsmanager-have-been-removed
