### ISSUE TITLE
Unable to set bitmap image from imageId

### ISSUE THREAD

**Issue by ameerprpt** [mapbox/mapbox-maps-android#2252]
## Environment

- Android OS version: 13/14
- Devices affected: All
- Maps SDK Version: 11.0.0

## Observed behavior and steps to reproduce

How can we convert the Image data into bitmap.
I tried below code
```
   val bitmap = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888)
            bitmap.copyPixelsFromBuffer(mapView?.mapboxMap?.getStyleImage(imageIcon)?.data?.buffer)
            vImageMarker.setImageBitmap(bitmap)
```
however app is crashing with following exception

```
Process: com.magnolia.android.app, PID: 23732
java.lang.RuntimeException: Buffer not large enough for pixels
at android.graphics.Bitmap.copyPixelsFromBuffer(Bitmap.java:655)
```

## Expected behavior

In 10.6 version, I was able to set using   
```
fun Image.bitmap(): Bitmap {
        val configBmp: Bitmap.Config = Bitmap.Config.ARGB_8888
        val bitmap: Bitmap = Bitmap.createBitmap(this.width, this.height, configBmp)
        val buffer: ByteBuffer = ByteBuffer.wrap(this.data)
        bitmap.copyPixelsFromBuffer(buffer)
        return bitmap
    }
```

**Comment by kiryldz** [comment]
@ameerprpt I tried locally code similar to the one you pasted and I don't see the exception. Most likely `width` / `height` you specified are not correct and they [exceed](https://android.googlesource.com/platform/frameworks/base.git/+/7f9f99ea11051614a7727dfb9f9578b518e76e3c/graphics/java/android/graphics/Bitmap.java#346) the buffer size.

**Comment by ameerprpt** [comment]
It was width and height issue and now the image is loading
