### ISSUE TITLE
random crash

### ISSUE THREAD

**Issue by areenjaradat96** [mapbox/mapbox-maps-android#2260]
## Environment

- Android OS version: 12
- Devices affected: Samsung Note 10
- Maps SDK Version: 11.0.0

## Observed behavior and steps to reproduce

random crash

`  runtime.cc:669]   at android.os.Handler.postDelayed(Handler.java:530)
                                                                                                    runtime.cc:669]   at androidx.core.os.HandlerCompat$Api28Impl.postDelayed(HandlerCompat.java:276)
                                                                                                    runtime.cc:669]   at androidx.core.os.HandlerCompat.postDelayed(HandlerCompat.java:183)
                                                                                                    runtime.cc:669]   at com.mapbox.maps.renderer.FpsManager.postRender(FpsManager.kt:228)
                                                                                                    runtime.cc:669]   at com.mapbox.maps.renderer.MapboxRenderThread.draw(MapboxRenderThread.kt:334)
                                                                                                    runtime.cc:669]   at com.mapbox.maps.renderer.MapboxRenderThread.doFrame(MapboxRenderThread.kt:557)
                                                                                                    runtime.cc:669]   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1106)
                                                                                                    runtime.cc:669]   at android.view.Choreographer.doCallbacks(Choreographer.java:866)
                                                                                                    runtime.cc:669]   at android.view.Choreographer.doFrame(Choreographer.java:792)
                                                                                                    runtime.cc:669]   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
                                                                                                    runtime.cc:669]   at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    runtime.cc:669]   at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    runtime.cc:669]   at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    runtime.cc:669]   at android.os.Looper.loop(Looper.java:313)
                                                                                                    runtime.cc:669]   at android.os.HandlerThread.run(HandlerThread.java:67)
                                                                                                    runtime.cc:669] 
                                                                                                    runtime.cc:669] "main" prio=10 tid=1 Native
                                                                                                    runtime.cc:669]   | group="" sCount=1 ucsCount=0 flags=1 obj=0x732e1828 self=0x775bc1dbe0
                                                                                                    runtime.cc:669]   | sysTid=31894 nice=-10 cgrp=default sched=0/0 handle=0x78f4180500
                                                                                                    runtime.cc:669]   | state=S schedstat=( 13816026753 1151143630 11047 ) utm=1254 stm=127 core=4 HZ=100
                                                                                                    runtime.cc:669]   | stack=0x7fcb00e000-0x7fcb010000 stackSize=8188KB
                                                                                                    runtime.cc:669]   | held mutexes=
                                                                                                    runtime.cc:669]   native: #00 pc 000000000004d81c  /apex/com.android.runtime/lib64/bionic/libc.so (syscall+28)`

**Comment by kiryldz** [comment]
@areenjaradat96 please provide the full error stacktrace, thanks!

**Comment by areenjaradat96** [comment]
@kiryldz 
Apologies for the delay in responding. After investigating the issue, I realized it wasn't related to the report I submitted. It stemmed from adding a style before the onMapReady trigger in my code.

**Comment by kiryldz** [comment]
Closing as non-actionable.
