### ISSUE TITLE
[v11] [compose] Configuring the network stack when using v11

### ISSUE THREAD

**Issue by GioraGit** [mapbox/mapbox-maps-android#2262]
Mapbox sdk used: v11.1.0 + Mapbox Compose extension

Among the breaking changes that were introduced in mapbox sdk v11, there were [these ones](https://docs.mapbox.com/android/maps/guides/migrate-to-v11/#315-changes-in-the-network-stack), that stated: "**This means that you are not allowed to overwrite the Mapbox network stack anymore.**"

In our app we try to prefetch few dozen weather tiles (dozens of raster sources and matching raster layers) in order to animate their transition over time once they are all downloaded. However, with the default `HttpServiceInterface` it takes about a minute (sometimes more) of waiting to complete the entire download. In our corresponding iOS app, using mapbox iOS sdk v11, the same process with the same amount of tiles takes about ~15 seconds.

When using the prohibited functions on Android: 
`HttpServiceFactory.getInstance().setMaxRequestsPerHost(Byte.MAX_VALUE)`
(public function annotated with `@RestrictTo(value = Scope.LIBRARY_GROUP_PREFIX)`)
it **significantly** decreases the time to download the entire tiles, such that it takes about 15 seconds, similar to the default iOS sdk implementation.

Would love to hear from you how we can work around the new limitation regarding modifying the network stack in order to achieve this kind of scenario (and because we're curious - why this limitation was inserted, compared for example to the previous version of the sdk).

**Comment by tatiana-yan** [comment]
Hello @GioraGit .
We use okhttp under the hood in our HttpService implementation for Android and use the default value for `MaxRequestsPerHost` from okhttp implementation. The optimal value for `MaxRequestsPerHost` may depend on file sizes, server-side file distribution speed, connection quality, etc., and in your case, defaults are definitely not optimal. If the public static method `HttpServiceFactory::setMaxRequestsPerHost` works for you, we can add it in the 11.2 release.

**Comment by GioraGit** [comment]
Hi @tatiana-yan ,
Thank you for your quick reply.

Yes, `setMaxRequestsPerHost()` works great for us, and it would be very helpful if you add it in the next release.

**Comment by tatiana-yan** [comment]
added, internal issue id is CORESDK-2296, PR is https://github.com/mapbox/mapbox-sdk-common/pull/4113
