### ISSUE TITLE
Release build failure due to missing proguard rule

### ISSUE THREAD

**Issue by akirmse** [mapbox/mapbox-maps-android#2265]
## Environment

- Android OS version: N/A
- Devices affected: N/A
- Maps SDK Version: 11.1.0

## Observed behavior and steps to reproduce

When building in release mode, I get the following error on the Proguard step:

:peakbagger:minifyReleaseWithR8
Missing classes detected while running R8. Please add the missing classes or apply additional keep rules that are generated in /Users/akirmse/peakbagger/android/peakbagger/build/outputs/mapping/release/missing_rules.txt.
Missing class com.tobrun.datacompat.annotation.Default (referenced from: void com.mapbox.maps.plugin.attribution.generated.AttributionSettingsData.<init>(boolean, int, int, float, float, float, float, boolean) and 11 other contexts)

Adding the following to proguard.txt allows the build to complete:

-dontwarn com.tobrun.datacompat.annotation.Default

Perhaps this can be added to Mapbox's proguard file, so that every project doesn't need to do it.  This error did not occur on Mapbox v10.16.3.

**Comment by jush** [comment]
Thanks, this will be fixed in the next release.
The issue was fixed in the data compat library: https://github.com/tobrun/kotlin-data-compat/pull/40

**Comment by raajnadar** [comment]
In which version this fix will be applied?

**Comment by kiryldz** [comment]
> In which version this fix will be applied?

This was fixed in https://github.com/mapbox/mapbox-maps-android/releases/tag/v11.2.0-beta.1

**Comment by raajnadar** [comment]
Ah, we need to wait for the 11.2.0 stable release

**Comment by akirmse** [comment]
I can confirm that this is fixed in 11.2.0.  Thanks!
