### ISSUE TITLE
Cannot load models with 'file' URL scheme

### ISSUE THREAD

**Issue by fawzirifai** [mapbox/mapbox-maps-android#2266]
## Environment

- Android OS version: 14.0
- Devices affected: All
- Maps SDK Version: 11.0.0

## Observed behavior and steps to reproduce

I am trying to download model files from a server, cache them, and then load them onto a map using their cached file URLs. However, I am encountering an issue with the Mapbox SDK. The specific error message I receive is: 'Could not load model file:/data/user/0/com.penguinin.demopennavui/cache/model7837898436723026176.glb: Expected URL scheme 'http' or 'https' but was 'file'.

## Expected behavior

We should be able to load model files using a 'file' URL scheme, similar to the functionality available on iOS.
<img width="2032" alt="Screenshot 2024-01-23 at 10 14 59 PM" src="https://github.com/mapbox/mapbox-maps-android/assets/109214745/f54cbfc2-285c-47d8-9b0f-3f802c020f36">

**Comment by kiryldz** [comment]
@fawzirifai thanks for reaching out. Working with local files in Android SDK is done through [assets](https://developer.android.com/guide/topics/resources/providing-resources#OriginalFiles). Please refer to an example we have where we showcase loading the `glb` both from web and [from local assets](https://github.com/mapbox/mapbox-maps-android/blob/844b95570ef2f486ac0ec5798df2a48c71bed8f7/app/src/main/java/com/mapbox/maps/testapp/examples/terrain3D/ModelLayerActivity.kt#L82).
