### ISSUE TITLE
Log is spammed by Mbgl-RenderThread

### ISSUE THREAD

**Issue by adepto-io** [mapbox/mapbox-maps-android#2275]
## Environment

- Android OS version: 14
- Devices affected: Google Pixel 6a
- Maps SDK Version: 11.1.0 (compose extension)

## Observed behavior and steps to reproduce

The following log entry is infinitely repeated every ~20ms when navigating away from a screen with a map. It never stops logging, even when navigating back to the screen that displays the map.

_**[maps-android\Mbgl-RenderThread]: renderThreadPrepared=false and Android surface is not valid (isValid=false). Waiting for new one.**_

### Map creation

08:59:25.904 Mbgl-FontUtils                       I  Couldn't map font family for local ideograph, using sans-serif instead
08:59:25.915 Mapbox                               I  [maps-android\ThreadChecker]: Unable to lookup build config of application. app.example.com.BuildConfig
08:59:25.948 CompatibilityChangeReporter          D  Compat change id reported: 193247900; UID 10274; state: ENABLED
08:59:25.949 Mapbox                               I  [maps-android\Mbgl-RenderThread]: Renderer resumed, renderThreadPrepared=false, surface.isValid=null
08:59:25.949                                      I  [maps-android\Mbgl-RenderThread]: renderThreadPrepared=false and Android surface is not valid (isValid=null). Waiting for new one.
08:59:25.957                                      I  [maps-android\Mbgl-RenderThread]: renderThreadPrepared=false and Android surface is not valid (isValid=null). Waiting for new one.
08:59:25.959                                      I  [maps-android\Mbgl-RenderThread]: onSurfaceCreated
08:59:25.959                                      I  [maps-android\Mbgl-RenderThread]: onSurfaceCreated: waiting Android surface to be processed...
08:59:25.961                                      I  [maps-android\Mbgl-RenderThread]: Setting up render thread, flags: creatingSurface=true, nativeRenderCreated=false, eglContextMadeCurrent=false, eglContextCreated=false, paused=false
08:59:25.962 libEGL                               D  loaded /vendor/lib64/egl/libGLES_mali.so
08:59:26.017 Mapbox                               I  [maps-android\Mbgl-EGLConfigChooser]: In emulator: false
08:59:26.025                                      I  [maps-android\Mbgl-EglCore]: EGLContext created, client version 3
08:59:26.027                                      I  [maps-core]: Using OpenGL render backend
08:59:26.029                                      I  [maps-android\Mbgl-RenderThread]: Native renderer created.
08:59:26.029                                      I  [maps-android\Mbgl-RenderThread]: onSurfaceCreated: Android surface was processed.
08:59:30.912 Mapbox                               I  [tile_store]: Searching for stale partial downloads to clean up
08:59:30.913                                      I  [tile_store]: Cleanup of stray partial downloads complete

### Map destruction

09:03:02.952 Mapbox                               I  [maps-android\Mbgl-RenderThread]: Skip render frame - NOT creating surface although renderNotSupported (false) || paused (true)
09:03:02.970                                      I  [maps-android\Mbgl-RenderThread]: Skip render frame - NOT creating surface although renderNotSupported (false) || paused (true)
09:03:02.986                                      I  [maps-android\Mbgl-RenderThread]: Skip render frame - NOT creating surface although renderNotSupported (false) || paused (true)
09:03:03.004                                      I  [maps-android\Mbgl-RenderThread]: Skip render frame - NOT creating surface although renderNotSupported (false) || paused (true)
09:03:03.024                                      I  [maps-android\Mbgl-RenderThread]: Skip render frame - NOT creating surface although renderNotSupported (false) || paused (true)
09:03:03.039                                      I  [maps-android\Mbgl-RenderThread]: Skip render frame - NOT creating surface although renderNotSupported (false) || paused (true)
09:03:03.054                                      I  [maps-android\Mbgl-RenderThread]: Skip render frame - NOT creating surface although renderNotSupported (false) || paused (true)
09:03:03.068                                      I  [maps-android\Mbgl-RenderThread]: Skip render frame - NOT creating surface although renderNotSupported (false) || paused (true)
09:03:03.086                                      I  [maps-android\Mbgl-RenderThread]: Skip render frame - NOT creating surface although renderNotSupported (false) || paused (true)
09:03:03.104                                      I  [maps-android\Mbgl-RenderThread]: Skip render frame - NOT creating surface although renderNotSupported (false) || paused (true)
09:03:03.120                                      I  [maps-android\Mbgl-RenderThread]: Skip render frame - NOT creating surface although renderNotSupported (false) || paused (true)
09:03:03.138                                      I  [maps-android\Mbgl-RenderThread]: Skip render frame - NOT creating surface although renderNotSupported (false) || paused (true)
09:03:03.154                                      I  [maps-android\Mbgl-RenderThread]: Skip render frame - NOT creating surface although renderNotSupported (false) || paused (true)
09:03:03.172                                      I  [maps-android\Mbgl-RenderThread]: Skip render frame - NOT creating surface although renderNotSupported (false) || paused (true)
09:03:03.191                                      I  [maps-android\Mbgl-RenderThread]: Skip render frame - NOT creating surface although renderNotSupported (false) || paused (true)
09:03:03.206                                      I  [maps-android\Mbgl-RenderThread]: Skip render frame - NOT creating surface although renderNotSupported (false) || paused (true)
09:03:03.222                                      I  [maps-android\Mbgl-RenderThread]: Skip render frame - NOT creating surface although renderNotSupported (false) || paused (true)
09:03:03.239                                      I  [maps-android\Mbgl-RenderThread]: Skip render frame - NOT creating surface although renderNotSupported (false) || paused (true)
09:03:03.254                                      I  [maps-android\Mbgl-RenderThread]: Skip render frame - NOT creating surface although renderNotSupported (false) || paused (true)
09:03:03.272                                      I  [maps-android\Mbgl-RenderThread]: Skip render frame - NOT creating surface although renderNotSupported (false) || paused (true)
09:03:03.287                                      I  [maps-android\Mbgl-RenderThread]: Skip render frame - NOT creating surface although renderNotSupported (false) || paused (true)
09:03:03.302                                      I  [maps-android\Mbgl-RenderThread]: Skip render frame - NOT creating surface although renderNotSupported (false) || paused (true)
09:03:03.321                                      I  [maps-android\Mbgl-RenderThread]: Skip render frame - NOT creating surface although renderNotSupported (false) || paused (true)
09:03:03.337                                      I  [maps-android\Mbgl-RenderThread]: Skip render frame - NOT creating surface although renderNotSupported (false) || paused (true)
09:03:03.354                                      I  [maps-android\Mbgl-RenderThread]: Skip render frame - NOT creating surface although renderNotSupported (false) || paused (true)
09:03:03.371                                      I  [maps-android\Mbgl-RenderThread]: Skip render frame - NOT creating surface although renderNotSupported (false) || paused (true)
09:03:03.390                                      I  [maps-android\Mbgl-RenderThread]: Skip render frame - NOT creating surface although renderNotSupported (false) || paused (true)
09:03:03.404                                      I  [maps-android\Mbgl-RenderThread]: Skip render frame - NOT creating surface although renderNotSupported (false) || paused (true)
09:03:03.420                                      I  [maps-android\Mbgl-RenderThread]: Skip render frame - NOT creating surface although renderNotSupported (false) || paused (true)
09:03:03.465                                      I  [maps-android\Mbgl-RenderThread]: onSurfaceDestroyed
09:03:03.465                                      I  [maps-android\Mbgl-RenderThread]: onSurfaceDestroyed: waiting until EGL will be cleaned up...
09:03:03.467                                      I  [maps-android\Mbgl-EglCore]: EGL surface was destroyed.
09:03:03.467                                      I  [maps-android\Mbgl-RenderThread]: onSurfaceDestroyed: EGL resources were cleaned up.
09:03:03.486                                      I  [maps-android\Mbgl-RenderThread]: destroy
09:03:03.486                                      I  [maps-android\Mbgl-RenderThread]: destroy: waiting until all resources will be cleaned up...
09:03:03.499                                      I  [maps-android\Mbgl-RenderThread]: Native renderer destroyed.
09:03:03.499                                      I  [maps-android\Mbgl-EglCore]: EGL surface was already destroyed before.
09:03:03.504                                      I  [maps-android\Mbgl-RenderThread]: destroy: all resources were cleaned up.
09:03:03.517                                      I  [maps-android\Mbgl-RenderThread]: renderThreadPrepared=false and Android surface is not valid (isValid=false). Waiting for new one.
09:03:03.749 Mapbox                               I  [maps-android\Mbgl-RenderThread]: renderThreadPrepared=false and Android surface is not valid (isValid=false). Waiting for new one.
09:03:03.763                                      I  [maps-android\Mbgl-RenderThread]: renderThreadPrepared=false and Android surface is not valid (isValid=false). Waiting for new one.
09:03:03.780                                      I  [maps-android\Mbgl-RenderThread]: renderThreadPrepared=false and Android surface is not valid (isValid=false). Waiting for new one.
09:03:03.797                                      I  [maps-android\Mbgl-RenderThread]: renderThreadPrepared=false and Android surface is not valid (isValid=false). Waiting for new one.
09:03:03.815                                      I  [maps-android\Mbgl-RenderThread]: renderThreadPrepared=false and Android surface is not valid (isValid=false). Waiting for new one.
09:03:03.834                                      I  [maps-android\Mbgl-RenderThread]: renderThreadPrepared=false and Android surface is not valid (isValid=false). Waiting for new one.
09:03:03.848                                      I  [maps-android\Mbgl-RenderThread]: renderThreadPrepared=false and Android surface is not valid (isValid=false). Waiting for new one.
09:03:03.864                                      I  [maps-android\Mbgl-RenderThread]: renderThreadPrepared=false and Android surface is not valid (isValid=false). Waiting for new one.

## Expected behavior

Shouldn't this Mbgl-RenderThread be closed at this point? If that's not the case, is there a way to silence this info log entry?

**Comment by kiryldz** [comment]
@adepto-io out of curiosity (and to help the others facing somewhat similar) - may you specify how did you resolve the issue?
