### ISSUE TITLE
cameraForCoordinates, cameraForGeometry and cameraForCoordinateBounds do not work correctly (incorrect zoom) after loading the style and in doOnNextLayout when the view is already measured and inflated to have correct width and height values

### ISSUE THREAD

**Issue by Copatych** [mapbox/mapbox-maps-android#2282]
## Environment

- Android OS version: 11
- Devices affected: Samsung Galaxy A50
- Maps SDK Version: 11.1.0     

Also tested on emulator with api 33

## Observed behavior and steps to reproduce

cameraForCoordinates, cameraForGeometry and cameraForCoordinateBounds do not work correctly ((incorrect zoom) after loading the style and in doOnNextLayout when the view is already measured and inflated to have correct width and height values.

The documentation for cameraForGeometry and cameraForCoordinateBounds states that "_In order for this method to produce correct results MapView must be already measured and inflated to have correct width and height values. Calling this method in Activity.onCreate will lead to incorrect results_". That is why the methods for getting CameraOptions are called in doOnNextLayout when the dimensions of the view are precisely known. But this does not help, the zoom of the resulting CameraOptions differs from what would have been obtained if these methods had been called in response to user actions when the map had been drawn a long time ago.

If I don't upload a new style, but work with the default one (I get the style via mapboxMap.getStyle), then everything works correctly.

The code for reproducing the problem:

```
class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        val mapView = MapView(this)
        setContentView(mapView)

        val points = listOf(
            Point.fromLngLat(-122.483696, 37.833818),
            Point.fromLngLat(-122.483482, 37.833174),
            Point.fromLngLat(-122.483396, 37.8327),
            Point.fromLngLat(-122.483568, 37.832056),
            Point.fromLngLat(-122.48404, 37.831141),
            Point.fromLngLat(-122.48404, 37.830497),
            Point.fromLngLat(-122.483482, 37.82992),
            Point.fromLngLat(-122.483568, 37.829548),
            Point.fromLngLat(-122.48507, 37.829446),
            Point.fromLngLat(-122.4861, 37.828802),
            Point.fromLngLat(-122.486958, 37.82931),
            Point.fromLngLat(-122.487001, 37.830802),
            Point.fromLngLat(-122.487516, 37.831683),
            Point.fromLngLat(-122.488031, 37.832158),
            Point.fromLngLat(-122.488889, 37.832971),
            Point.fromLngLat(-122.489876, 37.832632),
            Point.fromLngLat(-122.490434, 37.832937),
            Point.fromLngLat(-122.49125, 37.832429),
            Point.fromLngLat(-122.491636, 37.832564),
            Point.fromLngLat(-122.492237, 37.833378),
            Point.fromLngLat(-122.493782, 37.833683)
        )

//        mapView.mapboxMap.getStyle { style ->
        mapView.mapboxMap.loadStyle(Style.LIGHT) { style ->
            val pointsSource = "pointsSource"
            style.addSource(geoJsonSource(pointsSource) {
                feature(
                    Feature.fromGeometry(
                        LineString.fromLngLats(points)
                    )
                )
            })

            style.addLayer(
                lineLayer("pointsLayer", pointsSource) {
                    lineWidth(10.0)
                }
            )


            fun focusPoints() {
                val edgeInsets = EdgeInsets(100.0, 100.0, 100.0, 100.0)
//                val cameraOptions = mapView.mapboxMap.cameraForCoordinates(points, edgeInsets)
//                val cameraOptions = mapView.mapboxMap.cameraForGeometry(GeometryCollection.fromGeometries(points), edgeInsets)
                val cameraOptions = mapView.mapboxMap.cameraForCoordinateBounds(
                    CoordinateBounds(
                        Point.fromLngLat(points.maxOf { it.longitude() }, points.maxOf { it.latitude() }),
                        Point.fromLngLat(points.minOf { it.longitude() }, points.minOf { it.latitude() })
                    ),
                    edgeInsets
                )

                mapView.mapboxMap.setCamera(cameraOptions)
            }

            // In the doOnNextLayout, focusPoints() method does not work correctly, the zoom is detected incorrectly.
            mapView.doOnNextLayout {
                focusPoints()
            }

            // To verify that focusPoints() works as expected after delay
            mapView.postDelayed(5000) {
                focusPoints()
            }
        }
    }
}
```

## Expected behavior

Once the width and height of the MapView are known, the methods for obtaining CameraOptions work the same way as if the map had been drawn a long time ago. 

## Additional links and references

The code for reproducing the problem: https://github.com/Copatych/MapboxBugs/tree/cameraForGeometryBug

Video showing that the focus on the points occurs with an incorrect zoom at the beginning, and after 5 seconds the correct focus on the dots occurs [Screen_recording_20240220_123512.webm](https://github.com/mapbox/mapbox-maps-android/assets/57287061/336b4230-f07a-4c8e-a675-6ccf028aa2b2)

**Comment by Copatych** [comment]
Similar issue https://github.com/mapbox/mapbox-maps-android/issues/2080

**Comment by kiryldz** [comment]
@Copatych `doOnNextLayout` is not enough as we are using our own render thread and it's not connected anyhow with `MapView` measure / layout. The best (and easiest) way is indeed call `cameraFor*` methods when style / map is loaded. We will add clearer docs and / or revisit how this could be more clear for end users.
