### ISSUE TITLE
can not build the testapp, Could not get unknown property 'SDK_REGISTRY_TOKEN' for project ':mapbox-convention-plugin' of type org.gradle.api.Project.

### ISSUE THREAD

**Issue by ssss1108** [mapbox/mapbox-maps-android#2290]
<img width="1042" alt="Screenshot 2024-02-27 at 16 41 24" src="https://github.com/mapbox/mapbox-maps-android/assets/158240251/2acfe8f7-28b3-440e-9d76-f2beee4eef87">
<img width="848" alt="Screenshot 2024-02-27 at 16 41 34" src="https://github.com/mapbox/mapbox-maps-android/assets/158240251/229d3182-ccf8-4ee1-9021-95d8826b6709">

I have added SDK_REGISTRY_TOKEN in the root directory, but I still get an error when sync gradle. I want to run testapp.

thx!!!

**Comment by jush** [comment]
Please add it as a system environment variable instead.
