### ISSUE TITLE
MapboxLifecyclePluginImpl leaks MapView

### ISSUE THREAD

**Issue by brendanw** [mapbox/mapbox-maps-android#2292]
I first observed this in an application that uses `11.2.0-rc.1` and does not use the compose extension. After reading through github issues, I gave the compose extension a try and still observed the memory leak. I've setup a small sample project that makes it easy to reproduce the issue at https://github.com/brendanw/MapboxMemLeak/tree/master

Steps to reproduce:
1. run app
2. navigate between the two screens 5-10x
3. run `android profiler`
4. capture heap dump
5. search for `MapView` instances in heap dump.

expected: there should be 1 `MapView` instance in heap dump
actual: there are 10 `MapView` instances in heap dump

I also tested and confirmed issue is also on versions `11.1.0` and `11.0.0` of mapbox-android

Video demo of issue
https://www.youtube.com/watch?v=N0CNxQyJVNs

**Comment by kiryldz** [comment]
@brendanw thanks for the detailed report. Do I get it right that this issue is related to Compose (looking into https://github.com/brendanw/MapboxMemLeak/tree/master)? I am asking because you mentioned 
 > I first observed this in an application that uses 11.2.0-rc.1 and does not use the compose extension

But then it seems you're talking about Compose only. Can you confirm that you also see that leak when _not_ using Compose extension?

**Comment by brendanw** [comment]
@kiryldz I see the leak when not using the Compose extension as well. Though, I should clarify, I am still using mapbox in a compose context via `AndroidView`. I'll make a separate branch to demo

**Comment by brendanw** [comment]
Here's an example reproducing using `AndroidView` to wrap `MapView` within a jetpack compose context https://github.com/brendanw/MapboxMemLeak/pull/1

<img width="1354" alt="image" src="https://github.com/mapbox/mapbox-maps-android/assets/585321/35d44a2f-2200-4a24-8146-40f63e487a7b">

**Comment by kiryldz** [comment]
@brendanw thanks, we'll take a look.

**Comment by brendanw** [comment]
@kiryldz any chance a fix makes it into next week's release?

**Comment by pengdev** [comment]
Hey @brendanw thanks for reporting, I managed to reproduce the leak in v11.2.0-rc.1. 
We have done some refactoring for v11.3.0-beta.1 which will rewrite the Android view based plugins to composable functions in the compose extension, and we also removed the initialisation of `MapboxLifecyclePluginImpl` as the lifecycle is fully handled by the compose extension. With these refactoring, I've tested your code again and see no more leaks, please help to validate once v11.3.0-beta.1 is out next week.

**Comment by brendanw** [comment]
@pengdev I just update the sample on this branch (https://github.com/brendanw/MapboxMemLeak/pull/1) to the latest version and I am still seeing the memory leak.  Please note this branch uses to `AndroidView` to wrap the non-compose version of mapbox.

<img width="1432" alt="image" src="https://github.com/mapbox/mapbox-maps-android/assets/585321/543edf07-2534-42f7-8837-a56fb0824fd4">

**Comment by brendanw** [comment]
Using 11.3.0 compose extension I cannot reproduce the memory leak using the main code sample (https://github.com/brendanw/MapboxMemLeak)

<img width="1313" alt="image" src="https://github.com/mapbox/mapbox-maps-android/assets/585321/07ef12a5-8720-48e0-8d7a-04baa5561a52">

**Comment by pengdev** [comment]
@brendanw did you try to reproduce with the mapbox compose extension? The fix was in the compose extension, if you wrap MapView using your own AndroidView wrapper, you will still see the issue.

**Comment by brendanw** [comment]
@pengdev Just confirmed with compose extension that the mem leak is no longer there. great work! thank you 🙏
