### ISSUE TITLE
ViewAnnotations stay in map after leaving Compose composition

### ISSUE THREAD

**Issue by jorisoudejans** [mapbox/mapbox-maps-android#2293]
## Environment

- Android OS version: 13
- Devices affected: Pixel 4
- Maps SDK Version: 11.2.0-rc.1 + compose

## Observed behavior and steps to reproduce
I've encountered an issue where `ViewAnnotation`s added to a Mapbox map through a Jetpack Compose UI do not get removed as expected when the corresponding composable leaves the composition. This occurs even after applying filters or actions that should result in the removal of these annotations from the map.

**Steps to reproduce**:
1. Add multiple `ViewAnnotation`s to a Mapbox map within a Jetpack Compose UI, tracking them in a mutable state list.
2. Apply a filter or take an action that changes the state, leading to the expected removal of some `ViewAnnotation`s from the composition.
3. Observe that the `ViewAnnotation`s still appear on the map, despite their corresponding composables no longer being part of the composition.

## Expected behavior
When a `ViewAnnotation` composable leaves the composition (e.g., due to state changes or filtering), I expect the corresponding view annotation to be removed from the Mapbox map. This behavior should align with the declarative nature of Jetpack Compose, where UI elements are expected to reflect the current state.

## Notes / preliminary analysis
It seems that the lifecycle of `ViewAnnotation`s is not fully integrated with the Jetpack Compose lifecycle, leading to discrepancies between the UI state and the map's displayed annotations. This might be due to a missing linkage or update mechanism between the Compose state and the imperative handling of view annotations in the Mapbox SDK.

When I use `CircleAnnotation`s in the exact same manner, they do work as expected.

**Comment by kiryldz** [comment]
Thanks for reporting, we'll take a look.

**Comment by brendanw** [comment]
Can confirm I am also seeing this issue on 11.2.0-rc.1 + compose

**Comment by pengdev** [comment]
Hey @jorisoudejans @brendanw Thanks for the report, the fix will be landed in 11.3.0-beta.1 release.

**Comment by jorisoudejans** [comment]
Thank you so much! Do you have any idea when that is released? Like days or weeks?

**Comment by kiryldz** [comment]
> Thank you so much! Do you have any idea when that is released? Like days or weeks?

Release will happen the week after next week. If you need the fix right now, you can use snapshot `11.3.0-SNAPSHOT.0301T1146Z.43068bd` (please read about using snapshots [here](https://github.com/mapbox/mapbox-maps-android/blob/main/DEVELOPING.md#use-snapshot-releases-in-your-app)). I'll close this one so that we don't forget to close it when official release will be out, feel free to re-open if the issue will persist.

**Comment by kiryldz** [comment]
> Thank you for your assistance. Following your suggestions resolved the most obvious issues, but I'm still seeing old markers show up.
> 
> I'm using a list to display 10 markers on a map, allowing users to select a marker that changes colour to black. Upon updating the list—even without changing the data—the ViewAnnotation seems to get removed and recreated, rather than updated. This is evident as the selected marker reverts to its unselected state. Occasionally, the selected marker remains, but a duplicate marker appears nearby in an unselected state.
> 
> I suspect this issue might be related to how keys are assigned to ViewAnnotation. Is there a way to specify custom keys for ViewAnnotation to ensure they are correctly identified and updated rather than duplicated?

@jorisoudejans thanks for the comment. I'll create an internal issue to track it.

**Comment by jorisoudejans** [comment]
Unfortunately, I couldn’t get it to work, so we reverted to XML views using
the AnnotationManager.

Joris Oudejans
Vlinderstorm BV
http://vlinderstorm.com
***@***.*** ***@***.***>om
+316 395 787 00
