### ISSUE TITLE
[COMPOSE] Compass keeps getting re-enabled

### ISSUE THREAD

**Issue by Immunix** [mapbox/mapbox-maps-android#2300]
## Environment

- Android OS version: 13+
- Devices affected: Any
- Maps SDK Version: 11+

## Observed behavior and steps to reproduce

I'm using the `MapboxMap` composable to display a map in screen A of my app. If I rotate the map so that the compass no longer points North and then navigate to screen B and then back to A, the compass will get re-enabled and shown on the map. 
I'm disabling the compass using the following:
`CompassSettings.Builder().setEnabled(false).setVisibility(false).build()`
Using `setOpacity(0f)` will prevent it from being visible as a quick fix but I don't think its a long-term solution.

## Expected behavior

Compass stays disabled.

**Comment by kiryldz** [comment]
@Immunix thanks for reporting. Compass and other MapView plugins (attribution, scalebar, logo) will be exposed as composable functions in upcoming v11.3.0-beta.1 coming out next week. This issue should be resolved there but please re-open the ticket if it will be no case.
