### ISSUE TITLE
Adding possibility to add imports to style

### ISSUE THREAD

**Issue by SlavkaMichal** [mapbox/mapbox-maps-android#2303]
## New Feature

I would suggest adding method `addStyleImport` to `StyleManager` which would add an import to current style.

## Why

There already is `removeStyleImport` method and it would make the API more complete.
Currently there is no way how to add imports, without loading new style json that already includes them (or at least I could not find any).

Thank you

**Comment by kiryldz** [comment]
@SlavkaMichal this API was added: [`addStyleImportFromURI`](https://docs.mapbox.com/android/maps/api/11.7.1/mapbox-maps-android/com.mapbox.maps/-mapbox-style-manager/add-style-import-from-u-r-i.html?query=open%20fun%20addStyleImportFromURI(importId:%20String,%20uri:%20String,%20config:%20HashMap%3CString,%20Value%3E?,%20importPosition:%20ImportPosition?):%20Expected%3CString,%20None%3E) and [`addStyleImportFromJSON`](https://docs.mapbox.com/android/maps/api/11.7.1/mapbox-maps-android/com.mapbox.maps/-mapbox-style-manager/add-style-import-from-j-s-o-n.html)
