### ISSUE TITLE
No callback for RENDER_FRAME_FINISHED event.

### ISSUE THREAD

**Issue by lantah-1** [mapbox/mapbox-maps-android#2306]
## Environment

- Android OS version: Android 14
- Devices affected: magic 6 pro
- Maps SDK Version: 11.2.0

## Observed behavior and steps to reproduce

In my project, I'm using the snapshot feature. After calling the method mapview.snapshot, there are two callbacks: the first one is null and the second one contains the correct bitmap. Upon inspecting the source code, I noticed that there is no callback for the RENDER_FRAME_FINISHED event with RenderModeType.FULL, which causes the property readyForSnapshot to be false.

## Expected behavior

This doesn't happen 100% of the time, but it's likely to occur.
The expected outcome is to receive a callback for the RenderModeType.FULL state within the RENDER_FRAME_FINISHED event, thereby setting the value of readyForSnapshot to true.

**Comment by kiryldz** [comment]
@lantah-1 we do not observe similar behaviour. If the issue is still relevant on latest version of Maps v11 - please provide the reproducible code as there could be plenty of things affecting render-finished callback. I'll this issue for now as stale.
