### ISSUE TITLE
Compose annotation parameters have no effect

### ISSUE THREAD

**Issue by atomicelliot** [mapbox/mapbox-maps-android#2314]
## Environment

- Android OS version: 14
- Devices affected: All
- Maps SDK Version: 11.2.0, 11.3.0-beta.1  (Compose Extension)

## Observed behavior and steps to reproduce

Add points annotations to a compose map using e.g. `PointAnnotationGroup`
Set any of the arguments e.g. set `textAllowOverlap` to `false` and `textIgnorePlacement` to `false`
The arguments have no effect. Text labels will still overlap each other.

The only argument that works is `onClick`

## Expected behavior

The arguments should be applied on the first composition, and updated on any subsequent compositions.

## Notes / preliminary analysis

It looks like this is caused by the layer not being loaded at the point that the arguments are set on the initial composition.
Adding a breakpoint in one of the setters within `PointAnnotationManager.kt` reveals that `layer` is `null`, which means the argument isn't applied.

If you set the argument after the first composition (e.g. via a delay/button press) then the layer is initialised and the argument works as expected.

**Comment by Immunix** [comment]
Any news regarding this issue? Or any workaround that can be used until this is fixed?

**Comment by atomicelliot** [comment]
This has been my (very hacky) workaround for now:

```kotlin
var overlapEnabled by remember {
    mutableStateOf<Boolean?>(null)
}
var textIgnorePlacement by remember {
    mutableStateOf<Boolean?>(null)
}
var textOptional by remember {
    mutableStateOf<Boolean?>(null)
}

MapEffect(Unit) { mapView ->
    mapView.mapboxMap.getStyle {
        overlapEnabled = false
        textIgnorePlacement = false
        textOptional = true
    }
}

PointAnnotationGroup(
    annotations = pois,
    textAllowOverlap = overlapEnabled,
    textIgnorePlacement = textIgnorePlacement,
    textOptional = textOptional,
)
```

**Comment by pengdev** [comment]
@atomicelliot Thanks for the report and analysis, we are working on a fix.

**Comment by benceNagyWien** [comment]
Hi @pengdev, I'm encountering the same issue and a solution would be crucial for my projects. Eagerly awaiting updates. Thanks for your dedication!

**Comment by kiryldz** [comment]
This should be fixed now in https://github.com/mapbox/mapbox-maps-android/releases/tag/v11.3.0-rc.1.
