### ISSUE TITLE
How to display road-title in Mapbox v9 on Android?

### ISSUE THREAD

**Issue by nguyenvanan18031993** [mapbox/mapbox-maps-android#2315]
## Environment
- Android OS version: Tested on Android 14, Android 12 and Android 10
- Maps SDK Version:

implementation ('com.mapbox.mapboxsdk:mapbox-android-sdk:9.7.2') {
        exclude group: 'group_name', module: 'module_name'
    }
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-locationlayer:0.11.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-sdk-services:4.8.0'
    implementation('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.42.6') {
        exclude group: 'com.mapbox.mapboxsdk', module:'mapbox-android-telemetry'
    }
    implementation 'com.mapbox.mapboxsdk:mapbox-sdk-services:6.15.0'

## Observed behavior and steps to reproduce
I created new style in Mapbox Studio with Supported Mapbox SDK versions Android: 9.3.0, iOS 11.0.0 and I see the warning below. 
![Screenshot 2024-03-25 at 00 52 49](https://github.com/mapbox/mapbox-maps-android/assets/12476534/5b784b23-3139-44da-ab2f-389fdaec5afd)

I checked in Studio, and it's displaying road-title, but it's not when I run it in Android.
![1711302981791](https://github.com/mapbox/mapbox-maps-android/assets/12476534/09db7617-3a86-4a52-b047-c30902144cbb)

Please kindly help me with that.

## Expected behavior

Display road-title on Mapbox v9.
![Screenshot 2024-03-25 at 00 53 48](https://github.com/mapbox/mapbox-maps-android/assets/12476534/4aeedd8c-970c-4d64-b023-47b9ac41b644)

**Comment by kiryldz** [comment]
This repo is for Maps v10 and Maps v11. Maps v9 are no longer supported.
