### ISSUE TITLE
Change the signature of the Compose Map Ornaments (Logo, Attribution, etc.) to separate out the padding from the Modifier

### ISSUE THREAD

**Issue by ElliotSknr** [mapbox/mapbox-maps-android#2317]
## New Feature/ Change Suggestion

Add a new parameter to the map ornaments with the default padding to provide. So that setting your own additional padding on via the Modifier does not unexpectedly remove padding.

## Why

In edge-to-edge use cases, you will want to apply padding to keep all ornaments from falling behind the system bars. e.g. via usage of a M3 scaffold and it's provided padding parameters. In the current implementation as of 11.3.0-beta.1 supplying this padding via Attribution(modifier = Modifier.padding(scaffoldPadding) will have the unexpected result of removing the 'default' padding. Instead the default padding should be moved to a separate parameter so it can still be overwritten, but does not get overwritten in cases where it isn't clear that it would be.

```kotlin
  // Current
@Composable
@MapboxExperimental
public fun Logo(modifier: Modifier = Modifier, alignment: Alignment = Alignment.BottomStart) {
  Image(
    modifier = with(boxScope) {
      if (modifier === Modifier) {
        Modifier
          .padding(4.dp)
      } else {
        modifier
      }.align(alignment)
    },
    painter = painterResource(id = R.drawable.mapbox_logo_icon),
    contentDescription = "Mapbox Logo"
  )
}

  // Suggested new implementation
@Composable
@MapboxExperimental
public fun Logo(modifier: Modifier = Modifier, contentPadding: PaddingValues = PaddingValues(4.dp), alignment: Alignment = Alignment.BottomStart) {
  Image(
    modifier = with(boxScope) {
      Modifier.padding(contentPadding)
        .then(modifier)
        .align(alignment)
      },
      painter = painterResource(id = R.drawable.mapbox_logo_icon),
      contentDescription = "Mapbox Logo"
  )
}
```

**Comment by kiryldz** [comment]
@ElliotSknr thanks, we'll discuss with a team.

**Comment by pengdev** [comment]
@ElliotSknr thanks for the suggestion, I think these makes sense, we will work on implementing this change!

**Comment by kiryldz** [comment]
This is available in https://github.com/mapbox/mapbox-maps-android/releases/tag/v11.3.0-rc.1.
