### ISSUE TITLE
Add click listener for circle annotations when use PointAnnotationGroup

### ISSUE THREAD

**Issue by agarasul** [mapbox/mapbox-maps-android#2324]
## New Feature

Currently in PointAnnotationGroup there is only callback for point annotation click. However if points clustered, there is no way to handle click on circle annotation

```
PointAnnotationGroup(
    annotations = items,
    annotationConfig = AnnotationConfig(
        annotationSourceOptions = AnnotationSourceOptions(
            clusterOptions = ClusterOptions(
                textColor = Color.WHITE,
                textSize = 10.0,
                circleRadius = 15.0
            ),
        ),
        layerId = "markers"
    ),
     onClick = {

     },
     onCircleClick = { 

     }
)
```

## Why
In the app I would like to implement zoom when user clicks on circle annonation, but currently there isn't any way to do it

**Comment by kiryldz** [comment]
@agarasul this feature is available in https://github.com/mapbox/mapbox-maps-android/releases/v11.8.0-beta.1
