### ISSUE TITLE
[COMPOSE] PointAnnotationGroup doesn't recompose when annotations change

### ISSUE THREAD

**Issue by Immunix** [mapbox/mapbox-maps-android#2326]
## Environment

- Android OS version: *
- Devices affected: *
- Maps SDK Version: 11.3.0-beta.1 & 11.3.0-rc.1

## Observed behavior and steps to reproduce

As mentioned in the title, when the annotation data is changed, no re-composition occurs. This was previously working in v11.2.1 and v11.2.2.

## Expected behavior

Re-composition occurs when the entire data set changes.

**Comment by pengdev** [comment]
Duplicates with https://github.com/mapbox/mapbox-maps-android/issues/2329
