### ISSUE TITLE
[COMPOSE] PointAnnotationGroup doesn't re-compose individual nodes

### ISSUE THREAD

**Issue by Immunix** [mapbox/mapbox-maps-android#2329]
## Environment

- Android OS version: *
- Devices affected: *
- Maps SDK Version: v11.*

## Observed behavior and steps to reproduce

When an individual node of the PointAnnotationGroup is modified (e.g iconSize & textSize are increased following user interaction) re-composition doesn't occur.

## Expected behavior

Re-composition occurs when one of the nodes is modified.

**Comment by pengdev** [comment]
@Immunix Thanks for the report, we have identified the issue and the fix will land in v11.3.0 release.

**Comment by pengdev** [comment]
@Immunix closing now as the [11.3.0](https://github.com/mapbox/mapbox-maps-android/releases/tag/v11.3.0) release is out, please give it a try and feel free to reopen if you still see issues, thanks!
