### ISSUE TITLE
No onVisibilityChange function

### ISSUE THREAD

**Issue by michal-bogucki** [mapbox/mapbox-maps-android#2336]
## New Feature

https://docs.mapbox.com/ios/maps/guides/markers-and-annotations/view-annotations/#handle-visibility

This function is missing on Android and I cannot check visibility on the map

**Comment by kiryldz** [comment]
@michal-bogucki here it is https://docs.mapbox.com/android/maps/api/11.2.2/mapbox-maps-android/com.mapbox.maps.viewannotation/-on-view-annotation-updated-listener/on-view-annotation-visibility-updated.html?query=open%20fun%20onViewAnnotationVisibilityUpdated(view:%20View,%20visible:%20Boolean).

Listener could be added like that:
```
    mapView.viewAnnotationManager.addOnViewAnnotationUpdatedListener(
      object : OnViewAnnotationUpdatedListener {

        override fun onViewAnnotationVisibilityUpdated(view: View, visible: Boolean) {
          super.onViewAnnotationVisibilityUpdated(view, visible)

        }
      }
    )
```

**Comment by michal-bogucki** [comment]
But this listener does not allow to retrieve PointAnnotation. This view is ViewAnnotation? How to download point from it?
