### ISSUE TITLE
Example code for MapboxMap Compose to support loading multiple 3D models

### ISSUE THREAD

**Issue by AndrewGe** [mapbox/mapbox-maps-android#2339]
## New Feature
Would the team provide some example code  for MapboxMap Compose to support loading multiple 3D models? 

The existing sample listed[ here ](https://docs.mapbox.com/android/maps/examples/3D-model-layer/) still uses non-compose MapView to load 2 3D models. We couldn't find similar examples. 

## Why
As Compose is universally applied in Android development nowadays, we need to apply MapboxMap compose in our app. It is also consistent with Mapbox's own efforts of 3D map, which we use to include our own 3D models too. 

We'd appreciate some estimated timeline so that we can plan accordingly for our development. 

cc: @peng.liu@mapbox.com

**Comment by AndrewGe** [comment]
Also, for the current compose function
```
@Composable
@MapboxExperimental
public fun MapboxMap( )
```
It looks like that we should be able to create another Composable  which would accepts a "MapView" argument. Of course, we need to handle its state after passing it to the new Composable. 

The benefits: we should be able to re-use most existing MapView features easily in the new Composable, in contrast to MapboxMap which creates MapView internally.

**Comment by pengdev** [comment]
Hey @AndrewGe thanks for the interest in the compose extension, we are actively working on bringing style composition to the compose extension, in the latest release https://github.com/mapbox/mapbox-maps-android/releases/tag/v11.3.0 , we have introduced experimental layer composable functions with source states, we are planning to add full runtime styling API support for compose extension, please stay tuned.

> It looks like that we should be able to create another Composable which would accepts a "MapView" or rememberMapViewWithLifecycle (similar to [this code](https://developer.android.com/codelabs/jetpack-compose-advanced-state-side-effects#7)) argument. Of course, we need to handle its state after passing it to the new Composable.

Please refer to our [document](https://github.com/mapbox/mapbox-maps-android/blob/main/extension-compose/README.md#use-raw-mapboxmap-methods-through-mapeffect), you can already use `MapEffect` within `MapboxMap` content to get the raw map controller(mapView) and use all the existing APIs, you can render the 3D models just like non-compose `MapView` example within `MapEffect` with existing APIs.

**Comment by pengdev** [comment]
the ModelLayer example is added at https://github.com/mapbox/mapbox-maps-android/blob/main/compose-app/src/main/java/com/mapbox/maps/compose/testapp/examples/style/ModelLayerActivity.kt
