### ISSUE TITLE
Scale velocity animation missing

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-maps-android#234]
The velocity animations for both scale and quick-scale gestures are not present for v10.
Scale:

https://user-images.githubusercontent.com/16925074/113418859-9bb3ed80-93c6-11eb-989f-13d80981f2d2.mp4

Quick-scale:

https://user-images.githubusercontent.com/16925074/113418879-a53d5580-93c6-11eb-95f0-cc86f6017638.mp4

Comparison with v9, scale:

https://user-images.githubusercontent.com/16925074/113418894-acfcfa00-93c6-11eb-8c5e-b1408729a6fa.mp4

and v9 quick-scale:

https://user-images.githubusercontent.com/16925074/113418914-b4240800-93c6-11eb-9083-0d05823deb18.mp4

cc @mapbox/maps-android

**Comment by kiryldz** [comment]
@tobrun is it a bug or a feature of v10? 😄

**Comment by tobrun** [comment]
I personally feel the current v10 behavior feels responsive but v9 additionally feels fluent.
I would opt to long term bring this back to v10

**Comment by kiryldz** [comment]
Stale, outdated.
