### ISSUE TITLE
Create type safe interface for reading style later properties

### ISSUE THREAD

**Issue by kmadsen** [mapbox/mapbox-maps-android#235]
When trying to figure out how to read map style properties (get the color of buildings, for example). I need to use the debugger to do it. Can someone provide a suggestion if I'm missing the interface somewhere?

https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/
Paint is a very common Mapbox Layer style type, so why isn't there a direct way to get it?

``` kotlin
  override fun getStyleLayerProperties(layerId: String): Expected<Value, String> {
    return styleManagerRef.call { this.getStyleLayerProperties(layerId) }
  }
```

This function seems to have potential but it is internal
https://github.com/mapbox/mapbox-maps-android/blob/fd0cb8f7b31d91c08443b473b59dda440fd75328/extension-style/src/main/java/com/mapbox/maps/extension/style/layers/Layer.kt#L146

![Screen Shot 2021-04-05 at 4 44 05 PM](https://user-images.githubusercontent.com/3021882/113639491-25192900-962e-11eb-93db-20970db66a1c.png)

**Comment by kmadsen** [comment]
I'm looking for a `PaintLayer`, but can't find it

![Screen Shot 2021-04-05 at 5 14 07 PM](https://user-images.githubusercontent.com/3021882/113641376-57c52080-9632-11eb-9d62-4672d8f95c36.png)

**Comment by pengdev** [comment]
Hi @kmadsen , in the Android maps sdk, the `paint` and `layout` property type are abstracted out, you can directly assess the property under the layer itself. And paint is not a layer type, in your case, I think you need to do the following:

```
mapView.getMapboxMap().getStyle { style ->
    val buildingColor = style.getLayerAs<FillExtrusionLayer>("building-layer-id").fillExtrusionColor
}
```

**Comment by knov** [comment]
@kmadsen did the above solution resolve your issue?

**Comment by kmadsen** [comment]
``` kotlin
mapView.getMapboxMap().getStyle { style ->
    val buildingColor = style.getLayerAs<FillExtrusionLayer>("building-layer-id").fillExtrusionColor
}
```

Yep, that's a nice interface I was looking for! Thanks @pengdev

**Comment by kmadsen** [comment]
Opening this ticket back up for discussion. Because we are interested in surfacing "Building" data when it is selected. Considering that java/kotlin developers are not javascript developers - could we explore the possibility of representing these objects with type safe classes?

``` kotlin
BuildingHighlightValue(
     buildings: List<MapBuilding>
)
MapBuilding(
     id: Long
     geometry: Polygon,
     minHeight: Double,
     height: Double,
     underground: Boolean,
     paint: Paint
)
```

**Comment by kmadsen** [comment]
Other options we're considering. 

1. Is surfacing the list of QueriedFeature objects. I dislike this because It still requires the downstream customer to take on the string/mapping assumptions in their own code base.
1. surface the list of Feature objects, same con as reason as 1
1. create a NavigationBuildingFeature. I dislike this because the building styles are defined in maps

My preference is to have maps build these types of objects https://github.com/mapbox/mapbox-maps-android/issues/235#issuecomment-841320263 and make it so downstream doesn't have to dig through the debugger to read map data.

**Comment by kmadsen** [comment]
Closing here, as we are going with the alternative options:
1. surface a list of QueriedFeature
2. create a NavigationBuildingFeature

https://github.com/mapbox/mapbox-navigation-android/pull/4420
