### ISSUE TITLE
[common\DeviceLocationProvider]: Failed to stop: java.lang.Exception: Cannot stop Google device location provider. Invalid mode: NONE

### ISSUE THREAD

**Issue by mj09** [mapbox/mapbox-maps-android#2351]
## Environment

- Android OS version: 14
- Devices affected: Several Pixes devices, 7, 6, 5
- Maps SDK Version: 11

## Observed behavior and steps to reproduce

When loading our app the map is loaded, but the navigation puck is nowhere to see and it seems like the location is not being updated. We can see in the logs this error is printed when this occurs: [common\DeviceLocationProvider]: Failed to stop: java.lang.Exception: Cannot stop Google device location provider. Invalid mode: NONE
However it is not an issue I can trigger at will, so not sure what is causing it.

On app start map and navigation puck should always be loaded

**Comment by jush** [comment]
We have fixed issues that caused that log. Those will be available in the upcoming 11.6.0 release.

Please re-open if the issue persists after you've upgraded 11.6.0
