### ISSUE TITLE
[Compose] Compass default visibility is true

### ISSUE THREAD

**Issue by martht** [mapbox/mapbox-maps-android#2352]
## Environment

- Android OS version: 14
- Devices affected: Pixel 7a
- Maps SDK Version: v11.3

## Observed behavior and steps to reproduce

When the MapboxMap is initialized with viewport bearing facing north, the Compass (using `fadeWhenFacingNorth = true`), is visible for some frames then disappears because of the bearing at 0.0.

## Expected behavior

If the default viewport bearing is facing north, the compass should not be visible at map initialization.

## Notes / preliminary analysis

In the `MapCompassScope.kt`, we see that `compassVisibility` is true by default

```kotlin
var compassVisibility by remember {
   mutableStateOf(true)
}
```

Maybe set it to false and let the `cameraChangedEvents` collect do it job to display or not the compass ?

Thank you

**Comment by pengdev** [comment]
Thanks @martht for the report, this will be fixed in upcoming releases.
