### ISSUE TITLE
Allow to stop ActiveGuidance on DropIn

### ISSUE THREAD

**Issue by mBaldasty** [mapbox/mapbox-maps-android#2356]
## New Feature

Currently you can start an active guidance session with the drop in ui to start a navigation.
To stop the navigation you currently have to rely on the integrated button.
Or am I just missing it?

## Why
Allow stopping the guidance session over a dedicated function. No need to overwrite the and overstyle the integrated button. Would opt for ease of use.

**Comment by baleboy** [comment]
This seems to be a Navigation SDK request, could you file it at https://github.com/mapbox/mapbox-navigation-android/issues ?
