### ISSUE TITLE
Can not sync com.mapbox.mapboxsdk:mapbox-android-sdk:9.5.0 on Apple silicon M1

### ISSUE THREAD

**Issue by h3clikejava** [mapbox/mapbox-maps-android#236]
Could not GET 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/mapboxsdk/mapbox-android-sdk/10.0.0-beta.15/mapbox-android-sdk-10.0.0-beta.15.pom'. Received status code 401 from server: Unauthorized
Disable Gradle 'offline mode' and sync project

x86 is fine.

**Comment by knov** [comment]
Hi @ h3clikejava, please refer to the [installation instructions](https://docs.mapbox.com/android/beta/maps/guides/install/) about adding your access token to download the SDK.
