### ISSUE TITLE
Compose questions

### ISSUE THREAD

**Issue by Plovotok** [mapbox/mapbox-maps-android#2363]
Hello, I'm currently working on my project. I have some questions about compose extension lib. 

1) Are compose maps compatible with Navigation API? 

2) I saw @Composable Layer functions and try to work with them, but it seems, dynamycal changing layers still works in function setStyleLayerProperty. For example I have own map style with traffic, and if I want to toggle layer visibility I should use this method. Probably I made mistakes cause didn't work with library before compose extension

**Comment by jush** [comment]
1. Mapbox Navigation does not yet have Compose support out of the box but you can still use it. You might need to use [MapEffect](https://github.com/mapbox/mapbox-maps-android/blob/fe5f76700070a48e912d0544bf0145a6b2a35776/extension-compose/README.md?plain=1#L125) to access the underlying map view and `MapboxMap`. 
2. If you need to use `setStyleLayerProperty` you can do so through `MapEffect`.
