### ISSUE TITLE
IncorrectNumberOfArgumentsInExpression lint rule shows error for 2 expressions

### ISSUE THREAD

**Issue by jsoberg** [mapbox/mapbox-maps-android#2388]
## Environment

- Android OS version: N/A - Dev Environment
- Devices affected: N/A - Dev Environment
- Maps SDK Version: 11.4.0

## Observed behavior and steps to reproduce

The `IncorrectNumberOfArgumentsInExpression` states that in an `Expression`, 2-3 expressions should be added instead of 1. However, using 2 expressions results in a Lint error. See [this](https://github.com/jsoberg/Mapbox-Android-App-Test-Template/pull/1/files) for an example of the Lint rule showing error for 2 expressions.

## Expected behavior

`IncorrectNumberOfArgumentsInExpression` should not signal a lint error when using 2 expressions in `eq`.

## Notes / preliminary analysis

`IllegalNumberOfArgumentsDetector ` may not be detecting as expected.

## Additional links and references

Example repository: https://github.com/jsoberg/Mapbox-Android-App-Test-Template/pull/1/files

**Comment by ittna** [comment]
Same as #2373

**Comment by jsoberg** [comment]
Thanks @ittna! Closing this as a duplicate of #2373
