### ISSUE TITLE
 Error setting geo json: A line string must have two or more coordinate points.

### ISSUE THREAD

**Issue by fantasyado** [mapbox/mapbox-maps-android#239]
Hi,
I got the error(as title) message in logcat when displaying some line using geojson.   And the whole line layer could not be properly displayed. The geojson does have some lineString with one coordinate point. But iOS and Web side can ignore the error and work properly.  Can I ignore the problematic data on Android or is there any quick solution I can filter those dirty datas.

Thanks.

**Comment by sbma44** [comment]
Your data must conform to the GeoJSON specification in order to avoid triggering this error, which means your LineStrings will need more than one point. Filtering should be relatively straightforward but is beyond the scope of the SDK.
