### ISSUE TITLE
[compose] GesturesSettings changes are not applied

### ISSUE THREAD

**Issue by Immunix** [mapbox/mapbox-maps-android#2417]
## Environment

- Android OS version: *
- Devices affected: *
- Maps SDK Version: 11.5.0-rc.1

## Observed behavior and steps to reproduce

Changes made to the `gesturesSettings` are not being applied to the map, e.g. disabling pitch/rotation has no effect on map behavior.

As an example, I'm initializing the state as follows:

```kotlin
val mapState = rememberMapState {
    gesturesSettings.toBuilder()
        .setPitchEnabled(false)
        .build()
}

MapboxMap(
    mapState = mapState,
    ...
)
``` 

If this is not the correct way I'd appreciate an example of how it should be done.

## Expected behavior

Changes made to the state correctly reflect in the map behavior.

**Comment by natiginfo** [comment]
Hi! While your code builds new gesture settings, it does not update `gestureSettings`.  Following would be the correct way to set gesture settings in MapState:
```
val mapState = rememberMapState {
    gesturesSettings = gesturesSettings.toBuilder()
        .setPitchEnabled(false)
        .build()
}

MapboxMap(
    mapState = mapState,
    ...
)
```

For now, I'll close this issue.
