### ISSUE TITLE
PointAnnotation Not Being Drawn on the Map

### ISSUE THREAD

**Issue by sofijatanaskovic** [mapbox/mapbox-maps-android#2419]
## Environment

- Android OS version: Android 14, Android 13
- Devices affected: Pixel 8 emulator, Pixel 7 Pro emulator, Xiaomi 11 Lite 5G NE
- Maps SDK Version: 11.4.1

## Observed behavior and steps to reproduce

We're trying to draw a simple PointAnnotation using the PointAnnotationManager. But the point annotation doesn't show up on the map. Previously we had the 11.1.0 version and everything worked as it should.
Here's a code sample: 

```
val annotationPlugin = binding.mapboxMapView.annotations
val droppedPinAnnotationManager = annotationPlugin.createPointAnnotationManager()

droppedPinAnnotationManager.createDroppedPin(droppedPin)
...
private fun PointAnnotationManager.createDroppedPin(droppedPin: DroppedPin) {
    val pointAnnotationOptions = PointAnnotationOptions()
        .withPoint(
            Point.fromLngLat(
                droppedPin.point.longitude(),
                droppedPin.point.latitude()
            )
        )
        .withIconImage(
            requireDrawable(
                requireContext(),
                droppedPin.icon
            ).toBitmap()
        )
    create(pointAnnotationOptions)
}
```

## Expected behavior

PointAnnotation icon drawn and visible on map. 

## Notes / preliminary analysis

Currently in production we have the 11.1.0 version in which everything works fine, but we can't upgrade to 11.4.1 because of this.
When evaluating the PointAnnotationManager's value after creating the point annotation, it's `annotations` list does contain the PointAnnotation which was created. There also don't seem to be any warnings or errors in the log.

**Comment by jush** [comment]
I tried to reproduce the issue in our example `AnimatePointAnnotationActivity` but all the points are rendered properly.

Make sure to check that your latitude and longitude are correct as well as your bitmap.

Please provide a small project where the issue can be reproduced.

**Comment by sofijatanaskovic** [comment]
Thank you for your reply!
Just an update, there seem to have been changes between 11.1 and 11.4 in the way raster layers get rendered. So one of the layers ended up on top of our PointAnnotation layer which caused it to look like PointAnnotations stopped working.
