### ISSUE TITLE
Incorrect bottom margin inside CompassViewImpl

### ISSUE THREAD

**Issue by yuryybk** [mapbox/mapbox-maps-android#242]
Pls use the `bottom` param instead of the `left`param  inside the `FrameLayout.setMargin()` call
https://github.com/mapbox/mapbox-maps-android/blob/android-v10.0.0-beta.16/plugin-compass/src/main/java/com/mapbox/maps/plugin/compass/CompassViewImpl.kt#L118

**Comment by tobrun** [comment]
patched and released
