### ISSUE TITLE
[Compose] SymbolLayer - minZoom & maxZoom don't work

### ISSUE THREAD

**Issue by lolo-io** [mapbox/mapbox-maps-android#2429]
## Environment

- Android OS version: 14
- Devices affected: All
- Maps SDK Version: 11.5.0

## Observed behavior and steps to reproduce

Properties minZoom and maxZoom on a symbol Layer have no effect.
I see all my data regardless the zoom on the map.
I am using geoJsonData and a bitmap image to represent my points. 

```
points.forEach {

    val state = rememberGeoJsonSourceState {
        data = GeoJSONData(
            Feature.fromGeometry(
                Point.fromLngLat(it.longitude, it.latitude)
            )
        )
        maxZoom = LongValue(8L)
    }

    SymbolLayer(
        sourceState = state,
        iconImage = ImageValue(getIconBitmap()),
        iconAllowOverlap = BooleanValue(true),
        minZoom = LongValue(5L),
        maxZoom = LongValue(8L),
    )
}
```

## Expected behavior
Data should hide when outside the zoom range. 

## Workaround
Data should hide when outside the zoom range. 

1- set a custom layerId to your layer : `layerId = "layer-$i",`
2- add `"minzoom"` and `"maxzoom"` properties to your map for this layer : 
```
MapEffect(Unit) {
    it.mapboxMap.setStyleLayerProperty("layer-$i","minzoom", Value(5.0))
    it.mapboxMap.setStyleLayerProperty("layer-$i","maxzoom", Value(8.0))
}
```

## Core problem

`SymbolLayer.kt` sets `"min-zoom" `and `"max-zoom" `properties. this should be `"minzoom"` and `"maxzoom" `

if (minZoom.notInitial) {
          setProperty("min-zoom", minZoom.value)
        }
        if (maxZoom.notInitial) {
          setProperty("max-zoom", maxZoom.value)
        }

**I will male a PR soon to correct this bug as soon as I have some time.**

**Comment by flasher297** [comment]
@lolo-io raised an internal ticket to fix this issue
https://mapbox.atlassian.net/browse/MAPSAND-1731
@pengdev @kiryldz

**Comment by pengdev** [comment]
@lolo-io thanks for reporting the issue, the fix is landed in https://github.com/mapbox/mapbox-maps-android/releases/tag/v11.6.0-beta.1
