### ISSUE TITLE
Allow to turn off CameraAnimationPlugin logs

### ISSUE THREAD

**Issue by yuryybk** [mapbox/mapbox-maps-android#243]
## New Feature
Allow to turn off CameraAnimationPlugin logs on the app side

## Why
CameraAnimationPlugin logs are too frequent and prevent analysis in some cases

**Comment by tobrun** [comment]
Duplicate of internal ticket

**Comment by kiryldz** [comment]
As additional request some frequent log messages will be downgraded to `verbose` instead of `info`
