### ISSUE TITLE
 Allow indexing/directory requests of new private maven

### ISSUE THREAD

**Issue by sddamico** [mapbox/mapbox-maps-android#2431]
This is a clone of this archived issue: https://github.com/mapbox/mapbox-gl-native-android/issues/617

In order to improve build speeds, our team utilizes artifactory to mirror remote repositories and cache them. The way that your maven server is currently configured does not allow for indexing and requesting of repository directories to discover what coordinates might be available.

For instance, this request is 404 with basic auth provided:

GET https://api.mapbox.com/downloads/v2/releases/maven/

If configured differently, maven would allow you to view the index of that directory (and sub-dirs) and build a local index of the repository.

It would be greatly appreciated if the mapbox team would enable this functionality so that we don't have to resort to hacking around the limitation (republishing a version of the binaries ourselves on our private maven, for instance).

**Comment by jush** [comment]
Unfortunately the service exposing the artifacts is not part of our team. Moreover it might require some license/ToS considerations.

Please reach out to our support team https://support.mapbox.com/.
