### ISSUE TITLE
Crash:gladLoadGLES2

### ISSUE THREAD

**Issue by Zzechen** [mapbox/mapbox-maps-android#2432]
## Online Crash

- Android OS version: 11,12,13,14
- Devices affected: Motorola One 5G Ace,Galaxy A23 5G,Moto G Stylus 5G
- Maps SDK Version:11.4.0

I Don't know how to reproduce this crash, here is the log
         
` Crashed: Thread: SIGSEGV  0x0000000000000000
#00 pc 0x0
#01 pc 0x72e8c4 libmapbox-maps.so (gladLoadGLES2) (BuildId: 87c28a50d281c087fd44895b82f5dd3ca925f9f4)
#02 pc 0x72fc48 libmapbox-maps.so (gladLoadGLES2) (BuildId: 87c28a50d281c087fd44895b82f5dd3ca925f9f4)
#03 pc 0x4ca85c libmapbox-maps.so (mapbox::maps::Version::getRevisionString()) (BuildId: 87c28a50d281c087fd44895b82f5dd3ca925f9f4)
#04 pc 0x4ca4fc libmapbox-maps.so (mapbox::maps::Version::getRevisionString()) (BuildId: 87c28a50d281c087fd44895b82f5dd3ca925f9f4)
#05 pc 0x671ecc libmapbox-maps.so (mapbox::maps::Version::getRevisionString()) (BuildId: 87c28a50d281c087fd44895b82f5dd3ca925f9f4)
#06 pc 0x53178c libmapbox-maps.so (mapbox::maps::Version::getRevisionString()) (BuildId: 87c28a50d281c087fd44895b82f5dd3ca925f9f4)
#07 pc 0x53f97c libmapbox-maps.so (mapbox::maps::Version::getRevisionString()) (BuildId: 87c28a50d281c087fd44895b82f5dd3ca925f9f4)
#08 pc 0x533bc8 libmapbox-maps.so (mapbox::maps::Version::getRevisionString()) (BuildId: 87c28a50d281c087fd44895b82f5dd3ca925f9f4)
#09 pc 0x532858 libmapbox-maps.so (mapbox::maps::Version::getRevisionString()) (BuildId: 87c28a50d281c087fd44895b82f5dd3ca925f9f4)
#10 pc 0x40cc7c libmapbox-maps.so (mapbox::maps::MapRecorder::createInstance(std::__ndk1::shared_ptr<mapbox::maps::Map> const&)) (BuildId: 87c28a50d281c087fd44895b82f5dd3ca925f9f4)
#11 pc 0x407194 libmapbox-maps.so (mapbox::maps::CoordinateBounds::extend(mapbox::maps::CoordinateBounds const&) const) (BuildId: 87c28a50d281c087fd44895b82f5dd3ca925f9f4)
#12 pc 0x7aca50 libmapbox-maps.so (gladLoadGLES2) (BuildId: 87c28a50d281c087fd44895b82f5dd3ca925f9f4)`

**Comment by Zzechen** [comment]
> @Zzechen is it possible for you to share whole logcat before the app crashes?

sorry, I can't reproduce in the test environment

do you have some idea? may be I can try some case to reproduce this
I saw all this crash are opened when app cold start and load the map

**Comment by kiryldz** [comment]
@Zzechen well, hard to say. Could you at least see if that crash happened once or is it happening all the time for given devices? Motorola One 5G Ace,Galaxy A23 5G,Moto G Stylus 5G

**Comment by Zzechen** [comment]
@kiryldz I suspect this crash is related to webview, although it's a bit hard to explain. Let me confirm it in the next two days.

**Comment by Zzechen** [comment]
This may be related to webview, so I will close this question for now. If there is definite information related to mapbox, I will reopen it later.
