### ISSUE TITLE
 collision behavior

### ISSUE THREAD

**Issue by huozhezhazha** [mapbox/mapbox-maps-android#2439]
Does mapbox support collision behavior, such as Google Maps' collision behavior=OPTIONAL-AND.HIDES-LOWER-PRIORITY, https://developers.google.cn/maps/documentation/javascript/advanced-markers/collision-behavior

**Comment by pengdev** [comment]
@huozhezhazha Mapbox Maps SDK do provide several configurations to customise the collision behaviour, you may find the following documentation helpful:
https://docs.mapbox.com/android/maps/api/11.5.1/mapbox-maps-android/com.mapbox.maps.extension.style.layers.generated/-symbol-layer/icon-allow-overlap.html
https://docs.mapbox.com/android/maps/api/11.5.1/mapbox-maps-android/com.mapbox.maps.extension.style.layers.generated/-symbol-layer/text-allow-overlap.html
https://docs.mapbox.com/android/maps/api/11.5.1/mapbox-maps-android/com.mapbox.maps.extension.style.layers.generated/-symbol-layer/symbol-z-order.html
