### ISSUE TITLE
easeTo() not working

### ISSUE THREAD

**Issue by lywedo** [mapbox/mapbox-maps-android#2449]
## Environment

- Android OS version: 11
- Devices affected: emulator
- Maps SDK Version: V10.18.3

## Observed behavior and steps to reproduce
I upgraded mapbox from v9 -> v10, the original code is 
```
val cameraUpdate = CameraUpdateFactory.newLatLngBounds(latLongBounds, padding)
        mapboxMap.easeCamera(cameraUpdate)
```
now, I change the code here to 
```
mapView?.getMapboxMap()?.apply {
            setCamera(cameraOptions)
            easeTo(EASE_TO_TARGET_CAMERA_POSITION, prepareAnimationOptions(2000))
private fun prepareAnimationOptions(duration: Long) = mapAnimationOptions {
        duration(duration)
        animatorListener(object : AnimatorListenerAdapter() {


        })
    }
    private val EASE_TO_TARGET_CAMERA_POSITION = cameraOptions {
        center(Point.fromLngLat(-0.07520, 51.50550))
        zoom(17.0)
        bearing(180.0)
        pitch(30.0)
    }
```
the map still stays in the initial position when running

## Expected behavior

It should move to the right position

**Comment by jush** [comment]
@lywedo your code looks good to me.

When are you calling that code? I wonder if `mapView` or `getMapboxMap()` could be null.

**Comment by lywedo** [comment]
> @lywedo your code looks good to me.
> 
> When are you calling that code? I wonder if `mapView` or `getMapboxMap()` could be null.

They are not null, I am debugging it, they could be seen in the snapshot
![image](https://github.com/user-attachments/assets/254a6e16-456b-4ee4-b679-fbc90afa5b5a)

**Comment by jush** [comment]
I see. Then the problem seems to be somewhere else.

I tried your code on top of the [SimpleMapActivity](https://github.com/mapbox/mapbox-maps-android/blob/main/app/src/main/java/com/mapbox/maps/testapp/examples/SimpleMapActivity.kt) and it works properly.

Could you please share a small app that reproduces the problem?
