### ISSUE TITLE
 coordinateBoundsForCamera inversed west and east longitude coordinates at 180 / -180 longitude

### ISSUE THREAD

**Issue by ybert** [mapbox/mapbox-maps-android#2452]
I would like to use coordinateBoundsForCamera to get map bounds to make a search in my search engine based on a bounding box area.

But for places like very east of Russia or New Zealand it doesnt work as this function return inversed west and east longitude when west  longitude is 175 and east  longitude is -175 (for example).

**Comment by kiryldz** [comment]
I assume [coordinateBoundsForCameraUnwrapped](https://docs.mapbox.com/android/maps/api/11.6.0/mapbox-maps-android/com.mapbox.maps.plugin.delegates/-map-camera-manager-delegate/coordinate-bounds-for-camera-unwrapped.html?query=abstract%20fun%20coordinateBoundsForCameraUnwrapped(camera:%20CameraOptions):%20CoordinateBounds) is what you're looking for.
