### ISSUE TITLE
Could not find com.mapbox.mapboxsdk:mapbox-android-accounts:0.7.0

### ISSUE THREAD

**Issue by chancyWu** [mapbox/mapbox-maps-android#2457]
## Environment

- Android OS version: 14
- Devices affected:
- Maps SDK Version: 9.2.1

## Observed behavior and steps to reproduce

Seems the mapbox-android-accounts lib was removed from Maven Central recently, which will cause the mapbox SDK 9.2.1 failed when build the app. https://central.sonatype.com/search?q=mapbox-android-accounts

the error is as below:

> Execution failed for task ':app:dataBindingMergeDependencyArtifactsSdpDebug'.
> > Could not resolve all files for configuration ':app:sdpDebugCompileClasspath'.
>    > Could not find com.mapbox.mapboxsdk:mapbox-android-accounts:0.7.0.
>      Required by:
>          project :app > com.mapbox.mapboxsdk:mapbox-android-sdk:9.2.1

## Expected behavior

Could anyone help to check why it's removed? is it possible to add it to the Maven Central again?

## Additional links and references

https://central.sonatype.com/search?q=mapbox-android-accounts
JCenter sunset https://jfrog.com/blog/jcenter-sunset/, previously still can download from jcenter to get the lib.
https://central.sonatype.com/artifact/com.mapbox.mapboxsdk/mapbox-android-sdk

**Comment by kiryldz** [comment]
@chancyWu Maps v9 are not supported anymore. Please migrate either to Maps v10 or v11.
