### ISSUE TITLE
MarkerView Replacement

### ISSUE THREAD

**Issue by VincentJoshuaET** [mapbox/mapbox-maps-android#246]
I am in the process of recreating an iOS app that extensively uses Mapbox. One feature I cannot implement is the MGLCalloutView. I cannot use symbol layers/annotations because the views I want to show have a checkbox that has a listener whether it is checked or not, then act accordingly.

**Comment by kiryldz** [comment]
See https://github.com/mapbox/mapbox-maps-android/issues/418#issuecomment-972996614.
