### ISSUE TITLE
Location puck bearing direction is wrong in version 11 of mapbox sdk for android

### ISSUE THREAD

**Issue by arbonvata** [mapbox/mapbox-maps-android#2466]
## Environment

- Android OS version: 14
- Devices affected: all
- Maps SDK Version: 11.6.0 and 11.5.1

## Observed behavior and steps to reproduce
Given the following code:

```
with(mapView) {
                location.locationPuck = createDefault2DPuck(withBearing = true)
                location.enabled = true
                location.puckBearing = PuckBearing.COURSE
                viewport.transitionTo(
                    targetState = viewport.makeFollowPuckViewportState(
                        options = FollowPuckViewportStateOptions.Builder()
                            .bearing(options = FollowPuckViewportStateBearing.SyncWithLocationPuck)
                            .build()
                    ),
                    transition = viewport.makeImmediateViewportTransition()
                )
                location.addOnIndicatorPositionChangedListener(onIndicatorPositionChangedListener)

            }
```

and also 

```
  private val onIndicatorPositionChangedListener = OnIndicatorPositionChangedListener {
        // Jump to the current indicator position
        binding.mapView.mapboxMap.setCamera(CameraOptions.Builder().bearing(0.0).build())
        // Set the gestures plugin's focal point to the current indicator location.
        binding.mapView.gestures.focalPoint = binding.mapView.mapboxMap.pixelForCoordinate(it)
    }
```
Have tried to remove the location.addOnIndicatorPositionChangedListener
 and replaced with 

```
  with(mapView) {
                location.locationPuck = createDefault2DPuck(withBearing = true)
                location.enabled = true
                location.puckBearing = PuckBearing.COURSE
                viewport.transitionTo(
                    targetState = viewport.makeFollowPuckViewportState(
                        options = FollowPuckViewportStateOptions.Builder()
                            .bearing(options = FollowPuckViewportStateBearing.SyncWithLocationPuck)
                            .build()
                    ),
                    transition = viewport.makeImmediateViewportTransition()
                )

            }
            mapboxMap.setCamera(CameraOptions
                .Builder()
                .bearing(90.0)
                .zoom(2.2)
                .build()
            )
```
without any impact
Changing bearing on CameraOptions.Builder().bearing doesn't have any impact at all.
I have played with values 0, 90, 180 and 270. No visible impact at all

Same with 
 location.puckBearing = PuckBearing.HEADING. No impact at all

See the attached file. We are moving from right to the left in the image

## Expected behavior
The location puck should have the same direction as the movement 

## Notes / preliminary analysis

I have followed the recommendation from the official tutorials, and I guess that the attached code is correct

## Additional links and references

![screen](https://github.com/user-attachments/assets/5f0b9860-9b60-4a19-bb91-96e45bfa7322)

**Comment by natiginfo** [comment]
Thanks for reporting the issue. We will take a look at it.

**Comment by pengdev** [comment]
Hi @arbonvata, I think you are missing `location.puckBearingEnabled = true` in your code snippet. 
In your case the puck bearing is not enabled at all, and please also note that once you are in `FollowPuckViewportState`, the camera bearing is driven by the viewport plugin(updated every frame), so the `setCamera` you pragmatically call will be overwritten by `FollowPuckViewportState` immediately. To be able to take over the bearing pragmatically while in `FollowPuckViewportState`, you will need to set `FollowPuckViewportStateOptions.Builder().bearing(null).build()`.

**Comment by arbonvata** [comment]
Thanks for the help. It works now
