### ISSUE TITLE
Compose MapboxMap SymbolLayer images in style

### ISSUE THREAD

**Issue by cholwell** [mapbox/mapbox-maps-android#2467]
## New Feature

I am using `@Composable MapBoxMap` with `SymbolLayer`. 

Is there a better way to load images to the style, to use in an expression for `iconImage` than the following:

```
 MapboxMap(
        modifier = Modifier.fillMaxSize()
        mapState = mapState,
        mapViewportState = mapViewportState,
        style = {
             //empty
        }
    ) {
        MapEffect(true) { mapView ->
            mapView.mapboxMap.loadStyle(
                style("mapbox://my-style") {
                    +image("ic_some_icon", someIcon)
                }
            )
        }
        SymbolLayer(
            sourceState = sourceState,
            iconImage = ImageValue(
                Expression.image {
                    get("icon")
                }
            )
        )
    }
```

## Why
This seems wrong but does work

**Comment by kiryldz** [comment]
@cholwell I guess [this](https://github.com/mapbox/mapbox-maps-android/blob/21bf717c3ea37403d492d7faad626ce1c536fe00/compose-app/src/main/java/com/mapbox/maps/compose/testapp/examples/style/StyleCompositionActivity.kt#L170-L175) is what you are looking for.
