### ISSUE TITLE
addStyleImportFromJSON doesn't work

### ISSUE THREAD

**Issue by SamYStudiO** [mapbox/mapbox-maps-android#2471]
## Environment

- Android OS version: any
- Devices affected: any
- Maps SDK Version: 11.5.1

## Observed behavior and steps to reproduce

I'm trying to add another style that return a simple transparent raster layer to be on top of a primary style using 
`addStyleImportFromJSON` but it has no effect, only main style is visible.

```
loadStyle(url) {
    val response = addStyleImportFromJSON("id", "style", null, null)
}
```
style json : 
```
{"version": 8,
  "sources": {
    "raster-tiles-pentes": {
      "type": "raster",
      "scheme": "xyz",
      "tiles": ["https://data.geopf.fr/wmts?Service=WMTS&Request=GetTile&Version=1.0.0&Layer=GEOGRAPHICALGRIDSYSTEMS.SLOPES.MOUNTAIN&Style=normal&Tilematrixset=PM&TileMatrix={z}&TileRow={y}&TileCol={x}&Format=image/png"],
    }
  },
  "layers": [
    {
      "id": "simple-tiles-pentes",
      "type": "raster",
      "source": "raster-tiles-pentes",
      "minzoom": 6,
      "maxzoom": 17,
      "paint": {
         "raster-opacity": 0.5
      }
    }
  ]
}
```
`response ` doesn't return any error looks everything is fine but imported style is not visible.

**Comment by kiryldz** [comment]
@SamYStudiO based on the info you provided second argument you provided is incorrect, it should be an actual JSON string while in your case it's `"style"`. However I also could assume that you have this correct and just put this like that in the issue description. In any case complete reproducible example will be really appreciated so that we can take a look.

**Comment by SamYStudiO** [comment]
Here is an example you need to set : 
- local.properties > MAPBOX_DOWNLOADS_TOKEN
- res/values/mapbox > mapbox_access_token

[MapboxImport.zip](https://github.com/user-attachments/files/16894244/MapboxImport.zip)

ps : Could you open back this issue https://github.com/mapbox/mapbox-maps-android/issues/2445 that is still happening a lot in my production app

**Comment by kiryldz** [comment]
@SamYStudiO I checked the code and it seems that your style import is simply not valid (something wrong with the `tiles` you provided from what I see). You can check it yourself if you actually will try to load your JSON not as a style import but with `map.loadStyle(yourStyleJSON)` and then in the logs you will see the error message.

However from our end it seems we should also look into an issue why does `addStyleImportFromJSON` does not return an error if the imported style definition is not valid, I'll check this with the needed team.
