### ISSUE TITLE
Library crash for Android 15

### ISSUE THREAD

**Issue by longquangpham90** [mapbox/mapbox-maps-android#2489]
## Environment

- Android OS version: Android 15
- Devices affected: Emulator Pixel 8A
- Maps SDK Version: v11.7.0

## Observed behavior and steps to reproduce

> MapboxOptions.accessToken = getString(R.string.mapbox_access_token)

<img width="1421" alt="Screenshot 2024-09-27 at 16 01 05" src="https://github.com/user-attachments/assets/c13a3626-53a2-4077-957c-563a6fc4f967">

For the Android 14. It's that work good
But Android 15, my application is crash
I can not setup work for android 15
Pls help me check
This is my example code
<img width="773" alt="Screenshot 2024-09-27 at 15 54 10" src="https://github.com/user-attachments/assets/d4a7806f-e570-4cce-a542-f4475665f323">

<img width="849" alt="Screenshot 2024-09-27 at 15 55 20" src="https://github.com/user-attachments/assets/b557ff82-c6e3-4bb4-9ade-afd36ba8afe4">

<img width="651" alt="Screenshot 2024-09-27 at 15 59 16" src="https://github.com/user-attachments/assets/7e00573d-c953-46ec-a397-d2a12c63670b">

## Expected behavior

No crash.

**Comment by Yelamanmyrzahanov** [comment]
> Okay I've update version SDK emulator it worked Thanks!

@longquangpham90 what version did you use?
