### ISSUE TITLE
Failed to download v11.9.0

### ISSUE THREAD

**Issue by vTechGIS** [mapbox/mapbox-maps-android#2551]
Hello, 
I get the error message on Android Studio:
Failed to resolve: com.mapbox.maps:android:11.9.0

Please fix it, many thanks.

**Comment by jush** [comment]
Please double check on your end.
It is resolving properly for us:
```
Download https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/maps/android/11.9.0/android-11.9.0.aar, took 807 ms
```
