### ISSUE TITLE
Getting "Image coordinates must be an array of four longitude latitude pairs" error when calling setCoordinates(LatLngQuad latLngQuad)

### ISSUE THREAD

**Issue by intra** [mapbox/mapbox-maps-android#302]
After update to mapbox version 9.6.1 we are getting **"Image coordinates must be an array of four longitude latitude pairs"** error  when calling setCoordinates(LatLngQuad latLngQuad) on ImageSource object.

 It looks like the problem might be in native code bellow:.

    if (!isArray(*coordinatesValue) || arrayLength(*coordinatesValue) != 4) {
        error.message = "Image coordinates must be an array of four longitude latitude pairs";
        return nullopt;
    }

**Comment by hungtrn75** [comment]
I have the same issue

**Comment by kiryldz** [comment]
This repo is for Maps v10 / v11 while this issue is for Maps v9 which is no longer supported.
