### ISSUE TITLE
Successive flyTo/ easeTo cause abrupt animation cancellation

### ISSUE THREAD

**Issue by florianPOLARSTEPS** [mapbox/mapbox-maps-android#318]
I am currently trying out Mapbox v10 and came across an issue when trying to do multiple flyTo/easeTo animations in a short period of time.

My usecase: User scrolls through a list of items that correspond to markers on the map. When an item is focused in the list, the corresponding marker will be centered on the map. (with an animation)

In **v9**, there seems to be logic in place which made the camera animation completely smooth when calling `animateTo` successively with different targets.

In **v10**, I noticed that each call to `flyTo/easeTo` completely cancels the currently running animation and starts with the new one. This makes the UI extremely jumpy of course. I understand that this probably comes from the flexibility to use Animators, but it would still be nice to have at least some utility in place that can bring back the old functionality.

**Comment by kiryldz** [comment]
Hello @florianPOLARSTEPS, old functionality was having a lot of glitches and no flexibility as transitions were happening in core.
New animation system provides more precise control for the users.

In your case if animation is already running guess new one should not get started. You could easily check current state of animator engine if you add https://github.com/mapbox/mapbox-maps-android/blob/5e45f3337465cfe8eb148cf4426182bc6ccbe66a/sdk-base/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsPlugin.kt#L307 (in your case you may check `CameraAnimatorType.CENTER` type).
