### ISSUE TITLE
Extension functions for default parameters

### ISSUE THREAD

**Issue by dudeuter** [mapbox/mapbox-maps-android#329]
### Move default parameters from MapInitOptions to extension functions on their respective options builder class.

While upgrading to beta 18 I ran into the MapOptions default values not being ideal for displaying the map. Mostly `pixelRatio` defaulting to `1` when my emulated device's screen density was `2`.

```kt
// mapOptions defaults
val mapOptions = MapOptions.Builder()
        .constrainMode(ConstrainMode.HEIGHT_ONLY)
//      .pixelRatio(1)  default value
        .glyphsRasterizationOptions(
                GlyphsRasterizationOptions.Builder()
                        .rasterizationMode(GlyphsRasterizationMode.IDEOGRAPHS_RASTERIZED_LOCALLY)
                        .build()
        )
        .build()

// defaults for device
val mapOptionsDevice = MapInitOptions.getDefaultMapOptions(applicationContext)

```

After poking around I found the default values used by the mapView are on `MapInitOptions#getDefaultMapOptions` and only return an instance of the `MapOptions` and not a builder. This means that if you do want to change a single value from these defaults, you would basically have to copy the implementation from `MapInitOptions`, as there's from toBuilder constructor for the builder.

It seems like a majority of the use cases that you would want to stray beyond the defaults and in the case that you do want to make a change, you would likely want to use the other default values.

So it might be easier to have something like this:

```kt
// MapInitOptions.kt

    /**
     * Get a default [MapOptions.Builder] with reasterization mode [GlyphsRasterizationMode#ALL_GLYPHS_RASTERIZED_LOCALLY]
     * @property context the context of the application.
     * @return [MapOptions.Builder]
     */
    fun MapOptions.Builder.applyDefaultParams(context: Context): MapOptions.Builder = also {
      glyphsRasterizationOptions(GlyphsRasterizationOptions.Builder()
        .rasterizationMode(GlyphsRasterizationMode.IDEOGRAPHS_RASTERIZED_LOCALLY)
        .fontFamily(FontUtils.extractValidFont(null))
        .build())
      pixelRatio(context.resources.displayMetrics.density)
      constrainMode(ConstrainMode.HEIGHT_ONLY)
      contextMode(ContextMode.UNIQUE)
      orientation(NorthOrientation.UPWARDS)
      viewportMode(ViewportMode.DEFAULT)
      crossSourceCollisions(true)
    }

    /**
     * Get a default [MapOptions] with reasterization mode [GlyphsRasterizationMode#ALL_GLYPHS_RASTERIZED_LOCALLY]
     * @property context the context of the application.
     * @return [MapOptions]
     */
    fun getDefaultMapOptions(context: Context): MapOptions = MapOptions.Builder()
      .applyDefaultParams(context)
      .build()
```

## Why

- improve discoverability
- reduce how tightly coupled these defaults are to the MapInitOptions

**Comment by pengdev** [comment]
Thanks @dudeuter for the suggestion, these extension functions looks clean, I will open a PR to also add the similar extension functions to ResourceOptions.
