### ISSUE TITLE
Style.getStyleImage returns null even if I added it before with Style.addImage

### ISSUE THREAD

**Issue by VincentJoshuaET** [mapbox/mapbox-maps-android#344]
Any idea why this happens? I have to readd the image before using it in a symbol layer.

**Comment by tobrun** [comment]
addImage returns an Expected object that either contains None (success) or a String error message. Could you check if an error occurred? are you able to use the image in your symbol layer without issue?

**Comment by VincentJoshuaET** [comment]
I add images initially using the MapboxMap.loadStyle block, with `+image("name,  block: ImageExtensionImpl.Builder.() -> Unit). This doesn't return an expected object.

**Comment by tobrun** [comment]
We haven't been able to reproduce on our end, if you have any more input we would love to hear it. Closing as stale
