### ISSUE TITLE
How to make the secret key Gradle work with GitHub Actions

### ISSUE THREAD

**Issue by PedroBarbosaPT** [mapbox/mapbox-maps-android#367]
I have my project on GitHub with actions to build automatically when I push the project, but the Mapbox always fails because of the secret key being missing, so the build command always returns " (...) Could not GET 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/mapboxsdk/mapbox-android-sdk/9.5.0/mapbox-android-sdk-9.5.0.pom'. Received status code 403 from server: Forbidden" 

Is there a way around this?

**Comment by knov** [comment]
Have you tried [setting up a .netrc file with Github actions](https://github.com/marketplace/actions/setup-netrc)?

**Comment by tobrun** [comment]
Github actions has the concept of secrets, this is where you woudl store the SDK_REGISTRY_TOKEN value
