### ISSUE TITLE
Do not apply geojson async setting data in specific scenario

### ISSUE THREAD

**Issue by kiryldz** [mapbox/mapbox-maps-android#381]
## Environment

- Android OS version: any
- Devices affected: any
- Maps SDK Version: v10.0.0-beta.21

## Observed behavior and steps to reproduce

As stated [here](https://github.com/mapbox/mapbox-maps-android/pull/380#issuecomment-851997325):

Imagine we're setting some data to `GeoJsonSource` using `feature`, `featureCollection` or `geometry`.
Issue that I'm noticing is wrt the cancellation policy - let's imagine these 3 calls made one by one:
1. U1 async
2. U2 sync
3. U3 async

The cancellation policy is solely based on the `ignoreParsedGeoJson` flag, which means that `U2` will set it, but `U3` will immediately unset it. This will result in this order of updates being rendered:
1. U2
2. U1
3. U3

Since there was a sync update (`U2`) scheduled _after_ an async update (`U1`), that async update should in all cases be dismissed and never rendered, but in the current setup, I see this risk of it appearing anyway.

## Expected behavior

Result should be:
1. U2
2. U3

**Comment by tobrun** [comment]
landed

**Comment by kiryldz** [comment]
@tobrun exactly that did not land 😄

**Comment by tobrun** [comment]
![giphy (1)](https://user-images.githubusercontent.com/2151639/124832428-f4be8f00-df7c-11eb-974f-17d28d8f87ec.gif)
