### ISSUE TITLE
Flag GesturesPlugin.disableRotateWhenScaling gets ignored

### ISSUE THREAD

**Issue by ToufiPF** [mapbox/mapbox-maps-android#386]
Hello!
## Environment

- Android OS version: API 24, 27, 29, 30 at least
- Devices affected: all devices (emulator and real devices)
- Maps SDK Version: com.mapbox.maps:android:10.0.0-beta.20

## Observed behavior and steps to reproduce
When setting the flag `disableRotateWhenScaling` of the GesturePlugin to false, it's still not possible to zoom and rotate at the same time.
Steps to reproduce:
- Create a simple activity that contains a MapboxView, grant all permissions beforehand. Then set the flags of the GesturePlugin:
``` 
mapboxView.gestures.apply {
    disableRotateWhenScaling = false
    increaseScaleThresholdWhenRotating = false
    increaseRotateThresholdWhenScaling = false
}
```

## Expected behavior
User can rotate and zoom at the same time (without lifting their fingers)

**Comment by tobrun** [comment]
@kiryldz haven't looked to deeply but it do see both rotate as scale hooking into animation API but one of the two is not being applied. By hunch would be that we can't have concurrent `easeToImmediately` invocations.

**Comment by kiryldz** [comment]
> @kiryldz haven't looked to deeply but it do see both rotate as scale hooking into animation API but one of the two is not being applied. By hunch would be that we can't have concurrent `easeToImmediately` invocations.

I guess we could (e.g. we do it when applying anchor + zoom) but it does not work in this particular case. Need to investigate.

**Comment by pengdev** [comment]
We have removed `disableRotateWhenScaling` flag in https://github.com/mapbox/mapbox-maps-android/pull/672, as we don't support running rotation and scaling gestures at the same time in our current design, we will consider adding support for it in next iterations. Closing for now.
