### ISSUE TITLE
lineDashArray does not support Expressions

### ISSUE THREAD

**Issue by SamuelBrucksch** [mapbox/mapbox-maps-android#400]
Current mapbox version: 10-beta19

Hi,

i get following error:
```
2021-06-07 15:55:30.494 28706-28706/? W/System.err: java.lang.RuntimeException: Add layer failed: Failed to set `line-dasharray` property for `route-layer` layer. Error: data expressions not supported
```

layer:
```
lineLayer("a", "b"){
                        lineDasharray(match {
                            get {
                                literal("isValid")
                            }
                            stop {
                                literal("false")
                                literal(listOf(2.0, 2.0))
                            }
                            literal(listOf(1.0, 0.0))
                        })
}
```

It seems this was just recently implemented in mapbox-gl-js:
https://github.com/mapbox/mapbox-gl-js/pull/10591

However here it does not seem to work yet.

Interface has following definition:
```
  /**
   * Set the LineDasharray property
   *
   * @param lineDasharray value of lineDasharray
   */
  fun lineDasharray(lineDasharray: List<Double>): LineLayer

  /**
   * Set the LineDasharray property
   *
   * @param lineDasharray value of lineDasharray as Expression
   */
  fun lineDasharray(lineDasharray: Expression): LineLayer
```
If it does not work with expressions, this should not be offered.

Is there any workaround available for this?

**Comment by SamuelBrucksch** [comment]
@tobrun i would consider part of this a bug, the interfaces offer setting expressions, but then a runtime exception comes up.

Can you provide an estimate, when this will be available? I really need this, and if this will not be available for a while, i have to find a workaround.

**Comment by tobrun** [comment]
It's marked as an unsupported to be used as a data driven property in the style-spec:

![image](https://user-images.githubusercontent.com/2151639/121178482-cf940f00-c85e-11eb-9af6-22edf5face87.png)

With the current expression API, you can use expression to set it as a constant value.
This is work-as-designed for us and is a feature request to align more with gl-js.

> Can you provide an estimate

No estimation atm but I did flag it upstream as a missing API

**Comment by SamuelBrucksch** [comment]
Thanks for your answer. Ok I understand.

> With the current expression API, you can use expression to set it as a constant value.

Can you please explain that a little more in detail what you mean by that? Would that help me in marking some LineStrings to be dashed and some others not?

**Comment by akirmse** [comment]
Does "basic functionality" including setting the property globally on the annotation manager?  I tried
```
        mPolylineAnnotationManager = annotationApi.createPolylineAnnotationManager(mMapView)
        mPolylineAnnotationManager.lineDasharray = listOf(100.0, 100.0)
```

but it has no effect.  Any polylines added to this manager are solid, not dashed.

If there's a way to make this work, can you please point me to an example?

**Comment by Chaoba** [comment]
> Does "basic functionality" including setting the property globally on the annotation manager?
Yes, annotation manager is a plugin based on maps sdk, can't implement features that are not supported by maps sdk.

**Comment by akirmse** [comment]
Can this be unarchived?  I'd still like to know how to get dashed lines on Android.

**Comment by yunikkk** [comment]
@akirmse I've checked similar expression with `lineDasharray` - can see dashed lines, works fine on my side. Please provide more details on your setup

**Comment by akirmse** [comment]
Here's what I'm doing: 

```
        mPolylineAnnotationManager = annotationApi.createPolylineAnnotationManager()
        mPolylineAnnotationManager.lineDasharray = listOf(100.0, 100.0)

        val mapboxOptions = toMapboxPolylineOptions(options)
        return MapboxPolyline(mPolylineAnnotationManager.create(mapboxOptions))
```

When I do this, the polyline is still solid.  I also don't see any way to specify dashes on a PolylineAnnotationsOptions object.

It's still listed as "not yet supported" on Android here:
https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/

@yunikkk Can you show the code you have that draws dashed lines correctly?

**Comment by yunikkk** [comment]
> @yunikkk Can you show the code you have that draws dashed lines correctly?

Yes you can try the [PolylineAnnotationsActivity](https://github.com/mapbox/mapbox-maps-android/blob/main/app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/PolylineAnnotationActivity.kt#L40) in the test app,
```
      polylineAnnotationManager = annotationPlugin.createPolylineAnnotationManager(
        annotationConfig = AnnotationConfig(PITCH_OUTLINE, LAYER_ID, SOURCE_ID)
      ).apply {
        lineDasharray = listOf(100.0, 100.0)
```
works fine and results in dashed lines.

> It's still listed as "not yet supported" on Android here: https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/

Right, so data-driven styling is not supported, but using constant values for lineDasharray is as @tobrun suggested
