### ISSUE TITLE
App crashes when changing camera tracking mode during animation

### ISSUE THREAD

**Issue by VitaminPSG** [mapbox/mapbox-maps-android#409]
## Environment

- Android OS version: **23**
- Maps SDK Version: **v10.0.0-beta.19**

## Observed behavior and steps to reproduce

After migrating to the Navigation SDK 2.0.0-beta, an application crashed when changing camera modes

- Change camera mode to OVERVIEW
- During animation change camera mode to TRACKING

### Animations log

> 06-09 17:34:43.938 observeCameraAnimations() called with: cameraAnimation = CameraAnimation(cameraUpdate=[center: , padding: [top: 324.0, left: 0.0, bottom: 166.0, right: 0.0], anchor: , zoom: 15.9, bearing: , pitch: 0.0], durationMillis=750, trackingMode=TRACKING))
> 06-09 17:35:12.901 observeCameraAnimations() called with: cameraAnimation = CameraAnimation(cameraUpdate=[center: Point{type=Point, bbox=null, coordinates=[-122.08107882014252, 37.39104258135701]}, padding: [top: 30.0, left: 430.0, bottom: 222.0, right: 30.0], anchor: , zoom: 14.97972522830253, bearing: -0.0, pitch: 0.0], durationMillis=750, trackingMode=OVERVIEW)
> 06-09 17:35:14.368 observeCameraAnimations() called with: cameraAnimation = CameraAnimation(cameraUpdate=[center: , padding: [top: 324.0, left: 0.0, bottom: 166.0, right: 0.0], anchor: , zoom: 15.9, bearing: , pitch: 0.0], durationMillis=750, trackingMode=TRACKING)

### Crash log

> 
> E/AndroidRuntime: Error reporting crash
>     android.os.TransactionTooLargeException: data parcel size 27895920 bytes
>         at android.os.BinderProxy.transactNative(Native Method)
>         at android.os.BinderProxy.transact(Binder.java:503)
>         at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:4425)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at leakcanary.ServiceWatcher$install$4$2.invoke(ServiceWatcher.kt:85)
>         at java.lang.reflect.Proxy.invoke(Proxy.java:393)
>         at $Proxy1.handleApplicationCrash(Unknown Source)
>         at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:90)
>         at com.mapbox.android.core.crashreporter.MapboxUncaughtExceptionHanlder.uncaughtException(MapboxUncaughtExceptionHanlder.java:102)
>         at com.google.firebase.crashlytics.internal.common.CrashlyticsUncaughtExceptionHandler.uncaughtException(CrashlyticsUncaughtExceptionHandler.java:63)
>         at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
>         at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
>         at kotlinx.coroutines.CoroutineExceptionHandlerImplKt.handleCoroutineExceptionImpl(CoroutineExceptionHandlerImpl.kt:39)
>         at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleCoroutineException(CoroutineExceptionHandler.kt:33)
>         at kotlinx.coroutines.StandaloneCoroutine.handleJobException(Builders.common.kt:193)
>         at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:229)
>         at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:906)
>         at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:863)
>         at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:828)
>         at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:111)
>         at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
>         at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:142)
>         at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
>         at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
>         at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
>         at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:69)
>         at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:357)
>         at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
>         at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:27)
>         at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
>         at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:158)
>         at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
>         at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
>         at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:49)
>         at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
>         at com.mapbox.nav.gm.search.presentation.category.CategorySearchViewModel.onCancelClicked(CategorySearchViewModel.kt:169)
>         at com.mapbox.nav.gm.map.presentation.ui.MapFragment$setupCategorySearch$$inlined$apply$lambda$1.onClick(MapFragment.kt:718)
>         at android.view.View.performClick(View.java:5198)
>         at android.view.View$PerformClick.run(View.java:21147)
>         at android.os.Handler.handleCallback(Handler.java:739)
>         at android.os.Handler.dispatchMessage(Handler.java:95)
>         at android.os.Looper.loop(Looper.java:148)
>         at android.app.ActivityThread.main(ActivityThread.java:5417)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

## Additional links and references

https://user-images.githubusercontent.com/5839897/121377809-53c3c080-c94b-11eb-9732-3e084c0d12d5.mp4

**Comment by LukasPaczos** [comment]
I can't see right away for this being related to Nav or Maps SDK. The only similar issue I know of would be https://github.com/mapbox/mapbox-navigation-android/issues/1188 but the stack trace would point to the notification impl. You might want to take a look at what coroutines are started in `CategorySearchViewModel.onCancelClicked`.

**Comment by LukasPaczos** [comment]
Capturing from https://github.com/mapbox/mapbox-navigation-android/pull/4575#issuecomment-874652245, this is the same as https://github.com/mapbox/mapbox-navigation-android/issues/4453. Closing here, the issue will be resolved in https://github.com/mapbox/mapbox-navigation-android/pull/4575.
