### ISSUE TITLE
How to load very large point on the map?

### ISSUE THREAD

**Issue by itchaosfun** [mapbox/mapbox-maps-android#412]
We have very large point  that saved in a local file, we try load it on the map, but the map load very slow and few minutes later, app will be crash.

**Comment by knov** [comment]
@itchaosfun can you provide sample code of what you are trying to achieve and crashlog for the associated crash?

**Comment by tobrun** [comment]
Instead of loading data through a file (eg. geojson). You should load this data on mapbox studio which allows you to tile the data. When you load a map, only a part of your data is loaded and should be able to get a more performant map.
