### ISSUE TITLE
How to use re routing feature of mapBoxNavActivity

### ISSUE THREAD

**Issue by developergirl53** [mapbox/mapbox-maps-android#413]
In MapBoxNavigationActivity I want to implement re- routing feature in a way that by adding the waypoint I get the new route while doing navigation on map dynamically.

When the waypoint list change again the re-routing should happen.

Please suggest some

**Comment by tobrun** [comment]
This repository is for mapbox maps SDK. For navigation, see https://github.com/mapbox/mapbox-navigation-android.

**Comment by developergirl53** [comment]
hi tobrun
 I require re- routing while  on onNavigationReady() the link whihc u hv shared I have read all but only no soultion.
And I required the changes while Navigating from from one waypoint to another waypoint on runtime dynamically.
