### ISSUE TITLE
Java-kotlin interoperability

### ISSUE THREAD

**Issue by knov** [mapbox/mapbox-maps-android#416]
This issue tracks updating Mapbox Maps SDK for Android to improve the Kotlin API for consumption through the Java programming language. While Kotlin code is compiled to be JVM compatible and Java and Kotlin are interoperable, the signatures the Kotlin compiler generates aren’t as developer friendly when consumed from Java. However, as documented on https://kotlinlang.org/docs/java-to-kotlin-interop.html, there are a couple of constructs available to improve the API signatures.

While we have made some of these changes already in https://github.com/mapbox/mapbox-maps-android/pull/374, specifically to improve our Style Kotlin DSL, we haven’t fully covered the public API. This issue will be used to track progress on this task, which will require breaking changes for developers using Java. 

cc @mapbox/maps-android

**Comment by tobrun** [comment]
I think we are good for now. We can follow up with more specific issues later
