### ISSUE TITLE
Annotations Feature Request

### ISSUE THREAD

**Issue by knov** [mapbox/mapbox-maps-android#418]
Annotations are text, icon or shape graphics on a map that display information useful to users, such as the names of streets, icons for POI data or lines representing a route. Annotations can add a more specific overlay of information to clarify the map to the user.

Currently the SDK supports an annotation API similar to the v9 https://github.com/mapbox/mapbox-plugins-android/. It provides a high level object oriented API that uses style layers and sources under the hood. We expose these APIs to make them more developer friendly and allow developers to write code that treats annotations on a per-object basis. 

To have full parity with the v9 annotations API, we need to support two additional features: the marker view and the infowindow API. A markerview (aka annotation view) synchronises the screen coordinate of an iOS/Android SDK view to a geographic coordinate on the map. A infowindow (aka a callout) displays content (usually text or images) in a popup window above the map, anchored to a geometry. 

iOS equivalent: https://github.com/mapbox/mapbox-maps-ios/issues/464

**Comment by Fritoo** [comment]
@knov +1 
Upvoting this feature request:
>A infowindow (aka a callout) displays content (usually text or images) in a popup window above the map, anchored to a geometry.

Could really use this in the Android sdk ( I'm using `10.0.0-rc.4` )

**Comment by VincentJoshuaET** [comment]
I am on the process of creating an Android app from an iOS app and this isn't possible with v10. I tried v9 with the MarkerView plugin but zooming in and out of the map will misplace the MarkerViews.

I saw there is a guide to create "info windows" but that just creates a bitmap from the view to show it as a symbol layer, but that means we can't have multiple click areas in a window e.g. I want to add a check box to the info window.

I hope this gets added.

**Comment by knov** [comment]
@VincentJoshuaET @Fritoo thank you for adding your support here. We understand the importance of this functionality and are evaluating the best solution to bring forward in v10. We hope to provide more details soon.

**Comment by kiryldz** [comment]
API landed in https://github.com/mapbox/mapbox-maps-android/releases/tag/android-v10.2.0-beta.1, please check it out. Also noting that in future more high-level API should arrive to incorporate view annotations to annotation plugin. Showcase example that should be actually replacing MarkerView from v9 could be found in this [activity](https://github.com/mapbox/mapbox-maps-android/blob/main/app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/ViewAnnotationShowcaseActivity.kt).
