### ISSUE TITLE
Duplicate class com.mapbox.mapboxsdk.text.LocalGlyphRasterizer

### ISSUE THREAD

**Issue by KayHung** [mapbox/mapbox-maps-android#419]
I'm using the Mapbox Navigation SDK and Traffic plugin
my gradle file
```
implementation 'com.mapbox.navigation:android:2.0.0-beta.8'
implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-traffic-v9:0.10.0'
```

When I build then get some error

> Duplicate class com.mapbox.mapboxsdk.text.LocalGlyphRasterizer found in modules jetified-android-core-10.0.0-beta.20-runtime (com.mapbox.maps:android-core:10.0.0-beta.20) and jetified-mapbox-android-sdk-9.0.0-runtime (com.mapbox.mapboxsdk:mapbox-android-sdk:9.0.0)

**Comment by LukasPaczos** [comment]
Hey @KayHung, unfortunately, the traffic plugin v9 is not compatible with Maps SDK v10 that's coming from the Nav SDK version that you're using.

cc @mapbox/maps-android

**Comment by KayHung** [comment]
@LukasPaczos How can I show traffic when use Maps SDK v10?

**Comment by tobrun** [comment]
You can either use a style that supports traffic layers out of then box or add them add runtime (see source code [here](https://github.com/mapbox/mapbox-plugins-android/blob/main/plugin-traffic/src/main/java/com/mapbox/mapboxsdk/plugins/traffic/TrafficPlugin.java).)

**Comment by KayHung** [comment]
@tobrun 
Is there any example about this case?
`You can either use a style that supports traffic layers out of then box `
