### ISSUE TITLE
mapSurface="texture_view" memory leak ?

### ISSUE THREAD

**Issue by Hospes** [mapbox/mapbox-maps-android#420]
## Environment

- Android OS version: 10
- Devices affected: One Plus 6
- Maps SDK Version: v10.0.0-rc.1

## Observed behavior and steps to reproduce
Place `MapView` into layout. Set layout for activity. Open and close activity multiple times.
Native and Graphics memory are always growing.
All lifecycle methods are setted correctly: `onStart` `onStop` `onLowMemory` `onDestroy`
Below I've attached images with android studio profiler where you can see that `Native` momoery grown to 0.4Gb and `Graphics` memory grown to 2.3Gb but at the beginning it was `0.07`Gb and `0.05`Gb accordingly.

## Expected behavior
Memory should be free after activity is closed or later by GC

## Notes / preliminary analysis
This happens only with `mapSurface="texture_view"` if view set to `mapSurface="surface_view"` - memory is cleared properly.

## Additional links and references
![Screenshot 2021-06-12 160507](https://user-images.githubusercontent.com/3521464/121777013-9d551b00-cb98-11eb-8419-cce726ca9c3f.png)
![Screenshot 2021-06-12 160535](https://user-images.githubusercontent.com/3521464/121777014-9dedb180-cb98-11eb-8097-b8ea68c6351c.png)
![Screenshot 2021-06-12 160601](https://user-images.githubusercontent.com/3521464/121777015-9e864800-cb98-11eb-9fdc-9892b8f8ac7a.png)

If I should provide more info just let me know !

**Comment by tobrun** [comment]
Thank you for the report @Hospes and the detailed write-up.
Was able to quantify that this is an issue with texture view:

![Screenshot from 2021-06-15 10-19-08](https://user-images.githubusercontent.com/2151639/122018825-83e3e700-cdc3-11eb-9596-3c1b89e0c93b.png)

While the normal surfaceview approach works as expected:

![image](https://user-images.githubusercontent.com/2151639/122018798-7af31580-cdc3-11eb-808a-249ab46420eb.png)


@kiryldz could you look into this with more detailed :eyes: ?
