### ISSUE TITLE
Documentation which packages needs to be downloaded from private Mapbox maven repository

### ISSUE THREAD

**Issue by audkar** [mapbox/mapbox-maps-android#424]
## New Feature
Provide a list/regex of private MapBox artifacts required from `https://api.mapbox.com/downloads/v2/releases/maven`

## Why
We restrict which artifact are being downloaded from private maven repositories. Seems that Mapbox has a lot of packages groups and modules scattered between mavenCentral and private repo. Please provide filter which are necessary for Mapbox.

expected `settings.gradle.kts` config:
```kotlin
dependencyResolutionManagement {
  repositories {
    mavenCentral()
    // <...>
    exclusiveContent {
      forRepository {
        val mapboxToken: String by settings
        maven {
          authentication {
            create<BasicAuthentication>("basic")
          }
          setUrl("https://api.mapbox.com/downloads/v2/releases/maven")
          credentials {
            username = "mapbox"
            password = mapboxToken
          }
        }
      }
      filter {
        includeGroup("com.mapbox.maps")
        // <---------------- What goes here?
      }
    }
  }
}

```

**Comment by tobrun** [comment]
@audkar, thank you for reaching out and using our products. We have an internal feature request to allows navigating through  our maven, similarly to the index.html files from maven central which should make it easier to create your filter.

This said, I don't think it's on us to provide or maintain a filter for your use-case. You are trying to achieve something that is I don't perceive to be the normal way of working. You can get which dependencies are pulled in from which repository by including `-i` in your gradle execution. To get a list of all underlying dependencies you can run something as `./gradlew app_module_name:dependencies`.
