### ISSUE TITLE
MapboxOptions#setDefaultResourceOptions not respected for map inflation

### ISSUE THREAD

**Issue by pengdev** [mapbox/mapbox-maps-android#43]
Calling `MapboxOptions#setDefaultResourceOptions` and afterward inflating the map results in the `MapboxMapOptions` still recreating the resources from scratch (and for example using token from XML) instead of taking the available default options.

Granted that I can reproduce the issue, but that logic doesn't seem to have fundamentally changed. I think it should rather be something like:
```
internalResourceOptions = if (MapboxOptions.isInitialized()) {
        MapboxOptions.getDefaultResourceOptions(context)
    } else {
        ResourcesAttributeParser.parseResourcesOptions(context, typedArray)
    }
```

**Comment by Chaoba** [comment]
Fixed in https://github.com/mapbox/mapbox-maps-android/pull/77
