### ISSUE TITLE
Deadlock on main thread (app not responding) when MapView is shown and onStart not called

### ISSUE THREAD

**Issue by e-hartig** [mapbox/mapbox-maps-android#431]
## Environment

- Android OS version: Any
- Devices affected: Any
- Maps SDK Version: 10.0.0-rc.1

## Observed behavior and steps to reproduce

When an application shows a MapView, then calls mapView.onStop(), then shows the MapView again without calling onStart(), a deadlock occurs on the main thread that freezes the entire application.

This is not proper use of the Mapbox SDK, but it is unexpected behavior.  Not all MapViews are directly tied to Activities or Fragments which can easily call onStart() or onStop() on lifecycle events.  We have some mini-maps that show deep in a view hierarchy which had to call onStart() and onStop() based on different triggers, which led to one case where onStart() would not be called on a resume and the app would become unresponsive (ANR).

## Expected behavior

If onStart() is not called, I'd expect the MapView to be in a bad state somehow, but not the entire application.

## Notes / preliminary analysis

The line `createCondition.await()` in [MapboxRenderThread.kt here ](https://github.com/mapbox/mapbox-maps-android/blob/5e193836ada33a36252cfec2338cb4652e4bbafc/sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderThread.kt#L282) awaits forever in this scenario.

## Additional links and references

Video of the problem:
https://user-images.githubusercontent.com/71792506/122276441-c89a7b80-ceb2-11eb-8699-b9aa579d1165.mov

This can be easily reproduced by running this application and briefly backgrounding it, then bringing it back to foreground:

MainActivity.kt
```
package com.example.mapboxsample

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.widget.Button
import android.widget.Toast
import com.mapbox.maps.MapView
import com.mapbox.maps.Style

class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        val mapView = findViewById<MapView>(R.id.mapView)
        // Calling mapView.onStart here instead of in activity.onStart() causes
        // mapView.onStart to not be called when resuming, triggering deadlock
        mapView?.onStart()
        mapView?.getMapboxMap()?.loadStyleUri(Style.MAPBOX_STREETS)

        val btn = findViewById<Button>(R.id.responsive_button)
        btn?.setOnClickListener { Toast.makeText(this, "App still responsive", Toast.LENGTH_SHORT).show() }
    }

    override fun onStop() {
        super.onStop()
        val mapView = findViewById<MapView>(R.id.mapView)
        mapView?.onStop()
    }
}
```

activity_main.xml:
```
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".MainActivity">

    <com.mapbox.maps.MapView
        xmlns:mapbox="http://schemas.android.com/apk/res-auto"
        android:id="@+id/mapView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        mapbox:mapbox_cameraTargetLat="40"
        mapbox:mapbox_cameraTargetLng="-104"
        mapbox:mapbox_cameraZoom="9.0"
        />

    <Button
        android:id="@+id/responsive_button"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        android:layout_alignParentEnd="true"
        android:layout_margin="16dp"
        android:text="Still responsive?"/>
</RelativeLayout>
```

Pausing the app while it is deadlocked gives this stack trace for the main thread (in 10.0.0-rc.1):
```
park:-1, Unsafe (sun.misc)
park:190, LockSupport (java.util.concurrent.locks)
await:2067, AbstractQueuedSynchronizer$ConditionObject (java.util.concurrent.locks)
onSurfaceCreated:279, MapboxRenderThread (com.mapbox.maps.renderer)
surfaceChanged:24, MapboxSurfaceRenderer (com.mapbox.maps.renderer)
surfaceChanged:23, MapboxSurfaceHolderRenderer (com.mapbox.maps.renderer)
updateSurface:1165, SurfaceView (android.view)
setWindowStopped:278, SurfaceView (android.view)
surfaceCreated:1644, SurfaceView (android.view)
notifySurfaceCreated:1751, ViewRootImpl (android.view)
performTraversals:2716, ViewRootImpl (android.view)
doTraversal:1952, ViewRootImpl (android.view)
run:8171, ViewRootImpl$TraversalRunnable (android.view)
run:972, Choreographer$CallbackRecord (android.view)
doCallbacks:796, Choreographer (android.view)
doFrame:731, Choreographer (android.view)
run:957, Choreographer$FrameDisplayEventReceiver (android.view)
handleCallback:938, Handler (android.os)
dispatchMessage:99, Handler (android.os)
loop:223, Looper (android.os)
main:7656, ActivityThread (android.app)
invoke:-1, Method (java.lang.reflect)
run:592, RuntimeInit$MethodAndArgsCaller (com.android.internal.os)
main:947, ZygoteInit (com.android.internal.os)
```

**Comment by e-hartig** [comment]
@knov This issue is a bit more serious than I previously thought. With an app that shows a MapView on its initial screen, if the user turns off the device screen or otherwise backgrounds the app while the app is starting up but before the MapView is drawn, it will freeze.  This reproduces on Android emulators and Android devices below API27 but it may happen on a newer device if it's slow enough.

The app will also become unresponsive if it follows these completely normal steps to reproduce on an Android emulator of API23 - API27, though I cannot reproduce the issue on a real device:
1. Start app that shows a map, onStart is called
2. Tap power button to turn off screen, onStop is called
3. Tap power button to turn screen back on - App is now frozen

**Comment by Chaoba** [comment]
@e-hartig Can you verify if the issue still exists with rc.5? We have a lifecycle plugin to handle these lifecycle events.

**Comment by e-hartig** [comment]
@Chaoba After updating to rc5 and removing the lifecycle-related code in my test app, I cannot reproduce the issue on a real device.  One issue does persist, though: On an x86 emulator using API26 or API27, though, the app still does freeze/ANR every time if you tap the power button to turn off the emulated screen and then turn it back on.

**Comment by Chaoba** [comment]
@e-hartig On emulator with API26 and 27, onStart method of the Activity is not called after the screen is turned on. Guess this is a bug in the emulator. 
It works well on emulator with API 30.

**Comment by e-hartig** [comment]
@Chaoba I believe that onStart not being called is actually a symptom of the deadlock.  Apps that don't show MapViews do call onStart after the screen is turned on.

**Comment by Chaoba** [comment]
After some research, the root cause for this is because after press the power button to turn on the screen on the emulator with API26/27, `onSurfaceCreated` event would be fired before `onStart` event, so the main thread would be blocked inside of sdk. 
IMO, it's a bug in the emulator.

**Comment by e-hartig** [comment]
OK, feel free to close.  I can open a new issue if I ever see this repro on a real device.
