### ISSUE TITLE
Annotation updates are being dropped

### ISSUE THREAD

**Issue by cramptonism** [mapbox/mapbox-maps-android#433]
## Environment

- Android OS version: API 25 through API 31 (note: I tried to test on API 23 and I got a SIGABRT with some permissions issue on the sample app)
- Devices affected: Tested Pixel 5 and Android Emulator (Pixel 4 API 25)
- Maps SDK Version: 33f4643e65db1a655b9908755b62b94e98e811e8 of sample app, beta21 on our app. This _does not_ repro on beta20.

## Observed behavior and steps to reproduce

"Linked" annotations updated during a very fast drag do not have all updates applied. I say linked because I have widgets in my app that are built from multiple annotations, and dragging one will affect the others.

## Expected behavior

All calls to `update` are respected and applied. Final state of the 3 annotations in my example should be the same point.

## Notes / preliminary analysis

I've verified all of the expected `.update(` calls are executed, but the annotations do not reflect the final state. In the above example the larger circle and the line are updated in `onAnnotationDrag` and end up in 3 different places. I will try to dig more into the SDK to verify the update calls make it to native but beyond that I can't do much more digging.

## Additional links and references

https://user-images.githubusercontent.com/13057523/122317999-42daf800-ced3-11eb-9bbc-36c6fbbc0e4a.mp4

Example CircleAnnotationActivity.kt code, applied to 33f4643e65db1a655b9908755b62b94e98e811e8
```
package com.mapbox.maps.testapp.examples.annotation

import android.graphics.Color
import android.os.Bundle
import androidx.appcompat.app.AppCompatActivity
import com.mapbox.geojson.Point
import com.mapbox.maps.plugin.annotation.Annotation
import com.mapbox.maps.plugin.annotation.AnnotationPlugin
import com.mapbox.maps.plugin.annotation.annotations
import com.mapbox.maps.plugin.annotation.generated.*
import com.mapbox.maps.testapp.R
import kotlinx.android.synthetic.main.activity_add_marker_symbol.mapView
import kotlinx.android.synthetic.main.activity_annotation.*
import java.util.*

/**
 * Example showing how to add Circle annotations
 */
class CircleAnnotationActivity : AppCompatActivity() {
  private val pairMap = mutableMapOf<CircleAnnotation, CircleAnnotation>()
  private val polylineMap = mutableMapOf<CircleAnnotation, PolylineAnnotation>()
  private val random = Random()
  private var circleManager: CircleAnnotationManager? = null
  private var polylineManager: PolylineAnnotationManager? = null
  private var index: Int = 0
  private val nextStyle: String
    get() {
      return AnnotationUtils.STYLES[index++ % AnnotationUtils.STYLES.size]
    }
  private lateinit var annotationPlugin: AnnotationPlugin

  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    setContentView(R.layout.activity_annotation)
    mapView.getMapboxMap().loadStyleUri(nextStyle) {
      annotationPlugin = mapView.annotations
      circleManager = annotationPlugin.createCircleAnnotationManager(mapView).apply {
        addDragListener(
          object : OnCircleAnnotationDragListener {
            var otherCircle: CircleAnnotation? = null
            var otherPolyline: PolylineAnnotation? = null

            override fun onAnnotationDragStarted(annotation: Annotation<*>) {
              otherCircle = pairMap[annotation]
              otherPolyline = polylineMap[annotation]
            }

            override fun onAnnotationDrag(annotation: Annotation<*>) {
              otherCircle?.let {
                it.point = (annotation as CircleAnnotation).point
                circleManager?.update(it)
              }
              otherPolyline?.let {
                it.points = listOf(it.points[0], (annotation as CircleAnnotation).point)
                polylineManager?.update(it)
              }
            }

            override fun onAnnotationDragFinished(annotation: Annotation<*>) {}
          }
        )
      }
      polylineManager = annotationPlugin.createPolylineAnnotationManager(mapView)

      // random add circles across the globe
      for (i in 0..20) {
        val color = Color.argb(255, random.nextInt(256), random.nextInt(256), random.nextInt(256))
        val randomPoint = AnnotationUtils.createRandomPoint()
        val bottom = circleManager!!.create(
          CircleAnnotationOptions()
            .withPoint(randomPoint)
            .withCircleColor(Color.argb(128, 255, 255, 255))
            .withCircleRadius(32.0)
            .withDraggable(false)
        )
        val top = circleManager!!.create(
          CircleAnnotationOptions()
            .withPoint(randomPoint)
            .withCircleColor(color)
            .withCircleRadius(16.0)
            .withDraggable(true)
        )
        val line = polylineManager!!.create(
          PolylineAnnotationOptions()
            .withPoints(listOf(Point.fromLngLat(0.0, 0.0), top.point))
            .withLineColor(Color.RED)
            .withLineWidth(2.0)
            .withDraggable(false)
        )
        pairMap[top] = bottom
        polylineMap[top] = line
      }
    }

    deleteAll.setOnClickListener {
      circleManager?.let {
        annotationPlugin.removeAnnotationManager(it)
      }
    }
    changeStyle.setOnClickListener {
      mapView.getMapboxMap().loadStyleUri(nextStyle)
    }
  }

  override fun onStart() {
    super.onStart()
    mapView.onStart()
  }

  override fun onStop() {
    super.onStop()
    mapView.onStop()
  }

  override fun onLowMemory() {
    super.onLowMemory()
    mapView.onLowMemory()
  }

  override fun onDestroy() {
    super.onDestroy()
    mapView.onDestroy()
  }

  companion object {
    private const val CIRCLE_LONGITUDE = 0.381457
    private const val CIRCLE_LATITUDE = 6.687337
  }
}
```

**Comment by cramptonism** [comment]
Important note: this doesn't repro on beta 20, only beta 21.

**Comment by srajala** [comment]
We also started seeing similar issues when creating/deleting multiple point and polyline annotations in one go. Started occurring with beta 21 and happens also in RC1, but not with beta 20. Might be related to geojson async data parsing. For example, calling `create(options: List<S>): List<T>` for point and polyline annotation managers, one after the other, sometimes fails to draw annotations on the map. 

Calling e.g. `update(annotations: List<T>` with an empty list after a delay will "fix" it, since it will make a call to `updateSource`. Our current workaround is to wrap the create/delete/update calls to polyline annotation manager with
`Handler(Looper.getMainLooper()).post { ... }` after first making calls to the point annotation manager. 

Haven't yet had a chance to try and create a sample to reproduce.

**Comment by cramptonism** [comment]
Thanks for the tip, @srajala , that does seem to mostly "fix" the issue. Though perf of the annotation updates does seem generally worse than beta20 so I don't think it'll be sustainable for my use case.
