### ISSUE TITLE
Adjust for new Android 12's "Approximate Location" implementation

### ISSUE THREAD

**Issue by VincentJoshuaET** [mapbox/mapbox-maps-android#434]
https://developer.android.com/about/versions/12/approximate-location

**Comment by knov** [comment]
Thanks for this request @VincentJoshuaET. We have this on the roadmap.

**Comment by tobrun** [comment]
:wave: @VincentJoshuaET, handling approximate location is fully to be handled by the app developer.
Happy to hear about any changes that the SDK would need to make but closing this as not actionable.

**Comment by VincentJoshuaET** [comment]
You should at least add the `android.permission.ACCESS_COARSE_LOCATION` permission in your manifest because it is required on Android 12.

**Comment by tobrun** [comment]
@VincentJoshuaET that is for apps, not for the SDK to add to the manifest.

**Comment by VincentJoshuaET** [comment]
```
 private void requestLocationPermissions(Activity activity, boolean requestFineLocation, boolean requestBackgroundLocation) {
        List<String> permissions = new ArrayList();
        if (requestFineLocation) {
            permissions.add("android.permission.ACCESS_FINE_LOCATION");
        } else {
            permissions.add("android.permission.ACCESS_COARSE_LOCATION");
        }

        if (VERSION.SDK_INT >= 29 && requestBackgroundLocation) {
            permissions.add("android.permission.ACCESS_BACKGROUND_LOCATION");
        }

        this.requestPermissions(activity, (String[])permissions.toArray(new String[permissions.size()]));
    }
```

Your permission request method doesn't include `ACCESS_COARSE_LOCATION`, meaning it will fail on Android 12.

**Comment by VincentJoshuaET** [comment]
Any updates? `PermissionsManager` will not work on Android 12.
