### ISSUE TITLE
Persistent layers do not retain correct position

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-maps-android#452]
## Environment
- Maps SDK Version: 10.0.0-rc.2

## Description
Refs https://github.com/mapbox/mapbox-navigation-android/pull/4532. When using the persistent layers API, the layers and sources are correctly kept across style changes (don't mind an arrow flash, wasn't integrated yet for that layer), but the `LayerPosition` is not respected after the style reload:

https://user-images.githubusercontent.com/16925074/123256037-c9ee2880-d4f0-11eb-92b9-5e8ed1aebd56.mp4

You can see that the route is initially drawn below the "Bolesława Drobnera" road label but after the style reload it's simply rendered on top of everything (including the puck).

The layers are added as:
```kotlin
style.addPersistentLayer(layer, LayerPosition(null, "road-label", null))
```

and the style sequence is:
1. `Style.MAPBOX_STREETS` (initial)
2. `Style.LIGHT`
3. `Style.SATELLITE`
4. `Style.MAPBOX_STREETS`

cc @mapbox/maps-android @cafesilencio

**Comment by pengdev** [comment]
Hi @LukasPaczos I think that's a known issue, same as https://github.com/mapbox/mapbox-maps-android/issues/428 and it will be resolved in rc.3 release.

**Comment by tobrun** [comment]
closed with https://github.com/mapbox/mapbox-maps-android/pull/442
