### ISSUE TITLE
Keep location puck always on top of all layers

### ISSUE THREAD

**Issue by VincentJoshuaET** [mapbox/mapbox-maps-android#453]

**Comment by Chaoba** [comment]
@VincentJoshuaET By default, the location puck will be added on top of all layers. However, if you add other self-defined layers, they may cover location puck, then you can use the `layerAbove` property to update the position of location puck.
```
mapView.location.apply {
    updateSettings {
      layerAbove = "water"
    }
}
```

**Comment by Chaoba** [comment]
Gonna close this issue, feel free to reopen it if you still have questions about it.

**Comment by maxmiranda** [comment]
Figured it out:  Location Indicator is given layer id of "location-indicator" so you can manipulate it as follows:        `try mapView.mapboxMap.style.moveLayer(withId: "location-indicator", to: .above("polygon-layer"))
`

**Comment by BillyLuisNeedham** [comment]
For anyone coming here (like I was) looking for an easy way to lay a location puck over all other layers easily, I add layers, then disable and re-enable the location puck and it draws over all other layers.

```
    private fun MapView.placeLocationPuckOverOtherLayers() {
        location2.enabled = false
        location2.enabled = true
    }
```

**Comment by timotheeduran** [comment]
> Figured it out: Location Indicator is given layer id of "location-indicator" so you can manipulate it as follows: `try mapView.mapboxMap.style.moveLayer(withId: "location-indicator", to: .above("polygon-layer")) `

For iOS, if you add a location indicator using this `mapView.location.options.puckType = .puck2D()`, the ID of the layer added by Mapbox is now `puck`. You can achieve the same thing with `try mapView?.mapboxMap.style.moveLayer(withId: "puck", to: .above("SOME_LAYER_ID"))`.

**Comment by alex-tifox** [comment]
> For anyone coming here (like I was) looking for an easy way to lay a location puck over all other layers easily, I add layers, then disable and re-enable the location puck and it draws over all other layers.
> 
> ```
>     private fun MapView.placeLocationPuckOverOtherLayers() {
>         location2.enabled = false
>         location2.enabled = true
>     }
> ```

Saved my day, works for me
