### ISSUE TITLE
How to getLayer use Java?

### ISSUE THREAD

**Issue by KayHung** [mapbox/mapbox-maps-android#469]
Use Kotlin, I can the target id layer like below
(style.getLayer(ROAD_NUMBER_SHIELD) as SymbolLayer).visibility(
    Visibility.NONE
 )

I want to know how to do the same thing when use Java

**Comment by VincentJoshuaET** [comment]
import com.mapbox.maps.extension.style.layers.LayerKt;

`LayerKt.getLayer(style, "LAYER_NAME")`

**Comment by KayHung** [comment]
@VincentJoshuaET 
Thanks

**Comment by pengdev** [comment]
Hey @KayHung thanks for the question, and thanks @VincentJoshuaET for the accurate answer 👍 

Yes, `LayerKt.getLayer(style, "LAYER_NAME")` works for maps releases before v10.0.0-rc.3.

We have been trying to optimise the Java API surface, and in https://github.com/mapbox/mapbox-maps-android/pull/454 , we specified the JvmName for the file that contains the extension functions on Layer and Source. After this PR you could use `LayerUtils.getLayer(style, "LAYER_NAME")` to get the layer.

This change is merged to main and will be available in v10.0.0-rc.4 release.
