### ISSUE TITLE
Ability to extrude a polygon by an altitude with 3D Terrain

### ISSUE THREAD

**Issue by alexandre-pereira** [mapbox/mapbox-maps-android#470]
## New Feature

Currently, when we set an extrusion base using the 3D Terrain, the base is taken in consideration in meters from the current ground level. To visualise better the data with an altitude, it would be nice to have an option to extrude the polygon from the sea level even when using a 3D Terrain.

## Why
Cause it's useful for visualizing flight data for exemple and it opens the ability to works properly on Planar, Paragliding, Hanggliding, Airplane tools.

**Comment by tobrun** [comment]
FYI, for this type of requirement @ivovandongen

**Comment by kiryldz** [comment]
Stale, outdated. Please re-open if needed. In theory this could already be better supported in later versions of our SDK.
