### ISSUE TITLE
How to set LocationPuck size by the screen density?

### ISSUE THREAD

**Issue by KayHung** [mapbox/mapbox-maps-android#489]
I want change the location puck size depend on screen density, how can I do?

**Mapbox Map SDK version:**
mapbox-maps-android-android-v10.0.0-rc.2

**Comment by tobrun** [comment]
LocationPuck2D class has a ScaleExpression field that can be used to scale the location puck images. You can use your screen density value as part of this. This said, why would you want to have it behave differently? The whole map and everything in it get automatically resized on screen density.

**Comment by KayHung** [comment]
@tobrun 
I have a device, the screen size is 800*480 and the dpi is 160.
The locationPuck is too large for this device.
