### ISSUE TITLE
setFeatureState causes SIGSEGV, code 1 (SEGV_MAPERR)

### ISSUE THREAD

**Issue by RedChops** [mapbox/mapbox-maps-android#494]
## Environment

- Android OS version: 11
- Devices affected: emulator
- Maps SDK Version: 10.0.0-rc.3, Kotlin

## Observed behavior and steps to reproduce

Calling setFeatureState with a provided feature ID (in this case from queryRenderedFeatures at a point) causes the app to crash after a couple milliseconds, I'm assuming once the enqueued task gets executed in the background. To reproduce I:

- Created a VectorSource, a LineLayer, and a FillLayer
- Listened to the onCameraChangeListener to receive the current map center point
- Queried the map using queryRenderedFeatures with this coordinate and the two layers (just for completeness)
- Get the feature, attempt to setFeatureState, app crashes

## Expected behavior

Feature state should properly update. I'm able to use getFeatureState with the supplied feature ID successfully, and the resultant list is of course empty.

## Notes / preliminary analysis

I'm attempting to set the feature state using: 
`mapboxMap.setFeatureState("source", "source-line",
                                featureId, valueOf(hashMapOf("hovered" to valueOf(true)))
                            )`
which crashes.

Using `mapboxMap.getFeatureState("source", "source-line", featureId) { [callback] }` works just fine, so I think the map is storing the features properly. I've tried using several different options for the sourceLayerId property, they all seem to work the same. I've tried stepping through the execution to find where the crash is, but it's somewhere in the enqueued job so not really easy to discover. I've also tried several different combinations for the state parameter which all seem to have the same effect.

## Additional links and references

Stacktrace is here: https://pastebin.com/DieStuXR though it doesn't seem to be quite helpful. I unfortunately cannot share the source URI as it's internal and running in a test capacity, but I can describe it if it would help. I can also share my source and layer instantiation if that would help at all

**Comment by Chaoba** [comment]
@RedChops I tried to reproduce it locally and not able to make it. Can you create a minimal project that could reproduce this issue to help us fix it? Thanks.

**Comment by RedChops** [comment]
@Chaoba Sure thing! I found a public data source that is similar to our internal one, so I've published a reproducible example here: https://github.com/RedChops/MapboxTest

**Comment by RedChops** [comment]
Thanks @pengdev. I tested it out and it works now with rc.7!
