### ISSUE TITLE
Persistent layer kept correctly only every other time

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-maps-android#498]
## Environment
- Maps SDK Version: 10.0.0-rc.3

## Description
Refs https://github.com/mapbox/mapbox-maps-android/issues/452 and https://github.com/mapbox/mapbox-navigation-android/pull/4532. When using the persistent layers API, the layers and sources are correctly kept across style changes only every other time. Otherwise, the order of layers is mixed up:

https://user-images.githubusercontent.com/16925074/125496881-5d26adef-3e3e-43f0-bf35-c3064f1ee206.mp4

The style sequence is:
1. `Style.MAPBOX_STREETS` (initial)
2. `Style.DARK`
3. `Style.LIGHT`
4. `Style.MAPBOX_STREETS`
5. `Style.DARK`
6. `Style.LIGHT`

In the example above we see 3 line layers stacked on top of each other:
```
mapbox-navigation-route-casing-layer
mapbox-navigation-route-layer
mapbox-navigation-route-traffic-layer
```
All of them are added to the map with the same `below` argument of `"road-label"` in the order that results in the desired stack:
```
options.routeLayerProvider.buildPrimaryRouteCasingLayer(
    style,
    options.resourceProvider.routeLineColorResources.routeCasingColor
).let {
    style.addPersistentLayer(it, LayerPosition(null, belowLayerIdToUse, null))
}

options.routeLayerProvider.buildPrimaryRouteLayer(
    style,
    options.resourceProvider.roundedLineCap,
    options.resourceProvider.routeLineColorResources.routeDefaultColor
).let {
    style.addPersistentLayer(it, LayerPosition(null, belowLayerIdToUse, null))
}

options.routeLayerProvider.buildPrimaryRouteTrafficLayer(
    style,
    options.resourceProvider.roundedLineCap,
    options.resourceProvider.routeLineColorResources.routeDefaultColor
).let {
    style.addPersistentLayer(it, LayerPosition(null, belowLayerIdToUse, null))
}
```

It looks like on every other style change the bottom-most layer pops to the front ignoring all other layer ordering. That layer is a thin dark-blue border around the route when things work correctly (`mapbox-navigation-route-casing-layer`), and then it jumps to the top when they don't. You can see that this is not style dependent - when cycled the same style sometimes works sometimes doesn't, the only consistency I was able to find is that the issue is present every other style change.

The route line layers are persisted correctly when the `below` argument is not specified. If all layers are just placed on top without any z-indexing, things work fine for line layers.  But then we see an issue with other line layers (arrow shaft) and symbol layers (arrow head) that create the arrow:

https://user-images.githubusercontent.com/16925074/125501070-cb1e16b3-311f-4993-9da0-4633a7a4d55b.mp4

where the arrow layers use `mapbox-navigation-route-traffic-layer` as the `above` argument to render the arrows on top of the line. The layers are not only discoloured but also mispositioned.

Again, when the `above` argument for arrow layers is removed and everything is just placed on top, everything works fine.

There seems to be a clear issue when some form of z-indexing and the persistent layers are paired together.

cc @mapbox/maps-android @cafesilencio @alexshalamov @dudeuter

**Comment by tobrun** [comment]
latest release included the "final" fix for this feature. We should be good-to-go

**Comment by LukasPaczos** [comment]
@tobrun just noting that we're still waiting for one more fix targeted for `rc.8`.
