### ISSUE TITLE
Allow Style packs and tile descriptors to use a local Style URI

### ISSUE THREAD

**Issue by DanielGarciaManyHats** [mapbox/mapbox-maps-android#499]
## New Feature

-Mapbox version: v10.0.0-rc.3
Currently working with Offline functionalities, when preparing to download a tilepack and style pack, the "loadStylePack()" and "createTilesetDescriptor()" methods only accept style urls, either of the "mapbox://" or "http://" form.
I would like to be able to create a style pack and tile descriptor using a local styleJSON with an uri of type "asset://" or "file://", similar to how loadStyleUri() allows for those types of URI form.

## Why
I'm working with raster tile styles hosted in a third party server like so: "https://someserver.com/somerasterstyle/{z}/{x}/{y}", There is a logic to apply further customizations to the style itself and those get added as GET parameters to the url, like so: "https://someserver.com/somerasterstyle/{z}/{x}/{y}?someFilter=true". These modifications, are managed on a local GSON object and reaplied to the map using the "loadStyleJson()" method. I can then the save this modified JSON in the local files, however I would like to use my modified JSON as a style for downloaded data.

**Comment by kiryldz** [comment]
@DanielGarciaManyHats sadly new Offline that you're referring to does not support this feature and will not support it in foreseeable future. Main reason for that is that we're operating not with individual tiles but with packs making it work faster comparing to legacy offline. 
However it should still be possible using legacy offline solution. We have basic sample [activity](https://github.com/mapbox/mapbox-maps-android/blob/main/app/src/main/java/com/mapbox/maps/testapp/examples/LegacyOfflineActivity.kt) in our examples and you could also read more about it in our [docs](https://docs.mapbox.com/android/maps/guides/offline/) (some classes were renamed but overall logic should be the same).
