### ISSUE TITLE
Tile store download fails with "Failed to resolve tileset descriptors"

### ISSUE THREAD

**Issue by ToufiPF** [mapbox/mapbox-maps-android#518]
## Environment

- Android OS version: API 24 and 29 at least
- Devices affected: Real device (Xperia xa1) and emulator (Pixel 2)
- Maps SDK Version: 10.0.0-rc4

## Observed behavior and steps to reproduce

Tilestore load fails with a TileRegion error with type = TilesetDescriptor and message = "Failed to resolve tileset descriptors: Loading request canceled".
Sample code:
```
private fun downloadMapboxData(styleUri: String, point: Geometry) {
    val stylePackOptions = StylePackLoadOptions.Builder()
        .glyphsRasterizationMode(GlyphsRasterizationMode.IDEOGRAPHS_RASTERIZED_LOCALLY)
        .acceptExpired(false)
        .build()

    mapboxOfflineManager.loadStylePack(
        Style.MAPBOX_STREETS,
        stylePackOptions,
        this::onProgress,
        this::onComplete
    )

    // Create the tileset descriptor. There seems to be a race between this method call and the request made above
    // inserting a delay here fixes the problem
    // runBlocking(Dispatchers.IO) { delay(2000) }

    val tilesetDescriptor = mapboxOfflineManager.createTilesetDescriptor(
        TilesetDescriptorOptions.Builder()
            .styleURI(Style.MAPBOX_STREETS)
            .stylePackOptions(stylePackOptions)
            .minZoom(15)
            .maxZoom(16)
            .build()
    )

    val tileRegionOptions = TileRegionLoadOptions.Builder()
        .descriptors(arrayListOf(tilesetDescriptor))
        .geometry(point)
        .acceptExpired(false)
        .networkRestriction(NetworkRestriction.NONE)
        .build()

    mapboxTileStore.loadTileRegion(
        TILE_REGION_ID,
        tileRegionOptions,
        this::onProgress,
        this::onComplete
    )
}
```

Tilestore & offline manager are created like so (and then injected in my code):
``` 
val tileStore = TileStore.create().apply {
    setOption(
        TileStoreOptions.MAPBOX_ACCESS_TOKEN,
        TileDataDomain.MAPS,
        Value.valueOf(context.getString(R.string.mapbox_access_token))
    )
}

val resourceOptions = ResourceOptions.Builder()
    .accessToken(context.getString(R.string.mapbox_access_token))
    .tileStore(tileStore)
    .tileStoreUsageMode(TileStoreUsageMode.READ_ONLY)
    .build()
val offlineManager = OfflineManager(resourceOptions)
```

## Expected behavior

Tile region is downloaded successfully.

## Notes / preliminary analysis

The problem seems to be a race between resolving the tileset descriptor and the style pack request. What tiped me was that during a normal execution, the loadTileRegion method failed, but when I tried to run the code step by step with the debugger, the download succeeded.
I think I managed to pinpoint the problem: if I block the thread between the calls to `OfflineManager.loadStylePack` and `OfflineManager.createTilesetDescriptor` for 2 or 3 seconds, the download will succeed.
Additional analysis is hard to give since the tile store code is native and I can't use the debugger to see what's happening.

Cheers

**Comment by kiryldz** [comment]
@ToufiPF the root cause of the race condition seems to be that you're firstly loading style pack here:
```
 mapboxOfflineManager.loadStylePack(
        Style.MAPBOX_STREETS,
        stylePackOptions,
        this::onProgress,
        this::onComplete
    )
```

and then loading style pack as part of tile region when creating tileset descriptor here:
```
val tilesetDescriptor = mapboxOfflineManager.createTilesetDescriptor(
        TilesetDescriptorOptions.Builder()
            .styleURI(Style.MAPBOX_STREETS)
            .stylePackOptions(stylePackOptions)
            .minZoom(15)
            .maxZoom(16)
            .build()
    )
```

could you please try removing `mapboxOfflineManager.loadStylePack` call, style pack will be created as expected when you do `.stylePackOptions(stylePackOptions)`.

**Comment by ToufiPF** [comment]
That indeed solved the problem, my apologies for the inconvenience!
