### ISSUE TITLE
removeOnMapClickListener not working

### ISSUE THREAD

**Issue by VincentJoshuaET** [mapbox/mapbox-maps-android#532]
## Environment

- Android OS version: Android 11
- Devices affected: Samsung Galaxy S20+
- Maps SDK Version: 10 rc5

## Observed behavior and steps to reproduce

addOnMapClickListener once then removeOnMapClickListener. Map is still clickable and onMapClick is called.

## Expected behavior

onMapClick is NOT called.

**Comment by kiryldz** [comment]
@VincentJoshuaET I've tested it and everything works as expected: after removing listener we do not get `onMapClick` callback triggered.
```
override fun onCreate(savedInstanceState: Bundle?) {
  super.onCreate(savedInstanceState)
  setContentView(R.layout.activity_simple_map)
  mapView.getMapboxMap().addOnMapClickListener(this)
  mapView.postDelayed(
    {
      mapView.getMapboxMap().removeOnMapClickListener(this)
    },
    5000L
  )
}

override fun onMapClick(point: Point): Boolean {
  Logger.e(TAG, "onMapClick")
  return true
}
```

If there's indeed some issue please re-open and provide your code that leads to such incorrect behaviour.
