### ISSUE TITLE
Compass fades out even when fadeWhenFacingNorth set to false

### ISSUE THREAD

**Issue by 32Vache** [mapbox/mapbox-maps-android#533]
## Environment

- Android OS version: 11 (API LVL 30)
- Devices affected: Xiaomi Poco X3 Pro
- Maps SDK Version: 10.0.0-rc.5

## Observed behavior and steps to reproduce

The compass fades out when facing north even through i set fadeWhenFacingNorth to false

`Style.OnStyleLoaded {
                        mapView.compass.updateSettings {
                            enabled = true
                            fadeWhenFacingNorth = false
                            clickable = true
                        }
                    }`

## Expected behavior

The compass should not fade away

**Comment by tobrun** [comment]
Double checked and code snippet works as expected:

![image.png](https://images.zenhubusercontent.com/5f7486a5af236f4570f046ee/9ee61cdb-5228-42a7-8c1b-acc3b7f1eaac)
