### ISSUE TITLE
Annotations do not show when 3D Terrain added

### ISSUE THREAD

**Issue by moritzzzzz** [mapbox/mapbox-maps-android#542]
## Environment

- Android OS version: Tested on API 29, 30
- Devices affected: 
- Maps SDK Version: tested on com.mapbox.maps:android:10.0.0-rc.3 - com.mapbox.maps:android:10.0.0-rc.5

## Observed behavior and steps to reproduce

Annotations (PointAnnotation, CircleAnnotation, PolyLineAnnotation) do not show when there is 3D Terrain added to the style.

```
mapboxMap.loadStyle(
            styleExtension = style(Style.SATELLITE_STREETS){
                +rasterDemSource(SOURCE) {
                    url(TERRAIN_URL_TILE_RESOURCE)
                    tileSize(512)
                }

            }

        ) 
```

To reproduce, add 3D Terrain as described above and try to create an annotation. (PointAnnotation, PolyLineAnnotation, CircleAnnotation) by:

```
val annotationApi = mapView?.annotations
circleAnnotationManager = annotationApi?.createCircleAnnotationManager(mapView)

val circleAnnotationOptions: CircleAnnotationOptions = CircleAnnotationOptions()
            // Define a geographic coordinate.
            .withPoint(point)
            // Style the circle that will be added to the map.
            .withCircleRadius(5.0)
            .withCircleColor("#ff0000")
            .withCircleStrokeWidth(1.0)
            .withCircleStrokeColor("#ffffff")

// Add the resulting circle to the map.
        circleAnnotationManager?.create(circleAnnotationOptions)
```

When excluding the `+rasterDemSource()` part, annotations show.

Please see the attached sample project that displays the behaviour on an emualted device on API 29 with `com.mapbox.maps:android:10.0.0-rc.5`.

Please note that the example project currently is on `com.mapbox.maps:android:10.0.0-rc.3` which does not show the behaviour on this device, but it shows this behaviour on other physical devices.

## Expected behavior

Annotations should be visible.

## Notes / preliminary analysis

This is related to the 3D Terrain. 

## Additional links and references

Example project that displays this behaviour:

[AnnotationBug3DTerrain.zip](https://github.com/mapbox/mapbox-maps-android/files/6926606/AnnotationBug3DTerrain.zip)

**Steps to run this:**
- add you access token to strings.xml
- run the project
- click somewhere, click again --> a line should be drawn
- change Maps SDK version to rc5
- run the project
- click somewhere
- click again --> nothing is drawn

cc @sbma44 @knov

**Comment by Chaoba** [comment]
With `rasterDemSource`, `style.isStyleLoaded` will always be false, so the annotation plugin will not be able to update the added annotations.  
@alexshalamov any idea why `style.isStyleLoaded` will always be false with  `rasterDemSource`?

**Comment by alexshalamov** [comment]
@Chaoba when core emits `StyleLoaded`, `style.isStyleLoaded` should be `true`. However, if inside the callback new source is added, `style.isStyleLoaded` may return `false`, because engine will start loading data for newly added source. This is in-sync with our gl-js engine, example:

```
map.on('load', function() {
  if (!map.getSource("satellite")) {
    console.log(`isStyleLoaded: ${map.isStyleLoaded()}`);
    map.addSource('satellite', {
      "type": 'raster',
      "url": "mapbox://mapbox.satellite",
      "tileSize": 256
    });
    console.log(`isStyleLoaded: ${map.isStyleLoaded()}`);
 }
});

// prints
"isStyleLoaded: true"
"isStyleLoaded: false"
```

If annotation manager depends on `StyleLoaded` + `style.isStyleLoaded : true` combination. Terrain could be added a bit earlier, for example when `StyleDataLoaded - {"type": "style"}` is emitted.

**Comment by Chaoba** [comment]
@alexshalamov How long will it load `rasterDemSource`? The logic inside of maps sdk is while getting the current sytle, if style.isStyleLoaded is false, it will register a callback and Annotations will be added if receive the style load callback. However, this callback is never triggered. 
```
  fun getStyle(onStyleLoaded: Style.OnStyleLoaded) {
    if (::style.isInitialized) {
      if (style.isStyleLoaded) {
        // style has loaded, notify callback immediately
        onStyleLoaded.onStyleLoaded(style)
      } else {
        // style load is occurring now, add callback
        styleObserver.addOnStyleLoadListener(onStyleLoaded)
      }
    } else {
      // no style has loaded yet, add callback
      styleObserver.addOnStyleLoadListener(onStyleLoaded)
    }
  }
```

**Comment by moritzzzzz** [comment]
@alexshalamov @Chaoba  It works when adding the 3D terrain after style has loaded:

```
mapboxMap.loadStyle(
            styleExtension = style(Style.SATELLITE_STREETS){

            }

        ) { // onStyleLoaded

            val annotationApi = mapView?.annotations
            circleAnnotationManager = annotationApi?.createCircleAnnotationManager(mapView)
            polylineAnnotationManager = annotationApi.createPolylineAnnotationManager(mapView)
            pointAnnotationManager = annotationApi?.createPointAnnotationManager(mapView)

            it.addSource(rasterDemSource(SOURCE) {
                url(TERRAIN_URL_TILE_RESOURCE)
                tileSize(512)})


        }
```

**Comment by moritzzzzz** [comment]
The [workaround ](https://github.com/mapbox/mapbox-maps-android/issues/542#issuecomment-893397776) works! Closing this!
