### ISSUE TITLE
Allow empty sources or warn at compile time

### ISSUE THREAD

**Issue by daniel-j-h** [mapbox/mapbox-maps-android#552]
There is a common use-case of adding a layer and a source once (e.g. during start or initialization), and then setting the source's data down the road, e.g. on user interaction or callbacks.

Something like

```
mbxMap.loadStyle(
  style(Style.LIGHT) {

      +fillLayer("my-layer-id", "my-source-id") {
         fillColor("#3aac8a")
      }

      +geoJsonSource("my-source-id") {
          // nop, will get filled later
      }

  }
)
```

will crash unexpectedly _at runtime_ because the source is empty.

Changing the source DSL to the trivial

```
+geoJsonSource("my-source-id") {
  data("")
}
```

fixes this problem and allows for this use-case.

Can we
- either check at compile-time that the source is not an empty source, or
- allow empty sources and handle them similarly to how we handle `data("")` above

**Comment by ank27** [comment]
Resolved with #602
