### ISSUE TITLE
map.queryRenderedFeatures returns Polygons for MultiPolygon features

### ISSUE THREAD

**Issue by daniel-j-h** [mapbox/mapbox-maps-android#555]
Hey folks,

I'm adding multipolygon features to my map with something like

```kotlin
val feat = Feature.fromGeometry(MultiPolygon.fromJson(geom))

featureCollection(FeatureCollection.fromFeatures(features))
```

when I then use the `map.queryRenderedFeatures` functionality on user-click, the `QueryFeaturesCallback` callback's `features` then look like the following

    [Feature{type=Feature, bbox=null, id=null, geometry=Polygon{type=Polygon, bbox=null, coordinates=[[Point{type=Point, bbox=null, coordinates=[-2.321730852127075, 53.32447492789089]}, ..]

which is unexpected in many ways
1. why are the features of type `Polygon` when I added `MultiPolygon`s to the layer's source
2. why do `Feature`s as well as e.g. `Point` have an id and a bbox attribute which is always null

**Comment by ank27** [comment]
@daniel-j-h . I have checked and it does return type `MultiPolynomial`. 

`[feature: Feature{type=Feature, bbox=null, id=null, geometry=Polygon{type=MultiPolygon, bbox=null, coordinates=[[[Point{type=Point, bbox=null, coordinates=[-69.23721313476562, 47.44759373848231]}, Point{type=Point, bbox=null, ..]]`

Can you check again that you are providing multipolynomial in the `fromJson()` function? maybe print `feat` from `val feat = Feature.fromGeometry(MultiPolygon.fromJson(geom))` and let us know.

**Comment by daniel-j-h** [comment]
Hey there I haven't forgotten this I was just out on vacation :hugs: 

@ank27 Here's how I'm providing the data

```kotlin
val poly = MultiPolygon.fromJson(geom.toString())
val feat = Feature.fromGeometry(poly, null, guid)
```

and here is how I'm setting up the on-click handler

```kotlin
map.addOnMapClickListener { point ->
    val pos = map.pixelForCoordinate(point)
    val opt = RenderedQueryOptions(listOf(MY_FILL_LAYER_ID), null)

    map.queryRenderedFeatures(pos, opt) { features ->
        val clickedFeatures = features.value?.map { it.feature }

        if (!clickedFeatures.isNullOrEmpty()) {
            Timber.i("onFeaturesClicked $clickedFeatures")
        }
    }
    
    true // consume click
}
```

The layer is a fill layer, in case that matters.

but what I then get out is

```
onFeaturesClicked [Feature{type=Feature, bbox=null, id=secret, geometry=Polygon{type=Polygon, bbox=null, coordinates=[[Point{type=Point, bbox=null, coordinates=secret}, Point{type=Point, bbox=null, coordinates=secret}, Point{type=Point, bbox=null, coordinates=secret}, Point{type=Point, bbox=null, coordinates=secret}, Point{type=Point, bbox=null, coordinates=secret}]]}, properties=secret}]
```

which is a `Polygon` feature and not a `MultiPolygon` feature.

**Comment by daniel-j-h** [comment]
@tyofemi @ank27 could you re-open this ticket again please, because it's still an unresolved issue. Thanks! :bow:
