### ISSUE TITLE
Support holes in polygons

### ISSUE THREAD

**Issue by akirmse** [mapbox/mapbox-maps-android#557]
## New Feature

A way to specify holes inside polygon annotations in PolygonAnnotationOptions, similar to the "points" field: https://docs.mapbox.com/android/maps/api/10.0.0-rc.5/-mapbox%20-maps%20-android/com.mapbox.maps.plugin.annotation.generated/-polygon-annotation-options/with-points.html

## Why

Google Maps supports this:
https://developers.google.com/android/reference/com/google/android/gms/maps/model/PolygonOptions#addHole(java.lang.Iterable%3Ccom.google.android.gms.maps.model.LatLng%3E)

Cross-SDK development is difficult without this support.

The particular polygons I have are wildfire perimeters specified in KML, which has the concept of outer boundaries and inner boundaries (inner boundaries are holes).

**Comment by akirmse** [comment]
This is also supported in the Mapbox iOS SDK, by adding multiple point arrays to the Turf.Feature in the PolygonAnnotation constructor:

https://docs.mapbox.com/ios/maps/api/10.0.0-rc.6/Structs/PolygonAnnotation.html#/s:10MapboxMaps17PolygonAnnotationV7feature4Turf7FeatureVvp

**Comment by akirmse** [comment]
I'm not sure why this was archived.  It is still a significant shortcoming of the Mapbox API when compared with the Google API, and doesn't even match Mapbox's own iOS API.

Also, I didn't get an email notification when this was archived, which seems like a problem with the process.

**Comment by pengdev** [comment]
Hey @akirmse sorry that this ticket was automatically archived, could you take a look at [this example](https://github.com/mapbox/mapbox-maps-android/blob/2a1e6d51f3128ba5e167126a0f3629377d0a9f63/app/src/main/java/com/mapbox/maps/testapp/examples/linesandpolygons/PolygonHolesActivity.kt) and see if suites your need?

Concretely, you should be able to construct a Polygon geometry with `Polygon.fromOuterInner(outerLineString, innerList)` and use the polygon with the annotations plugin(`PolygonAnnotationOptions.withGeometry()`).

**Comment by akirmse** [comment]
Thank you, that did the trick!
