### ISSUE TITLE
10.0.0-rc.6 not available on maven

### ISSUE THREAD

**Issue by daniel-j-h** [mapbox/mapbox-maps-android#560]
Hey folks I've just got a notification an hour ago that you have released 10.0.0-rc.6 and I wanted to update it in my small project

    implementation("com.mapbox.maps:android:10.0.0-rc.6")

```
   > Could not find com.mapbox.maps:android:10.0.0-rc.6.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/mapbox/maps/android/10.0.0-rc.6/android-10.0.0-rc.6.pom
       - https://repo.maven.apache.org/maven2/com/mapbox/maps/android/10.0.0-rc.6/android-10.0.0-rc.6.pom
       - https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/maps/android/10.0.0-rc.6/android-10.0.0-rc.6.pom
     Required by:
         project :app
```

Rolling back to

    implementation("com.mapbox.maps:android:10.0.0-rc.5")

works again then.

Have you folks maybe not triggered the build & upload process? Ideas?

**Comment by kiryldz** [comment]
Should be already available!
There's always some time delay from actually cutting a release here and binaries availability.
