### ISSUE TITLE
Check StyleManagerInterface.getSourceAs if null

### ISSUE THREAD

**Issue by VincentJoshuaET** [mapbox/mapbox-maps-android#57]
v9 does this already.

```
fun <T : Source?> StyleManagerInterface.getSourceAs(sourceId: String): T? {
    @Suppress("UNCHECKED_CAST")
    return getSource(sourceId) as? T
}
```

**Comment by kiryldz** [comment]
@VincentJoshuaET please use bug / new feature template when creating an issue in this repo and provide more detailed information.
Closing for now, feel free to re-open if you update issue description.
