### ISSUE TITLE
Robolectric Test for AlertDialog fail after bumping target SDK version to 30

### ISSUE THREAD

**Issue by pengdev** [mapbox/mapbox-maps-android#574]
The robolectric test for AlertDialog fails after we bump the target SDK version to 30 in https://github.com/mapbox/mapbox-maps-android/pull/514

The root issue seems to be that after bumping the target SDK version to 30. the following code block didn't trigger the alert dialog's handler logic:

```
alertDialog.getButton(DialogInterface.BUTTON_NEGATIVE)
button.performClick()
```

For now I ignored these test, but would be good to revisit later when the Robolectric works better with target SDK version 30.

**Comment by jush** [comment]
Fixed it by calling `ShadowLooper.runUiThreadTasks()` after `button.performClick()` as described in [Testing Dialogs in Robolectric](https://bterczynski.medium.com/testing-dialogs-in-robolectric-b7118f965ff3):
> Then to verify the dialog is dismissed, you have to do one extra thing: since the dismiss action is placed on the message queue for the UI thread, the dialog dismissal is not immediate. You have to tell the UI thread to run all of its current tasks to get the dialog to dismiss. So simply clicking on the negative button and then checking the dialog’s visibility right afterwards will not work. Instead, you have to tell Robolectric to run the UI Thread tasks with a call to `ShadowLooper.runUiThreadTasks()`
