### ISSUE TITLE
In Multi display example, how can I keep two view synchronization?

### ISSUE THREAD

**Issue by KayHung** [mapbox/mapbox-maps-android#600]
I want to start navigation on first screen, how can I also start navigation on second screen and it's synchronize ?
https://github.com/mapbox/mapbox-maps-android/blob/main/app/src/main/java/com/mapbox/maps/testapp/examples/MultiDisplayActivity.kt

**Comment by kiryldz** [comment]
@KayHung can you please add visuals how it's working right now in your case?

**Comment by KayHung** [comment]
@kiryldz 
I want do like this.
![android-auto](https://user-images.githubusercontent.com/66655517/132619812-2c4f3d1e-be4e-40f2-a3d8-99c81b040627.png)

**Comment by kiryldz** [comment]
Stale, outdated.
