### ISSUE TITLE
Older Android devices fully recreate map surface if using texture view

### ISSUE THREAD

**Issue by kiryldz** [mapbox/mapbox-maps-android#607]
## Environment

- Android OS version: confirmed on 5.1.1, higher should not be affected
- Devices affected: confirmed on Nexus 10, Galaxy J3
- Maps SDK Version: v10.0.0-rc.8

## Observed behavior and steps to reproduce

Minimize and maximize device that fulfils requirements above.
You will see map reloading from scratch because of full resource recreation and new surface.

Newer devices are not affected as `TextureView.SurfaceTextureListener.onSurfaceTextureDestroyed` / `TextureView.SurfaceTextureListener.onSurfaceTextureAvailable` are not even get called when stopping / starting host activity / fragment.

## Expected behavior

Should behave the same as for surface view.

## Additional links and references

Fix was introduced [here](https://github.com/mapbox/mapbox-maps-android/pull/598)

**Comment by pengdev** [comment]
@kiryldz is this done? shall we close it?

**Comment by kiryldz** [comment]
That's not done.

**Comment by kiryldz** [comment]
Stale, outdated.
