### ISSUE TITLE
Allow map textSize to follow system accessibility Font Size settings

### ISSUE THREAD

**Issue by cramptonism** [mapbox/mapbox-maps-android#612]
## New Feature

Either have the textSize values respect system Font Size, or provide a standard multiplier setting that could be set on the entire MapView.

## Why

We have a lot of users complain that the text on our maps is too small, and a lot who are completely happy with it. Ideally the text size would be adjustable with the system Font Size setting. Changing the Display Size _does_ change the font size, presumably because it's based on pixel density. The users who complain that the map labels are too small are the same ones using larger font sizes on their devices.

Perhaps I'm missing something obvious, but it would be great if there was a way to have the font size change with the rest of the app font sizes. Or at least provide some way to adjust the textSize on the entire MapView.

We solved this on one platform by actually manipulating every textSize tag in the MapStyle JSON but it is very burdensome and I'm wondering if there's a better approach before mirroring this on the other platform.

Font Size -> Default
![Screenshot_1630627089](https://user-images.githubusercontent.com/13057523/131930997-d93018db-1622-4b54-a07a-a49103a65d76.png)

Font Size -> Large
![Screenshot_1630627108](https://user-images.githubusercontent.com/13057523/131931014-17015a9d-e963-4946-86ec-7e109a5a1d0e.png)

**Comment by kiryldz** [comment]
We have a bigger task about this and it will be supported in one of the upcoming v11 releases. Please check the changelog for upcoming releases. cc @dserebriakov for visibility. Closing for now.
