### ISSUE TITLE
Copy Pasta 🍝 in the docs

### ISSUE THREAD

**Issue by daniel-j-h** [mapbox/mapbox-maps-android#613]
Hey folks, I'm going over the docs to look up a few things and every now and then I'm coming across copy & paste issues where the docs do not align with the function or type they are meant for.

Here a few examples from today
- https://docs.mapbox.com/android/maps/api/10.0.0-rc.7/-mapbox%20-maps%20-android/com.mapbox.maps.plugin.delegates.listeners/ the first two listener functions are not the same
- https://docs.mapbox.com/android/maps/api/10.0.0-rc.7/-mapbox%20-maps%20-android/com.mapbox.maps.plugin.delegates.listeners/-on-map-idle-listener/ this listener is not for the camera
- https://docs.mapbox.com/android/maps/api/10.0.0-rc.7/-mapbox%20-maps%20-android/com.mapbox.maps.plugin.animation/-camera-animations-plugin/add-camera-zoom-change-listener.html this listener is not for the bearing

It would be great if you could go through your public api docs and make sure they're not just copy pasted but for the actual api.

**Comment by pengdev** [comment]
Thanks @daniel-j-h for the catching these, we will work on fixing these docs issues 👍
