### ISSUE TITLE
Location component location retrieval speed and reliability decreased with 10.0.0-rc.4

### ISSUE THREAD

**Issue by moritzzzzz** [mapbox/mapbox-maps-android#614]
## Environment

- Android OS version: tested on API 29 / 30
- Devices affected: Tested on Xiaomi Mi MIX 2s, Emulator Pixel 4 API 29
- Maps SDK Version: 10.0.0-rc.4 and above

## Observed behavior and steps to reproduce

Please find attached an example project that showcases the behaviour. I have built in a timer that will pop open a alter window showing the time elapsed since the style has loaded until the `locationComponent` found the position:

[locationComponentBug.zip](https://github.com/mapbox/mapbox-maps-android/files/7112309/locationComponentBug.zip)

Test out the change in behaviour by changing the dependency in the app level build.gradle from `    implementation 'com.mapbox.maps:android:10.0.0-rc.3'`  to `    implementation 'com.mapbox.maps:android:10.0.0-rc.4'`

## Expected behavior

The behaviour experienced in `10.0.0-rc.3` is expected.
LocationComponent should retrieve position ~50ms after style was loaded.

## Notes / preliminary analysis

When running simultaneously a normal location request using GMS services, the location is returned within milliseconds. 
When the locationComponent does not fetch a location at all, it helps to update the `lastKnownLocation` by finding the location in a different application.

--> I assume a location update from the `FusedLocationProvider` might be requested with the wrong priority. Can you please check that you are requesting with highest priority?

## Additional links and references

Please see attached project.

**Comment by kiryldz** [comment]
Hey @moritzzzzz please add correct dependency in your `build.gradle` file explicitly like done [here](https://github.com/mapbox/mapbox-maps-android/blob/6aca5e170d8a077f82a851d0756f3d87484452df/app/build.gradle.kts#L89).

**Comment by moritzzzzz** [comment]
hi @kiryldz  adding `implementation 'com.google.android.gms:play-services-location:18.0.0'` does not change/improve the behaviour.

**Comment by moritzzzzz** [comment]
@kiryldz i made another observation:

When starting the application (see example project) the `onMapReady()` function is called, the style is loaded, the `onStyleLoaded` callback is invoked and the `onIndicatorPositionchangedListener` is attached.

However the `locationComponent` does not fetch the location and display it.

BUT when putting the application in background and returning to it, the `locationComponent` will find and the display the position.

**Comment by pengdev** [comment]
I think it's related to the way we check if the style is loaded or not. Related PR in rc.4 release: https://github.com/mapbox/mapbox-maps-android/pull/332

**Comment by pengdev** [comment]
There's a PR #643 in flight that probably will address this issue.
I verified the issue in the attached project is fixed by using the snapshot from #643.

**Comment by Chaoba** [comment]
Verified this issue is fixed with rc.9
