### ISSUE TITLE
onStyleLoaded callbacks are missing if the style is loaded while activity is stopped

### ISSUE THREAD

**Issue by zeac** [mapbox/mapbox-maps-android#618]
## Environment

- Android OS version: Any
- Maps SDK Version: android-v10.0.0-rc.7

## Observed behavior and steps to reproduce
1. Open an Activity with MapView.
2. Call to `mapView.getMapboxMap().loadStyleUri`
3. Move the Activity to stopped state.(Switch to another application).
4. `onStyleLoaded` will never be called.

The second way:
1. Open an Activity with MapView.
2. Move the Activity to stopped state.(Switch to another application).
3. Call to `mapView.getMapboxMap().loadStyleUri`
4. `onStyleLoaded` will never be called.

Tests are included: https://github.com/mapbox/mapbox-maps-android/pull/619

## Expected behavior

When a style is loaded, `onStyleLoaded` is notified even activity is stopped.

**Comment by zeac** [comment]
The root of the problem is in `NativeObserver` which unsubscribes in `onStop`.

**Comment by kiryldz** [comment]
@pengdev as original author can you take a look at it?

I can't say I'm 100% sure that `observable.get()?.unsubscribe(this)` should be called when hosting activity / fragment calls `onStop`. Was there any particular reason for adding it? Why don't we actually want to receive events even if we're in background __but__ core notifies us?

**Comment by zeac** [comment]
`MapboxMap(getStyle()` also depends on this callbacks and will return null.

**Comment by pengdev** [comment]
> @pengdev as original author can you take a look at it?
> 
> I can't say I'm 100% sure that `observable.get()?.unsubscribe(this)` should be called when hosting activity / fragment calls `onStop`. Was there any particular reason for adding it? Why don't we actually want to receive events even if we're in background **but** core notifies us?

I thought it makes no sense to continue listen to the map events if the map is no longer active. but seems we are saving the style loading states and indeed this would introduce missing callbacks etc.

Maybe we should move the unsubscribe to the `onDestroy` instead of `onStop`(And maybe move the subscribe from `onStart` to the constructor of MapController), wdyt?

**Comment by kiryldz** [comment]
> > @pengdev as original author can you take a look at it?
> > I can't say I'm 100% sure that `observable.get()?.unsubscribe(this)` should be called when hosting activity / fragment calls `onStop`. Was there any particular reason for adding it? Why don't we actually want to receive events even if we're in background **but** core notifies us?
> 
> I thought it makes no sense to continue listen to the map events if the map is no longer active. but seems we are saving the style loading states and indeed this would introduce missing callbacks etc.
> 
> Maybe we should move the unsubscribe to the `onDestroy` instead of `onStop`(And maybe move the subscribe from `onStart` to the constructor of MapController), wdyt?

💯  we should subscribe once and unsubscribe in `onDestroy`. Tagging @mapbox/maps-android to collect more opinions here.

**Comment by ank27** [comment]
Yeah 💯, we should unsubscribe in `onDestroy` and subscribe in constructor of MapController.
