### ISSUE TITLE
Pan speed at high tilt is way too fast

### ISSUE THREAD

**Issue by akirmse** [mapbox/mapbox-maps-android#631]
The behavior of the pan gesture was changed from v10-rc7 to v10-rc8.  At high tilt, a pan gesture that comes near the horizon winds up moving the camera many hundreds of miles, often leaving the user with a blank view of the ocean.  See the attached video, where the finger location is indicated by a circle:

https://user-images.githubusercontent.com/2266354/132752425-61a40692-9ed2-4e2b-bf63-a5c287219257.mp4

I speculate that the pan speed is now being taken from the distance from the camera to the touched point on the ground.  So if a pan gesture starts near the bottom of the screen and moves up, the camera starts moving slowly, then accelerates to near light-speed as the gesture approaches the horizon. 

Perhaps the speed should remain constant through the gesture (i.e. determined by only where the gesture first starts on the screen), and/or the movement speed should be capped?

I see the same behavior on the Mapbox iOS SDK in rc8.

**Comment by tobrun** [comment]
> I speculate that the pan speed is now being taken from the distance from the camera to the touched point on the ground. So if a pan gesture starts near the bottom of the screen and moves up, the camera starts moving slowly, then accelerates to near light-speed as the gesture approaches the horizon. 

That is correct, in that regard it's work as designed.

> Perhaps the speed should remain constant through the gesture (i.e. determined by only where the gesture first starts on the screen), and/or the movement speed should be capped?

I will ticket this upstream as an improvement. Removing bug label and adding feature request instead.

**Comment by akirmse** [comment]
Here's a potentially related problem with pan that does not involve tilt.  If you hold down a finger and pinch to zoom, then start panning, the panning will be extremely slow (if you zoom out), or extremely fast (if you zoom in).  The pan speed appears to be in absolute terms of meters per pixel dragged, ignoring the zoom level.

https://user-images.githubusercontent.com/2266354/133835680-84e22928-0dcf-4a84-a594-50d8a20e6cc4.mp4

.

**Comment by akirmse** [comment]
This second problem is the same as this: https://github.com/mapbox/mapbox-maps-android/issues/564

The first one is different, I think.

**Comment by tobrun** [comment]
will be resolved with v10.2.0
