### ISSUE TITLE
Level of detail for imagery and terrain is incorrect near camera

### ISSUE THREAD

**Issue by akirmse** [mapbox/mapbox-maps-android#632]
At high tilt near the camera, the level of detail changes dramatically during a rotate operation, when you would expect that it wouldn't change at all, since the distance from the camera to the terrain isn't changing.  See the blurry imagery here:

https://user-images.githubusercontent.com/2266354/132788497-a696cdb9-4f4e-4a57-bf99-2f987661ce14.mov

Perhaps the LOD is being computed based on the distance from the camera to the center of the tile?

**Comment by kiryldz** [comment]
@akirmse would be grateful if you could specify SDK version you're using and also provide exact `CameraOptions` for the location you shared in video. 
I tried to do the same in rc.8 but do not see such issues.

**Comment by akirmse** [comment]
This is in rc.8.  The coordinates I'm rotating around are shown in the lower left of this video.  You should set the tilt to maximum.

https://user-images.githubusercontent.com/2266354/132896531-a98caad3-e140-44e3-9e5a-cc6932ffbed4.mov

**Comment by kiryldz** [comment]
Stale, outdated. Please re-open if the issue persists in latest versions.
