### ISSUE TITLE
MapboxMap#getStyle returns null after adding a source

### ISSUE THREAD

**Issue by mfazekas** [mapbox/mapbox-maps-android#634]
## Environment

- Maps SDK Version: v10.0.0-rc.8

## Observed behavior and steps to reproduce

`MapboxMap#getStyle` is `null` after adding something (style or layer)

```kotlin
map.getStyle().addSource(source)
assert(map.getStyle() != null)
map.getStyle().addLayer(layer)
```

The assertion in above code fails.

## Expected behavior

IMO `MapboxMap#getStyle` should  return the style even if we've added something, and it's not fully loaded yet. I'd expect `getStyle()` to return null initially, but one it's non-null it should remain non `null`. 

We do have interface that waits for the style to finish loading, but in many cases we can add layers/sources to the style even if something still pending on the style. 

Of course we can work around the current behaviour of `getStyle` in a lot of ways. But current behaviour is a bit surprising IMO.

## Additional links and references

See also #583

**Comment by tobrun** [comment]
@Chaoba you have been looking into a similar related issue. Could you look more into this one?
