### ISSUE TITLE
"Mapbox" word overlaps blue click button in RTL

### ISSUE THREAD

**Issue by akirmse** [mapbox/mapbox-maps-android#635]
Put the phone in RTL mode (e.g. Settings -> Developer options -> Force RTL layout direction)
The "Mapbox" map overlay overlaps the little blue button you can click on.  See the lower right corner of this screenshot.

![Screenshot_20210912-194016](https://user-images.githubusercontent.com/2266354/133016123-eb2b667a-8d92-40ba-bb56-b8d5b3ad0b30.jpg)

This is in rc8.

**Comment by ZiZasaurus** [comment]
@akirmse thank you for bringing this to our attention. We are working on a fix [here](https://github.com/mapbox/mapbox-maps-android/pull/674), which should be available in our next release.
