### ISSUE TITLE
Offline

### ISSUE THREAD

**Issue by Ks-y** [mapbox/mapbox-maps-android#685]
## New Feature

1. I want to download Map SDK offline map resources that can be used in V10 version. Is there any other way besides downloading using V10 version of Map SDK?

2. How to load and display the mbgl-offline.db database file downloaded by the mbgl-offline tool using V10 version of Map SDK？

3. How to export offline map resources downloaded by Map SDK of V10 version to the specified folder？

4. How does the V10 version of Map SDK use the exported offline map resources？

5. Can you provide some demos that can export and merge offline map resource databases?

## Why

1. I used the Map SDK version 9.6.2 before and wanted to switch to the Map SDK version V10. During the switch process, I encountered problems related to the use of offline maps.

thanks

**Comment by ZiZasaurus** [comment]
@Ks-y thanks for writing in. I've provided the answers to your questions below, however, if you can let us know what issues you're having with offline, I'd be happy to help. 

1. There is no way to download Map SDK offline map resources that can be used in V10 version outside of downloading offline regions using V10 version of Map SDK.
2. We no longer support sideloading and recommend you use our offline activity to first display and then download offline regions.
3. Please take a look at our offline activity example [here](https://github.com/mapbox/mapbox-maps-android/blob/2a1e6d51f3128ba5e167126a0f3629377d0a9f63/app/src/main/java/com/mapbox/maps/testapp/examples/OfflineActivity.kt).
4. The Offline Manager API and tile store provide methods for listing and managing offline data. Please take a look at our documentation on managing offline downloads [here](https://docs.mapbox.com/android/beta/maps/guides/offline/#manage-offline-data).
5. See offline activity example above.
