### ISSUE TITLE
MapView is leaking if never attached to the Window

### ISSUE THREAD

**Issue by zeac** [mapbox/mapbox-maps-android#693]
## Environment

- Android OS version: Any
- Devices affected: Any
- Maps SDK Version: 10.0.0-rc.8

## Observed behavior and steps to reproduce

Reasonable scenario looks like
1. Create `MapView` in `Activity.onCreate` and add it to the View tree.
2. Call `recreate` in the end of `Activity.onCreate`.

In the result: Activity is recreated, the first instance of `MapView` is not destroyed.

## Expected behavior

MapView is destroyed.

## Notes / preliminary analysis

Here is `MapboxLifecyclePluginImpl` to receive `Lifecycle.EVENT.ON_DESTROY`, it starts to observe lifecycle events from `MapView.onAttachedToWindow` callback. The problem is that `onAttachedToWindow` is dispatched for all View in the hierarchy only on the first layout pass. But there will no layout pass at all if activity instance is destroyed immediately.

It is a weird to recreate Activity right after it started, but we see such behaviour at one of our customers.

**Comment by alexander-kulikovskii** [comment]
For now can be used such workaround:
Explicitly calls mapView.onDestroy() when recreate activity
