### ISSUE TITLE
In 3D terrain mountains behind front mountains becomes unexpectedly blurry 

### ISSUE THREAD

**Issue by axti** [mapbox/mapbox-maps-android#703]
**Platform:** Android 9 / Samsung S8
**Mapbox SDK version:** v10

https://user-images.githubusercontent.com/5171553/135597512-11374acc-638e-481d-b9d8-dff1981ada02.mp4

### Steps to trigger behavior

 1. Run 3d Terrain example
 2. Move camera close to the mountain edge slowly

### Expected behavior
Mountains behind should be consistently shape and not blurred 
### Actual behavior
Mountains behind become more blurry with each camera moves to the from mountain edge

**Comment by astojilj** [comment]
@axti thanks for the report. And great to have you using new v10 Mapbox Maps SDK for Android. 

This is an interesting issue.... by following API contract that defines map position as zoom to point under the center of screen, we left the possibility that zoom level of tiles at the back could fluctuate (depending on how far is camera from ground that is under center of screen). Let's see what we can do to fix this.

Hope you don't mind, moved the report to v10 Mapbox Maps SDK for Android repository https://github.com/mapbox/mapbox-maps-android.

**Comment by kiryldz** [comment]
Stale, outdated.
