### ISSUE TITLE
Wrong xml attribute name for mapbox_accessToken

### ISSUE THREAD

**Issue by YahiaRagae** [mapbox/mapbox-maps-android#705]
## Environment

- Android OS version: 11
- Devices affected:
- Maps SDK Version:10.0.0-rc.8

## Observed behavior and steps to reproduce

When using the `com.mapbox.maps.MapView` without having a `mapbox_access_token` defined in strings it carshed giving the error : 
`Caused by: com.mapbox.maps.MapboxConfigurationException: 
     Using MapView requires providing a valid access token when inflating or creating the view.
     Provide the token by creating a mapbox_access_token string resource
      or by passing it using MapView's 'mapbox_accessToken' XML attribute.`

<img width="1847" alt="Screen Shot 2021-10-04 at 12 05 51 PM" src="https://user-images.githubusercontent.com/7969139/135774439-e8faed11-baed-4f09-b48d-13cc04e84b70.png">

## Expected behavior

it seems `mapbox_accessToken` is not the right property name, after lots of searches I found out that `mapbox_resourcesAccessToken` is the right one. 

Thanks

**Comment by kiryldz** [comment]
@YahiaRagae thanks for catching it and sorry for inconvenience caused by wrong exception text.
