### ISSUE TITLE
Fit camera in bounding box v10

### ISSUE THREAD

**Issue by YahiaRagae** [mapbox/mapbox-maps-android#715]
Hi, 

I'm migrating to v10, but I'm not able to achieve the exact behaviour of `Fit camera in bounding box` like in that [example](https://docs.mapbox.com/android/maps/examples/fit-camera-in-bounding-box/) 

So it used to be 

```
LatLngBounds latLngBounds = new LatLngBounds.Builder()
.include(locationOne) // Northeast
.include(locationTwo) // Southwest
.build();
mapboxMap.easeCamera(CameraUpdateFactory.newLatLngBounds(latLngBounds, 50), 5000);
```

I have tried :
```
val cameraOptions = CameraOptions.Builder()
      .center(center)
      .padding(EdgeInsets(50.0, 180.0, 350.0, 350.0))
      .zoom(9.0)
      .build()
val mapAnimationOptions = MapAnimationOptions.Builder().duration(2000).build()
mapView.easeTo(cameraOptions, mapAnimationOptions)
```
with this implementation, I need to pass in the zoom, but with the previous one, it used to be calculated automatically.
     
Thanks

**Comment by ank27** [comment]
@YahiaRagae in v10 we have `CoordinateBounds` in place of `LatLangBounds`. 
You can check out this activity [RestrictBoundsActivity.kt](https://github.com/mapbox/mapbox-maps-android/blob/main/app/src/main/java/com/mapbox/maps/testapp/examples/camera/RestrictBoundsActivity.kt) for the similar implementation.

**Comment by YahiaRagae** [comment]
@ank27 thanks a lot for your quick response.

**Comment by xiaxiayige** [comment]
Before v10 I can do it 

`LatLngBounds.Builder builder = new LatLngBounds.Builder();
        .include(aaaaaaaaaa) 
       .include(bbbbbbbb) 
      .include(cccccccccc) 

  mapBoxMapView.getMapBoxMap().easeCamera(CameraUpdateFactory.newLatLngBounds(
                builder.build(),
                paddingStart, paddingTop, paddingEnd, paddingBottom));`

 
Now  how to do ?  Thanks
