### ISSUE TITLE
Application containing MapView freezes after device lock/unlock

### ISSUE THREAD

**Issue by PeroMed** [mapbox/mapbox-maps-android#716]
## Environment

- Android OS version: 9
- Devices affected: Samsung A50, Nokia 8
- Maps SDK Version: 10.0.0-rc.9

## Observed behavior and steps to reproduce

1. Open simple app with MapView mapbox 10
2. Lock device and wait for 10 seconds
3. Enter device pin and unlock the device

MapView is black and everything else in the app is unresponsive

## Expected behavior

App and MapView should resume normally

## Notes / preliminary analysis

It cannot be reproduced every time. But it occurs very commonly.

## Additional links and references
Video link:
https://photos.app.goo.gl/9Ct8i5G3uKXXzjme7

**Comment by kiryldz** [comment]
@PeroMed seems to duplicate https://github.com/mapbox/mapbox-maps-android/issues/684.
Will be fixed in release coming tomorrow, fix should be https://github.com/mapbox/mapbox-maps-android/pull/688.

Will close it, let's re-open if issue will persist.
