### ISSUE TITLE
dependencies for configuration

### ISSUE THREAD

**Issue by machfe** [mapbox/mapbox-maps-android#72]
* What went wrong:
Could not determine the dependencies of task ':app:compileReleaseJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:releaseCompileClasspath'.
   > Could not resolve com.mapbox.common:okhttp:10.0.0-beta.8.
     Required by:
         project :app > project :sdk
      > Could not resolve com.mapbox.common:okhttp:10.0.0-beta.8.
         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/common/okhttp/10.0.0-beta.8/okhttp-10.0.0-beta.8.pom'.
            > Could not GET 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/common/okhttp/10.0.0-beta.8/okhttp-10.0.0-beta.8.pom'. Received status code 403 from server: Forbidden
      > Could not resolve com.mapbox.common:okhttp:10.0.0-beta.8.
         > Could not get resource 'https://oss.jfrog.org/artifactory/oss-snapshot-local/com/mapbox/common/okhttp/10.0.0-beta.8/okhttp-10.0.0-beta.8.pom'.
            > Could not GET 'https://oss.jfrog.org/artifactory/oss-snapshot-local/com/mapbox/common/okhttp/10.0.0-beta.8/okhttp-10.0.0-beta.8.pom'. Received status code 409 from server: 
   > Could not resolve com.mapbox.maps:android-core:10.0.0-beta.13.
     Required by:
         project :app > project :sdk > project :sdk-base
      > Could not resolve com.mapbox.maps:android-core:10.0.0-beta.13.
         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/maps/android-core/10.0.0-beta.13/android-core-10.0.0-beta.13.pom'.
            > Could not GET 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/maps/android-core/10.0.0-beta.13/android-core-10.0.0-beta.13.pom'. Received status code 403 from server: Forbidden

**Comment by kiryldz** [comment]
Hello @machfe , did you follow [instructions](https://docs.mapbox.com/android/beta/maps/guides/install/) regarding providing correct token?

**Comment by tobrun** [comment]
Note the part of `A secret access token with the Downloads:Read scope.`
