### ISSUE TITLE
Style#isStyleLoaded intermittently returns false

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-maps-android#748]
Maps SDK Version: v10.0.0

1. Set a map style, wait for it to fully load
2. Make changes to the map, move it, etc (I don't know whether there's a specific interaction that triggers this behavior)
3. Periodically check for whether the style is fully loaded (`Style#isStyleLoaded`)

Occasionally (not hard to reproduce), the `isStyleLoaded` reports `false`.

Nav SDK before updating any source checks whether the style is loaded, this intermittently delivered wrong style state results in updates that are dropped, for example:

https://user-images.githubusercontent.com/16925074/137479992-fb89737c-7f33-4fa7-8f69-8cc038db33a4.mp4

In the video you can see that sometimes the destination symbol is not updated, sometimes only one line layer is updated instead of all of them, etc. All of this occurrences are caused by the `Style#isStyleLoaded` intermittently reporting `false`.

I understand that this values come in directly from GL-Native and the `StyleManager#isStyleLoaded`, happy to dig in more if there's anything specific I should be looking at. I can't reproduce the issue on 10.0.0-rc.9.

cc @mapbox/maps-android @mapbox/gl-native

**Comment by LukasPaczos** [comment]
Just noting that `AnnotationManagerImpl#updateSource` suffers from the same problem as the Nav SDK implementation:
https://github.com/mapbox/mapbox-maps-android/blob/a9b1a54a192ce8fb744bdefe2563b7ae63254eb0/plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationManagerImpl.kt#L409-L412

It should not check for the `isFullyLoaded` because it will report `false` while other sources are updating.

**Comment by kiryldz** [comment]
> Just noting that `AnnotationManagerImpl#updateSource` suffers from the same problem as the Nav SDK implementation:
> 
> https://github.com/mapbox/mapbox-maps-android/blob/a9b1a54a192ce8fb744bdefe2563b7ae63254eb0/plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationManagerImpl.kt#L409-L412
> 
> It should not check for the `isFullyLoaded` because it will report `false` while other sources are updating.

@Chaoba could you please create a task for that as well as the fix for annotations?

**Comment by LukasPaczos** [comment]
The current model is misrepresenting the `Style` object's state, especially since multiple platform-side instances are backed by the same data, so a style that is theoretically reloaded on the platform side would still report "fully loaded".

Should we keep this open and reconsider changing the way the `Style` object is exposed by the platform for `v11`? Looks like GL-Native treats it now more as a singleton, while the platform follows a different pattern.

**Comment by tobrun** [comment]
> Should we keep this open and reconsider changing the way the Style object is exposed by the platform for v11

Agreed that this needs revisiting for v11

**Comment by kiryldz** [comment]
Stale, outdated and tracked in another tickets. Might be revisited for v12.
