### ISSUE TITLE
How to view C + + source code

### ISSUE THREAD

**Issue by caizhen2** [mapbox/mapbox-maps-android#757]
## New Feature

<- Description of the feature being requested and any outcomes desired, an example use case, and any suggestions for solution ->

## Why
<- 1-2 sentence description of why you're requesting this feature. What problem does it solve? Why is it valuable? ->
How to view C + + source code

**Comment by ank27** [comment]
@caizhen2 this might help : https://github.com/mapbox/mapbox-maps-android/blob/main/app/src/main/java/com/mapbox/maps/testapp/examples/OfflineActivity.kt
