### ISSUE TITLE
Quick zoom focal point - Android

### ISSUE THREAD

**Issue by ChristineRobinson** [mapbox/mapbox-maps-android#771]
## Make quick zoom focal point the center of the screen

Current behavior: When a user does a quick zoom pinch, our maps zoom to the point where the gesture/pinch is applied.
Expected behavior in Android: When a user quick zoom son the screen, they expect it to remain centered. We would like to keep the focal point as the center of the screen.  A related request is to add granular control of focal points on specific gestures.

## Why
The current behavior being different from other Android applications is frustrating for users

**Comment by Sonosar** [comment]
Same issue here
We are trying to switch to mapbox from google maps, and this is the only thing holding us back…

**Comment by kiryldz** [comment]
@Sonosar @ChristineRobinson perhaps I do not get an issue but as I understand focal point for quick zoom in (douple tap) is used both in Goolge Maps and Mapbox Maps.

https://user-images.githubusercontent.com/15800566/144043581-be00e5d2-1bbc-4375-9383-11760a7c0fcf.mp4

Can you provide a bit more information (perhaps with visuals)?

**Comment by Sonosar** [comment]
Please take a look at this 2 videos

https://user-images.githubusercontent.com/9080655/144051417-e447ef75-94e0-497a-b293-97ed752a62af.mp4

https://user-images.githubusercontent.com/9080655/144051393-522a5088-2ad5-40ac-93b5-3b0d8becb829.mp4

The first on is the desired behavior, the second video is the actual behavior
Please note that we have the same issue with iOS as well

**Comment by kiryldz** [comment]
@Sonosar although we have API in place for that case, here I do set to always use screen center as focal point:
```
mapView.getMapboxMap().getGesturesSettings()?.focalPoint = ScreenCoordinate(
  mapView.width / 2.0,
  mapView.height / 2.0
)
```
it seems it does not work as expected, I'll remove feature tag and we'll look into this bug.

**Comment by kiryldz** [comment]
@Sonosar I was doing it not correct in https://github.com/mapbox/mapbox-maps-android/issues/771#issuecomment-982678074.

I did verify that if focal point is applied correctly (e.g. center of the screen) if you do it the following way:
```
mapView.post {
  mapView.gestures.updateSettings {
    focalPoint = ScreenCoordinate(mapView.width / 2.0, mapView.height / 2.0)
  }
}
```

However in order to unblock even an easier way I've prepared https://github.com/mapbox/mapbox-maps-android/pull/952
Closing that issue, please feel free to re-open if issue will persist!
