### ISSUE TITLE
Telemetry Settings cannot be changed programmatically

### ISSUE THREAD

**Issue by stolzda** [mapbox/mapbox-maps-android#772]
## Environment

- Android OS version: 10
- Maps SDK Version: 10.0.0

## Observed behavior and steps to reproduce

By default, telemetry seems to be enabled. We would like to integrate the settings into the app overall settings, and toggle the settings from there, which it seems it was possible, see:

https://github.com/mapbox/mapbox-gl-native/issues/13304
https://github.com/mapbox/mapbox-gl-native-android/issues/90#issuecomment-563320288

These functions are not exposed anymore. With some digging I found the following:

```
val telemetry = mapView.getPlugin<AttributionPlugin>(Plugin.MAPBOX_ATTRIBUTION_PLUGIN_ID)!!
	.getMapAttributionDelegate().telemetry()
telemetry.disableTelemetrySession()
telemetry.setUserTelemetryRequestState(false)
```

However, this does not stop the MapboxTelemetryService, and neither seems the Telemetry to be disabled.

## Expected behavior

Telemetry is disabled, MapboxTelemetryService is stopped.

**Comment by ZiZasaurus** [comment]
@stolzda It is not currently possible to opt-out of telemetry on behalf of your users. You must give your end-users the ability to opt in or out within your application. For additional information about telemetry, please take a look at our documentation [here](https://www.mapbox.com/telemetry/#opt-out).

**Comment by stolzda** [comment]
> @stolzda It is not currently possible to opt-out of telemetry on behalf of your users. You must give your end-users the ability to opt in or out within your application. For additional information about telemetry, please take a look at our documentation [here](https://www.mapbox.com/telemetry/#opt-out).

Yes, this is what we are trying to implement. We want to integrate this possibility within the settings screen within our app - but when the user opts out on this screen, we need to call the corresponding mapBox opt-out function. I left out the settings part and only put a minimal example of how I assumed that I need to call the mapBox SDK to pass the opt-out request of the user - but it did not work.

Can you tell me which function I need to call when the user opts-out / opts-in?

**Comment by ZiZasaurus** [comment]
@stolzda we fixed a bug affecting the persistence of user settings in [v10.0.1](https://github.com/mapbox/mapbox-maps-ios/releases/tag/v10.0.1). Can you please try updating to that version and see if the issue persists? 

Please note, you would need to set a boolean value for the `MGLMapboxMetricsEnabled` key in UserDefaults.standard.

**Comment by daniel-j-h** [comment]
@ZiZasaurus your links and notes seem to be about the Swift / iOS version, while this ticket is about the Android Maps SDK.

I am facing the same problem for my app on Android using the Maps SDK v10 where I must allow users to decide on all telemetry and location collection for regulatory reasons.

**Comment by tobrun** [comment]
> Currently, the attribution control is the mechanism by which users are given the ability to opt out. We understand the desire to consolidate settings, and you're right that in the past we have supported multiple ways of changing this setting. In practice, relatively few customers used it. It's helpful to hear that there is a need--we'll reconsider it when we next plan our roadmap.
One shorter-term improvement we could potentially offer is the ability to launch to your app with the telem dialog opened via a public API.

**Comment by quangpaypay** [comment]
@tobrun : Thanks for your explanation.
We are migrating to version 10 and facing a similar issue that @daniel-j-h has.

> I must allow users to decide on all telemetry and location collection for regulatory reasons.

By the way, what do you mean by this option? Thanks.

> Currently, the attribution control is the mechanism by which users are given the ability to opt out.

**Comment by ben-j69** [comment]
Hello,
We also need to disable telemetry in v10 like we were doing on v9:

```
        TelemetryEnabler.updateTelemetryState(TelemetryEnabler.State.DISABLED);
        final TelemetryDefinition telemetryDefinition = Mapbox.getTelemetry();
        if (telemetryDefinition != null) {
            telemetryDefinition.setUserTelemetryRequestState(false);
        }
```
I did not find any documentation on how to disable telemetry, globally or on a MapView.

**Comment by VincentJoshuaET** [comment]
Any update?

**Comment by mrfaa** [comment]
Is this an option:

`            mapView.attribution.getMapAttributionDelegate().telemetry().disableTelemetrySession()
`

?

**Comment by trusohamn** [comment]
any updates? I cannot migrate to version 10 because of this issue

**Comment by krizman** [comment]
Any official way of opting out of telemetry gathering? 

Out of curiosity, why are telemetry events being sent even when the app hasn't yet loaded/showed the map?
