### ISSUE TITLE
Failed to download customized offline tiles using "tilestore. Loadtileregion()"

### ISSUE THREAD

**Issue by caizhen2** [mapbox/mapbox-maps-android#777]
## New Feature

<- Description of the feature being requested and any outcomes desired, an example use case, and any suggestions for solution ->
@ank27 
## Why
<- 1-2 sentence description of why you're requesting this feature. What problem does it solve? Why is it valuable? ->
Does not exist
  ![image](https://user-images.githubusercontent.com/19689727/138855312-3a0c018e-6ad8-4130-8015-a4ae20cd97a8.png)

**Comment by pengdev** [comment]
Hi @caizhen2, could you please provide a bit more context on what style you used? You mentioned `download customized offline tiles`, how did you customise the offline tiles?
The new offline solution(TileStore) currently only works with Mapbox tiles, if you need to use offline with your customised tiles, you can still use the [legacy offline manager](https://docs.mapbox.com/android/maps/api/10.1.0/mapbox-maps-android/com.mapbox.maps/[android-jvm]-offline-region-manager/?query=class%20OfflineRegionManager%20:%20OfflineRegionManagerInterface).

**Comment by knov** [comment]
closing as stale. please reopen and provide additional information if you need additional support.
