### ISSUE TITLE
Scalebar ratio setting not applied correctly

### ISSUE THREAD

**Issue by skienzl** [mapbox/mapbox-maps-android#809]
## Environment

- Android OS version: all
- Devices affected: all
- Maps SDK Version: 10.1.0-rc.1

## Observed behavior and steps to reproduce

If you change the ratio of the scalebar plugin the bar and labels get cut off if the ratio is higher than 0.5:

![image](https://user-images.githubusercontent.com/4992387/140040343-98bbaf36-bbc3-4468-a6f6-a95d21c78ba0.png)

## Expected behavior

Apply the correct ratio to the bar and lables

## Notes / preliminary analysis

In the the root case is in `ScaleBarImpl.kt` on line 63 in which the width is calculated with a fixed ratio if 0.5: 

`val width = mapViewWidth / 2`

The possible fix would be to apply the ratio from the settings: 

`val width = mapViewWidth * settings.ratio`

**Comment by Chaoba** [comment]
Thank you @skienzl for reporting this, we will fix this issue soon.
