### ISSUE TITLE
v10 zoom and rotation do not use correct axis

### ISSUE THREAD

**Issue by sbma44** [mapbox/mapbox-maps-android#82]
## Environment
- Android OS version: 9
- Devices affected: replicated on Lenovo TB-8505FS
- Maps SDK Version: v10 beta 12

## Observed behavior and steps to reproduce
Same issue as reported for iOS in https://github.com/mapbox/mapbox-maps-ios/issues/65 with exception of fact that panning works while two-finger gesture is in progress, which is not true on iOS.

## Expected behavior
pinch to zoom and rotate center on the gesture rather than center of the map

**Comment by pengdev** [comment]
Tried to reproduce the issue locally, the issue seems to be related to the animations plugin. 
If I change https://github.com/mapbox/mapbox-maps-android/blob/main/plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPluginImpl.kt#L568 from `easeTo` to `jumpTo`, the issue seems to be fixed.


cc @mapbox/maps-android

**Comment by kiryldz** [comment]
> Tried to reproduce the issue locally, the issue seems to be related to the animations plugin.
> If I change https://github.com/mapbox/mapbox-maps-android/blob/main/plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPluginImpl.kt#L568 from `easeTo` to `jumpTo`, the issue seems to be fixed.
> 
> Since all the easeTo functions uses the same cameraAnimation options:
> 
> ```
> mapAnimationOptions {
>       duration = 0
>       owner = MapAnimationOwnerRegistry.GESTURES
>     }
> ```
> 
> Shall we remove the dependency of AnimationsPlugin and use jumpTo instead? would this cause issue to the gestures ownership management?
> 
> cc @mapbox/maps-android @kiryldz

That was the main idea to use `easeTo` with zero duration to perform immediate jump but do it via animations plugin. I'll take a look at it - `easeTo` with `duration = 0` should actually do a single `jumpTo` under the hood, seems to be a bug.
