### ISSUE TITLE
Java example for SDK v10 integration into application 

### ISSUE THREAD

**Issue by alexeysi** [mapbox/mapbox-maps-android#820]
## New Feature
Is there going any Java example for SDK v10 integration into application?
## Why
We have an application in Java and never going to switch to Kotlin

**Comment by Chaoba** [comment]
We have two java [examples]( https://github.com/mapbox/mapbox-maps-android/tree/main/app/src/main/java/com/mapbox/maps/testapp/examples/java) and a [Java interface checker ](https://github.com/mapbox/mapbox-maps-android/blob/main/app/src/main/java/com/mapbox/maps/testapp/examples/JavaInterfaceChecker.java)you can refer to
