### ISSUE TITLE
update annotaion

### ISSUE THREAD

**Issue by 229222025** [mapbox/mapbox-maps-android#825]
## Environment

- Android OS version:7.0
- Devices affected:
- Maps SDK Version:10.1.0

pointAnnotationManager1.update(PointAnnotation) will refresh all annotations on the layer corresponding to pointannotationmanager1, resulting in higher CPU utilization. Is there any way to refresh only one annotation

**Comment by Chaoba** [comment]
The current architecture requires updating all even you update only one annotation.
A workaround is creating several pointAnnotationManager and separating annotations into them.

**Comment by 229222025** [comment]
I tried to create multiple pointannotationmanagers, but the onpointinnotationclicklistener will not be triggered. Is there any way to solve this problem?
