### ISSUE TITLE
OnPointAnnotationClickListener not to execute

### ISSUE THREAD

**Issue by 229222025** [mapbox/mapbox-maps-android#829]
## Environment

- Android OS version:7.0
- Devices affected:
- Maps SDK Version:10.1.0

Creating multiple pointAnnotationManagers causes the onPointAnnotannotationClicklistener not to execute

https://github.com/mapbox/mapbox-maps-android/issues/825#issuecomment-961687531

**Comment by Chaoba** [comment]
@229222025 I'm not seeing this issue while testing it locally. Do you consume the click events in `OnPointAnnotationClickListener`?
