### ISSUE TITLE
Issue in filter map using expression on a single layer with multiple ids.

### ISSUE THREAD

**Issue by priyaji1** [mapbox/mapbox-maps-android#833]
## New Feature
  for (trails in trailsList) {

  expressiontrail =

                match {
                    get {
                        literal(AppConstant.MapBoxConstants.t_id)

                    }
                    literal(trail.id) // getting when itterating through loop
                    stop {
                        literal(
                            AppConstant.MapBoxConstants.TRAIL_SEL_COLOR1
                        )
                        literal(
                            AppConstant.MapBoxConstants.TRAIL_SEL_COLOR2
                        )
                    }
                }

            layerHalodev.lineColor(expressiontrail!!)
}

when i am passing a constant id then it will give result correct but when i am looping through and passing different ids of trails it is not working as expected .this executes second condition of stop.i am using mapbox v10 new version i.e (10.1.0)

**Comment by ZiZasaurus** [comment]
@priyaji1 for `match` you don't need to declare `stop`. Additionally, it looks like you are trying to filter, however, `lineColor` does not pertain to filtering. If you would like all of your trails to be colored color1 except for t_id, which is colored color2, then you would want to use a `case` expression instead like in our [iconPropertyActivity example](https://github.com/mapbox/mapbox-maps-android/blob/70e0f160bc461955430f5311bbaf266286d893dd/app/src/main/java/com/mapbox/maps/testapp/examples/IconPropertyActivity.kt#L53).

**Comment by priyaji1** [comment]
Hi Thank you for reply.switch case not work in my case because i am passing an array of trail ids and need to check each item of array with corresponding trail ids. i have used this code which i have attached it is working fine in IOS but not work in android. 

val openCloseExpression = match {

                get {
                    literal(AppConstant.MapBoxConstants.t_id)
                }
                literal(closeTrailList) //long type array of trail ids 
                stop {
                    color(Color.GREEN)
                    color(Color.RED)
                }
            }
            layerHalodev.lineColor(openCloseExpression)

**Comment by ZiZasaurus** [comment]
@priyaji1 since all the constant values are wrapped to literal expressions at the moment, for android you would need to use `Expression.fromRaw(expressionJson)`. This [PR](https://github.com/mapbox/mapbox-maps-android/pull/961) updates one of our examples to demonstrate the use of `Expression.fromRaw(expressionJson)`.

**Comment by ZiZasaurus** [comment]
Closing this ticket but please feel free to reopen if you have additional questions.
