### ISSUE TITLE
Puck bearing resource cannot exceed a specific size

### ISSUE THREAD

**Issue by Christophe668** [mapbox/mapbox-maps-android#836]
## Environment

- Maps SDK Version: 2.0.0-rc.7 (Mapbox Maps SDK v10.0.0)

## Observed behavior and steps to reproduce
Cannot set a bearing resource larger than 'x' pixels, if it does, it will be compacted:

![Screenshot_20211018-122936](https://user-images.githubusercontent.com/1552554/137715174-82e330f9-f177-4339-8f14-752b899d7f72.jpg)

## Expected behavior

On Mapbox 1.0 it was possible to use resources in this format :

![puck-user](https://user-images.githubusercontent.com/1552554/137713806-75d86151-a8e5-47bd-9973-b93202fbf1bf.png)

And have a rendering like this : 

| Case 1 | Case 2 |
| --- | --- |
|![Screenshot_20211018-123240](https://user-images.githubusercontent.com/1552554/137715188-67903818-8447-4308-855f-2661fef660ba.jpg)|![Screenshot_20211018-123319](https://user-images.githubusercontent.com/1552554/137715202-d03acd85-59ed-4dce-897a-1cc542225183.jpg)|

Thank you for your help, let me know if I can provide any more useful information!

**Comment by ZiZasaurus** [comment]
@Christophe668 I changed the image to square and no longer experience this issue. Can you try using a square image, rather than the rectangular image you posted above and verify whether it addresses the appearance of the bearing image?

**Comment by ZiZasaurus** [comment]
Closing this ticket for now, however, if this does not answer your question please feel free to reopen.

**Comment by Christophe668** [comment]
I did help, I just fixed this on my side and it's perfect! Thanks for the help!
