### ISSUE TITLE
How to decrypt a custom vector  tiles ？

### ISSUE THREAD

**Issue by caizhen2** [mapbox/mapbox-maps-android#837]
Is there an interface programming way to solve this problem?

**Comment by dudeuter** [comment]
Hello @caizhen2,

This while the Maps SDK certainly utilizes vector tiles, this is not a Maps SDK issue 🙂 

Please refer to our public documentation on the [vector tile spec](https://docs.mapbox.com/vector-tiles/specification/).

If you have any further questions please open a support request at https://support.mapbox.com.
