### ISSUE TITLE
Animate Camera in v10

### ISSUE THREAD

**Issue by Reafidy** [mapbox/mapbox-maps-android#838]
Hi Team,  

Unfortunately with all the help files in Kotlin, its left myself as an amateur developer rather lost.

In mapbox v9 I could animate the camera using the animatecamera method.  Nice and simple.

In mapbox v10 it says to use flyTo or easeTo. However none of these methods exist in the mapboxMap object?

```
mapView = findViewById(R.id.mapView)
mapboxMap = mapView.getMapboxMap()
mapboxMap.flyTo();  //Method not found??
```

How do I use flyTo and easeTo in plain old java?

**Comment by kiryldz** [comment]
Hey @Reafidy, if using Java you could call it by:
```
final Cancelable cancelable = CameraAnimationsUtils.easeTo(mapView.getMapboxMap(), new CameraOptions.Builder().zoom(5.0).build(), new MapAnimationOptions.Builder().duration(4000).build());

// or to get actual object of animation plugin and call functions directly with it

final CameraAnimationsPlugin camera = CameraAnimationsUtils.getCamera(mapView);
final Cancelable cancelable = camera.easeTo(
        new CameraOptions.Builder().zoom(5.0).build(),
        new MapAnimationOptions.Builder().duration(4000).build()
);
```

The way it's called this way is that now animation is much more flexible and lives in it's own module. It's very easily accessible if you use Kotlin but signature for Java is indeed not that obvious. 
I'll also update docs on public site with Java examples shortly, sorry for that inconvenience.

**Comment by Reafidy** [comment]
@kiryldz  Thank you very much for the reply.   This now makes sense and having the help files in Java would be great at some point.
