### ISSUE TITLE
repository should be added to settings.gradle NOT build.gradle

### ISSUE THREAD

**Issue by sonwh98** [mapbox/mapbox-maps-android#840]
## Environment

- Android OS version: 30
- Devices affected: any
- Maps SDK Version: 10.1.0

## Observed behavior and steps to reproduce
Cannot download dependency

the solution was to put repository information in settings.gradle
https://stackoverflow.com/questions/68822705/problem-with-mapbox-installation-android-studio-kotlin

https://developer.android.com/studio/preview/features#settings-gradle

**Comment by kiryldz** [comment]
You should put dependency in _project_ level `build.gradle` file both in 
```
buildscript {
  repositories {
    ... here ...
  }
}
```
and 
```
allprojects {
  repositories {
    ... here ...
  }
}
```
and then it should work.
Example is in this repo [here](https://github.com/mapbox/mapbox-maps-android/blob/main/build.gradle.kts).
