### ISSUE TITLE
Failed to load style: HTTP status code 401

### ISSUE THREAD

**Issue by TarekBenDriss** [mapbox/mapbox-maps-android#860]
I followed the documentation from this link:
https://docs.mapbox.com/android/maps/guides/install/

But I still have the error:
**Failed to load style: HTTP status code 401
 OnMapLoadError: STYLE, message: Failed to load style: HTTP status code 401, sourceID: null, tileID: null**

I checked the token and even created a new one that grants all permissions ... but to no avail

**Comment by ZiZasaurus** [comment]
@TarekBenDriss where are you setting your token, within the view controller or in the info.plist?

**Comment by TarekBenDriss** [comment]
> @TarekBenDriss where are you setting your tokens?

It's an android and not ios project.

**Comment by chi-yeung** [comment]
How was this solved?
I have tried placing my secret token in gradle.property (per direction) as well as in build.gradle directly.

E/Mapbox: [maps-core]: {ps.testapp.auto}[Setup]: Failed to load style: HTTP status code 401
E/Mapbox: [maps-android\Mbgl-StyleObserver]: OnMapLoadError: STYLE, message: Failed to load style: HTTP status code 401, sourceID: null, tileID: null

**Comment by zyz0201** [comment]
I also encountered the same problem, how to solve it
