### ISSUE TITLE
View annotation: support for WRAP_CONTENT dimensions

### ISSUE THREAD

**Issue by kiryldz** [mapbox/mapbox-maps-android#874]
## New Feature

Now only concrete width / height dimensions are supported.
It would be nice to support not only fixed user view dimensions but dynamic based on view's content:
```
android:layout_width="wrap_content"
android:layout_height="wrap_content"
```

## Why
Support all types of Android views user wishes to place on top of the map.

**Comment by VincentJoshuaET** [comment]
As a workaround, is it possible if we manually inflate our custom layouts and then retrieve the actual view dimensions and set that in the view annotation options?

**Comment by kdawal** [comment]
Issue persist in v11.1.0-rc.1
