### ISSUE TITLE
Camera Rotation

### ISSUE THREAD

**Issue by Reafidy** [mapbox/mapbox-maps-android#880]
It would be useful to support rotation of the camera about the horizontal plane.  ie To simulate an aircraft bank angle, in 3D terrain.

Example:
https://ipadpilotnews.com/wp-content/uploads/2018/11/iPhone-X-FF-SV-landscape.jpg

**Comment by ank27** [comment]
@Reafidy Currently this is not supported with [FreeCameraOption](https://docs.mapbox.com/mapbox-gl-js/api/properties/#freecameraoptions) as for the orientation of camera we use zoom, pitch and bearing and not roll, pitch, bearing. Although you can try tweaking FreeCameraOption's parameter to simulate roll (for eg. using yaw and altitude, although this is not correct roll representation). We could check this feature in future :).

**Comment by shesio** [comment]
Does the roll view now be supported？

**Comment by flasher297** [comment]
In v11 we have a wide range of animations now.
https://docs.mapbox.com/android/maps/guides/camera-and-animation/animations/
