### ISSUE TITLE
CircleAnnotationManager scale problem

### ISSUE THREAD

**Issue by 229222025** [mapbox/mapbox-maps-android#881]
In version 10.1.0, how does the circle annotation manager scale with the map?

**Comment by ZiZasaurus** [comment]
For CircleManager of annotations, we can only use fixed values, not expressions. If you would like to be able to use expressions with zoom as input, you would need to move the solution to normal circle layers. For more information, take a look at our documentation on StyleLayers [here](https://docs.mapbox.com/ios/maps/guides/annotations/#style-layers).
