### ISSUE TITLE
WMTS tile server support

### ISSUE THREAD

**Issue by Toprakete** [mapbox/mapbox-maps-android#891]
Is it possible to view maps from an WMTS tile server with url format like:

{TileMatrixSet}/{TileMatrix}/{TileCol}/{TileRow}

Using version 10.1.0 for WMS I do it so:
```

ArrayList<String> tiles = new ArrayList<>();
String url = "...?REQUEST=GetMap&VERSION=1.3.0&LAYERS=OGC:WMS&STYLES=&CRS=EPSG:3857&BBOX={bbox-epsg-3857}&WIDTH=256&HEIGHT=256&FORMAT=image/png";

tiles.add(url);
TileSet tileset = new TileSet.Builder("tileset",tiles).build();
m_wmsSource = null;
m_wmsSource = new RasterSource.Builder(WMS_SOURCE_ID).tileSet(tileset).tileSize(256).build();
initWMSLayer(loadedMapStyle,(float) minZ,(float) maxZ);
SourceUtils.addSource(loadedMapStyle,m_wmsSource);

```

with:

```
private void initWMSLayer(@NonNull Style loadedMapStyle, float minZ, float maxZ) {
       RasterLayer layer;
       // init layer
       layer = new RasterLayer(WMS_LAYER_ID, WMS_SOURCE_ID);
       layer.minZoom(minZ);
       layer.maxZoom(maxZ);
       LayerUtils.addLayer(loadedMapStyle,layer);
}
```

Is there something similar for an url in the format:
.../{TileMatrixSet}/{TileMatrix}/{TileCol}/{TileRow}

??
br

**Comment by ZiZasaurus** [comment]
@Toprakete have you seen our [WMS example](https://github.com/mapbox/mapbox-maps-android/blob/7e6c94892f063c1bee878bfac84043f9162e10ad/app/src/main/java/com/mapbox/maps/testapp/examples/WmsSourceActivity.kt)? What are you seeing when you use you URL with this example?

**Comment by ZiZasaurus** [comment]
@Toprakete, please take a look at our TileSet class, which is compatible with TileJSON. You can find an 
example [here](https://github.com/mapbox/mapbox-maps-android/blob/main/app/src/main/java/com/mapbox/maps/testapp/examples/style/TileJsonActivity.kt).

**Comment by Toprakete** [comment]
Can you please provide a sample with a wmts source template like 
https://maps.stadt-salzburg.at/geodaten/wmts/bmapgrau/{Style}/google3857/{TileMatrix}/{TileRow}/{TileCol}.jpg
didn't get it work
more source urls here:
https://api.nasa.gov/vesta-wmts/catalog/
thx

**Comment by ZiZasaurus** [comment]
@Toprakete, this jsfiddle is a good example of someone doing the same thing: https://jsfiddle.net/qroyj8bh/. Additionally, from this example, it appears that TileMatrix={z}, TileRow={y}, TileCol={x} in GL JS, so you should also be able to accomplish this in Android.
