### ISSUE TITLE
the map in the demo is black screen 

### ISSUE THREAD

**Issue by zhufeixiang** [mapbox/mapbox-maps-android#895]
phone  oneplus 6T 
android 1

could you give me some solution？thanks
![WechatIMG48](https://user-images.githubusercontent.com/26599058/143181672-e94d3fea-092a-402b-a8ab-7960326b7ef1.jpeg)

**Comment by zhufeixiang** [comment]
android  10

**Comment by kiryldz** [comment]
hey @zhufeixiang , for me it seems that you have either token missing or token invalid, please see instructions [here](https://docs.mapbox.com/android/maps/guides/install/).
Please re-open with more details if issue will persist.
