### ISSUE TITLE
Compass disappears when hiding the scalebar. Compass only appears if the view is paused and resumed

### ISSUE THREAD

**Issue by Agosto44** [mapbox/mapbox-maps-android#907]
## Environment

- Android OS version: 11
- Maps SDK Version: 10

## Observed behavior and steps to reproduce

When hiding the scalebar on the map, be it through `mapView.scalebar.updateSettings { enabled = false }` 
or through `mapView.scalebar.enabled = false`, the compass also gets hidden. 

The compass only appears if the view is paused and resumed - for example, when going to the android main menu and returning to the application.

## Expected behavior

Hiding the scaleBar shouldn't affect the compass in any way.

**Comment by ank27** [comment]
@Agosto44, I have tested with hiding the scalebar, the compass does not disappear (check the attached video), maybe you can share your implementation (Also are you using v10.0.0 or v10.1.0?).

https://user-images.githubusercontent.com/11589497/143854098-375da0f4-ff1c-4876-9792-b700a9fb5d6d.mp4
