### ISSUE TITLE
How to add marker using Java in v10?

### ISSUE THREAD

**Issue by karatuno** [mapbox/mapbox-maps-android#916]
The document only shows how to add markers only using [Kotlin](https://docs.mapbox.com/android/maps/guides/annotations/). While I have figured out how to use the rest of the features(gestures, adding style, disabling scale), but I'm not able to add markers using java. Why you guys don't have Java documentation?

**Comment by karatuno** [comment]
```
        AnnotationPlugin annotationAPI = AnnotationPluginImplKt.getAnnotations((MapPluginProviderDelegate)mapView);
        PointAnnotationManager pointAnnotationManager = PointAnnotationManagerKt.createPointAnnotationManager(annotationAPI,mapView);
        PointAnnotationOptions pointAnnotationOptions = new PointAnnotationOptions()
                .withPoint(com.mapbox.geojson.Point.fromLngLat(YOUR_LONG, YOUR_LAT))
                .withIconImage(getBitmap(R.drawable.icon));
        pointAnnotationManager.create(pointAnnotationOptions);
```

But you should include Java documentation. Is it that hard? If so how can I contribute?

**Comment by miptildar** [comment]
From my experience they will answer you after 4-6 months

**Comment by NitayMG** [comment]
any process?

**Comment by miptildar** [comment]
@NitayMG I have created a multi-module project in Android, where MapBox related work is done using Kotlin. 
That is the easiest way to solve the problem.

**Comment by NitayMG** [comment]
i cant....im getting into project that is already in java so i must to do
it with java

‫בתאריך יום ד׳, 31 בינו׳ 2024 ב-11:24 מאת ‪Ildar Zaripov‬‏ <‪
***@***.***‬‏>:‬

**Comment by NitayMG** [comment]
im trying to create PointAnnotationManager
BUT NOTHING THAT ID O IS NOT WORKING

‫בתאריך יום ד׳, 31 בינו׳ 2024 ב-11:24 מאת ‪Ildar Zaripov‬‏ <‪
***@***.***‬‏>:‬

**Comment by miptildar** [comment]
@NitayMG it is possible to combine Java and Kotlin code in Android. I use Kotlin to define data classes and interfaces (for null-safety). Implementation is in Java.

**Comment by NitayMG** [comment]
Thanks, I'll check it out.

‫בתאריך יום ד׳, 31 בינו׳ 2024 ב-17:17 מאת ‪Ildar Zaripov‬‏ <‪
***@***.***‬‏>:‬

**Comment by rogergcc** [comment]
> @NitayMG it is possible to combine Java and Kotlin code in Android. I use Kotlin to define data classes and interfaces (for null-safety). Implementation is in Java.

this work for me
cause seems docs from v10 only kotlin
