### ISSUE TITLE
 When will the documentation for Java integration mapbox 10 be provided?

### ISSUE THREAD

**Issue by caizhen2** [mapbox/mapbox-maps-android#917]
## New Feature

<- Description of the feature being requested and any outcomes desired, an example use case, and any suggestions for solution ->
## Why
<- 1-2 sentence description of why you're requesting this feature. What problem does it solve? Why is it valuable? ->

**Comment by kiryldz** [comment]
@caizhen2 could you please add a reference what docs have you taken a look at so far?
