### ISSUE TITLE
Publish dependencies to Maven Central, now that JCenter will be sunset

### ISSUE THREAD

**Issue by VincentJoshuaET** [mapbox/mapbox-maps-android#92]
![image](https://user-images.githubusercontent.com/19756326/107601299-429ac980-6c61-11eb-8658-be037dc57c73.png)

**Comment by pengdev** [comment]
Hi @VincentJoshuaET, thank you for reaching out and providing feebdack! Currently all of these dependencies are published to the Mapbox hosted maven infrastructure instead of jcenter. We will not publish new artifacts to the JCenter or Maven Central, please follow the instructions in https://docs.mapbox.com/android/beta/maps/guides/install/#add-the-dependency to add the Mapbox dependency to your project.

**Comment by VincentJoshuaET** [comment]
I have already done that. Removing `jcenter()` will cause the Gradle sync to fail as it cannot find the dependencies in the picture.

**Comment by tobrun** [comment]
That is correct, we haven't migrated that project as we plan to fold that into another existing project

**Comment by VincentJoshuaET** [comment]
So right now jcenter is still required right?

**Comment by VincentJoshuaET** [comment]
`Please remove usages of `jcenter()` Maven repository from your build scripts and migrate your build to other Maven repositories.`

Removing jcenter() and then building the app causes this error:

```
Execution failed for task ':app:dataBindingMergeDependencyArtifactsDebug'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.mapbox.base:annotations:0.5.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/mapbox/base/annotations/0.5.0/annotations-0.5.0.pom
       - https://repo.maven.apache.org/maven2/com/mapbox/base/annotations/0.5.0/annotations-0.5.0.pom
       - https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/base/annotations/0.5.0/annotations-0.5.0.pom
     Required by:
         project :app > com.mapbox.maps:android:10.0.0-beta.14
         project :app > com.mapbox.plugin:maps-attribution:10.0.0-beta.14
         project :app > com.mapbox.maps:android:10.0.0-beta.14 > com.mapbox.base:common:0.5.0
         project :app > com.mapbox.maps:android:10.0.0-beta.14 > com.mapbox.plugin:maps-annotation:10.0.0-beta.14
         project :app > com.mapbox.maps:android:10.0.0-beta.14 > com.mapbox.common:okhttp:10.0.0-beta.11 > com.mapbox.common:common:10.0.0-beta.11
   > Could not find com.mapbox.common:logger:0.5.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/mapbox/common/logger/0.5.0/logger-0.5.0.pom
       - https://repo.maven.apache.org/maven2/com/mapbox/common/logger/0.5.0/logger-0.5.0.pom
       - https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/common/logger/0.5.0/logger-0.5.0.pom
     Required by:
         project :app > com.mapbox.maps:android:10.0.0-beta.14 > com.mapbox.common:okhttp:10.0.0-beta.11 > com.mapbox.common:common:10.0.0-beta.11
   > Could not find com.mapbox.common:loader:0.5.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/mapbox/common/loader/0.5.0/loader-0.5.0.pom
       - https://repo.maven.apache.org/maven2/com/mapbox/common/loader/0.5.0/loader-0.5.0.pom
       - https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/common/loader/0.5.0/loader-0.5.0.pom
     Required by:
         project :app > com.mapbox.maps:android:10.0.0-beta.14 > com.mapbox.common:okhttp:10.0.0-beta.11 > com.mapbox.common:common:10.0.0-beta.11

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
 ```

This should be fixed ASAP. We won't be able to use this library after May 1.

**Comment by tobrun** [comment]
> Why is this closed?

Correct, we shouldn't close this issue until all underlying dependencies have been migrated and this repository no longer relies on JCenter. I'm working on finalizing it this week.

Thank you for following up on the project @VincentJoshuaET, appreciate it!

**Comment by tobrun** [comment]
All referenced dependencies are migrated!
Can't fully remove jcenter from this project due to:
```
 What went wrong:
Execution failed for task ':sdk-base:lint'.
> Could not resolve all files for configuration ':sdk-base:lintClassPath'.
   > Could not find org.jetbrains.trove4j:trove4j:20160824.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/jetbrains/trove4j/trove4j/20160824/trove4j-20160824.pom
       - https://repo.maven.apache.org/maven2/org/jetbrains/trove4j/trove4j/20160824/trove4j-20160824.pom
       - https://api.mapbox.com/downloads/v2/releases/maven/org/jetbrains/trove4j/trove4j/20160824/trove4j-20160824.pom
     Required by:
         project :sdk-base > com.android.tools.lint:lint-gradle:27.1.1 > com.android.tools:sdk-common:27.1.1
         project :sdk-base > com.android.tools.lint:lint-gradle:27.1.1 > com.android.tools.external.com-intellij:intellij-core:27.1.1


```

I do want to call out that jcenter will be around until February 1, 2022.

**Comment by VincentJoshuaET** [comment]
> All referenced dependencies are migrated!
> Can't fully remove jcenter from this project due to:
> ```
>  What went wrong:
> Execution failed for task ':sdk-base:lint'.
> > Could not resolve all files for configuration ':sdk-base:lintClassPath'.
>    > Could not find org.jetbrains.trove4j:trove4j:20160824.
>      Searched in the following locations:
>        - https://dl.google.com/dl/android/maven2/org/jetbrains/trove4j/trove4j/20160824/trove4j-20160824.pom
>        - https://repo.maven.apache.org/maven2/org/jetbrains/trove4j/trove4j/20160824/trove4j-20160824.pom
>        - https://api.mapbox.com/downloads/v2/releases/maven/org/jetbrains/trove4j/trove4j/20160824/trove4j-20160824.pom
>      Required by:
>          project :sdk-base > com.android.tools.lint:lint-gradle:27.1.1 > com.android.tools:sdk-common:27.1.1
>          project :sdk-base > com.android.tools.lint:lint-gradle:27.1.1 > com.android.tools.external.com-intellij:intellij-core:27.1.1
> 
> 
> ```
> 
> I do want to call out that jcenter will be around until February 1, 2022.

This is already fixed on the latest beta version of the Android Gradle Plugin. Hopefully it comes to stable soon.

**Comment by VincentJoshuaET** [comment]
Thank you. I now just have to do this until AGP 4.2 becomes available:

```
buildscript {
    repositories {
        google()
        mavenCentral()
        jcenter {
            content {
                includeModule("org.jetbrains.trove4j", "trove4j")
            }
        }
    }
}

buildscript {
    repositories {
        google()
        mavenCentral()
        maven("https://api.mapbox.com/downloads/v2/releases/maven") {
            authentication {
                create<BasicAuthentication>("basic")
            }
            credentials {
                username = "mapbox"
                password = property("MAPBOX_ACCESS_TOKEN") as String
            }
            content {
                includeGroupByRegex("com.mapbox.*")
            }
        }
        jcenter {
            content {
                includeModule("org.jetbrains.trove4j", "trove4j")
            }
        }
    }
}
```

**Comment by tobrun** [comment]
There is nothing actionable for us to handle here. Closing
