### ISSUE TITLE
Is it possible to open the interface to set the background outside the globe?

### ISSUE THREAD

**Issue by RocCaiy23** [mapbox/mapbox-maps-android#921]
## New Feature

For example, the universe, stars, etc. This is to increase the sense of reality, thank you very much.

## Why
<- 1-2 sentence description of why you're requesting this feature. What problem does it solve? Why is it valuable? ->

**Comment by kiryldz** [comment]
@RocCaiy23 it's not possible at the moment. However we may look into this feature in the future.

**Comment by RocCaiy23** [comment]
> @RocCaiy23 it's not possible at the moment. However we may look into this feature in the future.

Is this feature a high priority for you?

**Comment by RocCaiy23** [comment]
> @RocCaiy23 it's not possible at the moment. However we may look into this feature in the future.

@kiryldz Is this feature a high priority for you?

**Comment by kiryldz** [comment]
> > @RocCaiy23 it's not possible at the moment. However we may look into this feature in the future.
> 
> @kiryldz Is this feature a high priority for you?

No, it's not highest priority for now, however I'll drop any news here after some internal discussions within the team.

**Comment by kiryldz** [comment]
This was implemented in v11 as `Atmosphere`.
