### ISSUE TITLE
User Location bearing is not accurate in v10

### ISSUE THREAD

**Issue by jonschmidt** [mapbox/mapbox-maps-android#922]
## Environment

- Android OS version: 12
- Devices affected: Pixel 5
- Maps SDK Version: 10.1.0

## Observed behavior and steps to reproduce

Hi. I have a simple map setup where I show the user location + bearing. On v9, this works very well, as I move the phone around, the bearing updates smoothly, reflecting where I am pointing.

## Expected behavior

I would expect bearing operate in v10 as in v9. When I move the phone around me, the bearing should reflect my movements. However, it does not. Not only does it not move when I turn, but it randomly turns back and forth when my phone is sitting idle on my desk.

## Notes / preliminary analysis

I have only briefly looked at the source code, but I think this might have something to do with v9 listening to phone sensors, and v10 only using the location bearing (which is not that accurate normally)

## Additional links and references

I don't want to provide a video as it will contain my real location, but this is very reproducible. Happy to help further if I can do so.

**Comment by ZiZasaurus** [comment]
Thank you for reporting. I was able to reproduce this behavior on a Google Pixel 3 as well.

**Comment by Chaoba** [comment]
Will fix in https://github.com/mapbox/mapbox-maps-android/pull/970

**Comment by yunikkk** [comment]
@felixkrautschuk have you tried to change bearing source for the location puck https://docs.mapbox.com/android/maps/guides/user-location/#set-puck-bearing-source ?

**Comment by felixkrautschuk** [comment]
@yunikkk yes I tried that, but I still cannot see any difference

**Comment by yunikkk** [comment]
@felixkrautschuk seems like a bug then, please submit a ticket with the details and we'll look into it
