### ISSUE TITLE
How to remove the specified annotations?

### ISSUE THREAD

**Issue by RocCaiy23** [mapbox/mapbox-maps-android#946]
I can’t seem to assign an id to it, nor can I query it in `mapView.annotations`

**Comment by RocCaiy23** [comment]
In version `android-v10.2.0-beta.1`

**Comment by Chaoba** [comment]
You can refer to the [API docs](https://docs.mapbox.com/android/maps/api/10.2.0-beta.1/mapbox-maps-android/com.mapbox.maps.plugin.annotation.generated/-circle-annotation-manager/#533088528%2FFunctions%2F540127926)
