### ISSUE TITLE
Native crash when navigating between Fragments using a shared element transition

### ISSUE THREAD

**Issue by deRonbrown** [mapbox/mapbox-maps-android#948]
## Environment

- Android OS version: 10, 11, 12
- Devices affected: Pixel 4, Pixel 5, Pixel 6, etc.
- Maps SDK Version: 9 and 10

## Observed behavior and steps to reproduce

While trying to use a shared element transition between a RecyclerView and another Fragment, the app crashes with a SIGABRT. Demo project for both v9 and v10:

- v9: https://github.com/deRonbrown/MapboxCrash
- v10: https://github.com/deRonbrown/MapboxCrash/tree/v10

## Expected behavior

Transition succeeds without a fatal crash.

## Notes / preliminary analysis

Previously reported here: https://github.com/mapbox/mapbox-gl-native-android/issues/641
Shared element transition implementation is described here: https://github.com/deRonbrown/MapboxCrash/tree/main#transition-info

## Additional links and references

Traces: https://gist.github.com/deRonbrown/84c9e5f4591494f290695353b0f6f6c8

**Comment by Chaoba** [comment]
@deRonbrown Thanks for reporting. From the trace, the crash roots from a system lib, it is not related to mapbox.
Guess there is conflict on the native side.

**Comment by kiryldz** [comment]
Stale, outdated.
