### ISSUE TITLE
Disabling Telemetry

### ISSUE THREAD

**Issue by deRonbrown** [mapbox/mapbox-maps-android#957]
On v9, I was able to disable telemetry using the following methods:
```
TelemetryEnabler.updateTelemetryState(State.DISABLED)
Plugin.Mapbox.getTelemetry()?.setUserTelemetryRequestState(false)
```
How do I disable Telemetry on v10? I see the `MapTelemetry` interface, but I'm not sure how to obtain an instance.

**Comment by ank27** [comment]
@deRonbrown you can follow this [example](https://github.com/mapbox/mapbox-maps-android/blob/main/app/src/main/java/com/mapbox/maps/testapp/examples/CustomAttributionActivity.kt#L114-L131) related to Telemetry in v10.
