### ISSUE TITLE
Add ability to disable bearing for the user location puck. 

### ISSUE THREAD

**Issue by DejanRistic** [mapbox/mapbox-maps-android#962]
## New Feature
Add ability to disable bearing completely for the user location puck. 

## Why
We replace the pucks top image with a user avatar and we don't like it rotating around. I believe we did this with the older sdks by setting a RenderMode that ignored the bearing.

**Comment by Chaoba** [comment]
Fix in https://github.com/mapbox/mapbox-maps-android/pull/1131

**Comment by Chaoba** [comment]
[PR](https://github.com/mapbox/mapbox-maps-ios/pull/1107) for iOS to align with android
