### ISSUE TITLE
Symbol#textFont

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-maps-android#97]
We got customer feedback about textFonts not working as expected. We are seeing the following log message, even if we aren't using the textFont ourselves:

> Layer 'mapbox-android-symbol-layer-1' has an invalid value for text-font and will not render text. Output values must be contained as literals within the expression.

First issue is that we provide a default value, while capturing from the style-spec, this isn't required. By default
it will fallback on a font from the style. We can't make any assumptions on which fonts will be availlable.

```kotlin

  // currently 
  /**
   * Font stack to use for displaying text.
   */
  var textFont: List<String> = listOf("Open Sans Regular", "Arial Unicode MS Regular")

  // excpected
  /**
   * Font stack to use for displaying text.
   */
  var textFont: List<String>? = null
```

The second issue is that we aren't handling the "null" case correclty. We should be checking if the JsonArray value size is larger as zero before calling into enableDataDrivenProperty.

```kotlin

  // currently 
  if (!(jsonObject.get(SymbolOptions.PROPERTY_TEXT_FONT).isJsonNull)) {
    annotationManager.enableDataDrivenProperty(SymbolOptions.PROPERTY_TEXT_FONT)
  }

  // expected
  if ((jsonObject.get(SymbolOptions.PROPERTY_TEXT_FONT) as JsonArray).size() > 0) {
    annotationManager.enableDataDrivenProperty(SymbolOptions.PROPERTY_TEXT_FONT)
  }
```

**Comment by pengdev** [comment]
@tobrun @Chaoba It seems we should set the default value of textFont
```
var textFont: List<String> = listOf(
    "Open Sans Regular",
    "Arial Unicode MS Regular"
  )
```
Otherwise, if one of the symbols has provided the textFont, we will enable the data driven property of textFont and thus other symbols that don't specify the textFont property to have an empty text-font list, and result in
The resource `https://api.mapbox.com/fonts/v1/mapbox//0-255.pbf` not found
