### ISSUE TITLE
Center coordinate is not calculated correctly for some points and zoom

### ISSUE THREAD

**Issue by dimysa** [mapbox/mapbox-maps-android#972]
## Environment

- Android OS version: 11
- Devices affected: OnePlus 8 Pro
- Maps SDK Version: 10.1.0

## Observed behavior and steps to reproduce

For me, it is reproduced only with special presets and at some points. I have attached a video and source code in which I have problems. When the zoom is large, then the camera moves incorrectly, but if you zoom out, then everything works as expected. Perhaps I am doing something wrong?

## Expected behavior

Center coordinate will be calculated correctly

## Notes / preliminary analysis

It looks like the screen coordinates from the point are calculated incorrectly

## Additional links and references

https://gist.github.com/dimysa/48ff5b53c049ccb73e32afdfdd437108

https://user-images.githubusercontent.com/14176511/145549796-b5133276-54f9-4225-8ebb-9f0cca8a9575.mp4

**Comment by samcrawford** [comment]
It sounds similar to the issue I hit in the iOS SDK in https://github.com/mapbox/mapbox-maps-ios/issues/834. I've not tested your code, but perhaps try changing your `it.cameraForCoordinates(...)` call to set bearing=0 and pitch=0.

**Comment by dimysa** [comment]
Thanks, bearing = 0 and pitch = 0 works well. I do not know if it is worth closing this issue, but the solution suits me

**Comment by samcrawford** [comment]
They seem to be treating it as a bug on the iOS side, so I'd suggest it's probably a bug here too. I'd suggest leaving this open, as my suggestion is very much a workaround.

**Comment by endanke** [comment]
Thanks for reporting! Tracking this as I'm working on a fix in gl-native which will most likely solve this issue on both platforms.

**Comment by endanke** [comment]
@dimysa could you try it again using our latest release? https://github.com/mapbox/mapbox-maps-android/releases/tag/android-v10.3.0-rc.1

**Comment by kiryldz** [comment]
Closing, feel free to re-open if issue persists.

**Comment by etherlind** [comment]
Hello! I'm still having this issue with the v10.3.0 release. I'm trying to center a map on a feature, and it works correctly with pitch = 0 but not with pitch = 45 for instance.

**Comment by endanke** [comment]
Hi! For full context, the fix I've mentioned above was related to the issue in the case when pitch is zero.
I think we have a separate bug for non-zero pitch cases, which could be related to the following issue: https://github.com/mapbox/mapbox-maps-ios/issues/788
