### ISSUE TITLE
Switching BackgroundLayers with different colors doesn't work after the first switch

### ISSUE THREAD

**Issue by gilgil28** [mapbox/mapbox-maps-android#993]
## Environment

- Android OS version: 10, 11
- Devices affected: all
- Maps SDK Version: 10.1.0

## Observed behavior and steps to reproduce

Setting a BackgroundLayer with color A works great. Removing that layer and adding another BackgroundLayer with color B also works. Then Removing That BackgroundLayer and adding a new BackgroundLayer with color A does not work and I am stuck with color B
Keeping the same layer and just setting the color causes the same problem
`val layer = mapStyle.getLayerAs<BackgroundLayer>("background")`
`layer.backgroundColor(backgroundColor)`

## Expected behavior

I should be able to change multiple BackgroundLayers without a problem

## Notes / preliminary analysis

The layer id doesn't matter

**Comment by ank27** [comment]
@gilgil28 I have checked using the steps you provided, it works as expected. I am able to change the `BackgroundColor` of the layer multiple times. 
Also, you can check whether the style layer still exists or not (after you removed it) using `style.styleLayerExists(layer_id)` and see if it is still there. could you also share the code snippet here, in case it doesn't work :)

**Comment by gilgil28** [comment]
@ank27 The layer does not exist after removal. If I didn't remove it I would have got an exception.
Here is the exact snippet as of now (not removing, just changing the color which works only once:
`
val backgroundColor = colorScheme.background
val layer = mapStyle.getLayerAs<BackgroundLayer>("background")
layer?.backgroundColor(backgroundColor.toArgb())
`

**Comment by gilgil28** [comment]
After some more research, it seems like the problem is with the recomposition of the view (using Jetpack Composable)

**Comment by ank27** [comment]
Yeah it could be with the recomposition with jetpack compose, i tried it again and works as expected. Closing since its not related to sdk. Please reopen again if it persist.
